var searchData=
[
  ['v0_203_200_0',['Phase 1: Core API (v0.3.0)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md120',1,'']]],
  ['v0_204_200_1',['v0 4 0',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md121',1,'Phase 2: Integration (v0.4.0)'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md108',1,'With Redundancy Framework (Future v0.4.0+)']]],
  ['validates_20the_20backend_20only_20executes_2',['2.2 The framework still validates; the backend only executes',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md58',1,'']]],
  ['variables_3',['2. Set Environment Variables',['../md_docs_2CROSS__COMPILATION.html#autotoc_md239',1,'']]],
  ['vector_20_3a_4',['Generate all diagrams as SVG (vector):',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md170',1,'']]],
  ['verification_5ffailures_5',['verification_failures',['../structsapi__checksum__stats__t.html#a336736b8b2b6b372b5fe66ea0826e1a1',1,'sapi_checksum_stats_t']]],
  ['verification_5fpasses_6',['verification_passes',['../structsapi__checksum__stats__t.html#ac406b727a12b41dbe2e8d8d678f803c8',1,'sapi_checksum_stats_t']]],
  ['verify_20at_20compile_20time_7',['Verify at Compile-Time',['../memory_user_guide.html#memory_user_guide_sizing_verify',1,'']]],
  ['verify_20syntax_20without_20generating_3a_8',['Verify syntax without generating:',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md172',1,'']]],
  ['version_20control_9',['4. Version Control',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md215',1,'']]],
  ['via_20build_20diversity_10',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['via_20callbacks_11',['ADR-005: OAL Backend Registration via Callbacks',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html',1,'']]],
  ['view_12',['view',['../buffer_user_guide.html#buffer_user_guide_qs_init',1,'2. Bind Buffer View'],['../buffer_user_guide.html#buffer_user_guide_example_ringbuf',1,'Example 2: Read-Only View']]],
  ['view_20based_20buffer_20design_13',['View-Based Buffer Design',['../buffer_architecture.html#buffer_architecture_overview',1,'']]],
  ['view_20over_20static_20storage_14',['2.1 Ownership model: caller-owned view over static storage',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md26',1,'']]],
  ['virtual_20dispatch_20c_20redesign_15',['2.4 Why this isn&apos;t a virtual-dispatch / C++ redesign',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md60',1,'']]],
  ['vital_20architecture_20—_20ccf_20mitigation_20via_20build_20diversity_16',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['vital_20channel_17',['vital channel',['../ipc_transport_selection.html#ipc_transport_selection_vital_channel_integration',1,'Integration with Vital Channel'],['../vital_channel_user_guide.html#vital_channel_user_guide_overview',1,'What is Vital Channel?']]],
  ['vital_20channel_20abstraction_18',['Vital Channel Abstraction',['../group__vital__channel.html',1,'']]],
  ['vital_20channel_20communication_20architecture_19',['Vital Channel Communication Architecture',['../vital_channel_architecture.html',1,'']]],
  ['vital_20channel_20module_20user_20guide_20',['Vital Channel Module - User Guide',['../vital_channel_user_guide.html',1,'']]],
  ['vital_20channels_21',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['vital_20communication_22',['Creating Channels for Vital Communication',['../channel_configuration.html#channel_configuration_channel_creation',1,'']]],
  ['vital_20message_20wrapper_23',['3. Vital Message Wrapper',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md104',1,'']]],
  ['volatile_20memory_24',['Non-Volatile Memory',['../group__NVM.html',1,'']]],
  ['volatile_20memory_20architecture_25',['Non-Volatile Memory Architecture',['../nvm_architecture.html',1,'']]],
  ['volatile_20memory_20user_20guide_26',['Non-Volatile Memory User Guide',['../nvm_user_guide.html',1,'']]],
  ['voting_27',['voting',['../vital_channel_architecture.html#vital_channel_architecture_example_nmr',1,'N-out-of-M Voting'],['../vital_channel_architecture.html#vital_channel_architecture_receive_semantics',1,'Receive Semantics (Voting)']]],
  ['voting_20failure_28',['Example 1: Redundant Channel Voting Failure',['../safestate_user_guide.html#safestate_user_guide_example_voting',1,'']]],
  ['voting_20perfect_20agreement_20required_29',['2-out-of-2 Voting (Perfect Agreement Required)',['../vital_channel_architecture.html#vital_channel_architecture_example_2oo2',1,'']]],
  ['voting_20strategies_30',['Voting Strategies',['../vital_channel_user_guide.html#vital_channel_user_guide_strategies',1,'']]],
  ['voting_20tolerate_201_20fault_31',['2-out-of-3 Voting (Tolerate 1 Fault)',['../vital_channel_architecture.html#vital_channel_architecture_example_2oo3',1,'']]],
  ['voting_5fstrategy_32',['voting_strategy',['../structsapi__vital__channel__config__t.html#a7db948c213bb5b0adf936db24628107a',1,'sapi_vital_channel_config_t']]],
  ['vs_20systematic_20error_20detection_33',['Random vs Systematic Error Detection',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md113',1,'']]],
  ['vtable_20type_20and_20one_20registration_20function_20per_20service_34',['2.1 One backend vtable type and one registration function per service',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md57',1,'']]]
];
