var searchData=
[
  ['m_20voting_0',['N-out-of-M Voting',['../vital_channel_architecture.html#vital_channel_architecture_example_nmr',1,'']]],
  ['machine_20diagram_20behavioral_1',['4. State Machine Diagram (Behavioral)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md397',1,'']]],
  ['macro_20only_20no_20generated_20control_20flow_2',['2.1 Storage-shape macro only, no generated control flow',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html#autotoc_md289',1,'']]],
  ['macros_3',['macros',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md50',1,'2.6 Macros'],['../safestate_architecture.html#safestate_architecture_api_macros',1,'Convenience Macros']]],
  ['macros_20or_20c11_20tt_20_5fgeneric_20tt_4',['2.5 Why named functions instead of macros or C11 &lt;tt&gt;_Generic&lt;/tt&gt;',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md38',1,'']]],
  ['main_20loop_20heartbeat_5',['Example 1: System Watchdog (Main Loop Heartbeat)',['../watchdog_user_guide.html#watchdog_user_guide_example_system',1,'']]],
  ['majority_20vote_20bug_20fixed_6',['2.2 &lt;tt&gt;sapi_voter&lt;/tt&gt; (new) - N-way voting, with the majority-vote bug fixed',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md227',1,'']]],
  ['malloc_7',['Example 2: Ring Buffer Without malloc',['../memory_user_guide.html#memory_user_guide_example_ringbuf',1,'']]],
  ['manager_8',['manager',['../group__APPMANAGER.html',1,'Application Manager'],['../watchdog_architecture.html#watchdog_architecture_manager',1,'Watchdog Manager']]],
  ['manager_20integration_20with_20channels_9',['App Manager Integration with Channels',['../appmanager_integration.html',1,'']]],
  ['mandatory_20techniques_20supported_10',['Mandatory Techniques Supported',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md112',1,'']]],
  ['manipulation_11',['Bounded String Manipulation',['../group__STRING.html',1,'']]],
  ['manipulation_20—_20tt_20sapi_5fstring_20h_20tt_20adr_20006_12',['1.6 Bounded string manipulation — &lt;tt&gt;sapi_string.h&lt;/tt&gt; (ADR-006)',['../safeapi_srs.html#autotoc_md476',1,'']]],
  ['manipulation_20and_20endianness_20safe_20buffer_20access_13',['ADR-006: Safe String Manipulation and Endianness-Safe Buffer Access',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html',1,'']]],
  ['manual_20cmake_20invocation_14',['Manual CMake invocation',['../index.html#autotoc_md5',1,'']]],
  ['manual_20online_20confirmation_20on_20simultaneous_20dual_20reboot_15',['2.5 Known open item: manual ONLINE confirmation on simultaneous dual-reboot',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md265',1,'']]],
  ['many_20trains_20up_20to_20100_16',['ADR-036: Train-session multiplexing - one link, many trains (up to 100)',['../md_docs_2architecture_2ADR-036-train-session-multiplexing.html',1,'']]],
  ['map_20collapse_17',['3. Port map collapse',['../md_docs_2architecture_2ADR-036-train-session-multiplexing.html#autotoc_md336',1,'']]],
  ['markdown_20files_18',['In Markdown Files',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md405',1,'']]],
  ['marks_20and_20stage_20then_20commit_20output_19',['ADR-034: Checkpoint-signature marks and stage-then-commit output',['../md_docs_2architecture_2ADR-034-checkpoint-signature-marks.html',1,'']]],
  ['match_20',['match',['../structsapi__checksum__result__t.html#a9fe6db5a9e58dff1d1d1d8ba1a671e50',1,'sapi_checksum_result_t']]],
  ['matched_21',['matched',['../structdual__poll__result__t.html#a1492cb9551f2a29e8239f6c4155f4a31',1,'dual_poll_result_t']]],
  ['max_20requirements_22',['Calculate Max Requirements',['../memory_user_guide.html#memory_user_guide_sizing_calc',1,'']]],
  ['max_5fdelay_5fms_23',['max_delay_ms',['../structsapi__checkpoint__config__t.html#aa91a5f3cb397bcd4792789d057a68e78',1,'sapi_checkpoint_config_t::max_delay_ms'],['../structsapi__appmanager__checkpoint__config__t.html#aade453fc0a3da84c0cc79b0dabfe7c25',1,'sapi_appmanager_checkpoint_config_t::max_delay_ms']]],
  ['max_5fiterations_24',['max_iterations',['../structsapi__appmanager__config__t.html#a2d37adf24afa17dbb84364a50d121215',1,'sapi_appmanager_config_t']]],
  ['max_5fsubscribers_25',['max_subscribers',['../structsapi__ipc__pubsub__topic__config__t.html#a2e8b3680dbf534d139b1c35d15cd396b',1,'sapi_ipc_pubsub_topic_config_t']]],
  ['md_20not_20yet_20tagged_20per_20function_26',['3. Project-wide requirements (CLAUDE.md, not yet tagged per-function)',['../safeapi_srs.html#autotoc_md488',1,'']]],
  ['meaning_27',['2.1 Three cycle hooks, &lt;tt&gt;execute&lt;/tt&gt; unchanged in meaning',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md167',1,'']]],
  ['means_20here_20and_20what_20it_20deliberately_20doesn_20t_28',['2.3 What &quot;real&quot; means here, and what it deliberately doesn&apos;t',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md160',1,'']]],
  ['mechanically_29',['2.3 What changes mechanically',['../md_docs_2architecture_2ADR-024-configurable-feature-build.html#autotoc_md218',1,'']]],
  ['mechanics_30',['Timeout Mechanics',['../watchdog_architecture.html#watchdog_architecture_timeout',1,'']]],
  ['mechanism_31',['Watchdog Mechanism',['../group__WATCHDOG.html',1,'']]],
  ['memory_32',['memory',['../group__NVM.html',1,'Non-Volatile Memory'],['../memory_user_guide.html#memory_user_guide_error_handling',1,'Out-of-Memory']]],
  ['memory_20—_20tt_20sapi_5fnvm_20h_20tt_20adr_20001_20§4_33',['2.2 Non-volatile memory — &lt;tt&gt;sapi_nvm.h&lt;/tt&gt; (ADR-001 §4)',['../safeapi_srs.html#autotoc_md479',1,'']]],
  ['memory_20architecture_34',['Non-Volatile Memory Architecture',['../nvm_architecture.html',1,'']]],
  ['memory_20corruption_20detection_35',['Example 2: Memory Corruption Detection',['../reboot_user_guide.html#reboot_user_guide_example_memory',1,'']]],
  ['memory_20module_36',['What is the Memory Module?',['../memory_user_guide.html#memory_user_guide_overview',1,'']]],
  ['memory_20module_20architecture_37',['Memory Module - Architecture',['../memory_architecture.html',1,'']]],
  ['memory_20module_20user_20guide_38',['Memory Module - User Guide',['../memory_user_guide.html',1,'']]],
  ['memory_20primitive_39',['ADR-031: &lt;tt&gt;sapi_mem_util&lt;/tt&gt; - one sanctioned call site per libc memory primitive',['../md_docs_2architecture_2ADR-031-sapi-mem-util.html',1,'']]],
  ['memory_20reservation_40',['Static Memory Reservation',['../group__MEMORY.html',1,'']]],
  ['memory_20reservation_20—_20tt_20sapi_5fmemory_20h_20tt_20adr_20001_20§4_41',['2.3 Static memory reservation — &lt;tt&gt;sapi_memory.h&lt;/tt&gt; (ADR-001 §4)',['../safeapi_srs.html#autotoc_md480',1,'']]],
  ['memory_20reservation_20backend_20adaptation_42',['Static Memory Reservation - Backend Adaptation',['../group__MEMORY__BACKEND.html',1,'']]],
  ['memory_20transport_43',['Shared Memory Transport',['../ipc_transport_selection.html#ipc_transport_selection_shared_memory',1,'']]],
  ['memory_20user_20guide_44',['Non-Volatile Memory User Guide',['../nvm_user_guide.html',1,'']]],
  ['merged_20per_20site_20log_45',['3. Local test env: three processes, one merged per-site log',['../md_docs_2architecture_2ADR-037-role-c-gateway-decomposition.html#autotoc_md349',1,'']]],
  ['message_20buffer_46',['Example 1: Fixed-Size Message Buffer',['../buffer_user_guide.html#buffer_user_guide_example_message',1,'']]],
  ['message_20protocols_20and_20a_20missing_20reply_47',['5.2 One physical link, two message protocols, and a missing reply',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md174',1,'']]],
  ['message_20size_20limits_48',['Message Size Limits',['../vital_channel_architecture.html#vital_channel_architecture_message_size',1,'']]],
  ['message_20wrapper_49',['3. Vital Message Wrapper',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md104',1,'']]],
  ['message_5fsize_50',['message_size',['../structsapi__ipc__config__t.html#a1fcc91bd1775c1767eafb156ed754b58',1,'sapi_ipc_config_t::message_size'],['../structsapi__ipc__pubsub__topic__config__t.html#abc2c5a0797184e127ed5486d91009366',1,'sapi_ipc_pubsub_topic_config_t::message_size'],['../structsapi__netlink__config__t.html#a719d733132a652b5543fdaf45db520fa',1,'sapi_netlink_config_t::message_size'],['../structsapi__safechannel__vital__config__t.html#af570a65ce41d9d7188b338e387f26809',1,'sapi_safechannel_vital_config_t::message_size']]],
  ['metadata_20on_20the_20generic_20buffer_51',['2.2 No integrity metadata on the generic buffer',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md27',1,'']]],
  ['migration_52',['Post-acceptance fix (ADR-022, SITE&apos;s live &lt;tt&gt;sapi_safechannel&lt;/tt&gt; migration)',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md186',1,'']]],
  ['migration_20scope_20in_20safeapirbc2oo2_53',['2.4 Migration scope in safeAPIRBC2oo2',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html#autotoc_md201',1,'']]],
  ['minimal_20tt_20sapi_5flifecycle_20tt_20module_20req_20lifecycle_20001_20002_54',['2.1 A new, minimal &lt;tt&gt;sapi_lifecycle&lt;/tt&gt; module (REQ-LIFECYCLE-001/002)',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html#autotoc_md240',1,'']]],
  ['mirroring_55',['Pattern 3: Hot Standby with Mirroring',['../vital_channel_topologies.html#vital_channel_topologies_pattern_mirror_hot_standby',1,'']]],
  ['misra_20c_3a2012_56',['Static Analysis (MISRA C:2012)',['../index.html#autotoc_md6',1,'']]],
  ['misra_20c_3a2012_20compliance_57',['MISRA C:2012 Compliance',['../safestate_architecture.html#safestate_architecture_misra',1,'']]],
  ['misra_20compliance_58',['misra compliance',['../types_architecture.html#types_architecture_misra',1,'MISRA Compliance'],['../status_architecture.html#status_architecture_misra',1,'MISRA Compliance'],['../reboot_architecture.html#reboot_architecture_misra',1,'MISRA Compliance']]],
  ['misra_20compliant_59',['MISRA Compliant',['../checksum_architecture.html#checksum_architecture_misra',1,'']]],
  ['misra_20rule_2010_201_60',['MISRA Rule 10.1',['../cast_architecture.html#cast_architecture_misra',1,'']]],
  ['misra_20rule_2020_206_61',['MISRA Rule 20.6',['../memory_architecture.html#memory_architecture_misra',1,'']]],
  ['misra_20rule_2021_206_62',['MISRA Rule 21.6',['../string_architecture.html#string_architecture_misra',1,'']]],
  ['missing_20reply_63',['5.2 One physical link, two message protocols, and a missing reply',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md174',1,'']]],
  ['mitigation_64',['mitigation',['../system_architecture.html#system_architecture_ccf',1,'Common-Cause-Failure Mitigation'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md124',1,'Risk Mitigation']]],
  ['mitigation_20via_20build_20diversity_65',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['mitigation_3a_20diverse_20compilation_20not_20diverse_20hardware_66',['2.1 Primary mitigation: diverse compilation, not diverse hardware',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md85',1,'']]],
  ['mode_67',['mode',['../structsapi__timer__config__t.html#a5ddf924576714eef10035dd9d4756743',1,'sapi_timer_config_t']]],
  ['model_68',['model',['../buffer_architecture.html#buffer_architecture_ownership',1,'Ownership Model'],['../reboot_architecture.html#reboot_architecture_resource',1,'Resource Model'],['../timer_architecture.html#timer_architecture_storage',1,'Storage Model']]],
  ['model_3a_20caller_20owned_20view_20over_20static_20storage_69',['2.1 Ownership model: caller-owned view over static storage',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md26',1,'']]],
  ['modes_70',['Timer Modes',['../timer_user_guide.html#timer_user_guide_modes',1,'']]],
  ['modular_71',['NMR (N-Modular)',['../vital_channel_user_guide.html#vital_channel_user_guide_ss_nmr',1,'']]],
  ['module_72',['module',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md232',1,'2.7 Retirement of the old ADR-008 &lt;tt&gt;channel&lt;/tt&gt; module'],['../cast_user_guide.html#cast_user_guide_overview',1,'What is the Cast Module?'],['../memory_user_guide.html#memory_user_guide_overview',1,'What is the Memory Module?'],['../status_user_guide.html#status_user_guide_overview',1,'What is the Status Module?'],['../string_user_guide.html#string_user_guide_overview',1,'What is the String Module?'],['../safestate_architecture.html#safestate_architecture_integ_reboot',1,'With Reboot Module'],['../safestate_architecture.html#safestate_architecture_integ_watchdog',1,'With Watchdog Module']]],
  ['module_20architecture_73',['module architecture',['../buffer_architecture.html',1,'Buffer Module - Architecture'],['../cast_architecture.html',1,'Cast Module - Architecture'],['../checksum_architecture.html',1,'Checksum Module - Architecture'],['../log_architecture.html',1,'Log Module - Architecture'],['../memory_architecture.html',1,'Memory Module - Architecture'],['../reboot_architecture.html',1,'Reboot Module - Architecture'],['../safestate_architecture.html',1,'Safe-State Module - Architecture'],['../status_architecture.html',1,'Status Module - Architecture'],['../string_architecture.html',1,'String Module - Architecture'],['../task_architecture.html',1,'Task Queue Module - Architecture'],['../timer_architecture.html',1,'Timer Module - Architecture'],['../types_architecture.html',1,'Types Module - Architecture'],['../watchdog_architecture.html',1,'Watchdog Module - Architecture']]],
  ['module_20feature_20selection_20at_20configure_20time_74',['ADR-024: Per-Module Feature Selection at Configure Time',['../md_docs_2architecture_2ADR-024-configurable-feature-build.html',1,'']]],
  ['module_20one_20file_20per_20service_20one_20aggregator_75',['2.1 One module, one file per service, one aggregator',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md158',1,'']]],
  ['module_20req_20lifecycle_20001_20002_76',['2.1 A new, minimal &lt;tt&gt;sapi_lifecycle&lt;/tt&gt; module (REQ-LIFECYCLE-001/002)',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html#autotoc_md240',1,'']]],
  ['module_20structure_20adr_20007_20compliance_77',['Module Structure (ADR-007 compliance)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md100',1,'']]],
  ['module_20tt_20sapi_5fsafechannel_20tt_20not_20a_20repurposed_20tt_20sapi_5fchannel_20tt_78',['2.1 A new module, &lt;tt&gt;sapi_safechannel&lt;/tt&gt;, not a repurposed &lt;tt&gt;sapi_channel&lt;/tt&gt;',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html#autotoc_md198',1,'']]],
  ['module_20user_20guide_79',['module user guide',['../buffer_user_guide.html',1,'Buffer Module - User Guide'],['../cast_user_guide.html',1,'Cast Module - User Guide'],['../checksum_user_guide.html',1,'Checksum Module - User Guide'],['../log_user_guide.html',1,'Logging Module - User Guide'],['../memory_user_guide.html',1,'Memory Module - User Guide'],['../reboot_user_guide.html',1,'Reboot Module - User Guide'],['../safestate_user_guide.html',1,'Safe-State Module - User Guide'],['../status_user_guide.html',1,'Status Module - User Guide'],['../string_user_guide.html',1,'String Module - User Guide'],['../task_user_guide.html',1,'Task Queue Module - User Guide'],['../timer_user_guide.html',1,'Timer Module - User Guide'],['../types_user_guide.html',1,'Types Module - User Guide'],['../vital_channel_user_guide.html',1,'Vital Channel Module - User Guide'],['../watchdog_user_guide.html',1,'Watchdog Module - User Guide']]],
  ['modules_80',['With Existing Modules',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md109',1,'']]],
  ['monitoring_81',['monitoring',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md105',1,'4. Statistics &amp; Monitoring'],['../vital_channel_architecture.html#vital_channel_architecture_health_tracking',1,'Health Monitoring'],['../vital_channel_user_guide.html#vital_channel_user_guide_pattern_health',1,'Health Monitoring'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md424',1,'Pattern 2: Health Monitoring']]],
  ['monitoring_20loop_82',['Pattern 1: Health Monitoring Loop',['../safestate_user_guide.html#safestate_user_guide_pattern_health',1,'']]],
  ['moves_20behind_20the_20vtable_20tt_20safeapibackendposix_20tt_83',['2. POSIX implementation moves behind the vtable (&lt;tt&gt;safeAPIBackendPosix&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-035-platform-realtime-init.html#autotoc_md327',1,'']]],
  ['multi_20architecture_20docker_20builds_20sapi_20example_20app_20layer_84',['Multi-Architecture Docker Builds (SAPI example app layer)',['../md_docs_2CROSS__COMPILATION.html#autotoc_md442',1,'']]],
  ['multi_20threaded_85',['Pattern 3: Thread-Local State (Multi-Threaded)',['../memory_user_guide.html#memory_user_guide_pattern_thread',1,'']]],
  ['multi_20train_20protocol_20and_20failover_20ready_20session_20state_86',['ADR-029: RBC Train/IL/CTC Scenario - Real Multi-Train Protocol and Failover-Ready Session State',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html',1,'']]],
  ['multiplexed_20link_20per_20relay_20kind_20and_20tt_20c_20tt_20is_20a_20pure_20pipe_87',['2. One multiplexed link per relay kind - and &lt;tt&gt;C&lt;/tt&gt; is a pure pipe',['../md_docs_2architecture_2ADR-036-train-session-multiplexing.html#autotoc_md335',1,'']]],
  ['multiplexing_20one_20link_20many_20trains_20up_20to_20100_88',['ADR-036: Train-session multiplexing - one link, many trains (up to 100)',['../md_docs_2architecture_2ADR-036-train-session-multiplexing.html',1,'']]],
  ['mutex_20service_89',['Mutex Service',['../group__MUTEX.html',1,'']]],
  ['mutex_20service_20backend_20adaptation_90',['Mutex Service - Backend Adaptation',['../group__MUTEX__BACKEND.html',1,'']]],
  ['mutual_20exclusion_20primitive_91',['ADR-033: sapi_mutex - a portable mutual-exclusion primitive',['../md_docs_2architecture_2ADR-033-sapi-mutex.html',1,'']]]
];
