var searchData=
[
  ['qcc_20not_20found_0',['&quot;CMake not found&quot; / &quot;qcc not found&quot;',['../md_docs_2CROSS__COMPILATION.html#autotoc_md408',1,'']]],
  ['qnx_1',['3. Build for QNX',['../md_docs_2CROSS__COMPILATION.html#autotoc_md395',1,'']]],
  ['qnx_20application_2',['5. Use in Your QNX Application',['../md_docs_2CROSS__COMPILATION.html#autotoc_md397',1,'']]],
  ['qnx_20cmake_3',['Toolchain-QNX.cmake',['../md_docs_2CROSS__COMPILATION.html#autotoc_md405',1,'']]],
  ['qnx_20etc_4',['Cross-Compilation (Linux, QNX, etc.)',['../index.html#autotoc_md4',1,'']]],
  ['qnx_20presets_5',['QNX Presets',['../md_docs_2CROSS__COMPILATION.html#autotoc_md401',1,'']]],
  ['qnx_20rtos_6',['qnx rtos',['../md_docs_2CROSS__COMPILATION.html#autotoc_md392',1,'QNX RTOS'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md381',1,'QNX RTOS']]],
  ['qnx_20target_7',['4. Deploy to QNX Target',['../md_docs_2CROSS__COMPILATION.html#autotoc_md396',1,'']]],
  ['qnx_5fhost_20and_20qnx_5ftarget_20not_20set_8',['&quot;QNX_HOST and QNX_TARGET not set&quot;',['../md_docs_2CROSS__COMPILATION.html#autotoc_md409',1,'']]],
  ['qnx_5ftarget_20not_20set_9',['&quot;QNX_HOST and QNX_TARGET not set&quot;',['../md_docs_2CROSS__COMPILATION.html#autotoc_md409',1,'']]],
  ['query_10',['Query',['../watchdog_architecture.html#watchdog_architecture_api_query',1,'']]],
  ['queue_11',['queue',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md277',1,'2.6 Full-stack Docker hardening: a permanent safe-halt and an undersized queue'],['../task_user_guide.html#task_user_guide_overview',1,'What is Task Queue?']]],
  ['queue_20module_20architecture_12',['Task Queue Module - Architecture',['../task_architecture.html',1,'']]],
  ['queue_20module_20user_20guide_13',['Task Queue Module - User Guide',['../task_user_guide.html',1,'']]],
  ['queue_20operations_14',['Queue Operations',['../task_architecture.html#task_architecture_api',1,'']]],
  ['queue_5fdepth_15',['queue_depth',['../structsapi__ipc__pubsub__subscriber__config__t.html#a448a21e0e94c1be77091beca9f4a9436',1,'sapi_ipc_pubsub_subscriber_config_t::queue_depth'],['../structsapi__ipc__rr__server__config__t.html#a036f1a143c16916606dcfc80f41de910',1,'sapi_ipc_rr_server_config_t::queue_depth'],['../structsapi__ipc__config__t.html#a9b23692233e58588fe69ebc2a9a25bc2',1,'sapi_ipc_config_t::queue_depth']]],
  ['queues_16',['Pattern 2: Fixed-Size Queues',['../memory_user_guide.html#memory_user_guide_common_queue',1,'']]],
  ['quick_20examples_17',['Quick Examples',['../ipc_guide.html#ipc_guide_examples',1,'']]],
  ['quick_20start_18',['quick start',['../string_user_guide.html#string_user_guide_quick_start',1,'Quick Start'],['../log_user_guide.html#log_user_guide_quick_start',1,'Quick Start'],['../memory_user_guide.html#memory_user_guide_quick_start',1,'Quick Start'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md379',1,'Quick Start'],['../types_user_guide.html#types_user_guide_quick_start',1,'Quick Start'],['../nvm_user_guide.html#nvm_user_guide_quick_start',1,'Quick Start'],['../status_user_guide.html#status_user_guide_quick_start',1,'Quick Start'],['../safestate_user_guide.html#safestate_user_guide_quick_start',1,'Quick Start'],['../cast_user_guide.html#cast_user_guide_quick_start',1,'Quick Start'],['../buffer_user_guide.html#buffer_user_guide_quick_start',1,'Quick Start'],['../watchdog_user_guide.html#watchdog_user_guide_quick_start',1,'Quick Start'],['../checksum_user_guide.html#checksum_user_guide_quick_start',1,'Quick Start'],['../timer_user_guide.html#timer_user_guide_quick_start',1,'Quick Start'],['../task_user_guide.html#task_user_guide_quick_start',1,'Quick Start'],['../reboot_user_guide.html#reboot_user_guide_quick_start',1,'Quick Start']]],
  ['quick_20start_3a_202oo2_20dual_20redundant_20cpu_19',['Quick Start: 2oo2 Dual-Redundant CPU',['../vital_channel_user_guide.html#vital_channel_user_guide_quick_start',1,'']]],
  ['quo_20',['1. No Checksum (Status Quo)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md127',1,'']]],
  ['quorum_20requirements_21',['Quorum Requirements',['../vital_channel_architecture.html#vital_channel_architecture_quorum',1,'']]],
  ['quorum_5fsize_22',['quorum_size',['../structsapi__voter__config__t.html#a1a0b1b86c68c86839c6c62521c3276ab',1,'sapi_voter_config_t::quorum_size'],['../structsapi__safechannel__vital__config__t.html#abfb8e73f8ba2279368f5e27fa42fee88',1,'sapi_safechannel_vital_config_t::quorum_size']]]
];
