var searchData=
[
  ['c_0',['Pattern 1: Single-System 2oo2 (A ↔ B → C)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_single_2oo2',1,'']]],
  ['c_20abi_1',['3.1 Interface style: pure C ABI',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md13',1,'']]],
  ['c_20redesign_2',['2.4 Why this isn&apos;t a virtual-dispatch / C++ redesign',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md60',1,'']]],
  ['c11_20stdint_20h_20foundation_3',['C11 stdint.h Foundation',['../types_architecture.html#types_architecture_overview',1,'']]],
  ['c11_20tt_20_5fgeneric_20tt_4',['2.5 Why named functions instead of macros or C11 &lt;tt&gt;_Generic&lt;/tt&gt;',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md38',1,'']]],
  ['c_3a2012_5',['Static Analysis (MISRA C:2012)',['../index.html#autotoc_md6',1,'']]],
  ['c_3a2012_20compliance_6',['MISRA C:2012 Compliance',['../safestate_architecture.html#safestate_architecture_misra',1,'']]],
  ['calculate_20max_20requirements_7',['Calculate Max Requirements',['../memory_user_guide.html#memory_user_guide_sizing_calc',1,'']]],
  ['calculate_20required_20sizes_20upfront_8',['3. Calculate Required Sizes Upfront',['../memory_user_guide.html#memory_user_guide_qs_calculate',1,'']]],
  ['call_20no_20default_9',['2.5 Buffer endianness helpers: explicit per call, no default',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md71',1,'']]],
  ['call_20tt_20sapi_5freboot_20tt_20directly_10',['2.3 Why &lt;tt&gt;sapi_safestate&lt;/tt&gt; does not call &lt;tt&gt;sapi_reboot&lt;/tt&gt; directly',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md47',1,'']]],
  ['call_20tt_20strlen_20tt_20on_20unbounded_20untrusted_20input_11',['2.2 Never call &lt;tt&gt;strlen()&lt;/tt&gt; on unbounded/untrusted input',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md68',1,'']]],
  ['callback_12',['callback',['../timer_user_guide.html#timer_user_guide_qs_callback',1,'3. Implement Callback'],['../structsapi__timer__config__t.html#a417e21baafdf9292ac0f79364fb7b151',1,'sapi_timer_config_t::callback'],['../vital_channel_user_guide.html#vital_channel_user_guide_pattern_fault',1,'Fault Handling Callback']]],
  ['callback_20on_20timeout_13',['Example 2: Custom Callback on Timeout',['../watchdog_user_guide.html#watchdog_user_guide_example_custom',1,'']]],
  ['callback_20pattern_14',['Dispatcher Callback Pattern',['../channel_configuration.html#channel_configuration_dispatcher_callback',1,'']]],
  ['callback_20signature_15',['Callback Signature',['../timer_architecture.html#timer_architecture_callback',1,'']]],
  ['callbacks_16',['ADR-005: OAL Backend Registration via Callbacks',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html',1,'']]],
  ['caller_20owned_20view_20over_20static_20storage_17',['2.1 Ownership model: caller-owned view over static storage',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md26',1,'']]],
  ['capacity_18',['capacity',['../structsapi__buffer__t.html#a12702d063862983081335945184953a1',1,'sapi_buffer_t']]],
  ['cast_20module_19',['What is the Cast Module?',['../cast_user_guide.html#cast_user_guide_overview',1,'']]],
  ['cast_20module_20architecture_20',['Cast Module - Architecture',['../cast_architecture.html',1,'']]],
  ['cast_20module_20user_20guide_21',['Cast Module - User Guide',['../cast_user_guide.html',1,'']]],
  ['casting_22',['casting',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html',1,'ADR-003: Checked Integer Casting'],['../group__CAST.html',1,'Checked Integer Casting']]],
  ['cause_20failure_20mitigation_23',['Common-Cause-Failure Mitigation',['../system_architecture.html#system_architecture_ccf',1,'']]],
  ['ccf_20analysis_20is_20documented_20not_20implied_24',['2.3 CCF analysis is documented, not implied',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md87',1,'']]],
  ['ccf_20mitigation_20via_20build_20diversity_25',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['cd_20integration_26',['CI/CD Integration',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md209',1,'']]],
  ['certification_20documentation_27',['Certification Documentation',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md140',1,'']]],
  ['change_28',['2.3 What stays true from earlier ADRs despite the directory change',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md79',1,'']]],
  ['change_20slightly_29',['2.3 Status code semantics change slightly',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md59',1,'']]],
  ['channel_30',['channel',['../vital_channel_user_guide.html#vital_channel_user_guide_ss_2oo2',1,'2oo2 (Dual-Channel)'],['../vital_channel_user_guide.html#vital_channel_user_guide_ss_2oo3',1,'2oo3 (Triple-Channel)'],['../ipc_transport_selection.html#ipc_transport_selection_vital_channel_integration',1,'Integration with Vital Channel'],['../vital_channel_user_guide.html#vital_channel_user_guide_overview',1,'What is Vital Channel?']]],
  ['channel_20abstraction_31',['Vital Channel Abstraction',['../group__vital__channel.html',1,'']]],
  ['channel_20communication_20architecture_32',['Vital Channel Communication Architecture',['../vital_channel_architecture.html',1,'']]],
  ['channel_20configuration_20guide_33',['Channel Configuration Guide',['../channel_configuration.html',1,'']]],
  ['channel_20configuration_20pattern_34',['Channel Configuration Pattern',['../channel_configuration.html#channel_configuration_overview',1,'']]],
  ['channel_20identity_20and_20comparison_35',['Dual-Channel Identity and Comparison',['../group__CHANNEL.html',1,'']]],
  ['channel_20module_20user_20guide_36',['Vital Channel Module - User Guide',['../vital_channel_user_guide.html',1,'']]],
  ['channel_20topologies_20and_20redundancy_20patterns_37',['Channel Topologies and Redundancy Patterns',['../vital_channel_topologies.html',1,'']]],
  ['channel_20topology_20patterns_38',['Channel Topology Patterns',['../vital_channel_topologies.html#vital_channel_topologies_topology_overview',1,'']]],
  ['channel_20types_39',['Supported Channel Types',['../channel_configuration.html#channel_configuration_channel_types',1,'']]],
  ['channel_20vital_20architecture_20—_20ccf_20mitigation_20via_20build_20diversity_40',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['channel_20voting_20failure_41',['Example 1: Redundant Channel Voting Failure',['../safestate_user_guide.html#safestate_user_guide_example_voting',1,'']]],
  ['channel_5fconfiguration_42',['CHANNEL_CONFIGURATION',['../md_include_2safeapi_2ipc_2CHANNEL__CONFIGURATION.html',1,'']]],
  ['channel_5fcount_43',['channel_count',['../structsapi__vital__channel__config__t.html#aa5b7aac6a696145950eefef8d28e2fac',1,'sapi_vital_channel_config_t::channel_count'],['../structsapi__vital__channel__storage__t.html#a1dc78d0ad1031be80b1e2d569081fb07',1,'sapi_vital_channel_storage_t::channel_count']]],
  ['channel_5ftimeout_5fms_44',['channel_timeout_ms',['../structsapi__vital__channel__config__t.html#aa20b5431a16e5ad68702d9357cb11a95',1,'sapi_vital_channel_config_t']]],
  ['channel_5ftopologies_45',['CHANNEL_TOPOLOGIES',['../md_include_2safeapi_2vital__channel_2CHANNEL__TOPOLOGIES.html',1,'']]],
  ['channels_46',['channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'ADR-016: CRC-64 Data Integrity for Redundant Channels'],['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels'],['../appmanager_integration.html',1,'App Manager Integration with Channels'],['../structsapi__vital__channel__storage__t.html#a411d6a2b474919b71d66a10c281bcc32',1,'sapi_vital_channel_storage_t::channels']]],
  ['channels_20for_20vital_20communication_47',['Creating Channels for Vital Communication',['../channel_configuration.html#channel_configuration_channel_creation',1,'']]],
  ['check_20algorithm_20why_20it_20s_20correct_20without_20triggering_20tt_20wsign_20conversion_20tt_48',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]],
  ['check_20before_20convert_49',['Check-Before-Convert',['../cast_architecture.html#cast_architecture_strategy',1,'']]],
  ['check_20watchdog_20status_50',['Pattern 2: Check Watchdog Status',['../watchdog_user_guide.html#watchdog_user_guide_pattern_status',1,'']]],
  ['checked_20assertions_51',['checked assertions',['../safestate_user_guide.html#safestate_user_guide_qs_assert',1,'2. Use SAPI_ASSERT for Checked Assertions'],['../md_docs_2architecture_2ADR-004-safe-state-transitions.html',1,'ADR-004: Safe-State Transitions and Checked Assertions'],['../group__SAFESTATE.html',1,'Safe-State Transitions and Checked Assertions']]],
  ['checked_20integer_20casting_52',['checked integer casting',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html',1,'ADR-003: Checked Integer Casting'],['../group__CAST.html',1,'Checked Integer Casting']]],
  ['checklist_53',['Implementation Checklist',['../ipc_transport_selection.html#ipc_transport_selection_implementation_checklist',1,'']]],
  ['checkpoint_20flow_54',['6. Activity Diagram (Behavioral - Checkpoint Flow)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md196',1,'']]],
  ['checkpoint_20rendezvous_55',['Checkpoint Rendezvous',['../group__CHECKPOINT.html',1,'']]],
  ['checkpoint_20rendezvous_20and_20clock_20synchronization_20for_20distributed_20vital_20channels_56',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['checkpoint_5fid_57',['checkpoint_id',['../structsapi__checkpoint__config__t.html#a913ef1efa939a3713153a9a5761a1151',1,'sapi_checkpoint_config_t']]],
  ['checksum_58',['What is Checksum?',['../checksum_user_guide.html#checksum_user_guide_overview',1,'']]],
  ['checksum_20crc_20utilities_59',['Checksum &amp; CRC Utilities',['../group__CHECKSUM.html',1,'']]],
  ['checksum_20module_20architecture_60',['Checksum Module - Architecture',['../checksum_architecture.html',1,'']]],
  ['checksum_20module_20user_20guide_61',['Checksum Module - User Guide',['../checksum_user_guide.html',1,'']]],
  ['checksum_20status_20quo_62',['1. No Checksum (Status Quo)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md127',1,'']]],
  ['choose_20a_20topology_63',['How to Choose a Topology',['../vital_channel_topologies.html#vital_channel_topologies_selecting_topology',1,'']]],
  ['ci_20cd_20integration_64',['CI/CD Integration',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md209',1,'']]],
  ['clear_65',['Clear',['../buffer_user_guide.html#buffer_user_guide_op_clear',1,'']]],
  ['clock_20synchronization_20diagnostic_20timeout_20sizing_20only_66',['Clock Synchronization (diagnostic/timeout-sizing only)',['../group__CLOCKSYNC.html',1,'']]],
  ['clock_20synchronization_20for_20distributed_20vital_20channels_67',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['close_68',['close',['../structsapi__netlink__backend__t.html#a9f83bab6f55c2130ff20f0eed805d92e',1,'sapi_netlink_backend_t::close'],['../structsapi__nvm__backend__t.html#ad0de5482afe56edabbf9e5337804a69a',1,'sapi_nvm_backend_t::close']]],
  ['cmake_69',['cmake',['../md_docs_2CROSS__COMPILATION.html#autotoc_md249',1,'Toolchain-Linux.cmake'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md250',1,'Toolchain-QNX.cmake']]],
  ['cmake_20invocation_70',['Manual CMake invocation',['../index.html#autotoc_md5',1,'']]],
  ['cmake_20not_20found_20qcc_20not_20found_71',['&quot;CMake not found&quot; / &quot;qcc not found&quot;',['../md_docs_2CROSS__COMPILATION.html#autotoc_md253',1,'']]],
  ['cmake_20presets_20recommended_72',['Using CMake Presets (recommended)',['../index.html#autotoc_md3',1,'']]],
  ['cmake_20presets_20reference_73',['CMake Presets Reference',['../md_docs_2CROSS__COMPILATION.html#autotoc_md244',1,'']]],
  ['cmake_20target_20per_20feature_74',['2.2 One CMake target per feature',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md78',1,'']]],
  ['code_75',['2.4 New status code',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md37',1,'']]],
  ['code_20allocation_20strategy_76',['Code Allocation Strategy',['../status_architecture.html#status_architecture_code_allocation',1,'']]],
  ['code_20definitions_77',['Status Code Definitions',['../status_architecture.html#status_architecture_status_codes',1,'']]],
  ['code_20handling_78',['Reason Code Handling',['../reboot_architecture.html#reboot_architecture_reason',1,'']]],
  ['code_20reference_79',['Complete Status Code Reference',['../status_user_guide.html#status_user_guide_status_codes',1,'']]],
  ['code_20semantics_20change_20slightly_80',['2.3 Status code semantics change slightly',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md59',1,'']]],
  ['code_20strategy_81',['Reason Code Strategy',['../safestate_architecture.html#safestate_architecture_reason_codes',1,'']]],
  ['codes_82',['codes',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md130',1,'4. Hamming Codes'],['../status_architecture.html#status_architecture_extension',1,'Application-Specific Codes'],['../safestate_user_guide.html#safestate_user_guide_app_reason_codes',1,'Application-Specific Reason Codes'],['../group__STATUS.html',1,'Common Status and Error Codes'],['../reboot_user_guide.html#reboot_user_guide_reason_codes',1,'Reason Codes']]],
  ['codes_20to_20safety_20actions_83',['Status Codes to Safety Actions',['../status_user_guide.html#status_user_guide_mapping',1,'']]],
  ['comments_84',['Embedding Diagrams in Doxygen Comments',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md198',1,'']]],
  ['common_20cause_20failure_20mitigation_85',['Common-Cause-Failure Mitigation',['../system_architecture.html#system_architecture_ccf',1,'']]],
  ['common_20diagram_20patterns_20for_20safety_20critical_20systems_86',['Common Diagram Patterns for Safety-Critical Systems',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md217',1,'']]],
  ['common_20patterns_87',['common patterns',['../memory_user_guide.html#memory_user_guide_patterns',1,'Common Patterns'],['../watchdog_user_guide.html#watchdog_user_guide_patterns',1,'Common Patterns'],['../vital_channel_user_guide.html#vital_channel_user_guide_patterns',1,'Common Patterns'],['../safestate_user_guide.html#safestate_user_guide_patterns',1,'Common Patterns']]],
  ['common_20status_20and_20error_20codes_88',['Common Status and Error Codes',['../group__STATUS.html',1,'']]],
  ['common_20tt_20tt_20os_20tt_20grouping_20folder_20is_20dropped_20not_20renamed_89',['2.1 The &lt;tt&gt;common&lt;/tt&gt;/&lt;tt&gt;os&lt;/tt&gt; grouping folder is dropped, not renamed',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md77',1,'']]],
  ['common_20types_90',['Common Types',['../group__TYPES.html',1,'']]],
  ['communication_91',['communication',['../channel_configuration.html#channel_configuration_channel_creation',1,'Creating Channels for Vital Communication'],['../group__IPC.html',1,'Inter-Process Communication']]],
  ['communication_20architecture_92',['Vital Channel Communication Architecture',['../vital_channel_architecture.html',1,'']]],
  ['communication_20flow_202oo2_20example_93',['Communication Flow (2oo2 Example)',['../vital_channel_architecture.html#vital_channel_architecture_communication_flow',1,'']]],
  ['communication_20guide_94',['IPC (Inter-Process Communication) Guide',['../ipc_guide.html',1,'']]],
  ['communication_20ipc_20transport_20layer_95',['Inter-Process Communication (IPC) Transport Layer',['../ipc_transport_selection.html#ipc_transport_selection_overview',1,'']]],
  ['comparator_20identity_96',['2.2 New feature: &lt;tt&gt;sapi_channel&lt;/tt&gt; (comparator + identity)',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md86',1,'']]],
  ['comparison_97',['comparison',['../group__CHANNEL.html',1,'Dual-Channel Identity and Comparison'],['../vital_channel_topologies.html#vital_channel_topologies_topology_comparison',1,'Summary Comparison']]],
  ['compilation_20guide_98',['Cross-Compilation Guide',['../md_docs_2CROSS__COMPILATION.html',1,'']]],
  ['compilation_20linux_20qnx_20etc_99',['Cross-Compilation (Linux, QNX, etc.)',['../index.html#autotoc_md4',1,'']]],
  ['compilation_20not_20diverse_20hardware_100',['2.1 Primary mitigation: diverse compilation, not diverse hardware',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md85',1,'']]],
  ['compile_101',['Linux (Native or Cross-compile)',['../md_docs_2CROSS__COMPILATION.html#autotoc_md227',1,'']]],
  ['compile_20time_102',['Verify at Compile-Time',['../memory_user_guide.html#memory_user_guide_sizing_verify',1,'']]],
  ['compile_20time_20or_20initialization_103',['2. Allocate at Compile-Time or Initialization',['../memory_user_guide.html#memory_user_guide_qs_allocate',1,'']]],
  ['compiled_20targets_104',['Tests fail on cross-compiled targets',['../md_docs_2CROSS__COMPILATION.html#autotoc_md255',1,'']]],
  ['compiler_20warnings_20treated_20as_20errors_105',['&quot;Compiler warnings treated as errors&quot;',['../md_docs_2CROSS__COMPILATION.html#autotoc_md256',1,'']]],
  ['complete_20example_106',['Complete Example',['../appmanager_integration.html#appmanager_integration_complete_example',1,'']]],
  ['complete_20status_20code_20reference_107',['Complete Status Code Reference',['../status_user_guide.html#status_user_guide_status_codes',1,'']]],
  ['complexity_108',['Complexity',['../task_architecture.html#task_architecture_performance',1,'']]],
  ['compliance_109',['compliance',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md111',1,'EN 50128 Compliance'],['../safestate_architecture.html#safestate_architecture_misra',1,'MISRA C:2012 Compliance'],['../types_architecture.html#types_architecture_misra',1,'MISRA Compliance'],['../status_architecture.html#status_architecture_misra',1,'MISRA Compliance'],['../reboot_architecture.html#reboot_architecture_misra',1,'MISRA Compliance'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md100',1,'Module Structure (ADR-007 compliance)']]],
  ['compliant_110',['MISRA Compliant',['../checksum_architecture.html#checksum_architecture_misra',1,'']]],
  ['component_20diagram_20structural_111',['1. Component Diagram (Structural)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md186',1,'']]],
  ['computation_112',['Computation',['../checksum_architecture.html#checksum_architecture_compute',1,'']]],
  ['computed_113',['computed',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md102',1,'1. Lookup Tables (Pre-computed)'],['../structsapi__checksum__result__t.html#a8dbeda49f433b5e14e809894635cd1ec',1,'sapi_checksum_result_t::computed']]],
  ['conditional_20kick_20fail_20safe_20default_114',['Pattern 1: Conditional Kick (Fail-Safe Default)',['../watchdog_user_guide.html#watchdog_user_guide_pattern_conditional',1,'']]],
  ['config_115',['config',['../structsapi__watchdog__s.html#acb195ceb84f2ab57782d8361575ddf11',1,'sapi_watchdog_s::config'],['../structsapi__vital__channel__storage__t.html#a6bab703ba7f263d049c88c9e30e15dfa',1,'sapi_vital_channel_storage_t::config']]],
  ['configuration_116',['configuration',['../timer_architecture.html#timer_architecture_config',1,'Configuration'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md207',1,'Doxygen Configuration']]],
  ['configuration_20guide_117',['Channel Configuration Guide',['../channel_configuration.html',1,'']]],
  ['configuration_20parameter_20summary_118',['Configuration Parameter Summary',['../channel_configuration.html#channel_configuration_configuration_summary',1,'']]],
  ['configuration_20pattern_119',['Channel Configuration Pattern',['../channel_configuration.html#channel_configuration_overview',1,'']]],
  ['configuration_20sequences_120',['Behavioral Diagrams - Configuration Sequences',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md167',1,'']]],
  ['configurations_121',['Recommended Configurations',['../ipc_transport_selection.html#ipc_transport_selection_recommended_configurations',1,'']]],
  ['configure_20doxygen_122',['2. Configure Doxygen',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md182',1,'']]],
  ['connect_5ftimeout_5fms_123',['connect_timeout_ms',['../structsapi__netlink__config__t.html#a5c0e90d4aa6e42aa6f417104bbca5690',1,'sapi_netlink_config_t']]],
  ['consequences_124',['consequences',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md153',1,'3. Consequences'],['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md62',1,'3. Consequences'],['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md162',1,'3. Consequences'],['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md72',1,'3. Consequences'],['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md40',1,'3. Consequences'],['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md88',1,'3. Consequences'],['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md80',1,'3. Consequences'],['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md29',1,'3. Consequences'],['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md52',1,'4. Consequences'],['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md21',1,'6. Consequences']]],
  ['considered_125',['Alternatives Considered',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md126',1,'']]],
  ['consistency_126',['2. Consistency',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md213',1,'']]],
  ['constraints_127',['constraints',['../timer_architecture.html#timer_architecture_limits',1,'Constraints'],['../watchdog_architecture.html#watchdog_architecture_limits',1,'Constraints']]],
  ['context_128',['context',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md148',1,'1. Context'],['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md156',1,'1. Context'],['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md75',1,'1. Context'],['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md83',1,'1. Context'],['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md32',1,'1. Context'],['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md65',1,'1. Context'],['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md55',1,'1. Context'],['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md43',1,'1. Context'],['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md24',1,'1. Context'],['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md10',1,'1. Context'],['../structsapi__watchdog__config__t.html#ae10391fdc1e795ba00e050e2445f9892',1,'sapi_watchdog_config_t::context'],['../structsapi__vital__channel__config__t.html#a50d352e139f9fa8756abe8560f8a35b6',1,'sapi_vital_channel_config_t::context'],['../structsapi__appmanager__config__t.html#adde654d86a83ca31736d71b5a5852dd0',1,'sapi_appmanager_config_t::context'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md92',1,'Context']]],
  ['control_129',['4. Version Control',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md215',1,'']]],
  ['control_20system_130',['Example 1: Train Control System',['../memory_user_guide.html#memory_user_guide_example_train',1,'']]],
  ['controlled_20reboot_131',['Controlled Reboot',['../group__REBOOT.html',1,'']]],
  ['convenience_20macros_132',['Convenience Macros',['../safestate_architecture.html#safestate_architecture_api_macros',1,'']]],
  ['conventions_133',['3.3 Naming conventions',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md15',1,'']]],
  ['conversion_134',['String Conversion',['../status_architecture.html#status_architecture_conversion',1,'']]],
  ['conversion_20functions_135',['Conversion Functions',['../cast_architecture.html#cast_architecture_functions',1,'']]],
  ['conversion_20tt_136',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]],
  ['conversions_137',['Available Conversions',['../cast_user_guide.html#cast_user_guide_conversions',1,'']]],
  ['convert_138',['Check-Before-Convert',['../cast_architecture.html#cast_architecture_strategy',1,'']]],
  ['core_20api_139',['core api',['../timer_architecture.html#timer_architecture_api',1,'Core API'],['../safestate_architecture.html#safestate_architecture_api',1,'Core API'],['../watchdog_architecture.html#watchdog_architecture_api',1,'Core API'],['../buffer_architecture.html#buffer_architecture_api',1,'Core API']]],
  ['core_20api_20v0_203_200_140',['Phase 1: Core API (v0.3.0)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md120',1,'']]],
  ['core_20functions_141',['Core Functions',['../string_architecture.html#string_architecture_functions',1,'']]],
  ['correct_20without_20triggering_20tt_20wsign_20conversion_20tt_142',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]],
  ['correctness_143',['2.3 &lt;tt&gt;sapi_clocksync&lt;/tt&gt;: diagnostic only, never the basis of correctness',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md152',1,'']]],
  ['corruption_20detection_144',['Example 2: Memory Corruption Detection',['../reboot_user_guide.html#reboot_user_guide_example_memory',1,'']]],
  ['counters_145',['Example 2: Sized Counters',['../types_user_guide.html#types_user_guide_example_counter',1,'']]],
  ['covered_146',['2.3 Operations covered',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md69',1,'']]],
  ['cpu_147',['Quick Start: 2oo2 Dual-Redundant CPU',['../vital_channel_user_guide.html#vital_channel_user_guide_quick_start',1,'']]],
  ['crc_2032_20only_148',['2. CRC-32 Only',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md128',1,'']]],
  ['crc_2064_20data_20integrity_20for_20redundant_20channels_149',['ADR-016: CRC-64 Data Integrity for Redundant Channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'']]],
  ['crc_2064_20is_20right_20for_20sapi_150',['Why CRC-64 is Right for SAPI',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md95',1,'']]],
  ['crc_20utilities_151',['Checksum &amp; CRC Utilities',['../group__CHECKSUM.html',1,'']]],
  ['crc64_152',['crc64',['../structsapi__vital__message__t.html#a18d5da8bd29b3b016f4da13ad8893150',1,'sapi_vital_message_t']]],
  ['create_153',['create',['../structsapi__mem__pool__backend__t.html#ae8fbe9e393f70fca73baeb5df777ddf7',1,'sapi_mem_pool_backend_t::create'],['../structsapi__timer__backend__t.html#a8f09223db6a8b6aa28279e15f786c472',1,'sapi_timer_backend_t::create'],['../structsapi__task__backend__t.html#a8b20d555d130c0bec62f4d7994f44e05',1,'sapi_task_backend_t::create'],['../structsapi__ipc__backend__t.html#a66f30d1c595623e38ad851da9deabb7a',1,'sapi_ipc_backend_t::create']]],
  ['create_20timer_154',['1. Create Timer',['../timer_user_guide.html#timer_user_guide_qs_create',1,'']]],
  ['create_20watchdog_155',['2. Create Watchdog',['../watchdog_user_guide.html#watchdog_user_guide_qs_create',1,'']]],
  ['creating_20channels_20for_20vital_20communication_156',['Creating Channels for Vital Communication',['../channel_configuration.html#channel_configuration_channel_creation',1,'']]],
  ['creation_157',['Creation',['../watchdog_architecture.html#watchdog_architecture_api_create',1,'']]],
  ['critical_20error_158',['2. Request Reboot on Critical Error',['../reboot_user_guide.html#reboot_user_guide_qs_request',1,'']]],
  ['critical_20systems_159',['Common Diagram Patterns for Safety-Critical Systems',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md217',1,'']]],
  ['critical_20systems_20need_20guarantees_160',['Safety-Critical Systems Need Guarantees',['../memory_user_guide.html#memory_user_guide_rationale_comparison',1,'']]],
  ['cross_20compilation_20guide_161',['Cross-Compilation Guide',['../md_docs_2CROSS__COMPILATION.html',1,'']]],
  ['cross_20compilation_20linux_20qnx_20etc_162',['Cross-Compilation (Linux, QNX, etc.)',['../index.html#autotoc_md4',1,'']]],
  ['cross_20compile_163',['Linux (Native or Cross-compile)',['../md_docs_2CROSS__COMPILATION.html#autotoc_md227',1,'']]],
  ['cross_20compiled_20targets_164',['Tests fail on cross-compiled targets',['../md_docs_2CROSS__COMPILATION.html#autotoc_md255',1,'']]],
  ['cross_20layer_20data_20buffer_165',['Cross-Layer Data Buffer',['../group__BUFFER.html',1,'']]],
  ['cross_20layer_20data_20buffer_20abstraction_166',['ADR-002: Cross-Layer Data Buffer Abstraction',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html',1,'']]],
  ['custom_20callback_20on_20timeout_167',['Example 2: Custom Callback on Timeout',['../watchdog_user_guide.html#watchdog_user_guide_example_custom',1,'']]],
  ['custom_5faction_168',['custom_action',['../structsapi__watchdog__config__t.html#a0f7256f3541235e2d6a87e881518ed49',1,'sapi_watchdog_config_t']]]
];
