var searchData=
[
  ['random_20vs_20systematic_20error_20detection_0',['Random vs Systematic Error Detection',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md113',1,'']]],
  ['range_20check_20algorithm_20why_20it_20s_20correct_20without_20triggering_20tt_20wsign_20conversion_20tt_1',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]],
  ['ranges_2',['Type Ranges',['../types_user_guide.html#types_user_guide_ranges',1,'']]],
  ['rationale_3',['Design Rationale',['../status_architecture.html#status_architecture_rationale',1,'']]],
  ['raw_20link_20liveness_20and_20ordering_20closing_20a_20real_20docker_20confirmed_20regression_4',['2.4 Phase 2: raw-link liveness and ordering, closing a real Docker-confirmed regression',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md253',1,'']]],
  ['rbc_20train_20il_20ctc_20scenario_20—_20tt_20safeapirbc2oo2_20tt_20adr_20029_5',['3h. RBC Train/IL/CTC scenario — &lt;tt&gt;safeAPIRBC2oo2&lt;/tt&gt; (ADR-029)',['../safeapi_srs.html#autotoc_md462',1,'']]],
  ['rbc_20train_20il_20ctc_20scenario_20real_20multi_20train_20protocol_20and_20failover_20ready_20session_20state_6',['ADR-029: RBC Train/IL/CTC Scenario - Real Multi-Train Protocol and Failover-Ready Session State',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html',1,'']]],
  ['read_7',['read',['../structsapi__nvm__backend__t.html#a946711f74b92fe96d7c0b575c95ffab6',1,'sapi_nvm_backend_t']]],
  ['read_20data_8',['Read Data',['../buffer_user_guide.html#buffer_user_guide_op_read',1,'']]],
  ['read_20only_20view_9',['Example 2: Read-Only View',['../buffer_user_guide.html#buffer_user_guide_example_ringbuf',1,'']]],
  ['read_20write_20interface_10',['Read/Write Interface',['../nvm_architecture.html#nvm_architecture_api',1,'']]],
  ['readiness_20already_20built_20just_20surfaced_11',['2.2 Negotiation link: HOT/COLD standby readiness (already built, just surfaced)',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md262',1,'']]],
  ['ready_20session_20state_12',['ADR-029: RBC Train/IL/CTC Scenario - Real Multi-Train Protocol and Failover-Ready Session State',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html',1,'']]],
  ['real_20bug_3a_20the_20cyclic_20executive_20starves_20whenever_20checkpoint_20is_20paused_13',['2.4 The real bug: the cyclic executive starves whenever checkpoint is paused',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md264',1,'']]],
  ['real_20command_20channel_14',['2.7 Dual-homed sims and a real command channel',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md278',1,'']]],
  ['real_20debugging_20story_3a_20three_20genuine_20synchronization_20bugs_15',['2.5 The real debugging story: three genuine synchronization bugs',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md276',1,'']]],
  ['real_20docker_20confirmed_20regression_16',['2.4 Phase 2: raw-link liveness and ordering, closing a real Docker-confirmed regression',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md253',1,'']]],
  ['real_20means_20here_20and_20what_20it_20deliberately_20doesn_20t_17',['2.3 What &quot;real&quot; means here, and what it deliberately doesn&apos;t',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md160',1,'']]],
  ['real_20multi_20train_20protocol_20and_20failover_20ready_20session_20state_18',['ADR-029: RBC Train/IL/CTC Scenario - Real Multi-Train Protocol and Failover-Ready Session State',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html',1,'']]],
  ['real_20non_20zero_20startup_20latency_20two_20related_20fixes_19',['2.3 A UDP handshake has real, non-zero startup latency - two related fixes',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md252',1,'']]],
  ['real_20posix_20linux_20oal_20backend_20',['ADR-018: A Real POSIX/Linux OAL Backend',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html',1,'']]],
  ['real_20time_20bring_20up_21',['ADR-035: &lt;tt&gt;sapi_platform&lt;/tt&gt; OAL service for real-time bring-up',['../md_docs_2architecture_2ADR-035-platform-realtime-init.html',1,'']]],
  ['real_20time_20platform_20configuration_22',['Real-Time Platform Configuration',['../group__PLATFORM.html',1,'']]],
  ['real_20time_20platform_20configuration_20—_20tt_20sapi_5fplatform_20h_20tt_20adr_20035_23',['2.9 Real-time platform configuration — &lt;tt&gt;sapi_platform.h&lt;/tt&gt; (ADR-035)',['../safeapi_srs.html#autotoc_md443',1,'']]],
  ['real_20time_20platform_20configuration_20backend_20adaptation_24',['Real-Time Platform Configuration - Backend Adaptation',['../group__PLATFORM__BACKEND.html',1,'']]],
  ['real_20world_20impact_25',['Real-World Impact',['../memory_user_guide.html#memory_user_guide_rationale_example',1,'']]],
  ['realtime_5finit_26',['realtime_init',['../structsapi__platform__backend__t.html#a066724f081e3c7b99653f6aeaff43e09',1,'sapi_platform_backend_t']]],
  ['reason_20code_20handling_27',['Reason Code Handling',['../reboot_architecture.html#reboot_architecture_reason',1,'']]],
  ['reason_20code_20strategy_28',['Reason Code Strategy',['../safestate_architecture.html#safestate_architecture_reason_codes',1,'']]],
  ['reason_20codes_29',['reason codes',['../safestate_user_guide.html#safestate_user_guide_app_reason_codes',1,'Application-Specific Reason Codes'],['../reboot_user_guide.html#reboot_user_guide_reason_codes',1,'Reason Codes']]],
  ['reasons_200_204095_30',['Framework Reasons (0-4095)',['../safestate_architecture.html#safestate_architecture_reason_framework',1,'']]],
  ['reasons_204096_31',['Application Reasons (4096+)',['../safestate_architecture.html#safestate_architecture_reason_application',1,'']]],
  ['reboot_32',['reboot',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md265',1,'2.5 Known open item: manual ONLINE confirmation on simultaneous dual-reboot'],['../group__REBOOT.html',1,'Controlled Reboot'],['../reboot_user_guide.html#reboot_user_guide_example_watchdog',1,'Example 1: Watchdog-Triggered Reboot'],['../reboot_user_guide.html#reboot_user_guide_overview',1,'What is Reboot?']]],
  ['reboot_20—_20tt_20sapi_5freboot_20h_20tt_20adr_20004_20§3_33',['2.7 Controlled reboot — &lt;tt&gt;sapi_reboot.h&lt;/tt&gt; (ADR-004 §3)',['../safeapi_srs.html#autotoc_md441',1,'']]],
  ['reboot_20after_20a_20sustained_20outage_34',['2.1 Same-site channels: REBOOT after a sustained outage',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md261',1,'']]],
  ['reboot_20and_20a_20cyclic_20executive_20starvation_20fix_35',['ADR-028: Channel-Down Escalation to REBOOT, and a Cyclic-Executive Starvation Fix',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html',1,'']]],
  ['reboot_20backend_20adaptation_36',['Controlled Reboot - Backend Adaptation',['../group__REBOOT__BACKEND.html',1,'']]],
  ['reboot_20flow_37',['Reboot Flow',['../reboot_architecture.html#reboot_architecture_flow',1,'']]],
  ['reboot_20level_202_38',['REBOOT (Level 2)',['../safestate_user_guide.html#safestate_user_guide_level_reboot',1,'']]],
  ['reboot_20module_39',['With Reboot Module',['../safestate_architecture.html#safestate_architecture_integ_reboot',1,'']]],
  ['reboot_20module_20architecture_40',['Reboot Module - Architecture',['../reboot_architecture.html',1,'']]],
  ['reboot_20module_20user_20guide_41',['Reboot Module - User Guide',['../reboot_user_guide.html',1,'']]],
  ['reboot_20on_20critical_20error_42',['2. Request Reboot on Critical Error',['../reboot_user_guide.html#reboot_user_guide_qs_request',1,'']]],
  ['reboot_20with_20fallback_43',['Example 3: Reboot with Fallback',['../reboot_user_guide.html#reboot_user_guide_example_fallback',1,'']]],
  ['rebuild_20it_44',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['receive_45',['receive',['../structsapi__netlink__backend__t.html#ad1dc5bca6bb4cb15229cebdd4340e494',1,'sapi_netlink_backend_t::receive'],['../structsapi__ipc__backend__t.html#afaede7ddbe9ca2a0c80e6e3bd5ecc9b0',1,'sapi_ipc_backend_t::receive']]],
  ['receive_20semantics_20voting_46',['Receive Semantics (Voting)',['../vital_channel_architecture.html#vital_channel_architecture_receive_semantics',1,'']]],
  ['receive_5fcount_47',['receive_count',['../structsapi__channel__health__t.html#a894f008c71294931d8f1c61060c93f46',1,'sapi_channel_health_t']]],
  ['receive_5ferror_5fcount_48',['receive_error_count',['../structsapi__channel__health__t.html#ad2744a94da5d2dd3f40fd2e9455a132f',1,'sapi_channel_health_t']]],
  ['recommended_49',['Using CMake Presets (recommended)',['../index.html#autotoc_md3',1,'']]],
  ['recommended_20configurations_50',['Recommended Configurations',['../ipc_transport_selection.html#ipc_transport_selection_recommended_configurations',1,'']]],
  ['reconciliation_20not_20a_20framework_20change_51',['5.3 Safety-policy reconciliation, not a framework change',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md175',1,'']]],
  ['reconnect_20livelock_52',['2.6 Known correlation with ADR-027 §2.5&apos;s open reconnect livelock',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md266',1,'']]],
  ['reconnect_20livelock_20between_20two_20independently_20retrying_20endpoints_53',['2.5 Known open issue: reconnect livelock between two independently-retrying endpoints',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md254',1,'']]],
  ['recoveries_54',['recoveries',['../structsapi__watchdog__status__t.html#a1695a29f4470c911073b0943c4451a89',1,'sapi_watchdog_status_t::recoveries'],['../structsapi__watchdog__s.html#a3dd18e803fd5c248cb2cd68f61aa24dc',1,'sapi_watchdog_s::recoveries']]],
  ['recovery_20actions_55',['recovery actions',['../watchdog_architecture.html#watchdog_architecture_recovery',1,'Recovery Actions'],['../watchdog_user_guide.html#watchdog_user_guide_actions',1,'Recovery Actions']]],
  ['recv_56',['recv',['../structsapi__channel__config__t.html#aa8cc1353520131082a4bed96d11dea6a',1,'sapi_channel_config_t']]],
  ['redesign_57',['2.4 Why this isn&apos;t a virtual-dispatch / C++ redesign',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md60',1,'']]],
  ['redundancy_58',['3. Sequence Diagram (Behavioral - Redundancy)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md351',1,'']]],
  ['redundancy_202oo3_59',['Pattern 4: Triple Redundancy (2oo3)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_2oo3',1,'']]],
  ['redundancy_20framework_20future_20v0_204_200_60',['With Redundancy Framework (Future v0.4.0+)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md108',1,'']]],
  ['redundancy_20patterns_61',['redundancy patterns',['../vital_channel_topologies.html',1,'Channel Topologies and Redundancy Patterns'],['../ipc_transport_selection.html#ipc_transport_selection_online_standby_patterns',1,'Online/Standby Redundancy Patterns']]],
  ['redundant_20channel_20voting_20failure_62',['Example 1: Redundant Channel Voting Failure',['../safestate_user_guide.html#safestate_user_guide_example_voting',1,'']]],
  ['redundant_20channels_63',['ADR-016: CRC-64 Data Integrity for Redundant Channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'']]],
  ['redundant_20cpu_64',['Quick Start: 2oo2 Dual-Redundant CPU',['../vital_channel_user_guide.html#vital_channel_user_guide_quick_start',1,'']]],
  ['redundant_20link_65',['Channel Link (single redundant link)',['../group__channel__link.html',1,'']]],
  ['redundant_20systems_66',['SIL 3-4 (Redundant Systems)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md117',1,'']]],
  ['reentrant_20unlike_20tt_20strtok_20tt_67',['2.4 Splitting is reentrant, unlike &lt;tt&gt;strtok&lt;/tt&gt;',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md70',1,'']]],
  ['reference_68',['reference',['../md_docs_2CROSS__COMPILATION.html#autotoc_md407',1,'CMake Presets Reference'],['../status_user_guide.html#status_user_guide_status_codes',1,'Complete Status Code Reference']]],
  ['references_69',['references',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md144',1,'References'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md383',1,'References'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md423',1,'References']]],
  ['region_5fname_70',['region_name',['../structsapi__nvm__config__t.html#a9693d58c9386ca2177eebaf3e3221e78',1,'sapi_nvm_config_t']]],
  ['region_5fsize_71',['region_size',['../structsapi__nvm__config__t.html#ab21d1d72e4be6fa34a629ec9993506fb',1,'sapi_nvm_config_t']]],
  ['register_20backend_20at_20startup_72',['1. Register Backend at Startup',['../reboot_user_guide.html#reboot_user_guide_qs_backend',1,'']]],
  ['register_20dispatch_20are_20hand_20written_20per_20call_20site_20not_20generated_73',['2.2 Init/register/dispatch are hand-written per call site, not generated',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html#autotoc_md285',1,'']]],
  ['register_20handler_20at_20startup_74',['1. Register Handler at Startup',['../safestate_user_guide.html#safestate_user_guide_qs_register',1,'']]],
  ['registered_75',['2.2 One handler per level, application-registered',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md46',1,'']]],
  ['registered_20callback_20list_20shape_76',['ADR-030: &lt;tt&gt;sapi_notify&lt;/tt&gt; - fixed-capacity registered-callback list shape',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html',1,'']]],
  ['registered_20callback_20list_20storage_20shape_77',['Registered-Callback List Storage Shape',['../group__NOTIFY.html',1,'']]],
  ['registration_78',['Registration',['../safestate_architecture.html#safestate_architecture_api_register',1,'']]],
  ['registration_20and_20invocation_79',['Test 1: Handler Registration and Invocation',['../safestate_architecture.html#safestate_architecture_test_handler',1,'']]],
  ['registration_20and_20remaining_20setup_20only_20constructors_80',['ADR-032: Setup-phase lock coverage extended to backend registration and remaining setup-only constructors',['../md_docs_2architecture_2ADR-032-setup-phase-lock-coverage-extended.html',1,'']]],
  ['registration_20function_20per_20service_81',['2.1 One backend vtable type and one registration function per service',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md57',1,'']]],
  ['registration_20via_20callbacks_82',['ADR-005: OAL Backend Registration via Callbacks',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html',1,'']]],
  ['regression_83',['2.4 Phase 2: raw-link liveness and ordering, closing a real Docker-confirmed regression',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md253',1,'']]],
  ['regularly_84',['4. Kick Watchdog Regularly',['../watchdog_user_guide.html#watchdog_user_guide_qs_kick',1,'']]],
  ['related_85',['2.6 Logging/diagnostics — &lt;tt&gt;sapi_log.h&lt;/tt&gt; (ADR-001 §4, non-safety-related)',['../safeapi_srs.html#autotoc_md440',1,'']]],
  ['related_20fixes_86',['2.3 A UDP handshake has real, non-zero startup latency - two related fixes',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md252',1,'']]],
  ['relay_20no_20session_20state_20of_20its_20own_87',['2.2 C is a pure relay - no session state of its own',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md273',1,'']]],
  ['release_88',['release',['../structsapi__mem__pool__backend__t.html#a429ddb0bd137a23a34423187afd40b64',1,'sapi_mem_pool_backend_t']]],
  ['release_20build_89',['2. Linux Release Build',['../md_docs_2CROSS__COMPILATION.html#autotoc_md394',1,'']]],
  ['remaining_20setup_20only_20constructors_90',['ADR-032: Setup-phase lock coverage extended to backend registration and remaining setup-only constructors',['../md_docs_2architecture_2ADR-032-setup-phase-lock-coverage-extended.html',1,'']]],
  ['remaining_5fbudget_5fms_91',['remaining_budget_ms',['../sapi__checkpoint_8c.html#af417ffad5639f066111c166f6dcf92b9',1,'sapi_checkpoint.c']]],
  ['renamed_92',['2.1 The &lt;tt&gt;common&lt;/tt&gt;/&lt;tt&gt;os&lt;/tt&gt; grouping folder is dropped, not renamed',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md77',1,'']]],
  ['renamed_20from_20tt_20sapi_5fvital_5fchannel_20tt_20single_20link_93',['2.1 &lt;tt&gt;sapi_channel&lt;/tt&gt; (renamed from &lt;tt&gt;sapi_vital_channel&lt;/tt&gt;, single link)',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md226',1,'']]],
  ['rendezvous_94',['rendezvous',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html',1,'ADR-019: AppManager Cycle Hooks and Built-In Checkpoint Rendezvous'],['../group__CHECKPOINT.html',1,'Checkpoint Rendezvous']]],
  ['rendezvous_20—_20tt_20sapi_5fcheckpoint_20h_20tt_20adr_20017_20§2_202_95',['3a.1 Checkpoint rendezvous — &lt;tt&gt;sapi_checkpoint.h&lt;/tt&gt; (ADR-017 §2.2)',['../safeapi_srs.html#autotoc_md446',1,'']]],
  ['rendezvous_20and_20clock_20synchronization_20for_20distributed_20vital_20channels_96',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['rendezvous_20no_20new_20transport_20backend_97',['2.2 &lt;tt&gt;sapi_checkpoint&lt;/tt&gt;: bounded rendezvous, no new transport backend',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md151',1,'']]],
  ['replicated_20to_20all_209_98',['2.3 Rollout: piloted on &lt;tt&gt;sapi_timer&lt;/tt&gt;, then replicated to all 9',['../md_docs_2architecture_2ADR-021-consumer-backend-header-split.html#autotoc_md192',1,'']]],
  ['reply_99',['5.2 One physical link, two message protocols, and a missing reply',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md174',1,'']]],
  ['reply_5fconfirms_5fcheckpoint_100',['reply_confirms_checkpoint',['../sapi__checkpoint_8c.html#a543471f9296dbaf8a5eee2f432b99c75',1,'sapi_checkpoint.c']]],
  ['reply_5fsize_101',['reply_size',['../structsapi__ipc__rr__client__config__t.html#a632c1c63f0079a095de911fb4a9afa16',1,'sapi_ipc_rr_client_config_t::reply_size'],['../structsapi__ipc__rr__server__config__t.html#a2f360d0f68323f42a9d4cecd95a506b9',1,'sapi_ipc_rr_server_config_t::reply_size']]],
  ['repurposed_20tt_20sapi_5fchannel_20tt_102',['2.1 A new module, &lt;tt&gt;sapi_safechannel&lt;/tt&gt;, not a repurposed &lt;tt&gt;sapi_channel&lt;/tt&gt;',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html#autotoc_md198',1,'']]],
  ['req_20appmanager_20009_103',['2.3 Single-entry-point enforcement (REQ-APPMANAGER-009)',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html#autotoc_md242',1,'']]],
  ['req_20lifecycle_20001_104',['2.2 Which constructors are gated (REQ-LIFECYCLE-001)',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html#autotoc_md241',1,'']]],
  ['req_20lifecycle_20001_20002_105',['2.1 A new, minimal &lt;tt&gt;sapi_lifecycle&lt;/tt&gt; module (REQ-LIFECYCLE-001/002)',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html#autotoc_md240',1,'']]],
  ['req_20oal_20netlink_20014_106',['2.1 New UDP backend, same file, same accessor (REQ-OAL-NETLINK-014)',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md250',1,'']]],
  ['request_107',['request',['../structsapi__reboot__backend__t.html#a9aca0dde01fe603e487ea93fcd0ca73c',1,'sapi_reboot_backend_t']]],
  ['request_20reboot_20on_20critical_20error_108',['2. Request Reboot on Critical Error',['../reboot_user_guide.html#reboot_user_guide_qs_request',1,'']]],
  ['request_5fdata_109',['request_data',['../structsapi__ipc__rr__request__t.html#ad518e14d7ee868c573418e58a3dd6619',1,'sapi_ipc_rr_request_t']]],
  ['request_5fid_110',['request_id',['../structsapi__ipc__rr__request__t.html#a2a04d70cfaceb4aae1c8433c777335d5',1,'sapi_ipc_rr_request_t']]],
  ['request_5fsize_111',['request_size',['../structsapi__ipc__rr__server__config__t.html#a5103c61d3e1eeb0628583a600691b5a6',1,'sapi_ipc_rr_server_config_t::request_size'],['../structsapi__ipc__rr__client__config__t.html#a8a609e301e6c525cde811610be38ec82',1,'sapi_ipc_rr_client_config_t::request_size'],['../structsapi__ipc__rr__request__t.html#a20ea682b09837c909a47a4cc49282378',1,'sapi_ipc_rr_request_t::request_size']]],
  ['required_112',['2-out-of-2 Voting (Perfect Agreement Required)',['../vital_channel_architecture.html#vital_channel_architecture_example_2oo2',1,'']]],
  ['required_20sizes_20upfront_113',['3. Calculate Required Sizes Upfront',['../memory_user_guide.html#memory_user_guide_qs_calculate',1,'']]],
  ['required_20validates_20adr_20020_114',['2.2 Negotiation link: no functional change required (validates ADR-020)',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md251',1,'']]],
  ['requirements_115',['requirements',['../memory_user_guide.html#memory_user_guide_sizing_calc',1,'Calculate Max Requirements'],['../vital_channel_architecture.html#vital_channel_architecture_quorum',1,'Quorum Requirements']]],
  ['requirements_20claude_20md_20not_20yet_20tagged_20per_20function_116',['3. Project-wide requirements (CLAUDE.md, not yet tagged per-function)',['../safeapi_srs.html#autotoc_md444',1,'']]],
  ['requirements_20specification_20srs_117',['requirements specification srs',['../safeapi_srs.html#autotoc_md424',1,'Safe API Framework — Software Requirements Specification (SRS)'],['../safeapi_srs.html',1,'Software Requirements Specification (SRS)']]],
  ['reservation_118',['Static Memory Reservation',['../group__MEMORY.html',1,'']]],
  ['reservation_20—_20tt_20sapi_5fmemory_20h_20tt_20adr_20001_20§4_119',['2.3 Static memory reservation — &lt;tt&gt;sapi_memory.h&lt;/tt&gt; (ADR-001 §4)',['../safeapi_srs.html#autotoc_md436',1,'']]],
  ['reservation_20backend_20adaptation_120',['Static Memory Reservation - Backend Adaptation',['../group__MEMORY__BACKEND.html',1,'']]],
  ['reserved_121',['reserved',['../structsapi__vital__message__t.html#a1d0a2edc1501f1b547ed52bbc15b7a10',1,'sapi_vital_message_t::reserved'],['../structsapi__dual__frame__header__t.html#ab88218dcac4b601dc63d236d1271d845',1,'sapi_dual_frame_header_t::reserved']]],
  ['resource_20model_122',['Resource Model',['../reboot_architecture.html#reboot_architecture_resource',1,'']]],
  ['resource_20sizing_123',['Resource Sizing',['../memory_user_guide.html#memory_user_guide_sizing',1,'']]],
  ['resources_124',['PlantUML Resources',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md336',1,'']]],
  ['responsibility_125',['Implementation Responsibility',['../channel_configuration.html#channel_configuration_implementation_by_integrator',1,'']]],
  ['responsibility_20summary_126',['Responsibility Summary',['../appmanager_integration.html#appmanager_integration_responsibility',1,'']]],
  ['result_127',['5.4 Result',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md176',1,'']]],
  ['retirement_20of_20the_20old_20adr_20008_20tt_20channel_20tt_20module_128',['2.7 Retirement of the old ADR-008 &lt;tt&gt;channel&lt;/tt&gt; module',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md232',1,'']]],
  ['retrieval_129',['Retrieval',['../log_architecture.html#log_architecture_retrieve',1,'']]],
  ['retrofitting_20tt_20safeapirbc2oo2_20src_20application_20ab_20channel_5fab_20c_20tt_130',['5. Addendum: retrofitting &lt;tt&gt;safeAPIRBC2oo2/src/application/AB/channel_ab.c&lt;/tt&gt;',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md172',1,'']]],
  ['retrying_20endpoints_131',['2.5 Known open issue: reconnect livelock between two independently-retrying endpoints',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md254',1,'']]],
  ['return_20enforced_20defensively_132',['2.4 &quot;Does not return&quot;, enforced defensively',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md48',1,'']]],
  ['reuse_20the_20en_2050159_20envelope_20that_20already_20exists_20—_20don_20t_20rebuild_20it_133',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['reuses_20tt_20iteration_5fcount_20tt_20as_20the_20checkpoint_20id_134',['2.2 Checkpoint is opt-in, reuses &lt;tt&gt;iteration_count&lt;/tt&gt; as the checkpoint ID',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md168',1,'']]],
  ['rewiring_20tt_20sapi_5fcheckpoint_20tt_135',['2.5 Rewiring &lt;tt&gt;sapi_checkpoint&lt;/tt&gt;',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md230',1,'']]],
  ['rewiring_20tt_20sapi_5fsafechannel_20tt_20s_20voted_20path_136',['2.6 Rewiring &lt;tt&gt;sapi_safechannel&lt;/tt&gt;&apos;s voted path',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md231',1,'']]],
  ['right_20for_20sapi_137',['Why CRC-64 is Right for SAPI',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md95',1,'']]],
  ['ring_20buffer_138',['Ring Buffer',['../log_architecture.html#log_architecture_storage',1,'']]],
  ['ring_20buffer_20without_20malloc_139',['Example 2: Ring Buffer Without malloc',['../memory_user_guide.html#memory_user_guide_example_ringbuf',1,'']]],
  ['risk_20mitigation_140',['Risk Mitigation',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md124',1,'']]],
  ['role_141',['role',['../structsapi__netlink__config__t.html#a7344858f69326b31c5543b84e8c19358',1,'sapi_netlink_config_t::role'],['../structsapi__safechannel__endpoint__t.html#a89f41a44ebe4e2a379b5af272e5a13da',1,'sapi_safechannel_endpoint_t::role']]],
  ['rollout_20plan_142',['Rollout Plan',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md142',1,'']]],
  ['rollout_3a_20piloted_20on_20tt_20sapi_5ftimer_20tt_20then_20replicated_20to_20all_209_143',['2.3 Rollout: piloted on &lt;tt&gt;sapi_timer&lt;/tt&gt;, then replicated to all 9',['../md_docs_2architecture_2ADR-021-consumer-backend-header-split.html#autotoc_md192',1,'']]],
  ['rtos_144',['rtos',['../md_docs_2CROSS__COMPILATION.html#autotoc_md400',1,'QNX RTOS'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md389',1,'QNX RTOS']]],
  ['rule_2010_201_145',['MISRA Rule 10.1',['../cast_architecture.html#cast_architecture_misra',1,'']]],
  ['rule_2020_206_146',['MISRA Rule 20.6',['../memory_architecture.html#memory_architecture_misra',1,'']]],
  ['rule_2021_206_147',['MISRA Rule 21.6',['../string_architecture.html#string_architecture_misra',1,'']]]
];
