var searchData=
[
  ['padding_0',['padding',['../structsapi__vital__message__t.html#aeb2b79c397c57af3b307120882943f94',1,'sapi_vital_message_t']]],
  ['pair_20including_20widening_1',['2.1 Scope: every ordered pair, including widening',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md34',1,'']]],
  ['parameter_20summary_2',['Configuration Parameter Summary',['../channel_configuration.html#channel_configuration_configuration_summary',1,'']]],
  ['partial_3',['3b. Watchdog — &lt;tt&gt;sapi_watchdog.h&lt;/tt&gt; (partial)',['../safeapi_srs.html#autotoc_md448',1,'']]],
  ['path_4',['2.6 Rewiring &lt;tt&gt;sapi_safechannel&lt;/tt&gt;&apos;s voted path',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md231',1,'']]],
  ['pattern_5',['pattern',['../ipc_transport_selection.html#ipc_transport_selection_backend_vtable',1,'Backend Implementation Pattern'],['../channel_configuration.html#channel_configuration_overview',1,'Channel Configuration Pattern'],['../channel_configuration.html#channel_configuration_dispatcher_callback',1,'Dispatcher Callback Pattern']]],
  ['pattern_201_3a_20conditional_20kick_20fail_20safe_20default_6',['Pattern 1: Conditional Kick (Fail-Safe Default)',['../watchdog_user_guide.html#watchdog_user_guide_pattern_conditional',1,'']]],
  ['pattern_201_3a_20fault_20tolerance_7',['Pattern 1: Fault Tolerance',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md379',1,'']]],
  ['pattern_201_3a_20health_20monitoring_20loop_8',['Pattern 1: Health Monitoring Loop',['../safestate_user_guide.html#safestate_user_guide_pattern_health',1,'']]],
  ['pattern_201_3a_20pool_20based_20allocation_9',['Pattern 1: Pool-Based Allocation',['../memory_user_guide.html#memory_user_guide_common_pool',1,'']]],
  ['pattern_201_3a_20single_20system_202oo2_20a_20↔_20b_20→_20c_10',['Pattern 1: Single-System 2oo2 (A ↔ B → C)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_single_2oo2',1,'']]],
  ['pattern_201_3a_20static_20global_20buffers_11',['Pattern 1: Static Global Buffers',['../memory_user_guide.html#memory_user_guide_pattern_global',1,'']]],
  ['pattern_202_3a_20application_20state_20structure_12',['Pattern 2: Application State Structure',['../memory_user_guide.html#memory_user_guide_pattern_app',1,'']]],
  ['pattern_202_3a_20check_20watchdog_20status_13',['Pattern 2: Check Watchdog Status',['../watchdog_user_guide.html#watchdog_user_guide_pattern_status',1,'']]],
  ['pattern_202_3a_20distributed_202oo2_20a_20↔_20b_20across_20network_14',['Pattern 2: Distributed 2oo2 (A ↔ B Across Network)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_distributed_2oo2',1,'']]],
  ['pattern_202_3a_20fail_20safe_20by_20default_15',['Pattern 2: Fail-Safe-by-Default',['../safestate_user_guide.html#safestate_user_guide_pattern_failsafe',1,'']]],
  ['pattern_202_3a_20fixed_20size_20queues_16',['Pattern 2: Fixed-Size Queues',['../memory_user_guide.html#memory_user_guide_common_queue',1,'']]],
  ['pattern_202_3a_20health_20monitoring_17',['Pattern 2: Health Monitoring',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md380',1,'']]],
  ['pattern_203_3a_20hot_20standby_20with_20mirroring_18',['Pattern 3: Hot Standby with Mirroring',['../vital_channel_topologies.html#vital_channel_topologies_pattern_mirror_hot_standby',1,'']]],
  ['pattern_203_3a_20layered_20architecture_19',['Pattern 3: Layered Architecture',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md381',1,'']]],
  ['pattern_203_3a_20thread_20local_20state_20multi_20threaded_20',['Pattern 3: Thread-Local State (Multi-Threaded)',['../memory_user_guide.html#memory_user_guide_pattern_thread',1,'']]],
  ['pattern_204_3a_20triple_20redundancy_202oo3_21',['Pattern 4: Triple Redundancy (2oo3)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_2oo3',1,'']]],
  ['pattern_20no_20dynamic_20allocation_22',['3.4 Handle pattern (no dynamic allocation)',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md16',1,'']]],
  ['patterns_23',['patterns',['../memory_user_guide.html#memory_user_guide_allocation_patterns',1,'Allocation Patterns'],['../vital_channel_topologies.html',1,'Channel Topologies and Redundancy Patterns'],['../vital_channel_topologies.html#vital_channel_topologies_topology_overview',1,'Channel Topology Patterns'],['../memory_user_guide.html#memory_user_guide_patterns',1,'Common Patterns'],['../vital_channel_user_guide.html#vital_channel_user_guide_patterns',1,'Common Patterns'],['../watchdog_user_guide.html#watchdog_user_guide_patterns',1,'Common Patterns'],['../safestate_user_guide.html#safestate_user_guide_patterns',1,'Common Patterns'],['../status_user_guide.html#status_user_guide_error_handling',1,'Error Handling Patterns'],['../ipc_transport_selection.html#ipc_transport_selection_online_standby_patterns',1,'Online/Standby Redundancy Patterns'],['../task_user_guide.html#task_user_guide_patterns',1,'Patterns']]],
  ['patterns_20for_20safety_20critical_20systems_24',['Common Diagram Patterns for Safety-Critical Systems',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md378',1,'']]],
  ['patterns_20in_20framework_25',['Usage Patterns in Framework',['../status_architecture.html#status_architecture_usage_patterns',1,'']]],
  ['paused_26',['2.4 The real bug: the cyclic executive starves whenever checkpoint is paused',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md264',1,'']]],
  ['payload_27',['payload',['../structsapi__vital__message__t.html#ac997ccc9bb231fbc7b87cf3afa7f5858',1,'sapi_vital_message_t']]],
  ['payload_5foversize_28',['payload_oversize',['../structsapi__checksum__stats__t.html#a1c08bab5dba529cdadde31e9780a15b6',1,'sapi_checksum_stats_t']]],
  ['payload_5fsize_29',['payload_size',['../structsapi__vital__message__t.html#a4da9652a45314ec60aa1d66c975cd662',1,'sapi_vital_message_t']]],
  ['peer_20comparison_30',['2.3 &lt;tt&gt;sapi_cross_comparator&lt;/tt&gt; (new) - 2-way peer comparison',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md228',1,'']]],
  ['peer_20s_20state_31',['3. The negotiator keeps both its own and the peer&apos;s state',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md183',1,'']]],
  ['peer_5fid_32',['peer_id',['../structsapi__dual__negotiator__config__t.html#af6ad46d9407491078bb5193896a24f96',1,'sapi_dual_negotiator_config_t']]],
  ['peer_5flost_5ftimeout_5fms_33',['peer_lost_timeout_ms',['../structsapi__dual__negotiator__config__t.html#ae7f053c51bf1aabc6f3342c67f986ac9',1,'sapi_dual_negotiator_config_t']]],
  ['per_20buffer_34',['O(n) Per Buffer',['../checksum_architecture.html#checksum_architecture_performance',1,'']]],
  ['per_20call_20no_20default_35',['2.5 Buffer endianness helpers: explicit per call, no default',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md71',1,'']]],
  ['per_20call_20site_20not_20generated_36',['2.2 Init/register/dispatch are hand-written per call site, not generated',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html#autotoc_md285',1,'']]],
  ['per_20feature_37',['2.2 One CMake target per feature',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md78',1,'']]],
  ['per_20feature_20directory_20layout_38',['ADR-007: Per-Feature Directory Layout',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html',1,'']]],
  ['per_20function_39',['3. Project-wide requirements (CLAUDE.md, not yet tagged per-function)',['../safeapi_srs.html#autotoc_md444',1,'']]],
  ['per_20level_20application_20registered_40',['2.2 One handler per level, application-registered',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md46',1,'']]],
  ['per_20libc_20memory_20primitive_41',['ADR-031: &lt;tt&gt;sapi_mem_util&lt;/tt&gt; - one sanctioned call site per libc memory primitive',['../md_docs_2architecture_2ADR-031-sapi-mem-util.html',1,'']]],
  ['per_20module_20feature_20selection_20at_20configure_20time_42',['ADR-024: Per-Module Feature Selection at Configure Time',['../md_docs_2architecture_2ADR-024-configurable-feature-build.html',1,'']]],
  ['per_20service_43',['2.1 One backend vtable type and one registration function per service',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md57',1,'']]],
  ['per_20service_20one_20aggregator_44',['2.1 One module, one file per service, one aggregator',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md158',1,'']]],
  ['per_20timer_45',['O(1) Per Timer',['../timer_architecture.html#timer_architecture_performance',1,'']]],
  ['per_20watchdog_46',['State Per Watchdog',['../watchdog_architecture.html#watchdog_architecture_state',1,'']]],
  ['perfect_20agreement_20required_47',['2-out-of-2 Voting (Perfect Agreement Required)',['../vital_channel_architecture.html#vital_channel_architecture_example_2oo2',1,'']]],
  ['performance_48',['Performance',['../watchdog_architecture.html#watchdog_architecture_performance',1,'']]],
  ['period_5fms_49',['period_ms',['../structsapi__task__config__t.html#abd8843dc4d435e089a1a469f3d85f5b9',1,'sapi_task_config_t::period_ms'],['../structsapi__timer__config__t.html#a82ef7aa3ad90086b5120a7d320c21a28',1,'sapi_timer_config_t::period_ms']]],
  ['periodic_20heartbeat_50',['Example 1: Periodic Heartbeat',['../timer_user_guide.html#timer_user_guide_example_periodic',1,'']]],
  ['permanent_20safe_20halt_20and_20an_20undersized_20queue_51',['2.6 Full-stack Docker hardening: a permanent safe-halt and an undersized queue',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md277',1,'']]],
  ['phase_201_3a_20core_20api_20v0_203_200_52',['Phase 1: Core API (v0.3.0)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md120',1,'']]],
  ['phase_202_3a_20integration_20v0_204_200_53',['Phase 2: Integration (v0.4.0)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md121',1,'']]],
  ['phase_202_3a_20raw_20link_20liveness_20and_20ordering_20closing_20a_20real_20docker_20confirmed_20regression_54',['2.4 Phase 2: raw-link liveness and ordering, closing a real Docker-confirmed regression',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md253',1,'']]],
  ['phase_203_3a_20advanced_20future_55',['Phase 3: Advanced (Future)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md122',1,'']]],
  ['phase_20lock_56',['Application Setup-Phase Lock',['../group__LIFECYCLE.html',1,'']]],
  ['phase_20lock_20—_20tt_20sapi_5flifecycle_20h_20tt_20adr_20026_57',['3c-bis. Application setup-phase lock — &lt;tt&gt;sapi_lifecycle.h&lt;/tt&gt; (ADR-026)',['../safeapi_srs.html#autotoc_md450',1,'']]],
  ['phase_20lock_20and_20single_20entry_20point_20enforcement_58',['ADR-026: Application Setup-Phase Lock and Single-Entry-Point Enforcement',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html',1,'']]],
  ['phase_20lock_20coverage_20extended_20to_20backend_20registration_20and_20remaining_20setup_20only_20constructors_59',['ADR-032: Setup-phase lock coverage extended to backend registration and remaining setup-only constructors',['../md_docs_2architecture_2ADR-032-setup-phase-lock-coverage-extended.html',1,'']]],
  ['physical_20link_20two_20message_20protocols_20and_20a_20missing_20reply_60',['5.2 One physical link, two message protocols, and a missing reply',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md174',1,'']]],
  ['piloted_20on_20tt_20sapi_5ftimer_20tt_20then_20replicated_20to_20all_209_61',['2.3 Rollout: piloted on &lt;tt&gt;sapi_timer&lt;/tt&gt;, then replicated to all 9',['../md_docs_2architecture_2ADR-021-consumer-backend-header-split.html#autotoc_md192',1,'']]],
  ['pipes_20transport_62',['FIFO (Named Pipes) Transport',['../ipc_transport_selection.html#ipc_transport_selection_fifo',1,'']]],
  ['plan_63',['Rollout Plan',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md142',1,'']]],
  ['plantuml_64',['1. Install PlantUML',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md342',1,'']]],
  ['plantuml_20doxygen_65',['Architecture Diagrams with PlantUML &amp; Doxygen',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html',1,'']]],
  ['plantuml_20resources_66',['PlantUML Resources',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md336',1,'']]],
  ['platform_20configuration_67',['Real-Time Platform Configuration',['../group__PLATFORM.html',1,'']]],
  ['platform_20configuration_20—_20tt_20sapi_5fplatform_20h_20tt_20adr_20035_68',['2.9 Real-time platform configuration — &lt;tt&gt;sapi_platform.h&lt;/tt&gt; (ADR-035)',['../safeapi_srs.html#autotoc_md443',1,'']]],
  ['platform_20configuration_20backend_20adaptation_69',['Real-Time Platform Configuration - Backend Adaptation',['../group__PLATFORM__BACKEND.html',1,'']]],
  ['png_3a_70',['Generate all diagrams as PNG:',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md330',1,'']]],
  ['point_20enforcement_71',['ADR-026: Application Setup-Phase Lock and Single-Entry-Point Enforcement',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html',1,'']]],
  ['point_20enforcement_20req_20appmanager_20009_72',['2.3 Single-entry-point enforcement (REQ-APPMANAGER-009)',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html#autotoc_md242',1,'']]],
  ['point_20network_20link_20—_20tt_20sapi_5fnetlink_20h_20tt_20adr_20001_20§4_20adr_20005_20adr_20021_20adr_20027_73',['2.8 Point-to-point network link — &lt;tt&gt;sapi_netlink.h&lt;/tt&gt; (ADR-001 §4, ADR-005, ADR-021, ADR-027)',['../safeapi_srs.html#autotoc_md442',1,'']]],
  ['point_20of_20this_20adr_74',['2.4 Cross-site failover continuity - the actual point of this ADR',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md275',1,'']]],
  ['point_20to_20point_20network_20link_75',['Point-to-Point Network Link',['../group__NETLINK.html',1,'']]],
  ['point_20to_20point_20network_20link_20—_20tt_20sapi_5fnetlink_20h_20tt_20adr_20001_20§4_20adr_20005_20adr_20021_20adr_20027_76',['2.8 Point-to-point network link — &lt;tt&gt;sapi_netlink.h&lt;/tt&gt; (ADR-001 §4, ADR-005, ADR-021, ADR-027)',['../safeapi_srs.html#autotoc_md442',1,'']]],
  ['point_20to_20point_20network_20link_20backend_20adaptation_77',['Point-to-Point Network Link - Backend Adaptation',['../group__NETLINK__BACKEND.html',1,'']]],
  ['pointer_20wrapper_78',['Safe Pointer Wrapper',['../group__SAFEPTR.html',1,'']]],
  ['pointer_20wrapper_20—_20tt_20sapi_5fsafe_5fptr_20h_20tt_79',['2.3.1 Safe pointer wrapper — &lt;tt&gt;sapi_safe_ptr.h&lt;/tt&gt;',['../safeapi_srs.html#autotoc_md437',1,'']]],
  ['points_80',['Integration Points',['../safestate_architecture.html#safestate_architecture_integration',1,'']]],
  ['policy_20reconciliation_20not_20a_20framework_20change_81',['5.3 Safety-policy reconciliation, not a framework change',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md175',1,'']]],
  ['polynomial_82',['polynomial',['../structsapi__checksum__manager__t.html#a171f07b7de7dcb59111a9d3bf10e6db0',1,'sapi_checksum_manager_t']]],
  ['polynomial_20options_83',['2. Three Polynomial Options',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md103',1,'']]],
  ['pool_20based_20allocation_84',['Pattern 1: Pool-Based Allocation',['../memory_user_guide.html#memory_user_guide_common_pool',1,'']]],
  ['port_85',['port',['../structsapi__netlink__config__t.html#a57aeb391e22d0c1f768e0f387e85ac33',1,'sapi_netlink_config_t::port'],['../structsapi__safechannel__endpoint__t.html#a745afd5a34b549364c5b22325f0d33b9',1,'sapi_safechannel_endpoint_t::port']]],
  ['portable_20mutual_20exclusion_20primitive_86',['ADR-033: sapi_mutex - a portable mutual-exclusion primitive',['../md_docs_2architecture_2ADR-033-sapi-mutex.html',1,'']]],
  ['posix_20implementation_20moves_20behind_20the_20vtable_20tt_20safeapibackendposix_20tt_87',['2. POSIX implementation moves behind the vtable (&lt;tt&gt;safeAPIBackendPosix&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-035-platform-realtime-init.html#autotoc_md322',1,'']]],
  ['posix_20linux_20oal_20backend_88',['ADR-018: A Real POSIX/Linux OAL Backend',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html',1,'']]],
  ['posix_20oal_89',['Linux (POSIX OAL)',['../md_docs_2CROSS__COMPILATION.html#autotoc_md392',1,'']]],
  ['post_20acceptance_20fix_20adr_20022_20site_20s_20live_20tt_20sapi_5fsafechannel_20tt_20migration_90',['Post-acceptance fix (ADR-022, SITE&apos;s live &lt;tt&gt;sapi_safechannel&lt;/tt&gt; migration)',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md186',1,'']]],
  ['post_5fexecute_91',['post_execute',['../structsapi__appmanager__operations__t.html#a1b4d892d11c1e780931a308697bfb47e',1,'sapi_appmanager_operations_t']]],
  ['practical_20examples_92',['practical examples',['../cast_user_guide.html#cast_user_guide_examples',1,'Practical Examples'],['../reboot_user_guide.html#reboot_user_guide_examples',1,'Practical Examples'],['../memory_user_guide.html#memory_user_guide_examples',1,'Practical Examples'],['../timer_user_guide.html#timer_user_guide_examples',1,'Practical Examples'],['../checksum_user_guide.html#checksum_user_guide_examples',1,'Practical Examples'],['../watchdog_user_guide.html#watchdog_user_guide_examples',1,'Practical Examples'],['../types_user_guide.html#types_user_guide_examples',1,'Practical Examples'],['../string_user_guide.html#string_user_guide_examples',1,'Practical Examples'],['../status_user_guide.html#status_user_guide_examples',1,'Practical Examples'],['../buffer_user_guide.html#buffer_user_guide_examples',1,'Practical Examples'],['../safestate_user_guide.html#safestate_user_guide_examples',1,'Practical Examples']]],
  ['practices_93',['practices',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md372',1,'Best Practices'],['../nvm_user_guide.html#nvm_user_guide_guidelines',1,'Best Practices'],['../memory_user_guide.html#memory_user_guide_guidelines',1,'Best Practices'],['../buffer_user_guide.html#buffer_user_guide_guidelines',1,'Best Practices'],['../reboot_user_guide.html#reboot_user_guide_guidelines',1,'Best Practices'],['../timer_user_guide.html#timer_user_guide_guidelines',1,'Best Practices'],['../cast_user_guide.html#cast_user_guide_guidelines',1,'Best Practices'],['../watchdog_user_guide.html#watchdog_user_guide_guidelines',1,'Best Practices'],['../types_user_guide.html#types_user_guide_guidelines',1,'Best Practices'],['../string_user_guide.html#string_user_guide_guidelines',1,'Best Practices'],['../status_user_guide.html#status_user_guide_guidelines',1,'Best Practices'],['../checksum_user_guide.html#checksum_user_guide_guidelines',1,'Best Practices'],['../log_user_guide.html#log_user_guide_guidelines',1,'Best Practices'],['../vital_channel_user_guide.html#vital_channel_user_guide_guidelines',1,'Best Practices'],['../safestate_user_guide.html#safestate_user_guide_guidelines',1,'Best Practices']]],
  ['pre_20computed_94',['1. Lookup Tables (Pre-computed)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md102',1,'']]],
  ['pre_5fexecute_95',['pre_execute',['../structsapi__appmanager__operations__t.html#a365e23c52c1e6723fc404e21a93f525d',1,'sapi_appmanager_operations_t']]],
  ['prerequisites_96',['1. Prerequisites',['../md_docs_2CROSS__COMPILATION.html#autotoc_md401',1,'']]],
  ['presets_97',['presets',['../md_docs_2CROSS__COMPILATION.html#autotoc_md408',1,'Linux Presets'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md409',1,'QNX Presets']]],
  ['presets_20recommended_98',['Using CMake Presets (recommended)',['../index.html#autotoc_md3',1,'']]],
  ['presets_20reference_99',['CMake Presets Reference',['../md_docs_2CROSS__COMPILATION.html#autotoc_md407',1,'']]],
  ['primary_20mitigation_3a_20diverse_20compilation_20not_20diverse_20hardware_100',['2.1 Primary mitigation: diverse compilation, not diverse hardware',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md85',1,'']]],
  ['primitive_101',['primitive',['../md_docs_2architecture_2ADR-031-sapi-mem-util.html',1,'ADR-031: &lt;tt&gt;sapi_mem_util&lt;/tt&gt; - one sanctioned call site per libc memory primitive'],['../md_docs_2architecture_2ADR-033-sapi-mutex.html',1,'ADR-033: sapi_mutex - a portable mutual-exclusion primitive']]],
  ['primitive_20violation_20notification_102',['Safety Primitive Violation Notification',['../group__SAFETYVIOLATION.html',1,'']]],
  ['primitive_20violation_20notification_20—_20tt_20sapi_5fsafety_5fviolation_20h_20tt_103',['1.5.1 Safety-primitive violation notification — &lt;tt&gt;sapi_safety_violation.h&lt;/tt&gt;',['../safeapi_srs.html#autotoc_md431',1,'']]],
  ['principles_104',['principles',['../index.html#autotoc_md8',1,'Design principles'],['../ipc_guide.html#ipc_guide_design_principles',1,'Design Principles']]],
  ['priority_105',['priority',['../structsapi__task__config__t.html#afe7a346b07a78599030af132bc289f45',1,'sapi_task_config_t']]],
  ['priority_20levels_106',['Priority Levels',['../task_user_guide.html#task_user_guide_priority',1,'']]],
  ['priority_20ordering_107',['Priority Ordering',['../task_architecture.html#task_architecture_priority',1,'']]],
  ['problem_20statement_108',['Problem Statement',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md93',1,'']]],
  ['process_20communication_109',['Inter-Process Communication',['../group__IPC.html',1,'']]],
  ['process_20communication_20backend_20adaptation_110',['Inter-Process Communication - Backend Adaptation',['../group__IPC__BACKEND.html',1,'']]],
  ['process_20communication_20guide_111',['IPC (Inter-Process Communication) Guide',['../ipc_guide.html',1,'']]],
  ['process_20communication_20ipc_20transport_20layer_112',['Inter-Process Communication (IPC) Transport Layer',['../ipc_transport_selection.html#ipc_transport_selection_overview',1,'']]],
  ['process_20inter_20task_20communication_20—_20tt_20sapi_5fipc_20h_20tt_20adr_20001_20§4_113',['2.5 Inter-process/inter-task communication — &lt;tt&gt;sapi_ipc.h&lt;/tt&gt; (ADR-001 §4)',['../safeapi_srs.html#autotoc_md439',1,'']]],
  ['project_20wide_20requirements_20claude_20md_20not_20yet_20tagged_20per_20function_114',['3. Project-wide requirements (CLAUDE.md, not yet tagged per-function)',['../safeapi_srs.html#autotoc_md444',1,'']]],
  ['properties_115',['Safety Properties',['../vital_channel_architecture.html#vital_channel_architecture_safety_properties',1,'']]],
  ['property_20tests_116',['Property Tests',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md135',1,'']]],
  ['protocol_20and_20failover_20ready_20session_20state_117',['ADR-029: RBC Train/IL/CTC Scenario - Real Multi-Train Protocol and Failover-Ready Session State',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html',1,'']]],
  ['protocol_20one_20shared_20fixed_20size_20envelope_118',['2.1 Wire protocol - one shared, fixed-size envelope',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md272',1,'']]],
  ['protocols_20and_20a_20missing_20reply_119',['5.2 One physical link, two message protocols, and a missing reply',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md174',1,'']]],
  ['ptr_120',['ptr',['../structsapi__safe__ptr__t.html#a01cc28783a4b967296bf19d52920f7ce',1,'sapi_safe_ptr_t']]],
  ['public_20api_121',['Public API',['../reboot_architecture.html#reboot_architecture_api',1,'']]],
  ['pure_20c_20abi_122',['3.1 Interface style: pure C ABI',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md13',1,'']]],
  ['pure_20relay_20no_20session_20state_20of_20its_20own_123',['2.2 C is a pure relay - no session state of its own',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md273',1,'']]]
];
