var searchData=
[
  ['id_0',['2.2 Checkpoint is opt-in, reuses &lt;tt&gt;iteration_count&lt;/tt&gt; as the checkpoint ID',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md168',1,'']]],
  ['identity_1',['2.2 New feature: &lt;tt&gt;sapi_channel&lt;/tt&gt; (comparator + identity)',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md86',1,'']]],
  ['il_20ctc_20scenario_20—_20tt_20safeapirbc2oo2_20tt_20adr_20029_2',['3h. RBC Train/IL/CTC scenario — &lt;tt&gt;safeAPIRBC2oo2&lt;/tt&gt; (ADR-029)',['../safeapi_srs.html#autotoc_md453',1,'']]],
  ['il_20ctc_20scenario_20real_20multi_20train_20protocol_20and_20failover_20ready_20session_20state_3',['ADR-029: RBC Train/IL/CTC Scenario - Real Multi-Train Protocol and Failover-Ready Session State',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html',1,'']]],
  ['impact_4',['Real-World Impact',['../memory_user_guide.html#memory_user_guide_rationale_example',1,'']]],
  ['implement_5',['What You Need to Implement',['../appmanager_integration.html#appmanager_integration_you_implement',1,'']]],
  ['implement_20callback_6',['3. Implement Callback',['../timer_user_guide.html#timer_user_guide_qs_callback',1,'']]],
  ['implementation_7',['implementation',['../nvm_architecture.html#nvm_architecture_backend',1,'Backend Implementation'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md99',1,'Implementation'],['../safestate_architecture.html#safestate_architecture_assert',1,'SAPI_ASSERT Implementation']]],
  ['implementation_20checklist_8',['Implementation Checklist',['../ipc_transport_selection.html#ipc_transport_selection_implementation_checklist',1,'']]],
  ['implementation_20details_9',['Implementation Details',['../status_architecture.html#status_architecture_implementation',1,'']]],
  ['implementation_20pattern_10',['Backend Implementation Pattern',['../ipc_transport_selection.html#ipc_transport_selection_backend_vtable',1,'']]],
  ['implementation_20responsibility_11',['Implementation Responsibility',['../channel_configuration.html#channel_configuration_implementation_by_integrator',1,'']]],
  ['implementation_20timeline_12',['Implementation Timeline',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md119',1,'']]],
  ['implications_13',['SIL Implications',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md115',1,'']]],
  ['implied_14',['2.3 CCF analysis is documented, not implied',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md87',1,'']]],
  ['in_20adr_20documents_15',['In ADR Documents',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md354',1,'']]],
  ['in_20checkpoint_20rendezvous_16',['ADR-019: AppManager Cycle Hooks and Built-In Checkpoint Rendezvous',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html',1,'']]],
  ['in_20doxygen_17',['Using in Doxygen',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md326',1,'']]],
  ['in_20doxygen_20comments_18',['Embedding Diagrams in Doxygen Comments',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md351',1,'']]],
  ['in_20framework_19',['Usage Patterns in Framework',['../status_architecture.html#status_architecture_usage_patterns',1,'']]],
  ['in_20header_20files_20',['In Header Files',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md352',1,'']]],
  ['in_20markdown_20files_21',['In Markdown Files',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md353',1,'']]],
  ['in_20meaning_22',['2.1 Three cycle hooks, &lt;tt&gt;execute&lt;/tt&gt; unchanged in meaning',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md167',1,'']]],
  ['in_20reuses_20tt_20iteration_5fcount_20tt_20as_20the_20checkpoint_20id_23',['2.2 Checkpoint is opt-in, reuses &lt;tt&gt;iteration_count&lt;/tt&gt; as the checkpoint ID',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md168',1,'']]],
  ['in_20safeapirbc2oo2_24',['2.4 Migration scope in safeAPIRBC2oo2',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html#autotoc_md201',1,'']]],
  ['in_20your_20application_25',['4. Use in Your Application',['../md_docs_2CROSS__COMPILATION.html#autotoc_md388',1,'']]],
  ['in_20your_20qnx_20application_26',['5. Use in Your QNX Application',['../md_docs_2CROSS__COMPILATION.html#autotoc_md397',1,'']]],
  ['in_5fuse_27',['in_use',['../structsapi__watchdog__s.html#a00a99f33928204f56a499f1a1dfe420b',1,'sapi_watchdog_s']]],
  ['include_20header_28',['include header',['../memory_user_guide.html#memory_user_guide_qs_include',1,'1. Include Header'],['../types_user_guide.html#types_user_guide_qs_include',1,'1. Include Header'],['../watchdog_user_guide.html#watchdog_user_guide_qs_include',1,'1. Include Header']]],
  ['include_20trees_29',['2.1 Two top-level include trees',['../md_docs_2architecture_2ADR-021-consumer-backend-header-split.html#autotoc_md190',1,'']]],
  ['including_20widening_30',['2.1 Scope: every ordered pair, including widening',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md34',1,'']]],
  ['independently_20retrying_20endpoints_31',['2.5 Known open issue: reconnect livelock between two independently-retrying endpoints',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md254',1,'']]],
  ['index_32',['Diagram Index',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md318',1,'']]],
  ['indirection_33',['3.5 Backend indirection',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md17',1,'']]],
  ['init_34',['init',['../structsapi__appmanager__operations__t.html#a1f03aa6489eaf45e7ef8c29044af48b1',1,'sapi_appmanager_operations_t::init'],['../structsapi__log__backend__t.html#a66b725b77e2efc07a0f09b3e9ed052f2',1,'sapi_log_backend_t::init']]],
  ['init_20register_20dispatch_20are_20hand_20written_20per_20call_20site_20not_20generated_35',['2.2 Init/register/dispatch are hand-written per call site, not generated',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html#autotoc_md285',1,'']]],
  ['initialization_36',['initialization',['../memory_user_guide.html#memory_user_guide_qs_allocate',1,'2. Allocate at Compile-Time or Initialization'],['../checksum_architecture.html#checksum_architecture_init',1,'Initialization']]],
  ['initialize_37',['Initialize',['../buffer_user_guide.html#buffer_user_guide_op_init',1,'']]],
  ['initialized_38',['initialized',['../structsapi__checksum__manager__t.html#afa22104aa013495742494d340f35f4c1',1,'sapi_checksum_manager_t::initialized'],['../structsapi__channel__storage__t.html#a6da6b1f0ddfac18fba69749a1eb1f35d',1,'sapi_channel_storage_t::initialized']]],
  ['input_39',['2.2 Never call &lt;tt&gt;strlen()&lt;/tt&gt; on unbounded/untrusted input',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md68',1,'']]],
  ['inside_20each_20service_20s_20fixed_20opaque_20storage_40',['2.2 Fitting inside each service&apos;s fixed opaque storage',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md159',1,'']]],
  ['install_20plantuml_41',['1. Install PlantUML',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md334',1,'']]],
  ['install_20to_20system_42',['3. Install to System',['../md_docs_2CROSS__COMPILATION.html#autotoc_md387',1,'']]],
  ['instead_20of_20macros_20or_20c11_20tt_20_5fgeneric_20tt_43',['2.5 Why named functions instead of macros or C11 &lt;tt&gt;_Generic&lt;/tt&gt;',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md38',1,'']]],
  ['instructions_44',['Detailed Build Instructions',['../md_docs_2CROSS__COMPILATION.html#autotoc_md383',1,'']]],
  ['integer_20casting_45',['integer casting',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html',1,'ADR-003: Checked Integer Casting'],['../group__CAST.html',1,'Checked Integer Casting']]],
  ['integer_20casting_20—_20tt_20sapi_5fcast_20h_20tt_20adr_20003_46',['1.4 Checked integer casting — &lt;tt&gt;sapi_cast.h&lt;/tt&gt; (ADR-003)',['../safeapi_srs.html#autotoc_md421',1,'']]],
  ['integration_47',['integration',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md161',1,'2.4 Build integration'],['../vital_channel_architecture.html#vital_channel_architecture_integration',1,'Application Integration'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md362',1,'CI/CD Integration']]],
  ['integration_20architecture_48',['Integration Architecture',['../appmanager_integration.html#appmanager_integration_architecture',1,'']]],
  ['integration_20points_49',['Integration Points',['../safestate_architecture.html#safestate_architecture_integration',1,'']]],
  ['integration_20tests_50',['Integration Tests',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md134',1,'']]],
  ['integration_20v0_204_200_51',['Phase 2: Integration (v0.4.0)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md121',1,'']]],
  ['integration_20with_20channels_52',['App Manager Integration with Channels',['../appmanager_integration.html',1,'']]],
  ['integration_20with_20safe_20state_53',['integration with safe state',['../watchdog_architecture.html#watchdog_architecture_integration',1,'Integration with Safe-State'],['../reboot_user_guide.html#reboot_user_guide_integration',1,'Integration with Safe-State'],['../status_architecture.html#status_architecture_safestate',1,'Integration with Safe-State']]],
  ['integration_20with_20vital_20channel_54',['Integration with Vital Channel',['../ipc_transport_selection.html#ipc_transport_selection_vital_channel_integration',1,'']]],
  ['integration_5fguide_55',['INTEGRATION_GUIDE',['../md_include_2safeapi_2app_2appmanager_2INTEGRATION__GUIDE.html',1,'']]],
  ['integrity_20—_20tt_20sapi_5fchecksum_20h_20tt_56',['3g. Checksum / CRC-64 data integrity — &lt;tt&gt;sapi_checksum.h&lt;/tt&gt;',['../safeapi_srs.html#autotoc_md452',1,'']]],
  ['integrity_20for_20redundant_20channels_57',['ADR-016: CRC-64 Data Integrity for Redundant Channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'']]],
  ['integrity_20level_3a_20sil_203_204_58',['3.2 Target integrity level: SIL 3/4',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md14',1,'']]],
  ['integrity_20metadata_20on_20the_20generic_20buffer_59',['2.2 No integrity metadata on the generic buffer',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md27',1,'']]],
  ['inter_20process_20communication_60',['Inter-Process Communication',['../group__IPC.html',1,'']]],
  ['inter_20process_20communication_20backend_20adaptation_61',['Inter-Process Communication - Backend Adaptation',['../group__IPC__BACKEND.html',1,'']]],
  ['inter_20process_20communication_20guide_62',['IPC (Inter-Process Communication) Guide',['../ipc_guide.html',1,'']]],
  ['inter_20process_20communication_20ipc_20transport_20layer_63',['Inter-Process Communication (IPC) Transport Layer',['../ipc_transport_selection.html#ipc_transport_selection_overview',1,'']]],
  ['inter_20process_20inter_20task_20communication_20—_20tt_20sapi_5fipc_20h_20tt_20adr_20001_20§4_64',['2.5 Inter-process/inter-task communication — &lt;tt&gt;sapi_ipc.h&lt;/tt&gt; (ADR-001 §4)',['../safeapi_srs.html#autotoc_md431',1,'']]],
  ['inter_20task_20communication_20—_20tt_20sapi_5fipc_20h_20tt_20adr_20001_20§4_65',['2.5 Inter-process/inter-task communication — &lt;tt&gt;sapi_ipc.h&lt;/tt&gt; (ADR-001 §4)',['../safeapi_srs.html#autotoc_md431',1,'']]],
  ['interface_66',['interface',['../reboot_architecture.html#reboot_architecture_backend',1,'Backend Interface'],['../nvm_architecture.html#nvm_architecture_api',1,'Read/Write Interface']]],
  ['interface_20style_3a_20pure_20c_20abi_67',['3.1 Interface style: pure C ABI',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md13',1,'']]],
  ['internally_68',['2.2 One handle, one type enum, one config, netlink opened internally',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html#autotoc_md199',1,'']]],
  ['into_204_69',['ADR-023: Consolidate 22 CMake Library Targets into 4',['../md_docs_2architecture_2ADR-023-consolidate-cmake-libraries.html',1,'']]],
  ['into_20tt_20sapi_5fchannel_20tt_20tt_20sapi_5fvoter_20tt_20tt_20sapi_5fcross_5fcomparator_20tt_70',['ADR-025: Split &lt;tt&gt;sapi_vital_channel&lt;/tt&gt; into &lt;tt&gt;sapi_channel&lt;/tt&gt; + &lt;tt&gt;sapi_voter&lt;/tt&gt; + &lt;tt&gt;sapi_cross_comparator&lt;/tt&gt;',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html',1,'']]],
  ['invariants_71',['Invariants',['../buffer_architecture.html#buffer_architecture_invariants',1,'']]],
  ['invocation_72',['invocation',['../index.html#autotoc_md5',1,'Manual CMake invocation'],['../safestate_architecture.html#safestate_architecture_test_handler',1,'Test 1: Handler Registration and Invocation']]],
  ['ip_20transport_73',['TCP/IP Transport',['../ipc_transport_selection.html#ipc_transport_selection_tcp_ip',1,'']]],
  ['ipc_74',['2. Sequence Diagram (Behavioral - IPC)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md341',1,'']]],
  ['ipc_20architecture_20layers_75',['IPC Architecture Layers',['../ipc_guide.html#ipc_guide_layers',1,'']]],
  ['ipc_20inter_20process_20communication_20guide_76',['IPC (Inter-Process Communication) Guide',['../ipc_guide.html',1,'']]],
  ['ipc_20netlink_20from_20app_20code_77',['ADR-022: Unified &lt;tt&gt;sapi_safechannel&lt;/tt&gt; Factory (Hiding IPC/Netlink from App Code)',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html',1,'']]],
  ['ipc_20transport_20layer_78',['Inter-Process Communication (IPC) Transport Layer',['../ipc_transport_selection.html#ipc_transport_selection_overview',1,'']]],
  ['ipc_20transport_20selection_20guide_79',['IPC Transport Selection Guide',['../ipc_transport_selection.html',1,'']]],
  ['ipc_5fguide_80',['IPC_GUIDE',['../md_include_2safeapi_2oal_2ipc_2IPC__GUIDE.html',1,'']]],
  ['ipc_5ftransport_5fselection_81',['IPC_TRANSPORT_SELECTION',['../md_include_2safeapi_2oal_2ipc_2IPC__TRANSPORT__SELECTION.html',1,'']]],
  ['is_20a_20buffer_82',['What is a Buffer?',['../buffer_user_guide.html#buffer_user_guide_overview',1,'']]],
  ['is_20a_20pure_20relay_20no_20session_20state_20of_20its_20own_83',['2.2 C is a pure relay - no session state of its own',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md273',1,'']]],
  ['is_20a_20timer_84',['What is a Timer?',['../timer_user_guide.html#timer_user_guide_overview',1,'']]],
  ['is_20always_20active_85',['2.5 &lt;tt&gt;SAPI_ASSERT&lt;/tt&gt; is always active',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md49',1,'']]],
  ['is_20checksum_86',['What is Checksum?',['../checksum_user_guide.html#checksum_user_guide_overview',1,'']]],
  ['is_20documented_20not_20implied_87',['2.3 CCF analysis is documented, not implied',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md87',1,'']]],
  ['is_20dropped_20not_20renamed_88',['2.1 The &lt;tt&gt;common&lt;/tt&gt;/&lt;tt&gt;os&lt;/tt&gt; grouping folder is dropped, not renamed',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md77',1,'']]],
  ['is_20logging_89',['What is Logging?',['../log_user_guide.html#log_user_guide_overview',1,'']]],
  ['is_20nvm_90',['What is NVM?',['../nvm_user_guide.html#nvm_user_guide_overview',1,'']]],
  ['is_20opt_20in_20reuses_20tt_20iteration_5fcount_20tt_20as_20the_20checkpoint_20id_91',['2.2 Checkpoint is opt-in, reuses &lt;tt&gt;iteration_count&lt;/tt&gt; as the checkpoint ID',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md168',1,'']]],
  ['is_20paused_92',['2.4 The real bug: the cyclic executive starves whenever checkpoint is paused',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md264',1,'']]],
  ['is_20reboot_93',['What is Reboot?',['../reboot_user_guide.html#reboot_user_guide_overview',1,'']]],
  ['is_20reentrant_20unlike_20tt_20strtok_20tt_94',['2.4 Splitting is reentrant, unlike &lt;tt&gt;strtok&lt;/tt&gt;',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md70',1,'']]],
  ['is_20right_20for_20sapi_95',['Why CRC-64 is Right for SAPI',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md95',1,'']]],
  ['is_20safe_20state_96',['What is Safe-State?',['../safestate_user_guide.html#safestate_user_guide_overview',1,'']]],
  ['is_20task_20queue_97',['What is Task Queue?',['../task_user_guide.html#task_user_guide_overview',1,'']]],
  ['is_20the_20cast_20module_98',['What is the Cast Module?',['../cast_user_guide.html#cast_user_guide_overview',1,'']]],
  ['is_20the_20liveness_20signal_99',['2. Always send, wait for a bounded ACK - that IS the liveness signal',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md182',1,'']]],
  ['is_20the_20memory_20module_100',['What is the Memory Module?',['../memory_user_guide.html#memory_user_guide_overview',1,'']]],
  ['is_20the_20status_20module_101',['What is the Status Module?',['../status_user_guide.html#status_user_guide_overview',1,'']]],
  ['is_20the_20string_20module_102',['What is the String Module?',['../string_user_guide.html#string_user_guide_overview',1,'']]],
  ['is_20the_20watchdog_103',['What is the Watchdog?',['../watchdog_user_guide.html#watchdog_user_guide_overview',1,'']]],
  ['is_20types_104',['What is Types?',['../types_user_guide.html#types_user_guide_overview',1,'']]],
  ['is_20vital_20channel_105',['What is Vital Channel?',['../vital_channel_user_guide.html#vital_channel_user_guide_overview',1,'']]],
  ['is_5fhealthy_106',['is_healthy',['../structsapi__channel__health__t.html#abbbf09a839adc9fe99359c1f25f8f343',1,'sapi_channel_health_t']]],
  ['is_5fvalid_5faction_107',['is_valid_action',['../sapi__watchdog_8c.html#ae80e4fca3c6bbb43bf990420aa97df19',1,'sapi_watchdog.c']]],
  ['is_5fvalid_5fhandle_108',['is_valid_handle',['../sapi__watchdog_8c.html#a276607429a1cd38238764fc6cd8cef70',1,'sapi_watchdog.c']]],
  ['isn_20t_20a_20virtual_20dispatch_20c_20redesign_109',['2.4 Why this isn&apos;t a virtual-dispatch / C++ redesign',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md60',1,'']]],
  ['issue_3a_20reconnect_20livelock_20between_20two_20independently_20retrying_20endpoints_110',['2.5 Known open issue: reconnect livelock between two independently-retrying endpoints',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md254',1,'']]],
  ['it_111',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['it_20deliberately_20doesn_20t_112',['2.3 What &quot;real&quot; means here, and what it deliberately doesn&apos;t',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md160',1,'']]],
  ['it_20s_20correct_20without_20triggering_20tt_20wsign_20conversion_20tt_113',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]],
  ['item_3a_20manual_20online_20confirmation_20on_20simultaneous_20dual_20reboot_114',['2.5 Known open item: manual ONLINE confirmation on simultaneous dual-reboot',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md265',1,'']]],
  ['items_115',['7. Open items',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md22',1,'']]],
  ['iteration_5fcount_116',['iteration_count',['../structsapi__appmanager__state__t.html#a86a7eec86ed0c4ec3931073735e496d3',1,'sapi_appmanager_state_t']]],
  ['iteration_5fcount_20tt_20as_20the_20checkpoint_20id_117',['2.2 Checkpoint is opt-in, reuses &lt;tt&gt;iteration_count&lt;/tt&gt; as the checkpoint ID',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md168',1,'']]],
  ['its_20own_118',['2.2 C is a pure relay - no session state of its own',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md273',1,'']]],
  ['its_20own_20and_20the_20peer_20s_20state_119',['3. The negotiator keeps both its own and the peer&apos;s state',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md183',1,'']]],
  ['its_20own_20hysteresis_120',['2.3 Negotiation watchdog timeout was shorter than its own hysteresis',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md263',1,'']]]
];
