var searchData=
[
  ['warnings_20treated_20as_20errors_0',['&quot;Compiler warnings treated as errors&quot;',['../md_docs_2CROSS__COMPILATION.html#autotoc_md256',1,'']]],
  ['watchdog_1',['watchdog',['../watchdog_user_guide.html#watchdog_user_guide_qs_create',1,'2. Create Watchdog'],['../watchdog_user_guide.html#watchdog_user_guide_qs_start',1,'3. Start Watchdog'],['../watchdog_architecture.html#watchdog_architecture_state',1,'State Per Watchdog'],['../structsapi__checkpoint__config__t.html#aadf3ff5dcb28cf555d6712a2c9282089',1,'sapi_checkpoint_config_t::watchdog'],['../watchdog_user_guide.html#watchdog_user_guide_overview',1,'What is the Watchdog?']]],
  ['watchdog_20main_20loop_20heartbeat_2',['Example 1: System Watchdog (Main Loop Heartbeat)',['../watchdog_user_guide.html#watchdog_user_guide_example_system',1,'']]],
  ['watchdog_20manager_3',['Watchdog Manager',['../watchdog_architecture.html#watchdog_architecture_manager',1,'']]],
  ['watchdog_20mechanism_4',['Watchdog Mechanism',['../group__WATCHDOG.html',1,'']]],
  ['watchdog_20module_5',['With Watchdog Module',['../safestate_architecture.html#safestate_architecture_integ_watchdog',1,'']]],
  ['watchdog_20module_20architecture_6',['Watchdog Module - Architecture',['../watchdog_architecture.html',1,'']]],
  ['watchdog_20module_20user_20guide_7',['Watchdog Module - User Guide',['../watchdog_user_guide.html',1,'']]],
  ['watchdog_20regularly_8',['4. Kick Watchdog Regularly',['../watchdog_user_guide.html#watchdog_user_guide_qs_kick',1,'']]],
  ['watchdog_20status_9',['Pattern 2: Check Watchdog Status',['../watchdog_user_guide.html#watchdog_user_guide_pattern_status',1,'']]],
  ['watchdog_20triggered_20reboot_10',['Example 1: Watchdog-Triggered Reboot',['../reboot_user_guide.html#reboot_user_guide_example_watchdog',1,'']]],
  ['watchdog_20types_11',['Watchdog Types',['../watchdog_user_guide.html#watchdog_user_guide_types',1,'']]],
  ['wear_12',['Flash Wear',['../nvm_architecture.html#nvm_architecture_wear',1,'']]],
  ['what_20is_20a_20buffer_13',['What is a Buffer?',['../buffer_user_guide.html#buffer_user_guide_overview',1,'']]],
  ['what_20is_20a_20timer_14',['What is a Timer?',['../timer_user_guide.html#timer_user_guide_overview',1,'']]],
  ['what_20is_20checksum_15',['What is Checksum?',['../checksum_user_guide.html#checksum_user_guide_overview',1,'']]],
  ['what_20is_20logging_16',['What is Logging?',['../log_user_guide.html#log_user_guide_overview',1,'']]],
  ['what_20is_20nvm_17',['What is NVM?',['../nvm_user_guide.html#nvm_user_guide_overview',1,'']]],
  ['what_20is_20reboot_18',['What is Reboot?',['../reboot_user_guide.html#reboot_user_guide_overview',1,'']]],
  ['what_20is_20safe_20state_19',['What is Safe-State?',['../safestate_user_guide.html#safestate_user_guide_overview',1,'']]],
  ['what_20is_20task_20queue_20',['What is Task Queue?',['../task_user_guide.html#task_user_guide_overview',1,'']]],
  ['what_20is_20the_20cast_20module_21',['What is the Cast Module?',['../cast_user_guide.html#cast_user_guide_overview',1,'']]],
  ['what_20is_20the_20memory_20module_22',['What is the Memory Module?',['../memory_user_guide.html#memory_user_guide_overview',1,'']]],
  ['what_20is_20the_20status_20module_23',['What is the Status Module?',['../status_user_guide.html#status_user_guide_overview',1,'']]],
  ['what_20is_20the_20string_20module_24',['What is the String Module?',['../string_user_guide.html#string_user_guide_overview',1,'']]],
  ['what_20is_20the_20watchdog_25',['What is the Watchdog?',['../watchdog_user_guide.html#watchdog_user_guide_overview',1,'']]],
  ['what_20is_20types_26',['What is Types?',['../types_user_guide.html#types_user_guide_overview',1,'']]],
  ['what_20is_20vital_20channel_27',['What is Vital Channel?',['../vital_channel_user_guide.html#vital_channel_user_guide_overview',1,'']]],
  ['what_20it_20deliberately_20doesn_20t_28',['2.3 What &quot;real&quot; means here, and what it deliberately doesn&apos;t',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md160',1,'']]],
  ['what_20real_20means_20here_20and_20what_20it_20deliberately_20doesn_20t_29',['2.3 What &quot;real&quot; means here, and what it deliberately doesn&apos;t',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md160',1,'']]],
  ['what_20stays_20true_20from_20earlier_20adrs_20despite_20the_20directory_20change_30',['2.3 What stays true from earlier ADRs despite the directory change',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md79',1,'']]],
  ['what_20you_20need_20to_20implement_31',['What You Need to Implement',['../appmanager_integration.html#appmanager_integration_you_implement',1,'']]],
  ['where_20to_20go_20next_32',['Where to Go Next',['../system_architecture.html#system_architecture_docs',1,'']]],
  ['why_20crc_2064_20is_20right_20for_20sapi_33',['Why CRC-64 is Right for SAPI',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md95',1,'']]],
  ['why_20it_20s_20correct_20without_20triggering_20tt_20wsign_20conversion_20tt_34',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]],
  ['why_20named_20functions_20instead_20of_20macros_20or_20c11_20tt_20_5fgeneric_20tt_35',['2.5 Why named functions instead of macros or C11 &lt;tt&gt;_Generic&lt;/tt&gt;',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md38',1,'']]],
  ['why_20no_20dynamic_20allocation_36',['Why No Dynamic Allocation?',['../memory_user_guide.html#memory_user_guide_rationale',1,'']]],
  ['why_20this_20isn_20t_20a_20virtual_20dispatch_20c_20redesign_37',['2.4 Why this isn&apos;t a virtual-dispatch / C++ redesign',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md60',1,'']]],
  ['why_20tt_20sapi_5fsafestate_20tt_20does_20not_20call_20tt_20sapi_5freboot_20tt_20directly_38',['2.3 Why &lt;tt&gt;sapi_safestate&lt;/tt&gt; does not call &lt;tt&gt;sapi_reboot&lt;/tt&gt; directly',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md47',1,'']]],
  ['widening_39',['2.1 Scope: every ordered pair, including widening',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md34',1,'']]],
  ['width_20types_40',['2. Use Fixed-Width Types',['../types_user_guide.html#types_user_guide_qs_use',1,'']]],
  ['with_20channels_41',['App Manager Integration with Channels',['../appmanager_integration.html',1,'']]],
  ['with_20existing_20modules_42',['With Existing Modules',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md109',1,'']]],
  ['with_20fallback_43',['Example 3: Reboot with Fallback',['../reboot_user_guide.html#reboot_user_guide_example_fallback',1,'']]],
  ['with_20mirroring_44',['Pattern 3: Hot Standby with Mirroring',['../vital_channel_topologies.html#vital_channel_topologies_pattern_mirror_hot_standby',1,'']]],
  ['with_20plantuml_20doxygen_45',['Architecture Diagrams with PlantUML &amp; Doxygen',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html',1,'']]],
  ['with_20reboot_20module_46',['With Reboot Module',['../safestate_architecture.html#safestate_architecture_integ_reboot',1,'']]],
  ['with_20redundancy_20framework_20future_20v0_204_200_47',['With Redundancy Framework (Future v0.4.0+)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md108',1,'']]],
  ['with_20safe_20state_48',['with safe state',['../reboot_user_guide.html#reboot_user_guide_integration',1,'Integration with Safe-State'],['../watchdog_architecture.html#watchdog_architecture_integration',1,'Integration with Safe-State'],['../status_architecture.html#status_architecture_safestate',1,'Integration with Safe-State']]],
  ['with_20vital_20channel_49',['Integration with Vital Channel',['../ipc_transport_selection.html#ipc_transport_selection_vital_channel_integration',1,'']]],
  ['with_20watchdog_20module_50',['With Watchdog Module',['../safestate_architecture.html#safestate_architecture_integ_watchdog',1,'']]],
  ['without_20generating_3a_51',['Verify syntax without generating:',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md172',1,'']]],
  ['without_20malloc_52',['Example 2: Ring Buffer Without malloc',['../memory_user_guide.html#memory_user_guide_example_ringbuf',1,'']]],
  ['without_20triggering_20tt_20wsign_20conversion_20tt_53',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]],
  ['workflow_20for_20online_20standby_20setup_54',['Typical Workflow for Online/Standby Setup',['../ipc_guide.html#ipc_guide_workflow',1,'']]],
  ['world_20impact_55',['Real-World Impact',['../memory_user_guide.html#memory_user_guide_rationale_example',1,'']]],
  ['wrapper_56',['3. Vital Message Wrapper',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md104',1,'']]],
  ['wraps_20tt_20sapi_5fbuffer_5ft_20tt_57',['2.1 &lt;tt&gt;sapi_string_t&lt;/tt&gt; wraps &lt;tt&gt;sapi_buffer_t&lt;/tt&gt;',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md67',1,'']]],
  ['write_58',['write',['../structsapi__log__backend__t.html#a62ee7f650a6816035f55d5514d752481',1,'sapi_log_backend_t::write'],['../structsapi__nvm__backend__t.html#afd8403fe9dbd9d44b0360c117fee0ba3',1,'sapi_nvm_backend_t::write']]],
  ['write_20data_59',['Write Data',['../buffer_user_guide.html#buffer_user_guide_op_write',1,'']]],
  ['write_20interface_60',['Read/Write Interface',['../nvm_architecture.html#nvm_architecture_api',1,'']]],
  ['wsign_20conversion_20tt_61',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]]
];
