var searchData=
[
  ['b_20→_20c_0',['Pattern 1: Single-System 2oo2 (A ↔ B → C)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_single_2oo2',1,'']]],
  ['b_20across_20network_1',['Pattern 2: Distributed 2oo2 (A ↔ B Across Network)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_distributed_2oo2',1,'']]],
  ['b_3a_20the_20train_20session_20table_2',['2.3 A/B: the train-session table',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md274',1,'']]],
  ['backend_3',['backend',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md151',1,'2.2 &lt;tt&gt;sapi_checkpoint&lt;/tt&gt;: bounded rendezvous, no new transport backend'],['../md_docs_2architecture_2ADR-018-posix-oal-backend.html',1,'ADR-018: A Real POSIX/Linux OAL Backend']]],
  ['backend_20adaptation_4',['backend adaptation',['../group__CLOCKSYNC__BACKEND.html',1,'Clock Synchronization - Backend Adaptation'],['../group__REBOOT__BACKEND.html',1,'Controlled Reboot - Backend Adaptation'],['../group__IPC__BACKEND.html',1,'Inter-Process Communication - Backend Adaptation'],['../group__LOG__BACKEND.html',1,'Logging and Diagnostics - Backend Adaptation'],['../group__MUTEX__BACKEND.html',1,'Mutex Service - Backend Adaptation'],['../group__NVM__BACKEND.html',1,'NVM Service - Backend Adaptation'],['../group__NETLINK__BACKEND.html',1,'Point-to-Point Network Link - Backend Adaptation'],['../group__MEMORY__BACKEND.html',1,'Static Memory Reservation - Backend Adaptation'],['../group__TASK__BACKEND.html',1,'Task/Thread Scheduling - Backend Adaptation'],['../group__TIMER__BACKEND.html',1,'Timer Service - Backend Adaptation']]],
  ['backend_20at_20startup_5',['1. Register Backend at Startup',['../reboot_user_guide.html#reboot_user_guide_qs_backend',1,'']]],
  ['backend_20header_20separation_6',['ADR-021: Consumer / OS-Backend Header Separation',['../md_docs_2architecture_2ADR-021-consumer-backend-header-split.html',1,'']]],
  ['backend_20implementation_7',['Backend Implementation',['../nvm_architecture.html#nvm_architecture_backend',1,'']]],
  ['backend_20implementation_20pattern_8',['Backend Implementation Pattern',['../ipc_transport_selection.html#ipc_transport_selection_backend_vtable',1,'']]],
  ['backend_20indirection_9',['3.5 Backend indirection',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md17',1,'']]],
  ['backend_20interface_10',['Backend Interface',['../reboot_architecture.html#reboot_architecture_backend',1,'']]],
  ['backend_20only_20executes_11',['2.2 The framework still validates; the backend only executes',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md58',1,'']]],
  ['backend_20registration_20and_20remaining_20setup_20only_20constructors_12',['ADR-032: Setup-phase lock coverage extended to backend registration and remaining setup-only constructors',['../md_docs_2architecture_2ADR-032-setup-phase-lock-coverage-extended.html',1,'']]],
  ['backend_20registration_20via_20callbacks_13',['ADR-005: OAL Backend Registration via Callbacks',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html',1,'']]],
  ['backend_20same_20file_20same_20accessor_20req_20oal_20netlink_20014_14',['2.1 New UDP backend, same file, same accessor (REQ-OAL-NETLINK-014)',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md250',1,'']]],
  ['backend_20vtable_20type_20and_20one_20registration_20function_20per_20service_15',['2.1 One backend vtable type and one registration function per service',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md57',1,'']]],
  ['backends_16',['Transport Backends',['../vital_channel_architecture.html#vital_channel_architecture_transport_backends',1,'']]],
  ['backing_20storage_17',['1. Allocate Backing Storage',['../buffer_user_guide.html#buffer_user_guide_qs_storage',1,'']]],
  ['bar_18',['2.5 Verification bar',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html#autotoc_md202',1,'']]],
  ['base_20channel_20—_20tt_20sapi_5fdual_5fmsgchannel_20h_20tt_20adr_20020_20§1_20layer_201_19',['3e.2 Base Channel — &lt;tt&gt;sapi_dual_msgchannel.h&lt;/tt&gt; (ADR-020 §1, Layer 1)',['../safeapi_srs.html#autotoc_md439',1,'']]],
  ['based_20allocation_20',['Pattern 1: Pool-Based Allocation',['../memory_user_guide.html#memory_user_guide_common_pool',1,'']]],
  ['based_20buffer_20design_21',['View-Based Buffer Design',['../buffer_architecture.html#buffer_architecture_overview',1,'']]],
  ['based_20fault_20detection_22',['Example 3: Assertion-Based Fault Detection',['../safestate_user_guide.html#safestate_user_guide_example_assertion',1,'']]],
  ['basis_20of_20correctness_23',['2.3 &lt;tt&gt;sapi_clocksync&lt;/tt&gt;: diagnostic only, never the basis of correctness',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md152',1,'']]],
  ['before_20convert_24',['Check-Before-Convert',['../cast_architecture.html#cast_architecture_strategy',1,'']]],
  ['behavior_25',['Test 2: SAPI_ASSERT Behavior',['../safestate_architecture.html#safestate_architecture_test_assert',1,'']]],
  ['behavioral_26',['4. State Machine Diagram (Behavioral)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md340',1,'']]],
  ['behavioral_20checkpoint_20flow_27',['6. Activity Diagram (Behavioral - Checkpoint Flow)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md344',1,'']]],
  ['behavioral_20diagrams_20configuration_20sequences_28',['Behavioral Diagrams - Configuration Sequences',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md315',1,'']]],
  ['behavioral_20ipc_29',['2. Sequence Diagram (Behavioral - IPC)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md336',1,'']]],
  ['behavioral_20redundancy_30',['3. Sequence Diagram (Behavioral - Redundancy)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md338',1,'']]],
  ['best_20practices_31',['best practices',['../watchdog_user_guide.html#watchdog_user_guide_guidelines',1,'Best Practices'],['../types_user_guide.html#types_user_guide_guidelines',1,'Best Practices'],['../safestate_user_guide.html#safestate_user_guide_guidelines',1,'Best Practices'],['../reboot_user_guide.html#reboot_user_guide_guidelines',1,'Best Practices'],['../status_user_guide.html#status_user_guide_guidelines',1,'Best Practices'],['../string_user_guide.html#string_user_guide_guidelines',1,'Best Practices'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md359',1,'Best Practices'],['../nvm_user_guide.html#nvm_user_guide_guidelines',1,'Best Practices'],['../memory_user_guide.html#memory_user_guide_guidelines',1,'Best Practices'],['../timer_user_guide.html#timer_user_guide_guidelines',1,'Best Practices'],['../log_user_guide.html#log_user_guide_guidelines',1,'Best Practices'],['../checksum_user_guide.html#checksum_user_guide_guidelines',1,'Best Practices'],['../vital_channel_user_guide.html#vital_channel_user_guide_guidelines',1,'Best Practices'],['../buffer_user_guide.html#buffer_user_guide_guidelines',1,'Best Practices'],['../cast_user_guide.html#cast_user_guide_guidelines',1,'Best Practices']]],
  ['between_20two_20independently_20retrying_20endpoints_32',['2.5 Known open issue: reconnect livelock between two independently-retrying endpoints',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md254',1,'']]],
  ['bind_20buffer_20view_33',['2. Bind Buffer View',['../buffer_user_guide.html#buffer_user_guide_qs_init',1,'']]],
  ['bis_20application_20setup_20phase_20lock_20—_20tt_20sapi_5flifecycle_20h_20tt_20adr_20026_34',['3c-bis. Application setup-phase lock — &lt;tt&gt;sapi_lifecycle.h&lt;/tt&gt; (ADR-026)',['../safeapi_srs.html#autotoc_md432',1,'']]],
  ['block_5fcount_35',['block_count',['../structsapi__mem__pool__config__t.html#abbf4fbb3bfdfdd6e7646009758917ff6',1,'sapi_mem_pool_config_t']]],
  ['block_5fsize_36',['block_size',['../structsapi__mem__pool__config__t.html#a2109332171b85527842fd7d167e92561',1,'sapi_mem_pool_config_t']]],
  ['both_20its_20own_20and_20the_20peer_20s_20state_37',['3. The negotiator keeps both its own and the peer&apos;s state',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md183',1,'']]],
  ['bounded_20ack_20that_20is_20the_20liveness_20signal_38',['2. Always send, wait for a bounded ACK - that IS the liveness signal',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md182',1,'']]],
  ['bounded_20rendezvous_20no_20new_20transport_20backend_39',['2.2 &lt;tt&gt;sapi_checkpoint&lt;/tt&gt;: bounded rendezvous, no new transport backend',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md151',1,'']]],
  ['bounded_20string_20manipulation_40',['Bounded String Manipulation',['../group__STRING.html',1,'']]],
  ['bounded_20string_20manipulation_20—_20tt_20sapi_5fstring_20h_20tt_20adr_20006_41',['1.6 Bounded string manipulation — &lt;tt&gt;sapi_string.h&lt;/tt&gt; (ADR-006)',['../safeapi_srs.html#autotoc_md416',1,'']]],
  ['broadcast_42',['Send Semantics (Atomic Broadcast)',['../vital_channel_architecture.html#vital_channel_architecture_send_semantics',1,'']]],
  ['buf_43',['buf',['../structsapi__string__t.html#a6729d6bc50603d43ef507ef8b253eaa5',1,'sapi_string_t']]],
  ['buffer_44',['buffer',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md27',1,'2.2 No integrity metadata on the generic buffer'],['../buffer_user_guide.html#buffer_user_guide_qs_use',1,'3. Use Buffer'],['../group__BUFFER.html',1,'Cross-Layer Data Buffer'],['../buffer_user_guide.html#buffer_user_guide_example_message',1,'Example 1: Fixed-Size Message Buffer'],['../checksum_architecture.html#checksum_architecture_performance',1,'O(n) Per Buffer'],['../log_architecture.html#log_architecture_storage',1,'Ring Buffer'],['../buffer_user_guide.html#buffer_user_guide_overview',1,'What is a Buffer?']]],
  ['buffer_20—_20tt_20sapi_5fbuffer_20h_20tt_20adr_20002_45',['1.3 Cross-layer data buffer — &lt;tt&gt;sapi_buffer.h&lt;/tt&gt; (ADR-002)',['../safeapi_srs.html#autotoc_md413',1,'']]],
  ['buffer_20abstraction_46',['ADR-002: Cross-Layer Data Buffer Abstraction',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html',1,'']]],
  ['buffer_20access_47',['ADR-006: Safe String Manipulation and Endianness-Safe Buffer Access',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html',1,'']]],
  ['buffer_20design_48',['View-Based Buffer Design',['../buffer_architecture.html#buffer_architecture_overview',1,'']]],
  ['buffer_20endianness_20helpers_3a_20explicit_20per_20call_20no_20default_49',['2.5 Buffer endianness helpers: explicit per call, no default',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md71',1,'']]],
  ['buffer_20module_20architecture_50',['Buffer Module - Architecture',['../buffer_architecture.html',1,'']]],
  ['buffer_20module_20user_20guide_51',['Buffer Module - User Guide',['../buffer_user_guide.html',1,'']]],
  ['buffer_20operations_52',['Buffer Operations',['../buffer_user_guide.html#buffer_user_guide_operations',1,'']]],
  ['buffer_20view_53',['2. Bind Buffer View',['../buffer_user_guide.html#buffer_user_guide_qs_init',1,'']]],
  ['buffer_20without_20malloc_54',['Example 2: Ring Buffer Without malloc',['../memory_user_guide.html#memory_user_guide_example_ringbuf',1,'']]],
  ['buffers_55',['Pattern 1: Static Global Buffers',['../memory_user_guide.html#memory_user_guide_pattern_global',1,'']]],
  ['bug_20fixed_56',['2.2 &lt;tt&gt;sapi_voter&lt;/tt&gt; (new) - N-way voting, with the majority-vote bug fixed',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md227',1,'']]],
  ['bug_3a_20the_20cyclic_20executive_20starves_20whenever_20checkpoint_20is_20paused_57',['2.4 The real bug: the cyclic executive starves whenever checkpoint is paused',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md264',1,'']]],
  ['bugs_58',['2.5 The real debugging story: three genuine synchronization bugs',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md276',1,'']]],
  ['build_59',['build',['../md_docs_2CROSS__COMPILATION.html#autotoc_md380',1,'1. Native Linux Build'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md381',1,'2. Linux Release Build']]],
  ['build_20configuration_20adr_20024_60',['2.8 Build configuration (ADR-024)',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md233',1,'']]],
  ['build_20diagrams_20locally_61',['Build Diagrams Locally',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md353',1,'']]],
  ['build_20diversity_62',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['build_20for_20qnx_63',['3. Build for QNX',['../md_docs_2CROSS__COMPILATION.html#autotoc_md388',1,'']]],
  ['build_20instructions_64',['Detailed Build Instructions',['../md_docs_2CROSS__COMPILATION.html#autotoc_md378',1,'']]],
  ['build_20integration_65',['2.4 Build integration',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md161',1,'']]],
  ['build_20structure_66',['5. Directory / build structure',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md20',1,'']]],
  ['build_5farrival_5fmessage_67',['build_arrival_message',['../sapi__checkpoint_8c.html#a6eafe59042730a3fc0070b367f6148da',1,'sapi_checkpoint.c']]],
  ['building_68',['Building',['../index.html#autotoc_md2',1,'']]],
  ['building_20diagrams_20locally_69',['Building Diagrams Locally',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md316',1,'']]],
  ['built_20in_20checkpoint_20rendezvous_70',['ADR-019: AppManager Cycle Hooks and Built-In Checkpoint Rendezvous',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html',1,'']]],
  ['built_20just_20surfaced_71',['2.2 Negotiation link: HOT/COLD standby readiness (already built, just surfaced)',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md262',1,'']]],
  ['by_20default_72',['Pattern 2: Fail-Safe-by-Default',['../safestate_user_guide.html#safestate_user_guide_pattern_failsafe',1,'']]],
  ['by_20this_20adr_73',['2.6 Deliberately not addressed by this ADR',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md255',1,'']]]
];
