var searchData=
[
  ['each_20service_20s_20fixed_20opaque_20storage_0',['2.2 Fitting inside each service&apos;s fixed opaque storage',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md159',1,'']]],
  ['earlier_20adrs_20despite_20the_20directory_20change_1',['2.3 What stays true from earlier ADRs despite the directory change',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md79',1,'']]],
  ['em_20not_20em_20change_2',['em not em change',['../md_docs_2architecture_2ADR-023-consolidate-cmake-libraries.html#autotoc_md208',1,'2.1 What does &lt;em&gt;not&lt;/em&gt; change'],['../md_docs_2architecture_2ADR-024-configurable-feature-build.html#autotoc_md219',1,'2.4 What does &lt;em&gt;not&lt;/em&gt; change']]],
  ['embedding_20diagrams_20in_20doxygen_20comments_3',['Embedding Diagrams in Doxygen Comments',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md339',1,'']]],
  ['en_2050128_20compliance_4',['EN 50128 Compliance',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md111',1,'']]],
  ['en_2050159_5',['1. Two defensive layers, not one (EN 50159)',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md181',1,'']]],
  ['en_2050159_20envelope_20that_20already_20exists_20—_20don_20t_20rebuild_20it_6',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['enable_7',['2.2 Enforcement: explicit failure, not silent auto-enable',['../md_docs_2architecture_2ADR-024-configurable-feature-build.html#autotoc_md217',1,'']]],
  ['endianness_20helpers_3a_20explicit_20per_20call_20no_20default_8',['2.5 Buffer endianness helpers: explicit per call, no default',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md71',1,'']]],
  ['endianness_20safe_20buffer_20access_9',['ADR-006: Safe String Manipulation and Endianness-Safe Buffer Access',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html',1,'']]],
  ['endpoints_10',['endpoints',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md254',1,'2.5 Known open issue: reconnect livelock between two independently-retrying endpoints'],['../structsapi__safechannel__vital__config__t.html#ab523ed55e5e5f6fb4e2a068f60aaabaf',1,'sapi_safechannel_vital_config_t::endpoints'],['../structsapi__safechannel__dual__config__t.html#aa180096df53689b0565ef66dd3f0c398',1,'sapi_safechannel_dual_config_t::endpoints']]],
  ['enforced_20defensively_11',['2.4 &quot;Does not return&quot;, enforced defensively',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md48',1,'']]],
  ['enforcement_12',['ADR-026: Application Setup-Phase Lock and Single-Entry-Point Enforcement',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html',1,'']]],
  ['enforcement_20req_20appmanager_20009_13',['2.3 Single-entry-point enforcement (REQ-APPMANAGER-009)',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html#autotoc_md242',1,'']]],
  ['enforcement_3a_20explicit_20failure_20not_20silent_20auto_20enable_14',['2.2 Enforcement: explicit failure, not silent auto-enable',['../md_docs_2architecture_2ADR-024-configurable-feature-build.html#autotoc_md217',1,'']]],
  ['entering_20a_20level_15',['Entering a Level',['../safestate_architecture.html#safestate_architecture_api_enter',1,'']]],
  ['entry_16',['entry',['../structsapi__task__config__t.html#a0f2b31d8a9a183487ba731c7cd83e446',1,'sapi_task_config_t']]],
  ['entry_20format_17',['Entry Format',['../log_architecture.html#log_architecture_format',1,'']]],
  ['entry_20point_20enforcement_18',['ADR-026: Application Setup-Phase Lock and Single-Entry-Point Enforcement',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html',1,'']]],
  ['entry_20point_20enforcement_20req_20appmanager_20009_19',['2.3 Single-entry-point enforcement (REQ-APPMANAGER-009)',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html#autotoc_md242',1,'']]],
  ['enum_20one_20config_20netlink_20opened_20internally_20',['2.2 One handle, one type enum, one config, netlink opened internally',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html#autotoc_md199',1,'']]],
  ['envelope_21',['2.1 Wire protocol - one shared, fixed-size envelope',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md272',1,'']]],
  ['envelope_20that_20already_20exists_20—_20don_20t_20rebuild_20it_22',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['environment_20variables_23',['2. Set Environment Variables',['../md_docs_2CROSS__COMPILATION.html#autotoc_md380',1,'']]],
  ['error_24',['2. Request Reboot on Critical Error',['../reboot_user_guide.html#reboot_user_guide_qs_request',1,'']]],
  ['error_20codes_25',['Common Status and Error Codes',['../group__STATUS.html',1,'']]],
  ['error_20detection_26',['Random vs Systematic Error Detection',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md113',1,'']]],
  ['error_20handling_27',['3.6 Error handling',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md18',1,'']]],
  ['error_20handling_20patterns_28',['Error Handling Patterns',['../status_user_guide.html#status_user_guide_error_handling',1,'']]],
  ['error_5fcount_29',['error_count',['../structsapi__appmanager__state__t.html#ae5a611fc818cbc7d59fce546d049a9f1',1,'sapi_appmanager_state_t']]],
  ['error_5fthreshold_30',['error_threshold',['../structsapi__appmanager__config__t.html#a5ea836b854f51d6062bf60cc97222d0b',1,'sapi_appmanager_config_t']]],
  ['errors_31',['&quot;Compiler warnings treated as errors&quot;',['../md_docs_2CROSS__COMPILATION.html#autotoc_md397',1,'']]],
  ['escalation_20to_20reboot_20and_20a_20cyclic_20executive_20starvation_20fix_32',['ADR-028: Channel-Down Escalation to REBOOT, and a Cyclic-Executive Starvation Fix',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html',1,'']]],
  ['escape_20hatch_3a_20tt_20sapi_5fappmanager_5freset_5fstate_20tt_33',['2.4 The &lt;tt&gt;longjmp()&lt;/tt&gt; escape hatch: &lt;tt&gt;sapi_appmanager_reset_state()&lt;/tt&gt;',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html#autotoc_md243',1,'']]],
  ['etc_34',['Cross-Compilation (Linux, QNX, etc.)',['../index.html#autotoc_md4',1,'']]],
  ['every_20ordered_20pair_20including_20widening_35',['2.1 Scope: every ordered pair, including widening',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md34',1,'']]],
  ['example_36',['example',['../vital_channel_architecture.html#vital_channel_architecture_communication_flow',1,'Communication Flow (2oo2 Example)'],['../appmanager_integration.html#appmanager_integration_complete_example',1,'Complete Example']]],
  ['example_201_3a_20fixed_20size_20message_20buffer_37',['Example 1: Fixed-Size Message Buffer',['../buffer_user_guide.html#buffer_user_guide_example_message',1,'']]],
  ['example_201_3a_20periodic_20heartbeat_38',['Example 1: Periodic Heartbeat',['../timer_user_guide.html#timer_user_guide_example_periodic',1,'']]],
  ['example_201_3a_20redundant_20channel_20voting_20failure_39',['Example 1: Redundant Channel Voting Failure',['../safestate_user_guide.html#safestate_user_guide_example_voting',1,'']]],
  ['example_201_3a_20system_20watchdog_20main_20loop_20heartbeat_40',['Example 1: System Watchdog (Main Loop Heartbeat)',['../watchdog_user_guide.html#watchdog_user_guide_example_system',1,'']]],
  ['example_201_3a_20train_20control_20system_41',['Example 1: Train Control System',['../memory_user_guide.html#memory_user_guide_example_train',1,'']]],
  ['example_201_3a_20type_20safe_20structure_42',['Example 1: Type-Safe Structure',['../types_user_guide.html#types_user_guide_example_struct',1,'']]],
  ['example_201_3a_20watchdog_20triggered_20reboot_43',['Example 1: Watchdog-Triggered Reboot',['../reboot_user_guide.html#reboot_user_guide_example_watchdog',1,'']]],
  ['example_202_3a_20custom_20callback_20on_20timeout_44',['Example 2: Custom Callback on Timeout',['../watchdog_user_guide.html#watchdog_user_guide_example_custom',1,'']]],
  ['example_202_3a_20graceful_20degradation_45',['Example 2: Graceful Degradation',['../safestate_user_guide.html#safestate_user_guide_example_degraded',1,'']]],
  ['example_202_3a_20memory_20corruption_20detection_46',['Example 2: Memory Corruption Detection',['../reboot_user_guide.html#reboot_user_guide_example_memory',1,'']]],
  ['example_202_3a_20one_20shot_20timeout_47',['Example 2: One-Shot Timeout',['../timer_user_guide.html#timer_user_guide_example_oneshot',1,'']]],
  ['example_202_3a_20read_20only_20view_48',['Example 2: Read-Only View',['../buffer_user_guide.html#buffer_user_guide_example_ringbuf',1,'']]],
  ['example_202_3a_20ring_20buffer_20without_20malloc_49',['Example 2: Ring Buffer Without malloc',['../memory_user_guide.html#memory_user_guide_example_ringbuf',1,'']]],
  ['example_202_3a_20sized_20counters_50',['Example 2: Sized Counters',['../types_user_guide.html#types_user_guide_example_counter',1,'']]],
  ['example_203_3a_20assertion_20based_20fault_20detection_51',['Example 3: Assertion-Based Fault Detection',['../safestate_user_guide.html#safestate_user_guide_example_assertion',1,'']]],
  ['example_203_3a_20reboot_20with_20fallback_52',['Example 3: Reboot with Fallback',['../reboot_user_guide.html#reboot_user_guide_example_fallback',1,'']]],
  ['examples_53',['examples',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md326',1,'Diagram Types &amp; Examples'],['../buffer_user_guide.html#buffer_user_guide_examples',1,'Practical Examples'],['../cast_user_guide.html#cast_user_guide_examples',1,'Practical Examples'],['../types_user_guide.html#types_user_guide_examples',1,'Practical Examples'],['../checksum_user_guide.html#checksum_user_guide_examples',1,'Practical Examples'],['../watchdog_user_guide.html#watchdog_user_guide_examples',1,'Practical Examples'],['../timer_user_guide.html#timer_user_guide_examples',1,'Practical Examples'],['../string_user_guide.html#string_user_guide_examples',1,'Practical Examples'],['../status_user_guide.html#status_user_guide_examples',1,'Practical Examples'],['../memory_user_guide.html#memory_user_guide_examples',1,'Practical Examples'],['../safestate_user_guide.html#safestate_user_guide_examples',1,'Practical Examples'],['../reboot_user_guide.html#reboot_user_guide_examples',1,'Practical Examples'],['../ipc_guide.html#ipc_guide_examples',1,'Quick Examples'],['../vital_channel_architecture.html#vital_channel_architecture_examples',1,'Usage Examples']]],
  ['execute_54',['execute',['../structsapi__appmanager__operations__t.html#a5f5e8440cd3b527558aa00b3c3adaad4',1,'sapi_appmanager_operations_t']]],
  ['execute_20tt_20unchanged_20in_20meaning_55',['2.1 Three cycle hooks, &lt;tt&gt;execute&lt;/tt&gt; unchanged in meaning',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md167',1,'']]],
  ['executes_56',['2.2 The framework still validates; the backend only executes',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md58',1,'']]],
  ['executive_20starvation_20fix_57',['ADR-028: Channel-Down Escalation to REBOOT, and a Cyclic-Executive Starvation Fix',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html',1,'']]],
  ['executive_20starves_20whenever_20checkpoint_20is_20paused_58',['2.4 The real bug: the cyclic executive starves whenever checkpoint is paused',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md264',1,'']]],
  ['existing_20approaches_59',['Existing Approaches',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md94',1,'']]],
  ['existing_20modules_60',['With Existing Modules',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md109',1,'']]],
  ['exists_20—_20don_20t_20rebuild_20it_61',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['expected_62',['expected',['../structsapi__checksum__result__t.html#a35b67972c86205128fb8fd0bd8edd965',1,'sapi_checksum_result_t']]],
  ['expected_5fnode_5fcount_63',['expected_node_count',['../structsapi__checkpoint__config__t.html#a499e6cc24cad2ce3424df0010f79a3b1',1,'sapi_checkpoint_config_t::expected_node_count'],['../structsapi__appmanager__checkpoint__config__t.html#aa3e23688758870814069ea70e53d5607',1,'sapi_appmanager_checkpoint_config_t::expected_node_count']]],
  ['expected_5fpeer_5fid_64',['expected_peer_id',['../structsapi__safechannel__dual__config__t.html#ab001a30151d05d4648386c6bdd3e01e2',1,'sapi_safechannel_dual_config_t::expected_peer_id'],['../structsapi__dual__msgchannel__config__t.html#ab8d07ee1900aa475b7ea987480a80562',1,'sapi_dual_msgchannel_config_t::expected_peer_id'],['../structsapi__dual__msgchannel__t.html#af6a75f54b6a48cb072e70f728266fcab',1,'sapi_dual_msgchannel_t::expected_peer_id'],['../structsapi__dual__channel__config__t.html#a4756bddfa1cdbe405cce8b84a4ce6a07',1,'sapi_dual_channel_config_t::expected_peer_id']]],
  ['expected_5fsequence_65',['expected_sequence',['../structsapi__dual__msgchannel__t.html#a8b7546b997a09e218984c6d86ebfb68b',1,'sapi_dual_msgchannel_t']]],
  ['explicit_20failure_20not_20silent_20auto_20enable_66',['2.2 Enforcement: explicit failure, not silent auto-enable',['../md_docs_2architecture_2ADR-024-configurable-feature-build.html#autotoc_md217',1,'']]],
  ['explicit_20per_20call_20no_20default_67',['2.5 Buffer endianness helpers: explicit per call, no default',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md71',1,'']]],
  ['explicitly_68',['3. Trigger Safe-State Explicitly',['../safestate_user_guide.html#safestate_user_guide_qs_trigger',1,'']]],
  ['extended_20to_20backend_20registration_20and_20remaining_20setup_20only_20constructors_69',['ADR-032: Setup-phase lock coverage extended to backend registration and remaining setup-only constructors',['../md_docs_2architecture_2ADR-032-setup-phase-lock-coverage-extended.html',1,'']]],
  ['extensions_70',['Future Extensions',['../status_architecture.html#status_architecture_future',1,'']]]
];
