var searchData=
[
  ['last_5ferror_0',['last_error',['../structsapi__vital__channel__health__t.html#a234c738f8ff2fa16f17a29a7b21b72f6',1,'sapi_vital_channel_health_t::last_error'],['../structsapi__appmanager__state__t.html#a835e05cf4eec23c0350d25d84499e4cc',1,'sapi_appmanager_state_t::last_error']]],
  ['last_5fkick_5fms_1',['last_kick_ms',['../structsapi__watchdog__s.html#a8b61fea3c4a2bbe4803446d725219c28',1,'sapi_watchdog_s']]],
  ['layer_2',['Inter-Process Communication (IPC) Transport Layer',['../ipc_transport_selection.html#ipc_transport_selection_overview',1,'']]],
  ['layer_20data_20buffer_3',['Cross-Layer Data Buffer',['../group__BUFFER.html',1,'']]],
  ['layer_20data_20buffer_20abstraction_4',['ADR-002: Cross-Layer Data Buffer Abstraction',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html',1,'']]],
  ['layer_20oal_20for_20the_20safe_20api_20framework_5',['ADR-001: OS Abstraction Layer (OAL) for the Safe API Framework',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html',1,'']]],
  ['layer_20oal_20services_6',['4. Scope of the first abstraction layer (OAL services)',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md19',1,'']]],
  ['layered_20architecture_7',['layered architecture',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md11',1,'2. Layered architecture'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md220',1,'Pattern 3: Layered Architecture']]],
  ['layering_8',['Layering',['../system_architecture.html#system_architecture_layers',1,'']]],
  ['layers_9',['IPC Architecture Layers',['../ipc_guide.html#ipc_guide_layers',1,'']]],
  ['layout_10',['layout',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html',1,'ADR-007: Per-Feature Directory Layout'],['../index.html#autotoc_md7',1,'Layout']]],
  ['length_11',['length',['../structsapi__const__buffer__t.html#ad79db1324548093bea6f36d75fa3ae2c',1,'sapi_const_buffer_t::length'],['../structsapi__buffer__t.html#a256248a77bd37b8ecadfa7a0ea3477ce',1,'sapi_buffer_t::length']]],
  ['level_12',['Entering a Level',['../safestate_architecture.html#safestate_architecture_api_enter',1,'']]],
  ['level_200_13',['DEGRADED (Level 0)',['../safestate_user_guide.html#safestate_user_guide_level_degraded',1,'']]],
  ['level_201_14',['SAFE (Level 1)',['../safestate_user_guide.html#safestate_user_guide_level_safe',1,'']]],
  ['level_202_15',['REBOOT (Level 2)',['../safestate_user_guide.html#safestate_user_guide_level_reboot',1,'']]],
  ['level_20application_20registered_16',['2.2 One handler per level, application-registered',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md46',1,'']]],
  ['level_3a_20sil_203_204_17',['3.2 Target integrity level: SIL 3/4',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md14',1,'']]],
  ['levels_18',['levels',['../log_user_guide.html#log_user_guide_levels',1,'Log Levels'],['../task_user_guide.html#task_user_guide_priority',1,'Priority Levels'],['../safestate_user_guide.html#safestate_user_guide_levels',1,'Safe-State Levels'],['../safestate_architecture.html#safestate_architecture_levels',1,'Three Severity Levels']]],
  ['levels_20not_20a_20single_20safe_20state_19',['2.1 Severity levels, not a single safe state',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md45',1,'']]],
  ['lifecycle_20',['lifecycle',['../appmanager_integration.html#appmanager_integration_lifecycle',1,'Application Lifecycle'],['../watchdog_architecture.html#watchdog_architecture_api_lifecycle',1,'Lifecycle']]],
  ['limitations_21',['Known Limitations',['../vital_channel_architecture.html#vital_channel_architecture_limitations',1,'']]],
  ['limits_22',['limits',['../vital_channel_architecture.html#vital_channel_architecture_message_size',1,'Message Size Limits'],['../safestate_architecture.html#safestate_architecture_storage',1,'Storage and Limits']]],
  ['link_23',['Point-to-Point Network Link',['../group__NETLINK.html',1,'']]],
  ['linux_20build_24',['1. Native Linux Build',['../md_docs_2CROSS__COMPILATION.html#autotoc_md232',1,'']]],
  ['linux_20cmake_25',['Toolchain-Linux.cmake',['../md_docs_2CROSS__COMPILATION.html#autotoc_md249',1,'']]],
  ['linux_20native_20or_20cross_20compile_26',['Linux (Native or Cross-compile)',['../md_docs_2CROSS__COMPILATION.html#autotoc_md227',1,'']]],
  ['linux_20oal_20backend_27',['ADR-018: A Real POSIX/Linux OAL Backend',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html',1,'']]],
  ['linux_20posix_20oal_28',['Linux (POSIX OAL)',['../md_docs_2CROSS__COMPILATION.html#autotoc_md231',1,'']]],
  ['linux_20presets_29',['Linux Presets',['../md_docs_2CROSS__COMPILATION.html#autotoc_md245',1,'']]],
  ['linux_20qnx_20etc_30',['Cross-Compilation (Linux, QNX, etc.)',['../index.html#autotoc_md4',1,'']]],
  ['linux_20release_20build_31',['2. Linux Release Build',['../md_docs_2CROSS__COMPILATION.html#autotoc_md233',1,'']]],
  ['local_20state_20multi_20threaded_32',['Pattern 3: Thread-Local State (Multi-Threaded)',['../memory_user_guide.html#memory_user_guide_pattern_thread',1,'']]],
  ['locally_33',['locally',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md205',1,'Build Diagrams Locally'],['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md168',1,'Building Diagrams Locally']]],
  ['location_34',['location',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md89',1,'4. Location'],['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md163',1,'4. Location'],['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md154',1,'4. Location'],['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md81',1,'4. Location'],['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md73',1,'4. Location'],['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md63',1,'4. Location'],['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md41',1,'4. Location'],['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md30',1,'4. Location'],['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md53',1,'5. Location']]],
  ['locations_35',['Diagram Locations',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md203',1,'']]],
  ['log_20levels_36',['Log Levels',['../log_user_guide.html#log_user_guide_levels',1,'']]],
  ['log_20module_20architecture_37',['Log Module - Architecture',['../log_architecture.html',1,'']]],
  ['log_5fdisagreements_38',['log_disagreements',['../structsapi__vital__channel__config__t.html#ab1f3cda9a723b2fc308683715ecd8d7f',1,'sapi_vital_channel_config_t']]],
  ['logging_39',['What is Logging?',['../log_user_guide.html#log_user_guide_overview',1,'']]],
  ['logging_20and_20diagnostics_40',['Logging and Diagnostics',['../group__LOG.html',1,'']]],
  ['logging_20module_20user_20guide_41',['Logging Module - User Guide',['../log_user_guide.html',1,'']]],
  ['lookup_20tables_20pre_20computed_42',['1. Lookup Tables (Pre-computed)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md102',1,'']]],
  ['loop_43',['Pattern 1: Health Monitoring Loop',['../safestate_user_guide.html#safestate_user_guide_pattern_health',1,'']]],
  ['loop_20heartbeat_44',['Example 1: System Watchdog (Main Loop Heartbeat)',['../watchdog_user_guide.html#watchdog_user_guide_example_system',1,'']]]
];
