var searchData=
[
  ['udp_20transport_0',['UDP Transport',['../ipc_transport_selection.html#ipc_transport_selection_udp',1,'']]],
  ['unbounded_20untrusted_20input_1',['2.2 Never call &lt;tt&gt;strlen()&lt;/tt&gt; on unbounded/untrusted input',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md68',1,'']]],
  ['unit_20tests_2',['unit tests',['../safestate_architecture.html#safestate_architecture_testing',1,'Unit Tests'],['../watchdog_architecture.html#watchdog_architecture_testing',1,'Unit Tests'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md133',1,'Unit Tests']]],
  ['unlike_20tt_20strtok_20tt_3',['2.4 Splitting is reentrant, unlike &lt;tt&gt;strtok&lt;/tt&gt;',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md70',1,'']]],
  ['untrusted_20input_4',['2.2 Never call &lt;tt&gt;strlen()&lt;/tt&gt; on unbounded/untrusted input',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md68',1,'']]],
  ['updating_20diagrams_5',['Updating Diagrams',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md174',1,'']]],
  ['upfront_6',['3. Calculate Required Sizes Upfront',['../memory_user_guide.html#memory_user_guide_qs_calculate',1,'']]],
  ['usage_20examples_7',['Usage Examples',['../vital_channel_architecture.html#vital_channel_architecture_examples',1,'']]],
  ['usage_20patterns_20in_20framework_8',['Usage Patterns in Framework',['../status_architecture.html#status_architecture_usage_patterns',1,'']]],
  ['use_20buffer_9',['3. Use Buffer',['../buffer_user_guide.html#buffer_user_guide_qs_use',1,'']]],
  ['use_20fixed_20width_20types_10',['2. Use Fixed-Width Types',['../types_user_guide.html#types_user_guide_qs_use',1,'']]],
  ['use_20in_20your_20application_11',['4. Use in Your Application',['../md_docs_2CROSS__COMPILATION.html#autotoc_md235',1,'']]],
  ['use_20in_20your_20qnx_20application_12',['5. Use in Your QNX Application',['../md_docs_2CROSS__COMPILATION.html#autotoc_md242',1,'']]],
  ['use_20sapi_5fassert_20for_20checked_20assertions_13',['2. Use SAPI_ASSERT for Checked Assertions',['../safestate_user_guide.html#safestate_user_guide_qs_assert',1,'']]],
  ['user_20guide_14',['user guide',['../buffer_user_guide.html',1,'Buffer Module - User Guide'],['../cast_user_guide.html',1,'Cast Module - User Guide'],['../checksum_user_guide.html',1,'Checksum Module - User Guide'],['../log_user_guide.html',1,'Logging Module - User Guide'],['../memory_user_guide.html',1,'Memory Module - User Guide'],['../nvm_user_guide.html',1,'Non-Volatile Memory User Guide'],['../reboot_user_guide.html',1,'Reboot Module - User Guide'],['../safestate_user_guide.html',1,'Safe-State Module - User Guide'],['../status_user_guide.html',1,'Status Module - User Guide'],['../string_user_guide.html',1,'String Module - User Guide'],['../task_user_guide.html',1,'Task Queue Module - User Guide'],['../timer_user_guide.html',1,'Timer Module - User Guide'],['../types_user_guide.html',1,'Types Module - User Guide'],['../vital_channel_user_guide.html',1,'Vital Channel Module - User Guide'],['../watchdog_user_guide.html',1,'Watchdog Module - User Guide']]],
  ['user_5fctx_15',['user_ctx',['../structsapi__timer__config__t.html#a84f0a537bf9b57a7d1b215e316d80c1d',1,'sapi_timer_config_t::user_ctx'],['../structsapi__task__config__t.html#a9564770ae90735b28050056093c4d4d2',1,'sapi_task_config_t::user_ctx']]],
  ['user_5fguide_16',['user_guide',['../md_include_2safeapi_2reboot_2USER__GUIDE.html',1,'USER_GUIDE'],['../md_include_2safeapi_2buffer_2USER__GUIDE.html',1,'USER_GUIDE'],['../md_include_2safeapi_2cast_2USER__GUIDE.html',1,'USER_GUIDE'],['../md_include_2safeapi_2checksum_2USER__GUIDE.html',1,'USER_GUIDE'],['../md_include_2safeapi_2log_2USER__GUIDE.html',1,'USER_GUIDE'],['../md_include_2safeapi_2memory_2USER__GUIDE.html',1,'USER_GUIDE'],['../md_include_2safeapi_2nvm_2USER__GUIDE.html',1,'USER_GUIDE'],['../md_include_2safeapi_2watchdog_2USER__GUIDE.html',1,'USER_GUIDE'],['../md_include_2safeapi_2safestate_2USER__GUIDE.html',1,'USER_GUIDE'],['../md_include_2safeapi_2status_2USER__GUIDE.html',1,'USER_GUIDE'],['../md_include_2safeapi_2string_2USER__GUIDE.html',1,'USER_GUIDE'],['../md_include_2safeapi_2task_2USER__GUIDE.html',1,'USER_GUIDE'],['../md_include_2safeapi_2timer_2USER__GUIDE.html',1,'USER_GUIDE'],['../md_include_2safeapi_2types_2USER__GUIDE.html',1,'USER_GUIDE'],['../md_include_2safeapi_2vital__channel_2USER__GUIDE.html',1,'USER_GUIDE']]],
  ['using_20cmake_20presets_20recommended_17',['Using CMake Presets (recommended)',['../index.html#autotoc_md3',1,'']]],
  ['using_20in_20doxygen_18',['Using in Doxygen',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md173',1,'']]],
  ['utilities_19',['Checksum &amp; CRC Utilities',['../group__CHECKSUM.html',1,'']]]
];
