var searchData=
[
  ['id_0',['2.2 Checkpoint is opt-in, reuses &lt;tt&gt;iteration_count&lt;/tt&gt; as the checkpoint ID',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md168',1,'']]],
  ['identity_1',['2.2 New feature: &lt;tt&gt;sapi_channel&lt;/tt&gt; (comparator + identity)',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md86',1,'']]],
  ['il_20ctc_20scenario_20—_20tt_20safeapirbc2oo2_20tt_20adr_20029_2',['3h. RBC Train/IL/CTC scenario — &lt;tt&gt;safeAPIRBC2oo2&lt;/tt&gt; (ADR-029)',['../safeapi_srs.html#autotoc_md506',1,'']]],
  ['il_20ctc_20scenario_20real_20multi_20train_20protocol_20and_20failover_20ready_20session_20state_3',['ADR-029: RBC Train/IL/CTC Scenario - Real Multi-Train Protocol and Failover-Ready Session State',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html',1,'']]],
  ['impact_4',['Real-World Impact',['../memory_user_guide.html#memory_user_guide_rationale_example',1,'']]],
  ['implement_5',['What You Need to Implement',['../appmanager_integration.html#appmanager_integration_you_implement',1,'']]],
  ['implement_20callback_6',['3. Implement Callback',['../timer_user_guide.html#timer_user_guide_qs_callback',1,'']]],
  ['implementation_7',['implementation',['../nvm_architecture.html#nvm_architecture_backend',1,'Backend Implementation'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md99',1,'Implementation'],['../safestate_architecture.html#safestate_architecture_assert',1,'SAPI_ASSERT Implementation']]],
  ['implementation_20checklist_8',['Implementation Checklist',['../ipc_transport_selection.html#ipc_transport_selection_implementation_checklist',1,'']]],
  ['implementation_20details_9',['Implementation Details',['../status_architecture.html#status_architecture_implementation',1,'']]],
  ['implementation_20moves_20behind_20the_20vtable_20tt_20safeapibackendposix_20tt_10',['2. POSIX implementation moves behind the vtable (&lt;tt&gt;safeAPIBackendPosix&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-035-platform-realtime-init.html#autotoc_md327',1,'']]],
  ['implementation_20pattern_11',['Backend Implementation Pattern',['../ipc_transport_selection.html#ipc_transport_selection_backend_vtable',1,'']]],
  ['implementation_20responsibility_12',['Implementation Responsibility',['../channel_configuration.html#channel_configuration_implementation_by_integrator',1,'']]],
  ['implementation_20timeline_13',['Implementation Timeline',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md119',1,'']]],
  ['implications_14',['SIL Implications',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md115',1,'']]],
  ['implied_15',['2.3 CCF analysis is documented, not implied',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md87',1,'']]],
  ['in_20adr_20documents_16',['In ADR Documents',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md406',1,'']]],
  ['in_20checkpoint_20rendezvous_17',['ADR-019: AppManager Cycle Hooks and Built-In Checkpoint Rendezvous',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html',1,'']]],
  ['in_20doxygen_18',['Using in Doxygen',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md378',1,'']]],
  ['in_20doxygen_20comments_19',['Embedding Diagrams in Doxygen Comments',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md403',1,'']]],
  ['in_20framework_20',['Usage Patterns in Framework',['../status_architecture.html#status_architecture_usage_patterns',1,'']]],
  ['in_20header_20files_21',['In Header Files',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md404',1,'']]],
  ['in_20markdown_20files_22',['In Markdown Files',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md405',1,'']]],
  ['in_20meaning_23',['2.1 Three cycle hooks, &lt;tt&gt;execute&lt;/tt&gt; unchanged in meaning',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md167',1,'']]],
  ['in_20reuses_20tt_20iteration_5fcount_20tt_20as_20the_20checkpoint_20id_24',['2.2 Checkpoint is opt-in, reuses &lt;tt&gt;iteration_count&lt;/tt&gt; as the checkpoint ID',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md168',1,'']]],
  ['in_20safeapirbc2oo2_25',['2.4 Migration scope in safeAPIRBC2oo2',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html#autotoc_md201',1,'']]],
  ['in_20your_20application_26',['4. Use in Your Application',['../md_docs_2CROSS__COMPILATION.html#autotoc_md440',1,'']]],
  ['in_20your_20qnx_20application_27',['5. Use in Your QNX Application',['../md_docs_2CROSS__COMPILATION.html#autotoc_md449',1,'']]],
  ['in_5fuse_28',['in_use',['../structsapi__watchdog__s.html#a00a99f33928204f56a499f1a1dfe420b',1,'sapi_watchdog_s']]],
  ['include_20header_29',['include header',['../types_user_guide.html#types_user_guide_qs_include',1,'1. Include Header'],['../memory_user_guide.html#memory_user_guide_qs_include',1,'1. Include Header'],['../watchdog_user_guide.html#watchdog_user_guide_qs_include',1,'1. Include Header']]],
  ['include_20trees_30',['2.1 Two top-level include trees',['../md_docs_2architecture_2ADR-021-consumer-backend-header-split.html#autotoc_md190',1,'']]],
  ['including_20widening_31',['2.1 Scope: every ordered pair, including widening',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md34',1,'']]],
  ['incomplete_20sweep_32',['C. REQ-RBC-029A - promotion during an incomplete sweep',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md284',1,'']]],
  ['independently_20retrying_20endpoints_33',['2.5 Known open issue: reconnect livelock between two independently-retrying endpoints',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md254',1,'']]],
  ['index_34',['Diagram Index',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md370',1,'']]],
  ['indication_20a_20c_20side_20pub_20sub_20broker_20an_20a_20b↔c_20util_20channel_35',['ADR-038: Status indication - a C-side pub/sub broker + an A/B↔C util channel',['../md_docs_2architecture_2ADR-038-status-indication-and-c-pubsub-broker.html',1,'']]],
  ['indirection_36',['3.5 Backend indirection',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md17',1,'']]],
  ['init_37',['init',['../structsapi__appmanager__operations__t.html#a1f03aa6489eaf45e7ef8c29044af48b1',1,'sapi_appmanager_operations_t::init'],['../structsapi__log__backend__t.html#a66b725b77e2efc07a0f09b3e9ed052f2',1,'sapi_log_backend_t::init']]],
  ['init_20register_20dispatch_20are_20hand_20written_20per_20call_20site_20not_20generated_38',['2.2 Init/register/dispatch are hand-written per call site, not generated',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html#autotoc_md290',1,'']]],
  ['initialization_39',['initialization',['../memory_user_guide.html#memory_user_guide_qs_allocate',1,'2. Allocate at Compile-Time or Initialization'],['../checksum_architecture.html#checksum_architecture_init',1,'Initialization']]],
  ['initialize_40',['Initialize',['../buffer_user_guide.html#buffer_user_guide_op_init',1,'']]],
  ['initialized_41',['initialized',['../structsapi__checksum__manager__t.html#afa22104aa013495742494d340f35f4c1',1,'sapi_checksum_manager_t::initialized'],['../structsapi__channel__storage__t.html#a6da6b1f0ddfac18fba69749a1eb1f35d',1,'sapi_channel_storage_t::initialized']]],
  ['input_42',['2.2 Never call &lt;tt&gt;strlen()&lt;/tt&gt; on unbounded/untrusted input',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md68',1,'']]],
  ['inside_20each_20service_20s_20fixed_20opaque_20storage_43',['2.2 Fitting inside each service&apos;s fixed opaque storage',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md159',1,'']]],
  ['install_20plantuml_44',['1. Install PlantUML',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md386',1,'']]],
  ['install_20to_20system_45',['3. Install to System',['../md_docs_2CROSS__COMPILATION.html#autotoc_md439',1,'']]],
  ['instead_20of_20macros_20or_20c11_20tt_20_5fgeneric_20tt_46',['2.5 Why named functions instead of macros or C11 &lt;tt&gt;_Generic&lt;/tt&gt;',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md38',1,'']]],
  ['instructions_47',['Detailed Build Instructions',['../md_docs_2CROSS__COMPILATION.html#autotoc_md435',1,'']]],
  ['integer_20casting_48',['integer casting',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html',1,'ADR-003: Checked Integer Casting'],['../group__CAST.html',1,'Checked Integer Casting']]],
  ['integer_20casting_20—_20tt_20sapi_5fcast_20h_20tt_20adr_20003_49',['1.4 Checked integer casting — &lt;tt&gt;sapi_cast.h&lt;/tt&gt; (ADR-003)',['../safeapi_srs.html#autotoc_md473',1,'']]],
  ['integration_50',['integration',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md161',1,'2.4 Build integration'],['../vital_channel_architecture.html#vital_channel_architecture_integration',1,'Application Integration'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md414',1,'CI/CD Integration']]],
  ['integration_20architecture_51',['Integration Architecture',['../appmanager_integration.html#appmanager_integration_architecture',1,'']]],
  ['integration_20points_52',['Integration Points',['../safestate_architecture.html#safestate_architecture_integration',1,'']]],
  ['integration_20tests_53',['Integration Tests',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md134',1,'']]],
  ['integration_20v0_204_200_54',['Phase 2: Integration (v0.4.0)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md121',1,'']]],
  ['integration_20with_20channels_55',['App Manager Integration with Channels',['../appmanager_integration.html',1,'']]],
  ['integration_20with_20safe_20state_56',['integration with safe state',['../watchdog_architecture.html#watchdog_architecture_integration',1,'Integration with Safe-State'],['../status_architecture.html#status_architecture_safestate',1,'Integration with Safe-State'],['../reboot_user_guide.html#reboot_user_guide_integration',1,'Integration with Safe-State']]],
  ['integration_20with_20vital_20channel_57',['Integration with Vital Channel',['../ipc_transport_selection.html#ipc_transport_selection_vital_channel_integration',1,'']]],
  ['integration_5fguide_58',['INTEGRATION_GUIDE',['../md_include_2safeapi_2app_2appmanager_2INTEGRATION__GUIDE.html',1,'']]],
  ['integrity_20—_20tt_20sapi_5fchecksum_20h_20tt_59',['3g. Checksum / CRC-64 data integrity — &lt;tt&gt;sapi_checksum.h&lt;/tt&gt;',['../safeapi_srs.html#autotoc_md505',1,'']]],
  ['integrity_20for_20redundant_20channels_60',['ADR-016: CRC-64 Data Integrity for Redundant Channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'']]],
  ['integrity_20level_3a_20sil_203_204_61',['3.2 Target integrity level: SIL 3/4',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md14',1,'']]],
  ['integrity_20metadata_20on_20the_20generic_20buffer_62',['2.2 No integrity metadata on the generic buffer',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md27',1,'']]],
  ['inter_20process_20communication_63',['Inter-Process Communication',['../group__IPC.html',1,'']]],
  ['inter_20process_20communication_20backend_20adaptation_64',['Inter-Process Communication - Backend Adaptation',['../group__IPC__BACKEND.html',1,'']]],
  ['inter_20process_20communication_20guide_65',['IPC (Inter-Process Communication) Guide',['../ipc_guide.html',1,'']]],
  ['inter_20process_20communication_20ipc_20transport_20layer_66',['Inter-Process Communication (IPC) Transport Layer',['../ipc_transport_selection.html#ipc_transport_selection_overview',1,'']]],
  ['inter_20process_20inter_20task_20communication_20—_20tt_20sapi_5fipc_20h_20tt_20adr_20001_20§4_67',['2.5 Inter-process/inter-task communication — &lt;tt&gt;sapi_ipc.h&lt;/tt&gt; (ADR-001 §4)',['../safeapi_srs.html#autotoc_md483',1,'']]],
  ['inter_20service_20communication_68',['5. Future: inter-service communication',['../md_docs_2architecture_2ADR-037-role-c-gateway-decomposition.html#autotoc_md351',1,'']]],
  ['inter_20site_20state_20transfer_3a_20active_20only_20chunked_20adr_20029_20§2_204_20amended_69',['4. Inter-site state transfer: active-only + chunked (ADR-029 §2.4 amended)',['../md_docs_2architecture_2ADR-036-train-session-multiplexing.html#autotoc_md337',1,'']]],
  ['inter_20task_20communication_20—_20tt_20sapi_5fipc_20h_20tt_20adr_20001_20§4_70',['2.5 Inter-process/inter-task communication — &lt;tt&gt;sapi_ipc.h&lt;/tt&gt; (ADR-001 §4)',['../safeapi_srs.html#autotoc_md483',1,'']]],
  ['interface_71',['interface',['../reboot_architecture.html#reboot_architecture_backend',1,'Backend Interface'],['../nvm_architecture.html#nvm_architecture_api',1,'Read/Write Interface']]],
  ['interface_20style_3a_20pure_20c_20abi_72',['3.1 Interface style: pure C ABI',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md13',1,'']]],
  ['internally_73',['2.2 One handle, one type enum, one config, netlink opened internally',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html#autotoc_md199',1,'']]],
  ['into_204_74',['ADR-023: Consolidate 22 CMake Library Targets into 4',['../md_docs_2architecture_2ADR-023-consolidate-cmake-libraries.html',1,'']]],
  ['into_20per_20client_20type_20service_20binaries_75',['ADR-037: Role C gateway - decomposition into per-client-type service binaries',['../md_docs_2architecture_2ADR-037-role-c-gateway-decomposition.html',1,'']]],
  ['into_20tt_20sapi_5fchannel_20tt_20tt_20sapi_5fvoter_20tt_20tt_20sapi_5fcross_5fcomparator_20tt_76',['ADR-025: Split &lt;tt&gt;sapi_vital_channel&lt;/tt&gt; into &lt;tt&gt;sapi_channel&lt;/tt&gt; + &lt;tt&gt;sapi_voter&lt;/tt&gt; + &lt;tt&gt;sapi_cross_comparator&lt;/tt&gt;',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html',1,'']]],
  ['invariants_77',['Invariants',['../buffer_architecture.html#buffer_architecture_invariants',1,'']]],
  ['invocation_78',['invocation',['../index.html#autotoc_md5',1,'Manual CMake invocation'],['../safestate_architecture.html#safestate_architecture_test_handler',1,'Test 1: Handler Registration and Invocation']]],
  ['ip_20transport_79',['TCP/IP Transport',['../ipc_transport_selection.html#ipc_transport_selection_tcp_ip',1,'']]],
  ['ipc_80',['2. Sequence Diagram (Behavioral - IPC)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md393',1,'']]],
  ['ipc_20architecture_20layers_81',['IPC Architecture Layers',['../ipc_guide.html#ipc_guide_layers',1,'']]],
  ['ipc_20inter_20process_20communication_20guide_82',['IPC (Inter-Process Communication) Guide',['../ipc_guide.html',1,'']]],
  ['ipc_20netlink_20from_20app_20code_83',['ADR-022: Unified &lt;tt&gt;sapi_safechannel&lt;/tt&gt; Factory (Hiding IPC/Netlink from App Code)',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html',1,'']]],
  ['ipc_20transport_20layer_84',['Inter-Process Communication (IPC) Transport Layer',['../ipc_transport_selection.html#ipc_transport_selection_overview',1,'']]],
  ['ipc_20transport_20selection_20guide_85',['IPC Transport Selection Guide',['../ipc_transport_selection.html',1,'']]],
  ['ipc_5fguide_86',['IPC_GUIDE',['../md_include_2safeapi_2oal_2ipc_2IPC__GUIDE.html',1,'']]],
  ['ipc_5ftransport_5fselection_87',['IPC_TRANSPORT_SELECTION',['../md_include_2safeapi_2oal_2ipc_2IPC__TRANSPORT__SELECTION.html',1,'']]],
  ['is_20a_20buffer_88',['What is a Buffer?',['../buffer_user_guide.html#buffer_user_guide_overview',1,'']]],
  ['is_20a_20compile_20time_20ceiling_20not_20the_20live_20count_89',['1. &lt;tt&gt;SAFEAPI_EXAMPLE_MAX_TRAINS&lt;/tt&gt; is a compile-time ceiling, not the live count',['../md_docs_2architecture_2ADR-036-train-session-multiplexing.html#autotoc_md334',1,'']]],
  ['is_20a_20pure_20pipe_90',['2. One multiplexed link per relay kind - and &lt;tt&gt;C&lt;/tt&gt; is a pure pipe',['../md_docs_2architecture_2ADR-036-train-session-multiplexing.html#autotoc_md335',1,'']]],
  ['is_20a_20pure_20relay_20no_20session_20state_20of_20its_20own_91',['2.2 C is a pure relay - no session state of its own',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md273',1,'']]],
  ['is_20a_20timer_92',['What is a Timer?',['../timer_user_guide.html#timer_user_guide_overview',1,'']]],
  ['is_20always_20active_93',['2.5 &lt;tt&gt;SAPI_ASSERT&lt;/tt&gt; is always active',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md49',1,'']]],
  ['is_20checksum_94',['What is Checksum?',['../checksum_user_guide.html#checksum_user_guide_overview',1,'']]],
  ['is_20documented_20not_20implied_95',['2.3 CCF analysis is documented, not implied',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md87',1,'']]],
  ['is_20dropped_20not_20renamed_96',['2.1 The &lt;tt&gt;common&lt;/tt&gt;/&lt;tt&gt;os&lt;/tt&gt; grouping folder is dropped, not renamed',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md77',1,'']]],
  ['is_20logging_97',['What is Logging?',['../log_user_guide.html#log_user_guide_overview',1,'']]],
  ['is_20nvm_98',['What is NVM?',['../nvm_user_guide.html#nvm_user_guide_overview',1,'']]],
  ['is_20opt_20in_20reuses_20tt_20iteration_5fcount_20tt_20as_20the_20checkpoint_20id_99',['2.2 Checkpoint is opt-in, reuses &lt;tt&gt;iteration_count&lt;/tt&gt; as the checkpoint ID',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md168',1,'']]],
  ['is_20paused_100',['2.4 The real bug: the cyclic executive starves whenever checkpoint is paused',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md264',1,'']]],
  ['is_20reboot_101',['What is Reboot?',['../reboot_user_guide.html#reboot_user_guide_overview',1,'']]],
  ['is_20reentrant_20unlike_20tt_20strtok_20tt_102',['2.4 Splitting is reentrant, unlike &lt;tt&gt;strtok&lt;/tt&gt;',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md70',1,'']]],
  ['is_20right_20for_20sapi_103',['Why CRC-64 is Right for SAPI',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md95',1,'']]],
  ['is_20runtime_104',['A. §2.3 session table - fixed size stays, live count is runtime',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md282',1,'']]],
  ['is_20safe_20state_105',['What is Safe-State?',['../safestate_user_guide.html#safestate_user_guide_overview',1,'']]],
  ['is_20task_20queue_106',['What is Task Queue?',['../task_user_guide.html#task_user_guide_overview',1,'']]],
  ['is_20the_20cast_20module_107',['What is the Cast Module?',['../cast_user_guide.html#cast_user_guide_overview',1,'']]],
  ['is_20the_20liveness_20signal_108',['2. Always send, wait for a bounded ACK - that IS the liveness signal',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md182',1,'']]],
  ['is_20the_20memory_20module_109',['What is the Memory Module?',['../memory_user_guide.html#memory_user_guide_overview',1,'']]],
  ['is_20the_20status_20module_110',['What is the Status Module?',['../status_user_guide.html#status_user_guide_overview',1,'']]],
  ['is_20the_20string_20module_111',['What is the String Module?',['../string_user_guide.html#string_user_guide_overview',1,'']]],
  ['is_20the_20watchdog_112',['What is the Watchdog?',['../watchdog_user_guide.html#watchdog_user_guide_overview',1,'']]],
  ['is_20types_113',['What is Types?',['../types_user_guide.html#types_user_guide_overview',1,'']]],
  ['is_20vital_20channel_114',['What is Vital Channel?',['../vital_channel_user_guide.html#vital_channel_user_guide_overview',1,'']]],
  ['is_5fhealthy_115',['is_healthy',['../structsapi__channel__health__t.html#abbbf09a839adc9fe99359c1f25f8f343',1,'sapi_channel_health_t']]],
  ['is_5fvalid_5faction_116',['is_valid_action',['../sapi__watchdog_8c.html#ae80e4fca3c6bbb43bf990420aa97df19',1,'sapi_watchdog.c']]],
  ['is_5fvalid_5fhandle_117',['is_valid_handle',['../sapi__watchdog_8c.html#a276607429a1cd38238764fc6cd8cef70',1,'sapi_watchdog.c']]],
  ['isn_20t_20a_20virtual_20dispatch_20c_20redesign_118',['2.4 Why this isn&apos;t a virtual-dispatch / C++ redesign',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md60',1,'']]],
  ['issue_3a_20reconnect_20livelock_20between_20two_20independently_20retrying_20endpoints_119',['2.5 Known open issue: reconnect livelock between two independently-retrying endpoints',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md254',1,'']]],
  ['it_120',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['it_20deliberately_20doesn_20t_121',['2.3 What &quot;real&quot; means here, and what it deliberately doesn&apos;t',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md160',1,'']]],
  ['it_20s_20correct_20without_20triggering_20tt_20wsign_20conversion_20tt_122',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]],
  ['item_3a_20manual_20online_20confirmation_20on_20simultaneous_20dual_20reboot_123',['2.5 Known open item: manual ONLINE confirmation on simultaneous dual-reboot',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md265',1,'']]],
  ['items_124',['7. Open items',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md22',1,'']]],
  ['iteration_5fcount_125',['iteration_count',['../structsapi__appmanager__state__t.html#a86a7eec86ed0c4ec3931073735e496d3',1,'sapi_appmanager_state_t']]],
  ['iteration_5fcount_20tt_20as_20the_20checkpoint_20id_126',['2.2 Checkpoint is opt-in, reuses &lt;tt&gt;iteration_count&lt;/tt&gt; as the checkpoint ID',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md168',1,'']]],
  ['its_20limit_127',['6. FRMCS analogy - and its limit',['../md_docs_2architecture_2ADR-036-train-session-multiplexing.html#autotoc_md339',1,'']]],
  ['its_20own_128',['2.2 C is a pure relay - no session state of its own',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md273',1,'']]],
  ['its_20own_20and_20the_20peer_20s_20state_129',['3. The negotiator keeps both its own and the peer&apos;s state',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md183',1,'']]],
  ['its_20own_20hysteresis_130',['2.3 Negotiation watchdog timeout was shorter than its own hysteresis',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md263',1,'']]]
];
