var searchData=
[
  ['facilities_0',['1. Common facilities',['../safeapi_srs.html#autotoc_md425',1,'']]],
  ['factory_1',['Unified Channel Factory',['../group__SAFECHANNEL.html',1,'']]],
  ['factory_20—_20tt_20sapi_5fsafechannel_20h_20tt_20adr_20022_2',['3f. Unified channel factory — &lt;tt&gt;sapi_safechannel.h&lt;/tt&gt; (ADR-022)',['../safeapi_srs.html#autotoc_md460',1,'']]],
  ['factory_20hiding_20ipc_20netlink_20from_20app_20code_3',['ADR-022: Unified &lt;tt&gt;sapi_safechannel&lt;/tt&gt; Factory (Hiding IPC/Netlink from App Code)',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html',1,'']]],
  ['fail_20on_20cross_20compiled_20targets_4',['Tests fail on cross-compiled targets',['../md_docs_2CROSS__COMPILATION.html#autotoc_md418',1,'']]],
  ['fail_20safe_20by_20default_5',['Pattern 2: Fail-Safe-by-Default',['../safestate_user_guide.html#safestate_user_guide_pattern_failsafe',1,'']]],
  ['fail_20safe_20default_6',['Pattern 1: Conditional Kick (Fail-Safe Default)',['../watchdog_user_guide.html#watchdog_user_guide_pattern_conditional',1,'']]],
  ['failover_20continuity_20the_20actual_20point_20of_20this_20adr_7',['2.4 Cross-site failover continuity - the actual point of this ADR',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md275',1,'']]],
  ['failover_20ready_20session_20state_8',['ADR-029: RBC Train/IL/CTC Scenario - Real Multi-Train Protocol and Failover-Ready Session State',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html',1,'']]],
  ['failure_9',['Example 1: Redundant Channel Voting Failure',['../safestate_user_guide.html#safestate_user_guide_example_voting',1,'']]],
  ['failure_20mitigation_10',['Common-Cause-Failure Mitigation',['../system_architecture.html#system_architecture_ccf',1,'']]],
  ['failure_20not_20silent_20auto_20enable_11',['2.2 Enforcement: explicit failure, not silent auto-enable',['../md_docs_2architecture_2ADR-024-configurable-feature-build.html#autotoc_md217',1,'']]],
  ['failure_20semantics_12',['2.2 Signature and failure semantics',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md35',1,'']]],
  ['fallback_13',['Example 3: Reboot with Fallback',['../reboot_user_guide.html#reboot_user_guide_example_fallback',1,'']]],
  ['fault_14',['2-out-of-3 Voting (Tolerate 1 Fault)',['../vital_channel_architecture.html#vital_channel_architecture_example_2oo3',1,'']]],
  ['fault_20detection_15',['Example 3: Assertion-Based Fault Detection',['../safestate_user_guide.html#safestate_user_guide_example_assertion',1,'']]],
  ['fault_20handling_20callback_16',['Fault Handling Callback',['../vital_channel_user_guide.html#vital_channel_user_guide_pattern_fault',1,'']]],
  ['fault_20tolerance_17',['Pattern 1: Fault Tolerance',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md379',1,'']]],
  ['feature_18',['2.2 One CMake target per feature',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md78',1,'']]],
  ['feature_20directory_20layout_19',['ADR-007: Per-Feature Directory Layout',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html',1,'']]],
  ['feature_20selection_20at_20configure_20time_20',['ADR-024: Per-Module Feature Selection at Configure Time',['../md_docs_2architecture_2ADR-024-configurable-feature-build.html',1,'']]],
  ['feature_3a_20tt_20sapi_5fchannel_20tt_20comparator_20identity_21',['2.2 New feature: &lt;tt&gt;sapi_channel&lt;/tt&gt; (comparator + identity)',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md86',1,'']]],
  ['fifo_20named_20pipes_20transport_22',['FIFO (Named Pipes) Transport',['../ipc_transport_selection.html#ipc_transport_selection_fifo',1,'']]],
  ['file_20per_20service_20one_20aggregator_23',['2.1 One module, one file per service, one aggregator',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md158',1,'']]],
  ['file_20same_20accessor_20req_20oal_20netlink_20014_24',['2.1 New UDP backend, same file, same accessor (REQ-OAL-NETLINK-014)',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md250',1,'']]],
  ['files_25',['files',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md360',1,'In Header Files'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md361',1,'In Markdown Files'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md411',1,'Toolchain Files']]],
  ['fired_26',['fired',['../structsapi__watchdog__s.html#aa5d4491f1e230c4c6b5b3f17b0e4f66a',1,'sapi_watchdog_s']]],
  ['fires_27',['fires',['../structsapi__watchdog__status__t.html#ab7fb0ebc0718e4b056894043caea91a8',1,'sapi_watchdog_status_t::fires'],['../structsapi__watchdog__s.html#ab3ff6deb6b155bf12e86114b72a9fd65',1,'sapi_watchdog_s::fires']]],
  ['first_20abstraction_20layer_20oal_20services_28',['4. Scope of the first abstraction layer (OAL services)',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md19',1,'']]],
  ['fit_29',['Architectural Fit',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md107',1,'']]],
  ['fitting_20inside_20each_20service_20s_20fixed_20opaque_20storage_30',['2.2 Fitting inside each service&apos;s fixed opaque storage',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md159',1,'']]],
  ['fix_31',['ADR-028: Channel-Down Escalation to REBOOT, and a Cyclic-Executive Starvation Fix',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html',1,'']]],
  ['fix_20adr_20022_20site_20s_20live_20tt_20sapi_5fsafechannel_20tt_20migration_32',['Post-acceptance fix (ADR-022, SITE&apos;s live &lt;tt&gt;sapi_safechannel&lt;/tt&gt; migration)',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md186',1,'']]],
  ['fixed_33',['2.2 &lt;tt&gt;sapi_voter&lt;/tt&gt; (new) - N-way voting, with the majority-vote bug fixed',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md227',1,'']]],
  ['fixed_20capacity_20registered_20callback_20list_20shape_34',['ADR-030: &lt;tt&gt;sapi_notify&lt;/tt&gt; - fixed-capacity registered-callback list shape',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html',1,'']]],
  ['fixed_20opaque_20storage_35',['2.2 Fitting inside each service&apos;s fixed opaque storage',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md159',1,'']]],
  ['fixed_20size_20envelope_36',['2.1 Wire protocol - one shared, fixed-size envelope',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md272',1,'']]],
  ['fixed_20size_20message_20buffer_37',['Example 1: Fixed-Size Message Buffer',['../buffer_user_guide.html#buffer_user_guide_example_message',1,'']]],
  ['fixed_20size_20queues_38',['Pattern 2: Fixed-Size Queues',['../memory_user_guide.html#memory_user_guide_common_queue',1,'']]],
  ['fixed_20width_20types_39',['2. Use Fixed-Width Types',['../types_user_guide.html#types_user_guide_qs_use',1,'']]],
  ['fixes_40',['2.3 A UDP handshake has real, non-zero startup latency - two related fixes',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md252',1,'']]],
  ['flash_20wear_41',['Flash Wear',['../nvm_architecture.html#nvm_architecture_wear',1,'']]],
  ['floor_42',['5.1 &lt;tt&gt;sapi_channel_init()&lt;/tt&gt;&apos;s &lt;tt&gt;channel_count &gt;= 2&lt;/tt&gt; floor',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md173',1,'']]],
  ['flow_43',['flow',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html#autotoc_md284',1,'2.1 Storage-shape macro only, no generated control flow'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md357',1,'6. Activity Diagram (Behavioral - Checkpoint Flow)'],['../reboot_architecture.html#reboot_architecture_flow',1,'Reboot Flow'],['../safestate_architecture.html#safestate_architecture_flow',1,'Transition Flow']]],
  ['flow_202oo2_20example_44',['Communication Flow (2oo2 Example)',['../vital_channel_architecture.html#vital_channel_architecture_communication_flow',1,'']]],
  ['folder_20is_20dropped_20not_20renamed_45',['2.1 The &lt;tt&gt;common&lt;/tt&gt;/&lt;tt&gt;os&lt;/tt&gt; grouping folder is dropped, not renamed',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md77',1,'']]],
  ['for_20a_20bounded_20ack_20that_20is_20the_20liveness_20signal_46',['2. Always send, wait for a bounded ACK - that IS the liveness signal',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md182',1,'']]],
  ['for_20checked_20assertions_47',['2. Use SAPI_ASSERT for Checked Assertions',['../safestate_user_guide.html#safestate_user_guide_qs_assert',1,'']]],
  ['for_20distributed_20vital_20channels_48',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['for_20online_20standby_20setup_49',['Typical Workflow for Online/Standby Setup',['../ipc_guide.html#ipc_guide_workflow',1,'']]],
  ['for_20qnx_50',['3. Build for QNX',['../md_docs_2CROSS__COMPILATION.html#autotoc_md403',1,'']]],
  ['for_20real_20time_20bring_20up_51',['ADR-035: &lt;tt&gt;sapi_platform&lt;/tt&gt; OAL service for real-time bring-up',['../md_docs_2architecture_2ADR-035-platform-realtime-init.html',1,'']]],
  ['for_20redundant_20channels_52',['ADR-016: CRC-64 Data Integrity for Redundant Channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'']]],
  ['for_20safety_20critical_20systems_53',['Common Diagram Patterns for Safety-Critical Systems',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md378',1,'']]],
  ['for_20sapi_54',['Why CRC-64 is Right for SAPI',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md95',1,'']]],
  ['for_20the_20safe_20api_20framework_55',['ADR-001: OS Abstraction Layer (OAL) for the Safe API Framework',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html',1,'']]],
  ['for_20this_20adr_56',['4. Non-goals for this ADR',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md184',1,'']]],
  ['for_20tt_20sapi_5fipc_20tt_20tt_20sapi_5fnetlink_20tt_20s_20status_57',['2.3 Consequence for &lt;tt&gt;sapi_ipc&lt;/tt&gt;/&lt;tt&gt;sapi_netlink&lt;/tt&gt;&apos;s status',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html#autotoc_md200',1,'']]],
  ['for_20tt_20sapi_5fnetlink_20tt_58',['ADR-027: UDP Transport for &lt;tt&gt;sapi_netlink&lt;/tt&gt;',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html',1,'']]],
  ['for_20vital_20communication_59',['Creating Channels for Vital Communication',['../channel_configuration.html#channel_configuration_channel_creation',1,'']]],
  ['format_60',['Entry Format',['../log_architecture.html#log_architecture_format',1,'']]],
  ['found_20qcc_20not_20found_61',['&quot;CMake not found&quot; / &quot;qcc not found&quot;',['../md_docs_2CROSS__COMPILATION.html#autotoc_md416',1,'']]],
  ['foundation_62',['C11 stdint.h Foundation',['../types_architecture.html#types_architecture_overview',1,'']]],
  ['framework_63',['framework',['../md_docs_2architecture_2ADR-035-platform-realtime-init.html#autotoc_md321',1,'1. New OAL service &lt;tt&gt;sapi_platform&lt;/tt&gt; (framework)'],['../md_docs_2architecture_2ADR-035-platform-realtime-init.html#autotoc_md323',1,'3. GP calls the framework'],['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html',1,'ADR-001: OS Abstraction Layer (OAL) for the Safe API Framework'],['../index.html',1,'Safe API Framework'],['../status_architecture.html#status_architecture_usage_patterns',1,'Usage Patterns in Framework']]],
  ['framework_20—_20software_20requirements_20specification_20srs_64',['Safe API Framework — Software Requirements Specification (SRS)',['../safeapi_srs.html#autotoc_md424',1,'']]],
  ['framework_20change_65',['5.3 Safety-policy reconciliation, not a framework change',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html#autotoc_md175',1,'']]],
  ['framework_20future_20v0_204_200_66',['With Redundancy Framework (Future v0.4.0+)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md108',1,'']]],
  ['framework_20reasons_200_204095_67',['Framework Reasons (0-4095)',['../safestate_architecture.html#safestate_architecture_reason_framework',1,'']]],
  ['framework_20still_20validates_20the_20backend_20only_20executes_68',['2.2 The framework still validates; the backend only executes',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md58',1,'']]],
  ['from_20app_20code_69',['ADR-022: Unified &lt;tt&gt;sapi_safechannel&lt;/tt&gt; Factory (Hiding IPC/Netlink from App Code)',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html',1,'']]],
  ['from_20earlier_20adrs_20despite_20the_20directory_20change_70',['2.3 What stays true from earlier ADRs despite the directory change',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md79',1,'']]],
  ['from_20tt_20sapi_5fvital_5fchannel_20tt_20single_20link_71',['2.1 &lt;tt&gt;sapi_channel&lt;/tt&gt; (renamed from &lt;tt&gt;sapi_vital_channel&lt;/tt&gt;, single link)',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md226',1,'']]],
  ['full_20stack_20docker_20hardening_3a_20a_20permanent_20safe_20halt_20and_20an_20undersized_20queue_72',['2.6 Full-stack Docker hardening: a permanent safe-halt and an undersized queue',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md277',1,'']]],
  ['function_73',['3. Project-wide requirements (CLAUDE.md, not yet tagged per-function)',['../safeapi_srs.html#autotoc_md444',1,'']]],
  ['function_20per_20service_74',['2.1 One backend vtable type and one registration function per service',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md57',1,'']]],
  ['functional_20change_20required_20validates_20adr_20020_75',['2.2 Negotiation link: no functional change required (validates ADR-020)',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md251',1,'']]],
  ['functions_76',['functions',['../cast_architecture.html#cast_architecture_functions',1,'Conversion Functions'],['../string_architecture.html#string_architecture_functions',1,'Core Functions'],['../checksum_user_guide.html#checksum_user_guide_functions',1,'Functions']]],
  ['functions_20instead_20of_20macros_20or_20c11_20tt_20_5fgeneric_20tt_77',['2.5 Why named functions instead of macros or C11 &lt;tt&gt;_Generic&lt;/tt&gt;',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md38',1,'']]],
  ['future_78',['Phase 3: Advanced (Future)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md122',1,'']]],
  ['future_20extensions_79',['Future Extensions',['../status_architecture.html#status_architecture_future',1,'']]],
  ['future_20v0_204_200_80',['With Redundancy Framework (Future v0.4.0+)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md108',1,'']]]
];
