var searchData=
[
  ['n_20modular_0',['NMR (N-Modular)',['../vital_channel_user_guide.html#vital_channel_user_guide_ss_nmr',1,'']]],
  ['n_20out_20of_20m_20voting_1',['N-out-of-M Voting',['../vital_channel_architecture.html#vital_channel_architecture_example_nmr',1,'']]],
  ['n_20per_20buffer_2',['O(n) Per Buffer',['../checksum_architecture.html#checksum_architecture_performance',1,'']]],
  ['name_3',['name',['../structsapi__ipc__rr__server__config__t.html#afe7ce817b82fe66a710bce9e39e40ab2',1,'sapi_ipc_rr_server_config_t::name'],['../structsapi__ipc__config__t.html#ad494b631712c4acb17d013455e1b3534',1,'sapi_ipc_config_t::name'],['../structsapi__task__config__t.html#ade34ea5e339aca7b00cbdee4ac5101c7',1,'sapi_task_config_t::name'],['../structsapi__watchdog__config__t.html#ace4926de9ceba31c6cda2ef518630322',1,'sapi_watchdog_config_t::name']]],
  ['named_20functions_20instead_20of_20macros_20or_20c11_20tt_20_5fgeneric_20tt_4',['2.5 Why named functions instead of macros or C11 &lt;tt&gt;_Generic&lt;/tt&gt;',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md38',1,'']]],
  ['named_20pipes_20transport_5',['FIFO (Named Pipes) Transport',['../ipc_transport_selection.html#ipc_transport_selection_fifo',1,'']]],
  ['naming_20conventions_6',['3.3 Naming conventions',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md15',1,'']]],
  ['native_20linux_20build_7',['1. Native Linux Build',['../md_docs_2CROSS__COMPILATION.html#autotoc_md232',1,'']]],
  ['native_20or_20cross_20compile_8',['Linux (Native or Cross-compile)',['../md_docs_2CROSS__COMPILATION.html#autotoc_md227',1,'']]],
  ['need_20guarantees_9',['Safety-Critical Systems Need Guarantees',['../memory_user_guide.html#memory_user_guide_rationale_comparison',1,'']]],
  ['need_20to_20implement_10',['What You Need to Implement',['../appmanager_integration.html#appmanager_integration_you_implement',1,'']]],
  ['network_11',['Pattern 2: Distributed 2oo2 (A ↔ B Across Network)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_distributed_2oo2',1,'']]],
  ['network_20link_12',['Point-to-Point Network Link',['../group__NETLINK.html',1,'']]],
  ['never_20call_20tt_20strlen_20tt_20on_20unbounded_20untrusted_20input_13',['2.2 Never call &lt;tt&gt;strlen()&lt;/tt&gt; on unbounded/untrusted input',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md68',1,'']]],
  ['never_20the_20basis_20of_20correctness_14',['2.3 &lt;tt&gt;sapi_clocksync&lt;/tt&gt;: diagnostic only, never the basis of correctness',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md152',1,'']]],
  ['new_20feature_3a_20tt_20sapi_5fchannel_20tt_20comparator_20identity_15',['2.2 New feature: &lt;tt&gt;sapi_channel&lt;/tt&gt; (comparator + identity)',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md86',1,'']]],
  ['new_20oal_20service_3a_20tt_20sapi_5freboot_20tt_16',['3. New OAL service: &lt;tt&gt;sapi_reboot&lt;/tt&gt;',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md51',1,'']]],
  ['new_20status_20code_17',['2.4 New status code',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md37',1,'']]],
  ['new_20targets_18',['Adding New Targets',['../md_docs_2CROSS__COMPILATION.html#autotoc_md258',1,'']]],
  ['new_20transport_20backend_19',['2.2 &lt;tt&gt;sapi_checkpoint&lt;/tt&gt;: bounded rendezvous, no new transport backend',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md151',1,'']]],
  ['next_20',['Where to Go Next',['../system_architecture.html#system_architecture_docs',1,'']]],
  ['next_20steps_21',['next steps',['../appmanager_integration.html#appmanager_integration_next_steps',1,'Next Steps'],['../ipc_guide.html#ipc_guide_next_steps',1,'Next Steps']]],
  ['nmr_20n_20modular_22',['NMR (N-Modular)',['../vital_channel_user_guide.html#vital_channel_user_guide_ss_nmr',1,'']]],
  ['no_20checksum_20status_20quo_23',['1. No Checksum (Status Quo)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md127',1,'']]],
  ['no_20default_24',['2.5 Buffer endianness helpers: explicit per call, no default',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md71',1,'']]],
  ['no_20dynamic_20allocation_25',['no dynamic allocation',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md16',1,'3.4 Handle pattern (no dynamic allocation)'],['../memory_user_guide.html#memory_user_guide_rationale',1,'Why No Dynamic Allocation?']]],
  ['no_20integrity_20metadata_20on_20the_20generic_20buffer_26',['2.2 No integrity metadata on the generic buffer',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md27',1,'']]],
  ['no_20new_20transport_20backend_27',['2.2 &lt;tt&gt;sapi_checkpoint&lt;/tt&gt;: bounded rendezvous, no new transport backend',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md151',1,'']]],
  ['non_20volatile_20memory_28',['Non-Volatile Memory',['../group__NVM.html',1,'']]],
  ['non_20volatile_20memory_20architecture_29',['Non-Volatile Memory Architecture',['../nvm_architecture.html',1,'']]],
  ['non_20volatile_20memory_20user_20guide_30',['Non-Volatile Memory User Guide',['../nvm_user_guide.html',1,'']]],
  ['not_20a_20single_20safe_20state_31',['2.1 Severity levels, not a single safe state',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md45',1,'']]],
  ['not_20call_20tt_20sapi_5freboot_20tt_20directly_32',['2.3 Why &lt;tt&gt;sapi_safestate&lt;/tt&gt; does not call &lt;tt&gt;sapi_reboot&lt;/tt&gt; directly',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md47',1,'']]],
  ['not_20diverse_20hardware_33',['2.1 Primary mitigation: diverse compilation, not diverse hardware',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md85',1,'']]],
  ['not_20found_20qcc_20not_20found_34',['&quot;CMake not found&quot; / &quot;qcc not found&quot;',['../md_docs_2CROSS__COMPILATION.html#autotoc_md253',1,'']]],
  ['not_20hand_20authorship_35',['2.6 Generation, not hand-authorship',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md39',1,'']]],
  ['not_20implied_36',['2.3 CCF analysis is documented, not implied',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md87',1,'']]],
  ['not_20renamed_37',['2.1 The &lt;tt&gt;common&lt;/tt&gt;/&lt;tt&gt;os&lt;/tt&gt; grouping folder is dropped, not renamed',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md77',1,'']]],
  ['not_20return_20enforced_20defensively_38',['2.4 &quot;Does not return&quot;, enforced defensively',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md48',1,'']]],
  ['not_20set_39',['&quot;QNX_HOST and QNX_TARGET not set&quot;',['../md_docs_2CROSS__COMPILATION.html#autotoc_md254',1,'']]],
  ['now_40',['now',['../structsapi__timer__backend__t.html#a9828173ad5986007a30dbba4c019fea8',1,'sapi_timer_backend_t']]],
  ['nvm_41',['What is NVM?',['../nvm_user_guide.html#nvm_user_guide_overview',1,'']]]
];
