var searchData=
[
  ['b_20→_20c_0',['Pattern 1: Single-System 2oo2 (A ↔ B → C)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_single_2oo2',1,'']]],
  ['b_20across_20network_1',['Pattern 2: Distributed 2oo2 (A ↔ B Across Network)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_distributed_2oo2',1,'']]],
  ['backend_2',['backend',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md151',1,'2.2 &lt;tt&gt;sapi_checkpoint&lt;/tt&gt;: bounded rendezvous, no new transport backend'],['../md_docs_2architecture_2ADR-018-posix-oal-backend.html',1,'ADR-018: A Real POSIX/Linux OAL Backend']]],
  ['backend_20at_20startup_3',['1. Register Backend at Startup',['../reboot_user_guide.html#reboot_user_guide_qs_backend',1,'']]],
  ['backend_20implementation_4',['Backend Implementation',['../nvm_architecture.html#nvm_architecture_backend',1,'']]],
  ['backend_20implementation_20pattern_5',['Backend Implementation Pattern',['../ipc_transport_selection.html#ipc_transport_selection_backend_vtable',1,'']]],
  ['backend_20indirection_6',['3.5 Backend indirection',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md17',1,'']]],
  ['backend_20interface_7',['Backend Interface',['../reboot_architecture.html#reboot_architecture_backend',1,'']]],
  ['backend_20only_20executes_8',['2.2 The framework still validates; the backend only executes',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md58',1,'']]],
  ['backend_20registration_20via_20callbacks_9',['ADR-005: OAL Backend Registration via Callbacks',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html',1,'']]],
  ['backend_20vtable_20type_20and_20one_20registration_20function_20per_20service_10',['2.1 One backend vtable type and one registration function per service',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md57',1,'']]],
  ['backend_5frecv_11',['backend_recv',['../structsapi__vital__channel__config__t.html#a8b79755d5fdd6824c5ea2493bf2d5638',1,'sapi_vital_channel_config_t']]],
  ['backend_5fsend_12',['backend_send',['../structsapi__vital__channel__config__t.html#ad48fa2c09091c8407ac8abfdb97342b8',1,'sapi_vital_channel_config_t']]],
  ['backends_13',['Transport Backends',['../vital_channel_architecture.html#vital_channel_architecture_transport_backends',1,'']]],
  ['backing_20storage_14',['1. Allocate Backing Storage',['../buffer_user_guide.html#buffer_user_guide_qs_storage',1,'']]],
  ['based_20allocation_15',['Pattern 1: Pool-Based Allocation',['../memory_user_guide.html#memory_user_guide_common_pool',1,'']]],
  ['based_20buffer_20design_16',['View-Based Buffer Design',['../buffer_architecture.html#buffer_architecture_overview',1,'']]],
  ['based_20fault_20detection_17',['Example 3: Assertion-Based Fault Detection',['../safestate_user_guide.html#safestate_user_guide_example_assertion',1,'']]],
  ['basis_20of_20correctness_18',['2.3 &lt;tt&gt;sapi_clocksync&lt;/tt&gt;: diagnostic only, never the basis of correctness',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md152',1,'']]],
  ['before_20convert_19',['Check-Before-Convert',['../cast_architecture.html#cast_architecture_strategy',1,'']]],
  ['behavior_20',['Test 2: SAPI_ASSERT Behavior',['../safestate_architecture.html#safestate_architecture_test_assert',1,'']]],
  ['behavioral_21',['4. State Machine Diagram (Behavioral)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md192',1,'']]],
  ['behavioral_20checkpoint_20flow_22',['6. Activity Diagram (Behavioral - Checkpoint Flow)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md196',1,'']]],
  ['behavioral_20diagrams_20configuration_20sequences_23',['Behavioral Diagrams - Configuration Sequences',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md167',1,'']]],
  ['behavioral_20ipc_24',['2. Sequence Diagram (Behavioral - IPC)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md188',1,'']]],
  ['behavioral_20redundancy_25',['3. Sequence Diagram (Behavioral - Redundancy)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md190',1,'']]],
  ['best_20practices_26',['best practices',['../safestate_user_guide.html#safestate_user_guide_guidelines',1,'Best Practices'],['../vital_channel_user_guide.html#vital_channel_user_guide_guidelines',1,'Best Practices'],['../reboot_user_guide.html#reboot_user_guide_guidelines',1,'Best Practices'],['../watchdog_user_guide.html#watchdog_user_guide_guidelines',1,'Best Practices'],['../nvm_user_guide.html#nvm_user_guide_guidelines',1,'Best Practices'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md211',1,'Best Practices'],['../memory_user_guide.html#memory_user_guide_guidelines',1,'Best Practices'],['../log_user_guide.html#log_user_guide_guidelines',1,'Best Practices'],['../status_user_guide.html#status_user_guide_guidelines',1,'Best Practices'],['../string_user_guide.html#string_user_guide_guidelines',1,'Best Practices'],['../checksum_user_guide.html#checksum_user_guide_guidelines',1,'Best Practices'],['../cast_user_guide.html#cast_user_guide_guidelines',1,'Best Practices'],['../timer_user_guide.html#timer_user_guide_guidelines',1,'Best Practices'],['../buffer_user_guide.html#buffer_user_guide_guidelines',1,'Best Practices'],['../types_user_guide.html#types_user_guide_guidelines',1,'Best Practices']]],
  ['bind_20buffer_20view_27',['2. Bind Buffer View',['../buffer_user_guide.html#buffer_user_guide_qs_init',1,'']]],
  ['block_5fcount_28',['block_count',['../structsapi__mem__pool__config__t.html#abbf4fbb3bfdfdd6e7646009758917ff6',1,'sapi_mem_pool_config_t']]],
  ['block_5fsize_29',['block_size',['../structsapi__mem__pool__config__t.html#a2109332171b85527842fd7d167e92561',1,'sapi_mem_pool_config_t']]],
  ['bounded_20rendezvous_20no_20new_20transport_20backend_30',['2.2 &lt;tt&gt;sapi_checkpoint&lt;/tt&gt;: bounded rendezvous, no new transport backend',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md151',1,'']]],
  ['bounded_20string_20manipulation_31',['Bounded String Manipulation',['../group__STRING.html',1,'']]],
  ['broadcast_32',['Send Semantics (Atomic Broadcast)',['../vital_channel_architecture.html#vital_channel_architecture_send_semantics',1,'']]],
  ['buf_33',['buf',['../structsapi__string__t.html#a6729d6bc50603d43ef507ef8b253eaa5',1,'sapi_string_t']]],
  ['buffer_34',['buffer',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md27',1,'2.2 No integrity metadata on the generic buffer'],['../buffer_user_guide.html#buffer_user_guide_qs_use',1,'3. Use Buffer'],['../group__BUFFER.html',1,'Cross-Layer Data Buffer'],['../buffer_user_guide.html#buffer_user_guide_example_message',1,'Example 1: Fixed-Size Message Buffer'],['../checksum_architecture.html#checksum_architecture_performance',1,'O(n) Per Buffer'],['../log_architecture.html#log_architecture_storage',1,'Ring Buffer'],['../buffer_user_guide.html#buffer_user_guide_overview',1,'What is a Buffer?']]],
  ['buffer_20abstraction_35',['ADR-002: Cross-Layer Data Buffer Abstraction',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html',1,'']]],
  ['buffer_20access_36',['ADR-006: Safe String Manipulation and Endianness-Safe Buffer Access',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html',1,'']]],
  ['buffer_20design_37',['View-Based Buffer Design',['../buffer_architecture.html#buffer_architecture_overview',1,'']]],
  ['buffer_20endianness_20helpers_3a_20explicit_20per_20call_20no_20default_38',['2.5 Buffer endianness helpers: explicit per call, no default',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md71',1,'']]],
  ['buffer_20module_20architecture_39',['Buffer Module - Architecture',['../buffer_architecture.html',1,'']]],
  ['buffer_20module_20user_20guide_40',['Buffer Module - User Guide',['../buffer_user_guide.html',1,'']]],
  ['buffer_20operations_41',['Buffer Operations',['../buffer_user_guide.html#buffer_user_guide_operations',1,'']]],
  ['buffer_20view_42',['2. Bind Buffer View',['../buffer_user_guide.html#buffer_user_guide_qs_init',1,'']]],
  ['buffer_20without_20malloc_43',['Example 2: Ring Buffer Without malloc',['../memory_user_guide.html#memory_user_guide_example_ringbuf',1,'']]],
  ['buffers_44',['Pattern 1: Static Global Buffers',['../memory_user_guide.html#memory_user_guide_pattern_global',1,'']]],
  ['build_45',['build',['../md_docs_2CROSS__COMPILATION.html#autotoc_md232',1,'1. Native Linux Build'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md233',1,'2. Linux Release Build']]],
  ['build_20diagrams_20locally_46',['Build Diagrams Locally',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md205',1,'']]],
  ['build_20diversity_47',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['build_20for_20qnx_48',['3. Build for QNX',['../md_docs_2CROSS__COMPILATION.html#autotoc_md240',1,'']]],
  ['build_20instructions_49',['Detailed Build Instructions',['../md_docs_2CROSS__COMPILATION.html#autotoc_md230',1,'']]],
  ['build_20integration_50',['2.4 Build integration',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md161',1,'']]],
  ['build_20structure_51',['5. Directory / build structure',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md20',1,'']]],
  ['build_5farrival_5fmessage_52',['build_arrival_message',['../sapi__checkpoint_8c.html#a6eafe59042730a3fc0070b367f6148da',1,'sapi_checkpoint.c']]],
  ['building_53',['Building',['../index.html#autotoc_md2',1,'']]],
  ['building_20diagrams_20locally_54',['Building Diagrams Locally',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md168',1,'']]],
  ['by_20default_55',['Pattern 2: Fail-Safe-by-Default',['../safestate_user_guide.html#safestate_user_guide_pattern_failsafe',1,'']]]
];
