var searchData=
[
  ['o_201_20all_20operations_0',['O(1) All Operations',['../buffer_architecture.html#buffer_architecture_performance',1,'']]],
  ['o_201_20per_20timer_1',['O(1) Per Timer',['../timer_architecture.html#timer_architecture_performance',1,'']]],
  ['o_20n_20per_20buffer_2',['O(n) Per Buffer',['../checksum_architecture.html#checksum_architecture_performance',1,'']]],
  ['oal_3',['Linux (POSIX OAL)',['../md_docs_2CROSS__COMPILATION.html#autotoc_md231',1,'']]],
  ['oal_20backend_4',['ADR-018: A Real POSIX/Linux OAL Backend',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html',1,'']]],
  ['oal_20backend_20registration_20via_20callbacks_5',['ADR-005: OAL Backend Registration via Callbacks',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html',1,'']]],
  ['oal_20for_20the_20safe_20api_20framework_6',['ADR-001: OS Abstraction Layer (OAL) for the Safe API Framework',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html',1,'']]],
  ['oal_20service_3a_20tt_20sapi_5freboot_20tt_7',['3. New OAL service: &lt;tt&gt;sapi_reboot&lt;/tt&gt;',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md51',1,'']]],
  ['oal_20services_8',['4. Scope of the first abstraction layer (OAL services)',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md19',1,'']]],
  ['of_202_20voting_20perfect_20agreement_20required_9',['2-out-of-2 Voting (Perfect Agreement Required)',['../vital_channel_architecture.html#vital_channel_architecture_example_2oo2',1,'']]],
  ['of_203_20voting_20tolerate_201_20fault_10',['2-out-of-3 Voting (Tolerate 1 Fault)',['../vital_channel_architecture.html#vital_channel_architecture_example_2oo3',1,'']]],
  ['of_20correctness_11',['2.3 &lt;tt&gt;sapi_clocksync&lt;/tt&gt;: diagnostic only, never the basis of correctness',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md152',1,'']]],
  ['of_20m_20voting_12',['N-out-of-M Voting',['../vital_channel_architecture.html#vital_channel_architecture_example_nmr',1,'']]],
  ['of_20macros_20or_20c11_20tt_20_5fgeneric_20tt_13',['2.5 Why named functions instead of macros or C11 &lt;tt&gt;_Generic&lt;/tt&gt;',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md38',1,'']]],
  ['of_20memory_14',['Out-of-Memory',['../memory_user_guide.html#memory_user_guide_error_handling',1,'']]],
  ['of_20the_20first_20abstraction_20layer_20oal_20services_15',['4. Scope of the first abstraction layer (OAL services)',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md19',1,'']]],
  ['on_20critical_20error_16',['2. Request Reboot on Critical Error',['../reboot_user_guide.html#reboot_user_guide_qs_request',1,'']]],
  ['on_20cross_20compiled_20targets_17',['Tests fail on cross-compiled targets',['../md_docs_2CROSS__COMPILATION.html#autotoc_md255',1,'']]],
  ['on_20the_20generic_20buffer_18',['2.2 No integrity metadata on the generic buffer',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md27',1,'']]],
  ['on_20timeout_19',['Example 2: Custom Callback on Timeout',['../watchdog_user_guide.html#watchdog_user_guide_example_custom',1,'']]],
  ['on_20unbounded_20untrusted_20input_20',['2.2 Never call &lt;tt&gt;strlen()&lt;/tt&gt; on unbounded/untrusted input',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md68',1,'']]],
  ['on_5fdisagreement_21',['on_disagreement',['../structsapi__vital__channel__config__t.html#a67e810c6f4a73b578fb50debdc2d99ff',1,'sapi_vital_channel_config_t']]],
  ['one_20backend_20vtable_20type_20and_20one_20registration_20function_20per_20service_22',['2.1 One backend vtable type and one registration function per service',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md57',1,'']]],
  ['one_20cmake_20target_20per_20feature_23',['2.2 One CMake target per feature',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md78',1,'']]],
  ['one_20file_20per_20service_20one_20aggregator_24',['2.1 One module, one file per service, one aggregator',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md158',1,'']]],
  ['one_20handler_20per_20level_20application_20registered_25',['2.2 One handler per level, application-registered',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md46',1,'']]],
  ['one_20module_20one_20file_20per_20service_20one_20aggregator_26',['2.1 One module, one file per service, one aggregator',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md158',1,'']]],
  ['one_20registration_20function_20per_20service_27',['2.1 One backend vtable type and one registration function per service',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md57',1,'']]],
  ['one_20shot_20timeout_28',['Example 2: One-Shot Timeout',['../timer_user_guide.html#timer_user_guide_example_oneshot',1,'']]],
  ['online_20standby_20redundancy_20patterns_29',['Online/Standby Redundancy Patterns',['../ipc_transport_selection.html#ipc_transport_selection_online_standby_patterns',1,'']]],
  ['online_20standby_20setup_30',['Typical Workflow for Online/Standby Setup',['../ipc_guide.html#ipc_guide_workflow',1,'']]],
  ['only_31',['only',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md128',1,'2. CRC-32 Only'],['../group__CLOCKSYNC.html',1,'Clock Synchronization (diagnostic/timeout-sizing only)'],['../memory_architecture.html#memory_architecture_overview',1,'Static Allocation Only']]],
  ['only_20executes_32',['2.2 The framework still validates; the backend only executes',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md58',1,'']]],
  ['only_20never_20the_20basis_20of_20correctness_33',['2.3 &lt;tt&gt;sapi_clocksync&lt;/tt&gt;: diagnostic only, never the basis of correctness',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md152',1,'']]],
  ['only_20view_34',['Example 2: Read-Only View',['../buffer_user_guide.html#buffer_user_guide_example_ringbuf',1,'']]],
  ['opaque_20storage_35',['2.2 Fitting inside each service&apos;s fixed opaque storage',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md159',1,'']]],
  ['open_36',['open',['../structsapi__nvm__backend__t.html#aa767d9fde2916bd4793c64cfad1f9327',1,'sapi_nvm_backend_t::open'],['../structsapi__netlink__backend__t.html#aebb91e307214f22625b89cde3db6fd1b',1,'sapi_netlink_backend_t::open']]],
  ['open_20items_37',['7. Open items',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md22',1,'']]],
  ['operations_38',['operations',['../buffer_user_guide.html#buffer_user_guide_operations',1,'Buffer Operations'],['../buffer_architecture.html#buffer_architecture_performance',1,'O(1) All Operations'],['../string_user_guide.html#string_user_guide_operations',1,'Operations'],['../task_architecture.html#task_architecture_api',1,'Queue Operations'],['../timer_user_guide.html#timer_user_guide_operations',1,'Timer Operations']]],
  ['operations_20covered_39',['2.3 Operations covered',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md69',1,'']]],
  ['ops_40',['ops',['../structsapi__appmanager__config__t.html#ae03d69327899e03ea71555cd42f563fb',1,'sapi_appmanager_config_t']]],
  ['options_41',['options',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md103',1,'2. Three Polynomial Options'],['../ipc_transport_selection.html#ipc_transport_selection_transport_options',1,'Available Transport Options']]],
  ['or_20c11_20tt_20_5fgeneric_20tt_42',['2.5 Why named functions instead of macros or C11 &lt;tt&gt;_Generic&lt;/tt&gt;',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md38',1,'']]],
  ['or_20cross_20compile_43',['Linux (Native or Cross-compile)',['../md_docs_2CROSS__COMPILATION.html#autotoc_md227',1,'']]],
  ['or_20initialization_44',['2. Allocate at Compile-Time or Initialization',['../memory_user_guide.html#memory_user_guide_qs_allocate',1,'']]],
  ['ordered_20pair_20including_20widening_45',['2.1 Scope: every ordered pair, including widening',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md34',1,'']]],
  ['ordering_46',['Priority Ordering',['../task_architecture.html#task_architecture_priority',1,'']]],
  ['os_20abstraction_20layer_20oal_20for_20the_20safe_20api_20framework_47',['ADR-001: OS Abstraction Layer (OAL) for the Safe API Framework',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html',1,'']]],
  ['os_20tt_20grouping_20folder_20is_20dropped_20not_20renamed_48',['2.1 The &lt;tt&gt;common&lt;/tt&gt;/&lt;tt&gt;os&lt;/tt&gt; grouping folder is dropped, not renamed',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md77',1,'']]],
  ['out_20of_202_20voting_20perfect_20agreement_20required_49',['2-out-of-2 Voting (Perfect Agreement Required)',['../vital_channel_architecture.html#vital_channel_architecture_example_2oo2',1,'']]],
  ['out_20of_203_20voting_20tolerate_201_20fault_50',['2-out-of-3 Voting (Tolerate 1 Fault)',['../vital_channel_architecture.html#vital_channel_architecture_example_2oo3',1,'']]],
  ['out_20of_20m_20voting_51',['N-out-of-M Voting',['../vital_channel_architecture.html#vital_channel_architecture_example_nmr',1,'']]],
  ['out_20of_20memory_52',['Out-of-Memory',['../memory_user_guide.html#memory_user_guide_error_handling',1,'']]],
  ['over_20static_20storage_53',['2.1 Ownership model: caller-owned view over static storage',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md26',1,'']]],
  ['overview_54',['overview',['../reboot_architecture.html#reboot_architecture_overview',1,'Design Overview'],['../safestate_architecture.html#safestate_architecture_overview',1,'Design Overview'],['../timer_architecture.html#timer_architecture_overview',1,'Design Overview'],['../status_architecture.html#status_architecture_overview',1,'Design Overview'],['../watchdog_architecture.html#watchdog_architecture_overview',1,'Design Overview'],['../vital_channel_architecture.html#vital_channel_architecture_overview',1,'Overview'],['../ipc_guide.html#ipc_guide_overview',1,'Overview'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md178',1,'Overview'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md224',1,'Overview'],['../appmanager_integration.html#appmanager_integration_overview',1,'Overview'],['../system_architecture.html',1,'System Architecture Overview']]],
  ['owned_20view_20over_20static_20storage_55',['2.1 Ownership model: caller-owned view over static storage',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md26',1,'']]],
  ['ownership_20model_56',['Ownership Model',['../buffer_architecture.html#buffer_architecture_ownership',1,'']]],
  ['ownership_20model_3a_20caller_20owned_20view_20over_20static_20storage_57',['2.1 Ownership model: caller-owned view over static storage',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md26',1,'']]]
];
