var searchData=
[
  ['fail_20on_20cross_20compiled_20targets_0',['Tests fail on cross-compiled targets',['../md_docs_2CROSS__COMPILATION.html#autotoc_md255',1,'']]],
  ['fail_20safe_20by_20default_1',['Pattern 2: Fail-Safe-by-Default',['../safestate_user_guide.html#safestate_user_guide_pattern_failsafe',1,'']]],
  ['fail_20safe_20default_2',['Pattern 1: Conditional Kick (Fail-Safe Default)',['../watchdog_user_guide.html#watchdog_user_guide_pattern_conditional',1,'']]],
  ['failure_3',['Example 1: Redundant Channel Voting Failure',['../safestate_user_guide.html#safestate_user_guide_example_voting',1,'']]],
  ['failure_20mitigation_4',['Common-Cause-Failure Mitigation',['../system_architecture.html#system_architecture_ccf',1,'']]],
  ['failure_20semantics_5',['2.2 Signature and failure semantics',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md35',1,'']]],
  ['fallback_6',['Example 3: Reboot with Fallback',['../reboot_user_guide.html#reboot_user_guide_example_fallback',1,'']]],
  ['fault_7',['2-out-of-3 Voting (Tolerate 1 Fault)',['../vital_channel_architecture.html#vital_channel_architecture_example_2oo3',1,'']]],
  ['fault_20detection_8',['Example 3: Assertion-Based Fault Detection',['../safestate_user_guide.html#safestate_user_guide_example_assertion',1,'']]],
  ['fault_20handling_20callback_9',['Fault Handling Callback',['../vital_channel_user_guide.html#vital_channel_user_guide_pattern_fault',1,'']]],
  ['fault_20tolerance_10',['Pattern 1: Fault Tolerance',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md218',1,'']]],
  ['feature_11',['2.2 One CMake target per feature',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md78',1,'']]],
  ['feature_20directory_20layout_12',['ADR-007: Per-Feature Directory Layout',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html',1,'']]],
  ['feature_3a_20tt_20sapi_5fchannel_20tt_20comparator_20identity_13',['2.2 New feature: &lt;tt&gt;sapi_channel&lt;/tt&gt; (comparator + identity)',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md86',1,'']]],
  ['fifo_20named_20pipes_20transport_14',['FIFO (Named Pipes) Transport',['../ipc_transport_selection.html#ipc_transport_selection_fifo',1,'']]],
  ['file_20per_20service_20one_20aggregator_15',['2.1 One module, one file per service, one aggregator',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md158',1,'']]],
  ['files_16',['files',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md199',1,'In Header Files'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md200',1,'In Markdown Files'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md248',1,'Toolchain Files']]],
  ['fired_17',['fired',['../structsapi__watchdog__s.html#aa5d4491f1e230c4c6b5b3f17b0e4f66a',1,'sapi_watchdog_s']]],
  ['fires_18',['fires',['../structsapi__watchdog__status__t.html#ab7fb0ebc0718e4b056894043caea91a8',1,'sapi_watchdog_status_t::fires'],['../structsapi__watchdog__s.html#ab3ff6deb6b155bf12e86114b72a9fd65',1,'sapi_watchdog_s::fires']]],
  ['first_20abstraction_20layer_20oal_20services_19',['4. Scope of the first abstraction layer (OAL services)',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md19',1,'']]],
  ['fit_20',['Architectural Fit',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md107',1,'']]],
  ['fitting_20inside_20each_20service_20s_20fixed_20opaque_20storage_21',['2.2 Fitting inside each service&apos;s fixed opaque storage',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md159',1,'']]],
  ['fixed_20opaque_20storage_22',['2.2 Fitting inside each service&apos;s fixed opaque storage',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md159',1,'']]],
  ['fixed_20size_20message_20buffer_23',['Example 1: Fixed-Size Message Buffer',['../buffer_user_guide.html#buffer_user_guide_example_message',1,'']]],
  ['fixed_20size_20queues_24',['Pattern 2: Fixed-Size Queues',['../memory_user_guide.html#memory_user_guide_common_queue',1,'']]],
  ['fixed_20width_20types_25',['2. Use Fixed-Width Types',['../types_user_guide.html#types_user_guide_qs_use',1,'']]],
  ['flash_20wear_26',['Flash Wear',['../nvm_architecture.html#nvm_architecture_wear',1,'']]],
  ['flow_27',['flow',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md196',1,'6. Activity Diagram (Behavioral - Checkpoint Flow)'],['../reboot_architecture.html#reboot_architecture_flow',1,'Reboot Flow'],['../safestate_architecture.html#safestate_architecture_flow',1,'Transition Flow']]],
  ['flow_202oo2_20example_28',['Communication Flow (2oo2 Example)',['../vital_channel_architecture.html#vital_channel_architecture_communication_flow',1,'']]],
  ['folder_20is_20dropped_20not_20renamed_29',['2.1 The &lt;tt&gt;common&lt;/tt&gt;/&lt;tt&gt;os&lt;/tt&gt; grouping folder is dropped, not renamed',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md77',1,'']]],
  ['for_20checked_20assertions_30',['2. Use SAPI_ASSERT for Checked Assertions',['../safestate_user_guide.html#safestate_user_guide_qs_assert',1,'']]],
  ['for_20distributed_20vital_20channels_31',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['for_20online_20standby_20setup_32',['Typical Workflow for Online/Standby Setup',['../ipc_guide.html#ipc_guide_workflow',1,'']]],
  ['for_20qnx_33',['3. Build for QNX',['../md_docs_2CROSS__COMPILATION.html#autotoc_md240',1,'']]],
  ['for_20redundant_20channels_34',['ADR-016: CRC-64 Data Integrity for Redundant Channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'']]],
  ['for_20safety_20critical_20systems_35',['Common Diagram Patterns for Safety-Critical Systems',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md217',1,'']]],
  ['for_20sapi_36',['Why CRC-64 is Right for SAPI',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md95',1,'']]],
  ['for_20the_20safe_20api_20framework_37',['ADR-001: OS Abstraction Layer (OAL) for the Safe API Framework',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html',1,'']]],
  ['for_20vital_20communication_38',['Creating Channels for Vital Communication',['../channel_configuration.html#channel_configuration_channel_creation',1,'']]],
  ['format_39',['Entry Format',['../log_architecture.html#log_architecture_format',1,'']]],
  ['found_20qcc_20not_20found_40',['&quot;CMake not found&quot; / &quot;qcc not found&quot;',['../md_docs_2CROSS__COMPILATION.html#autotoc_md253',1,'']]],
  ['foundation_41',['C11 stdint.h Foundation',['../types_architecture.html#types_architecture_overview',1,'']]],
  ['framework_42',['framework',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html',1,'ADR-001: OS Abstraction Layer (OAL) for the Safe API Framework'],['../index.html',1,'Safe API Framework'],['../status_architecture.html#status_architecture_usage_patterns',1,'Usage Patterns in Framework']]],
  ['framework_20future_20v0_204_200_43',['With Redundancy Framework (Future v0.4.0+)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md108',1,'']]],
  ['framework_20reasons_200_204095_44',['Framework Reasons (0-4095)',['../safestate_architecture.html#safestate_architecture_reason_framework',1,'']]],
  ['framework_20still_20validates_20the_20backend_20only_20executes_45',['2.2 The framework still validates; the backend only executes',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md58',1,'']]],
  ['from_20earlier_20adrs_20despite_20the_20directory_20change_46',['2.3 What stays true from earlier ADRs despite the directory change',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md79',1,'']]],
  ['function_20per_20service_47',['2.1 One backend vtable type and one registration function per service',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md57',1,'']]],
  ['functions_48',['functions',['../cast_architecture.html#cast_architecture_functions',1,'Conversion Functions'],['../string_architecture.html#string_architecture_functions',1,'Core Functions'],['../checksum_user_guide.html#checksum_user_guide_functions',1,'Functions']]],
  ['functions_20instead_20of_20macros_20or_20c11_20tt_20_5fgeneric_20tt_49',['2.5 Why named functions instead of macros or C11 &lt;tt&gt;_Generic&lt;/tt&gt;',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md38',1,'']]],
  ['future_50',['Phase 3: Advanced (Future)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md122',1,'']]],
  ['future_20extensions_51',['Future Extensions',['../status_architecture.html#status_architecture_future',1,'']]],
  ['future_20v0_204_200_52',['With Redundancy Framework (Future v0.4.0+)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md108',1,'']]]
];
