var searchData=
[
  ['m_20voting_0',['N-out-of-M Voting',['../vital_channel_architecture.html#vital_channel_architecture_example_nmr',1,'']]],
  ['machine_20diagram_20behavioral_1',['4. State Machine Diagram (Behavioral)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md192',1,'']]],
  ['macros_2',['macros',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md50',1,'2.6 Macros'],['../safestate_architecture.html#safestate_architecture_api_macros',1,'Convenience Macros']]],
  ['macros_20or_20c11_20tt_20_5fgeneric_20tt_3',['2.5 Why named functions instead of macros or C11 &lt;tt&gt;_Generic&lt;/tt&gt;',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md38',1,'']]],
  ['main_20loop_20heartbeat_4',['Example 1: System Watchdog (Main Loop Heartbeat)',['../watchdog_user_guide.html#watchdog_user_guide_example_system',1,'']]],
  ['malloc_5',['Example 2: Ring Buffer Without malloc',['../memory_user_guide.html#memory_user_guide_example_ringbuf',1,'']]],
  ['manager_6',['manager',['../group__APPMANAGER.html',1,'Application Manager'],['../watchdog_architecture.html#watchdog_architecture_manager',1,'Watchdog Manager']]],
  ['manager_20integration_20with_20channels_7',['App Manager Integration with Channels',['../appmanager_integration.html',1,'']]],
  ['mandatory_20techniques_20supported_8',['Mandatory Techniques Supported',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md112',1,'']]],
  ['manipulation_9',['Bounded String Manipulation',['../group__STRING.html',1,'']]],
  ['manipulation_20and_20endianness_20safe_20buffer_20access_10',['ADR-006: Safe String Manipulation and Endianness-Safe Buffer Access',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html',1,'']]],
  ['manual_20cmake_20invocation_11',['Manual CMake invocation',['../index.html#autotoc_md5',1,'']]],
  ['markdown_20files_12',['In Markdown Files',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md200',1,'']]],
  ['match_13',['match',['../structsapi__checksum__result__t.html#a9fe6db5a9e58dff1d1d1d8ba1a671e50',1,'sapi_checksum_result_t']]],
  ['max_20requirements_14',['Calculate Max Requirements',['../memory_user_guide.html#memory_user_guide_sizing_calc',1,'']]],
  ['max_5fdelay_5fms_15',['max_delay_ms',['../structsapi__checkpoint__config__t.html#aa91a5f3cb397bcd4792789d057a68e78',1,'sapi_checkpoint_config_t']]],
  ['max_5fiterations_16',['max_iterations',['../structsapi__appmanager__config__t.html#a2d37adf24afa17dbb84364a50d121215',1,'sapi_appmanager_config_t']]],
  ['max_5fsubscribers_17',['max_subscribers',['../structsapi__ipc__pubsub__topic__config__t.html#a2e8b3680dbf534d139b1c35d15cd396b',1,'sapi_ipc_pubsub_topic_config_t']]],
  ['means_20here_20and_20what_20it_20deliberately_20doesn_20t_18',['2.3 What &quot;real&quot; means here, and what it deliberately doesn&apos;t',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md160',1,'']]],
  ['mechanics_19',['Timeout Mechanics',['../watchdog_architecture.html#watchdog_architecture_timeout',1,'']]],
  ['mechanism_20',['Watchdog Mechanism',['../group__WATCHDOG.html',1,'']]],
  ['memory_21',['memory',['../group__NVM.html',1,'Non-Volatile Memory'],['../memory_user_guide.html#memory_user_guide_error_handling',1,'Out-of-Memory']]],
  ['memory_20architecture_22',['Non-Volatile Memory Architecture',['../nvm_architecture.html',1,'']]],
  ['memory_20corruption_20detection_23',['Example 2: Memory Corruption Detection',['../reboot_user_guide.html#reboot_user_guide_example_memory',1,'']]],
  ['memory_20module_24',['What is the Memory Module?',['../memory_user_guide.html#memory_user_guide_overview',1,'']]],
  ['memory_20module_20architecture_25',['Memory Module - Architecture',['../memory_architecture.html',1,'']]],
  ['memory_20module_20user_20guide_26',['Memory Module - User Guide',['../memory_user_guide.html',1,'']]],
  ['memory_20reservation_27',['Static Memory Reservation',['../group__MEMORY.html',1,'']]],
  ['memory_20transport_28',['Shared Memory Transport',['../ipc_transport_selection.html#ipc_transport_selection_shared_memory',1,'']]],
  ['memory_20user_20guide_29',['Non-Volatile Memory User Guide',['../nvm_user_guide.html',1,'']]],
  ['message_20buffer_30',['Example 1: Fixed-Size Message Buffer',['../buffer_user_guide.html#buffer_user_guide_example_message',1,'']]],
  ['message_20size_20limits_31',['Message Size Limits',['../vital_channel_architecture.html#vital_channel_architecture_message_size',1,'']]],
  ['message_20wrapper_32',['3. Vital Message Wrapper',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md104',1,'']]],
  ['message_5fsize_33',['message_size',['../structsapi__netlink__config__t.html#a719d733132a652b5543fdaf45db520fa',1,'sapi_netlink_config_t::message_size'],['../structsapi__ipc__pubsub__topic__config__t.html#abc2c5a0797184e127ed5486d91009366',1,'sapi_ipc_pubsub_topic_config_t::message_size'],['../structsapi__ipc__config__t.html#a1fcc91bd1775c1767eafb156ed754b58',1,'sapi_ipc_config_t::message_size']]],
  ['metadata_20on_20the_20generic_20buffer_34',['2.2 No integrity metadata on the generic buffer',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md27',1,'']]],
  ['mirroring_35',['Pattern 3: Hot Standby with Mirroring',['../vital_channel_topologies.html#vital_channel_topologies_pattern_mirror_hot_standby',1,'']]],
  ['misra_20c_3a2012_36',['Static Analysis (MISRA C:2012)',['../index.html#autotoc_md6',1,'']]],
  ['misra_20c_3a2012_20compliance_37',['MISRA C:2012 Compliance',['../safestate_architecture.html#safestate_architecture_misra',1,'']]],
  ['misra_20compliance_38',['misra compliance',['../reboot_architecture.html#reboot_architecture_misra',1,'MISRA Compliance'],['../status_architecture.html#status_architecture_misra',1,'MISRA Compliance'],['../types_architecture.html#types_architecture_misra',1,'MISRA Compliance']]],
  ['misra_20compliant_39',['MISRA Compliant',['../checksum_architecture.html#checksum_architecture_misra',1,'']]],
  ['misra_20rule_2010_201_40',['MISRA Rule 10.1',['../cast_architecture.html#cast_architecture_misra',1,'']]],
  ['misra_20rule_2020_206_41',['MISRA Rule 20.6',['../memory_architecture.html#memory_architecture_misra',1,'']]],
  ['misra_20rule_2021_206_42',['MISRA Rule 21.6',['../string_architecture.html#string_architecture_misra',1,'']]],
  ['mitigation_43',['mitigation',['../system_architecture.html#system_architecture_ccf',1,'Common-Cause-Failure Mitigation'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md124',1,'Risk Mitigation']]],
  ['mitigation_20via_20build_20diversity_44',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['mitigation_3a_20diverse_20compilation_20not_20diverse_20hardware_45',['2.1 Primary mitigation: diverse compilation, not diverse hardware',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md85',1,'']]],
  ['mode_46',['mode',['../structsapi__timer__config__t.html#a5ddf924576714eef10035dd9d4756743',1,'sapi_timer_config_t']]],
  ['model_47',['model',['../buffer_architecture.html#buffer_architecture_ownership',1,'Ownership Model'],['../reboot_architecture.html#reboot_architecture_resource',1,'Resource Model'],['../timer_architecture.html#timer_architecture_storage',1,'Storage Model']]],
  ['model_3a_20caller_20owned_20view_20over_20static_20storage_48',['2.1 Ownership model: caller-owned view over static storage',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md26',1,'']]],
  ['modes_49',['Timer Modes',['../timer_user_guide.html#timer_user_guide_modes',1,'']]],
  ['modular_50',['NMR (N-Modular)',['../vital_channel_user_guide.html#vital_channel_user_guide_ss_nmr',1,'']]],
  ['module_51',['module',['../cast_user_guide.html#cast_user_guide_overview',1,'What is the Cast Module?'],['../memory_user_guide.html#memory_user_guide_overview',1,'What is the Memory Module?'],['../status_user_guide.html#status_user_guide_overview',1,'What is the Status Module?'],['../string_user_guide.html#string_user_guide_overview',1,'What is the String Module?'],['../safestate_architecture.html#safestate_architecture_integ_reboot',1,'With Reboot Module'],['../safestate_architecture.html#safestate_architecture_integ_watchdog',1,'With Watchdog Module']]],
  ['module_20architecture_52',['module architecture',['../buffer_architecture.html',1,'Buffer Module - Architecture'],['../cast_architecture.html',1,'Cast Module - Architecture'],['../checksum_architecture.html',1,'Checksum Module - Architecture'],['../log_architecture.html',1,'Log Module - Architecture'],['../memory_architecture.html',1,'Memory Module - Architecture'],['../reboot_architecture.html',1,'Reboot Module - Architecture'],['../safestate_architecture.html',1,'Safe-State Module - Architecture'],['../status_architecture.html',1,'Status Module - Architecture'],['../string_architecture.html',1,'String Module - Architecture'],['../task_architecture.html',1,'Task Queue Module - Architecture'],['../timer_architecture.html',1,'Timer Module - Architecture'],['../types_architecture.html',1,'Types Module - Architecture'],['../watchdog_architecture.html',1,'Watchdog Module - Architecture']]],
  ['module_20one_20file_20per_20service_20one_20aggregator_53',['2.1 One module, one file per service, one aggregator',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md158',1,'']]],
  ['module_20structure_20adr_20007_20compliance_54',['Module Structure (ADR-007 compliance)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md100',1,'']]],
  ['module_20user_20guide_55',['module user guide',['../buffer_user_guide.html',1,'Buffer Module - User Guide'],['../cast_user_guide.html',1,'Cast Module - User Guide'],['../checksum_user_guide.html',1,'Checksum Module - User Guide'],['../log_user_guide.html',1,'Logging Module - User Guide'],['../memory_user_guide.html',1,'Memory Module - User Guide'],['../reboot_user_guide.html',1,'Reboot Module - User Guide'],['../safestate_user_guide.html',1,'Safe-State Module - User Guide'],['../status_user_guide.html',1,'Status Module - User Guide'],['../string_user_guide.html',1,'String Module - User Guide'],['../task_user_guide.html',1,'Task Queue Module - User Guide'],['../timer_user_guide.html',1,'Timer Module - User Guide'],['../types_user_guide.html',1,'Types Module - User Guide'],['../vital_channel_user_guide.html',1,'Vital Channel Module - User Guide'],['../watchdog_user_guide.html',1,'Watchdog Module - User Guide']]],
  ['modules_56',['With Existing Modules',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md109',1,'']]],
  ['monitoring_57',['monitoring',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md105',1,'4. Statistics &amp; Monitoring'],['../vital_channel_user_guide.html#vital_channel_user_guide_pattern_health',1,'Health Monitoring'],['../vital_channel_architecture.html#vital_channel_architecture_health_tracking',1,'Health Monitoring'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md219',1,'Pattern 2: Health Monitoring']]],
  ['monitoring_20loop_58',['Pattern 1: Health Monitoring Loop',['../safestate_user_guide.html#safestate_user_guide_pattern_health',1,'']]],
  ['multi_20threaded_59',['Pattern 3: Thread-Local State (Multi-Threaded)',['../memory_user_guide.html#memory_user_guide_pattern_thread',1,'']]]
];
