var searchData=
[
  ['t_0',['2.3 What &quot;real&quot; means here, and what it deliberately doesn&apos;t',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md160',1,'']]],
  ['t_20a_20virtual_20dispatch_20c_20redesign_1',['2.4 Why this isn&apos;t a virtual-dispatch / C++ redesign',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md60',1,'']]],
  ['t_20rebuild_20it_2',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['table_3',['table',['../structsapi__checksum__manager__t.html#a7da47e3a37fe20c12e3e75fc0692c2a3',1,'sapi_checksum_manager_t']]],
  ['tables_20pre_20computed_4',['1. Lookup Tables (Pre-computed)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md102',1,'']]],
  ['target_5',['4. Deploy to QNX Target',['../md_docs_2CROSS__COMPILATION.html#autotoc_md241',1,'']]],
  ['target_20integrity_20level_3a_20sil_203_204_6',['3.2 Target integrity level: SIL 3/4',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md14',1,'']]],
  ['target_20per_20feature_7',['2.2 One CMake target per feature',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md78',1,'']]],
  ['targets_8',['targets',['../md_docs_2CROSS__COMPILATION.html#autotoc_md258',1,'Adding New Targets'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md255',1,'Tests fail on cross-compiled targets']]],
  ['task_20queue_9',['What is Task Queue?',['../task_user_guide.html#task_user_guide_overview',1,'']]],
  ['task_20queue_20module_20architecture_10',['Task Queue Module - Architecture',['../task_architecture.html',1,'']]],
  ['task_20queue_20module_20user_20guide_11',['Task Queue Module - User Guide',['../task_user_guide.html',1,'']]],
  ['task_20thread_20scheduling_12',['Task/Thread Scheduling',['../group__TASK.html',1,'']]],
  ['tcp_20ip_20transport_13',['TCP/IP Transport',['../ipc_transport_selection.html#ipc_transport_selection_tcp_ip',1,'']]],
  ['techniques_20supported_14',['Mandatory Techniques Supported',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md112',1,'']]],
  ['test_201_3a_20handler_20registration_20and_20invocation_15',['Test 1: Handler Registration and Invocation',['../safestate_architecture.html#safestate_architecture_test_handler',1,'']]],
  ['test_202_3a_20sapi_5fassert_20behavior_16',['Test 2: SAPI_ASSERT Behavior',['../safestate_architecture.html#safestate_architecture_test_assert',1,'']]],
  ['testing_20strategy_17',['testing strategy',['../status_architecture.html#status_architecture_testing',1,'Testing Strategy'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md132',1,'Testing Strategy']]],
  ['tests_18',['tests',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md134',1,'Integration Tests'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md135',1,'Property Tests'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md133',1,'Unit Tests'],['../safestate_architecture.html#safestate_architecture_testing',1,'Unit Tests'],['../watchdog_architecture.html#watchdog_architecture_testing',1,'Unit Tests']]],
  ['tests_20fail_20on_20cross_20compiled_20targets_19',['Tests fail on cross-compiled targets',['../md_docs_2CROSS__COMPILATION.html#autotoc_md255',1,'']]],
  ['that_20already_20exists_20—_20don_20t_20rebuild_20it_20',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['the_20backend_20only_20executes_21',['2.2 The framework still validates; the backend only executes',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md58',1,'']]],
  ['the_20basis_20of_20correctness_22',['2.3 &lt;tt&gt;sapi_clocksync&lt;/tt&gt;: diagnostic only, never the basis of correctness',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md152',1,'']]],
  ['the_20cast_20module_23',['What is the Cast Module?',['../cast_user_guide.html#cast_user_guide_overview',1,'']]],
  ['the_20directory_20change_24',['2.3 What stays true from earlier ADRs despite the directory change',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md79',1,'']]],
  ['the_20en_2050159_20envelope_20that_20already_20exists_20—_20don_20t_20rebuild_20it_25',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['the_20first_20abstraction_20layer_20oal_20services_26',['4. Scope of the first abstraction layer (OAL services)',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md19',1,'']]],
  ['the_20framework_20still_20validates_20the_20backend_20only_20executes_27',['2.2 The framework still validates; the backend only executes',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md58',1,'']]],
  ['the_20generic_20buffer_28',['2.2 No integrity metadata on the generic buffer',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md27',1,'']]],
  ['the_20memory_20module_29',['What is the Memory Module?',['../memory_user_guide.html#memory_user_guide_overview',1,'']]],
  ['the_20safe_20api_20framework_30',['ADR-001: OS Abstraction Layer (OAL) for the Safe API Framework',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html',1,'']]],
  ['the_20status_20module_31',['What is the Status Module?',['../status_user_guide.html#status_user_guide_overview',1,'']]],
  ['the_20string_20module_32',['What is the String Module?',['../string_user_guide.html#string_user_guide_overview',1,'']]],
  ['the_20tt_20common_20tt_20tt_20os_20tt_20grouping_20folder_20is_20dropped_20not_20renamed_33',['2.1 The &lt;tt&gt;common&lt;/tt&gt;/&lt;tt&gt;os&lt;/tt&gt; grouping folder is dropped, not renamed',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md77',1,'']]],
  ['the_20watchdog_34',['What is the Watchdog?',['../watchdog_user_guide.html#watchdog_user_guide_overview',1,'']]],
  ['this_20isn_20t_20a_20virtual_20dispatch_20c_20redesign_35',['2.4 Why this isn&apos;t a virtual-dispatch / C++ redesign',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md60',1,'']]],
  ['thread_20local_20state_20multi_20threaded_36',['Pattern 3: Thread-Local State (Multi-Threaded)',['../memory_user_guide.html#memory_user_guide_pattern_thread',1,'']]],
  ['thread_20scheduling_37',['Task/Thread Scheduling',['../group__TASK.html',1,'']]],
  ['threaded_38',['Pattern 3: Thread-Local State (Multi-Threaded)',['../memory_user_guide.html#memory_user_guide_pattern_thread',1,'']]],
  ['three_20polynomial_20options_39',['2. Three Polynomial Options',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md103',1,'']]],
  ['three_20severity_20levels_40',['Three Severity Levels',['../safestate_architecture.html#safestate_architecture_levels',1,'']]],
  ['tick_20system_41',['Timer Tick System',['../timer_architecture.html#timer_architecture_timing',1,'']]],
  ['time_42',['Verify at Compile-Time',['../memory_user_guide.html#memory_user_guide_sizing_verify',1,'']]],
  ['time_20or_20initialization_43',['2. Allocate at Compile-Time or Initialization',['../memory_user_guide.html#memory_user_guide_qs_allocate',1,'']]],
  ['time_5fsince_5flast_5fkick_44',['time_since_last_kick',['../structsapi__watchdog__status__t.html#a9a321c9f81a385a1d95a06a2eeffc36f',1,'sapi_watchdog_status_t']]],
  ['time_5funtil_5ffire_45',['time_until_fire',['../structsapi__watchdog__status__t.html#ab42417835dfa51abec11a6ca87ec9ea2',1,'sapi_watchdog_status_t']]],
  ['timeline_46',['Implementation Timeline',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md119',1,'']]],
  ['timeout_47',['timeout',['../watchdog_user_guide.html#watchdog_user_guide_example_custom',1,'Example 2: Custom Callback on Timeout'],['../timer_user_guide.html#timer_user_guide_example_oneshot',1,'Example 2: One-Shot Timeout']]],
  ['timeout_20mechanics_48',['Timeout Mechanics',['../watchdog_architecture.html#watchdog_architecture_timeout',1,'']]],
  ['timeout_20selection_49',['Timeout Selection',['../watchdog_user_guide.html#watchdog_user_guide_timeout_tuning',1,'']]],
  ['timeout_20sizing_20only_50',['Clock Synchronization (diagnostic/timeout-sizing only)',['../group__CLOCKSYNC.html',1,'']]],
  ['timeout_5fms_51',['timeout_ms',['../structsapi__watchdog__config__t.html#a6dd9bcc8e23fcf28cde27c104936df56',1,'sapi_watchdog_config_t']]],
  ['timer_52',['timer',['../timer_user_guide.html#timer_user_guide_qs_create',1,'1. Create Timer'],['../timer_user_guide.html#timer_user_guide_qs_start',1,'2. Start Timer'],['../timer_architecture.html#timer_architecture_performance',1,'O(1) Per Timer'],['../timer_user_guide.html#timer_user_guide_overview',1,'What is a Timer?']]],
  ['timer_20modes_53',['Timer Modes',['../timer_user_guide.html#timer_user_guide_modes',1,'']]],
  ['timer_20module_20architecture_54',['Timer Module - Architecture',['../timer_architecture.html',1,'']]],
  ['timer_20module_20user_20guide_55',['Timer Module - User Guide',['../timer_user_guide.html',1,'']]],
  ['timer_20operations_56',['Timer Operations',['../timer_user_guide.html#timer_user_guide_operations',1,'']]],
  ['timer_20service_57',['Timer Service',['../group__TIMER.html',1,'']]],
  ['timer_20tick_20system_58',['Timer Tick System',['../timer_architecture.html#timer_architecture_timing',1,'']]],
  ['timestamp_5fms_59',['timestamp_ms',['../structsapi__vital__message__t.html#a35b82dca38979bfbff4daf75bcefe007',1,'sapi_vital_message_t']]],
  ['to_20choose_20a_20topology_60',['How to Choose a Topology',['../vital_channel_topologies.html#vital_channel_topologies_selecting_topology',1,'']]],
  ['to_20go_20next_61',['Where to Go Next',['../system_architecture.html#system_architecture_docs',1,'']]],
  ['to_20implement_62',['What You Need to Implement',['../appmanager_integration.html#appmanager_integration_you_implement',1,'']]],
  ['to_20point_20network_20link_63',['Point-to-Point Network Link',['../group__NETLINK.html',1,'']]],
  ['to_20qnx_20target_64',['4. Deploy to QNX Target',['../md_docs_2CROSS__COMPILATION.html#autotoc_md241',1,'']]],
  ['to_20safety_20actions_65',['Status Codes to Safety Actions',['../status_user_guide.html#status_user_guide_mapping',1,'']]],
  ['to_20system_66',['3. Install to System',['../md_docs_2CROSS__COMPILATION.html#autotoc_md234',1,'']]],
  ['tolerance_67',['Pattern 1: Fault Tolerance',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md218',1,'']]],
  ['tolerate_201_20fault_68',['2-out-of-3 Voting (Tolerate 1 Fault)',['../vital_channel_architecture.html#vital_channel_architecture_example_2oo3',1,'']]],
  ['toolchain_20files_69',['Toolchain Files',['../md_docs_2CROSS__COMPILATION.html#autotoc_md248',1,'']]],
  ['toolchain_20linux_20cmake_70',['Toolchain-Linux.cmake',['../md_docs_2CROSS__COMPILATION.html#autotoc_md249',1,'']]],
  ['toolchain_20qnx_20cmake_71',['Toolchain-QNX.cmake',['../md_docs_2CROSS__COMPILATION.html#autotoc_md250',1,'']]],
  ['topic_72',['topic',['../structsapi__ipc__pubsub__subscriber__config__t.html#a690df0513f71ced4c958342e9a0c7034',1,'sapi_ipc_pubsub_subscriber_config_t']]],
  ['topic_5fname_73',['topic_name',['../structsapi__ipc__pubsub__topic__config__t.html#af5e5c968f8cd8ade9e48cee52a65ce79',1,'sapi_ipc_pubsub_topic_config_t']]],
  ['topologies_20and_20redundancy_20patterns_74',['Channel Topologies and Redundancy Patterns',['../vital_channel_topologies.html',1,'']]],
  ['topology_75',['How to Choose a Topology',['../vital_channel_topologies.html#vital_channel_topologies_selecting_topology',1,'']]],
  ['topology_20patterns_76',['Channel Topology Patterns',['../vital_channel_topologies.html#vital_channel_topologies_topology_overview',1,'']]],
  ['total_5fchecksums_77',['total_checksums',['../structsapi__checksum__stats__t.html#ad371fcead6341a1cdcfa410db4ad08cb',1,'sapi_checksum_stats_t']]],
  ['traceability_78',['3. Traceability',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md214',1,'']]],
  ['train_20control_20system_79',['Example 1: Train Control System',['../memory_user_guide.html#memory_user_guide_example_train',1,'']]],
  ['transition_20flow_80',['Transition Flow',['../safestate_architecture.html#safestate_architecture_flow',1,'']]],
  ['transitions_20and_20checked_20assertions_81',['transitions and checked assertions',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html',1,'ADR-004: Safe-State Transitions and Checked Assertions'],['../group__SAFESTATE.html',1,'Safe-State Transitions and Checked Assertions']]],
  ['transport_82',['transport',['../ipc_transport_selection.html#ipc_transport_selection_fifo',1,'FIFO (Named Pipes) Transport'],['../ipc_transport_selection.html#ipc_transport_selection_shared_memory',1,'Shared Memory Transport'],['../ipc_transport_selection.html#ipc_transport_selection_tcp_ip',1,'TCP/IP Transport'],['../ipc_transport_selection.html#ipc_transport_selection_udp',1,'UDP Transport']]],
  ['transport_20backend_83',['2.2 &lt;tt&gt;sapi_checkpoint&lt;/tt&gt;: bounded rendezvous, no new transport backend',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md151',1,'']]],
  ['transport_20backends_84',['Transport Backends',['../vital_channel_architecture.html#vital_channel_architecture_transport_backends',1,'']]],
  ['transport_20layer_85',['Inter-Process Communication (IPC) Transport Layer',['../ipc_transport_selection.html#ipc_transport_selection_overview',1,'']]],
  ['transport_20options_86',['Available Transport Options',['../ipc_transport_selection.html#ipc_transport_selection_transport_options',1,'']]],
  ['transport_20selection_20decision_20tree_87',['Transport Selection Decision Tree',['../ipc_transport_selection.html#ipc_transport_selection_decision_tree',1,'']]],
  ['transport_20selection_20guide_88',['IPC Transport Selection Guide',['../ipc_transport_selection.html',1,'']]],
  ['treated_20as_20errors_89',['&quot;Compiler warnings treated as errors&quot;',['../md_docs_2CROSS__COMPILATION.html#autotoc_md256',1,'']]],
  ['tree_90',['Transport Selection Decision Tree',['../ipc_transport_selection.html#ipc_transport_selection_decision_tree',1,'']]],
  ['trigger_20safe_20state_20explicitly_91',['3. Trigger Safe-State Explicitly',['../safestate_user_guide.html#safestate_user_guide_qs_trigger',1,'']]],
  ['triggered_20reboot_92',['Example 1: Watchdog-Triggered Reboot',['../reboot_user_guide.html#reboot_user_guide_example_watchdog',1,'']]],
  ['triggering_20tt_20wsign_20conversion_20tt_93',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]],
  ['triple_20channel_94',['2oo3 (Triple-Channel)',['../vital_channel_user_guide.html#vital_channel_user_guide_ss_2oo3',1,'']]],
  ['triple_20redundancy_202oo3_95',['Pattern 4: Triple Redundancy (2oo3)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_2oo3',1,'']]],
  ['troubleshooting_96',['Troubleshooting',['../md_docs_2CROSS__COMPILATION.html#autotoc_md252',1,'']]],
  ['true_20from_20earlier_20adrs_20despite_20the_20directory_20change_97',['2.3 What stays true from earlier ADRs despite the directory change',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md79',1,'']]],
  ['tt_20_5fgeneric_20tt_98',['2.5 Why named functions instead of macros or C11 &lt;tt&gt;_Generic&lt;/tt&gt;',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md38',1,'']]],
  ['tt_20common_20tt_20tt_20os_20tt_20grouping_20folder_20is_20dropped_20not_20renamed_99',['2.1 The &lt;tt&gt;common&lt;/tt&gt;/&lt;tt&gt;os&lt;/tt&gt; grouping folder is dropped, not renamed',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md77',1,'']]],
  ['tt_20sapi_5fassert_20tt_20is_20always_20active_100',['2.5 &lt;tt&gt;SAPI_ASSERT&lt;/tt&gt; is always active',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md49',1,'']]],
  ['tt_20sapi_5fchannel_20tt_20comparator_20identity_101',['2.2 New feature: &lt;tt&gt;sapi_channel&lt;/tt&gt; (comparator + identity)',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md86',1,'']]],
  ['tt_20sapi_5fcheckpoint_20tt_20_3a_20bounded_20rendezvous_20no_20new_20transport_20backend_102',['2.2 &lt;tt&gt;sapi_checkpoint&lt;/tt&gt;: bounded rendezvous, no new transport backend',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md151',1,'']]],
  ['tt_20sapi_5fclocksync_20tt_20_3a_20diagnostic_20only_20never_20the_20basis_20of_20correctness_103',['2.3 &lt;tt&gt;sapi_clocksync&lt;/tt&gt;: diagnostic only, never the basis of correctness',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md152',1,'']]],
  ['tt_20sapi_5flog_20tt_20and_20tt_20sapi_5freboot_20tt_104',['2.5 &lt;tt&gt;sapi_log&lt;/tt&gt; and &lt;tt&gt;sapi_reboot&lt;/tt&gt;',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md61',1,'']]],
  ['tt_20sapi_5freboot_20tt_105',['3. New OAL service: &lt;tt&gt;sapi_reboot&lt;/tt&gt;',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md51',1,'']]],
  ['tt_20sapi_5fsafestate_20tt_20does_20not_20call_20tt_20sapi_5freboot_20tt_20directly_106',['2.3 Why &lt;tt&gt;sapi_safestate&lt;/tt&gt; does not call &lt;tt&gt;sapi_reboot&lt;/tt&gt; directly',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md47',1,'']]],
  ['tt_20sapi_5fstring_5ft_20tt_20wraps_20tt_20sapi_5fbuffer_5ft_20tt_107',['2.1 &lt;tt&gt;sapi_string_t&lt;/tt&gt; wraps &lt;tt&gt;sapi_buffer_t&lt;/tt&gt;',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md67',1,'']]],
  ['tt_20strlen_20tt_20on_20unbounded_20untrusted_20input_108',['2.2 Never call &lt;tt&gt;strlen()&lt;/tt&gt; on unbounded/untrusted input',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md68',1,'']]],
  ['tt_20strtok_20tt_109',['2.4 Splitting is reentrant, unlike &lt;tt&gt;strtok&lt;/tt&gt;',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md70',1,'']]],
  ['tt_20wsign_20conversion_20tt_110',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]],
  ['type_111',['type',['../structsapi__watchdog__config__t.html#aa19e608c5e4ecd70e0270f634f44b017',1,'sapi_watchdog_config_t']]],
  ['type_20and_20one_20registration_20function_20per_20service_112',['2.1 One backend vtable type and one registration function per service',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md57',1,'']]],
  ['type_20ranges_113',['Type Ranges',['../types_user_guide.html#types_user_guide_ranges',1,'']]],
  ['type_20safe_20structure_114',['Example 1: Type-Safe Structure',['../types_user_guide.html#types_user_guide_example_struct',1,'']]],
  ['types_115',['types',['../types_user_guide.html#types_user_guide_qs_use',1,'2. Use Fixed-Width Types'],['../types_user_guide.html#types_user_guide_types',1,'Available Types'],['../group__TYPES.html',1,'Common Types'],['../channel_configuration.html#channel_configuration_channel_types',1,'Supported Channel Types'],['../watchdog_user_guide.html#watchdog_user_guide_types',1,'Watchdog Types'],['../types_user_guide.html#types_user_guide_overview',1,'What is Types?']]],
  ['types_20examples_116',['Diagram Types &amp; Examples',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md185',1,'']]],
  ['types_20module_20architecture_117',['Types Module - Architecture',['../types_architecture.html',1,'']]],
  ['types_20module_20user_20guide_118',['Types Module - User Guide',['../types_user_guide.html',1,'']]],
  ['typical_20workflow_20for_20online_20standby_20setup_119',['Typical Workflow for Online/Standby Setup',['../ipc_guide.html#ipc_guide_workflow',1,'']]]
];
