var searchData=
[
  ['padding_0',['padding',['../structsapi__vital__message__t.html#aeb2b79c397c57af3b307120882943f94',1,'sapi_vital_message_t']]],
  ['pair_20including_20widening_1',['2.1 Scope: every ordered pair, including widening',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md34',1,'']]],
  ['parameter_20summary_2',['Configuration Parameter Summary',['../channel_configuration.html#channel_configuration_configuration_summary',1,'']]],
  ['pattern_3',['pattern',['../ipc_transport_selection.html#ipc_transport_selection_backend_vtable',1,'Backend Implementation Pattern'],['../channel_configuration.html#channel_configuration_overview',1,'Channel Configuration Pattern'],['../channel_configuration.html#channel_configuration_dispatcher_callback',1,'Dispatcher Callback Pattern']]],
  ['pattern_201_3a_20conditional_20kick_20fail_20safe_20default_4',['Pattern 1: Conditional Kick (Fail-Safe Default)',['../watchdog_user_guide.html#watchdog_user_guide_pattern_conditional',1,'']]],
  ['pattern_201_3a_20fault_20tolerance_5',['Pattern 1: Fault Tolerance',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md218',1,'']]],
  ['pattern_201_3a_20health_20monitoring_20loop_6',['Pattern 1: Health Monitoring Loop',['../safestate_user_guide.html#safestate_user_guide_pattern_health',1,'']]],
  ['pattern_201_3a_20pool_20based_20allocation_7',['Pattern 1: Pool-Based Allocation',['../memory_user_guide.html#memory_user_guide_common_pool',1,'']]],
  ['pattern_201_3a_20single_20system_202oo2_20a_20↔_20b_20→_20c_8',['Pattern 1: Single-System 2oo2 (A ↔ B → C)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_single_2oo2',1,'']]],
  ['pattern_201_3a_20static_20global_20buffers_9',['Pattern 1: Static Global Buffers',['../memory_user_guide.html#memory_user_guide_pattern_global',1,'']]],
  ['pattern_202_3a_20application_20state_20structure_10',['Pattern 2: Application State Structure',['../memory_user_guide.html#memory_user_guide_pattern_app',1,'']]],
  ['pattern_202_3a_20check_20watchdog_20status_11',['Pattern 2: Check Watchdog Status',['../watchdog_user_guide.html#watchdog_user_guide_pattern_status',1,'']]],
  ['pattern_202_3a_20distributed_202oo2_20a_20↔_20b_20across_20network_12',['Pattern 2: Distributed 2oo2 (A ↔ B Across Network)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_distributed_2oo2',1,'']]],
  ['pattern_202_3a_20fail_20safe_20by_20default_13',['Pattern 2: Fail-Safe-by-Default',['../safestate_user_guide.html#safestate_user_guide_pattern_failsafe',1,'']]],
  ['pattern_202_3a_20fixed_20size_20queues_14',['Pattern 2: Fixed-Size Queues',['../memory_user_guide.html#memory_user_guide_common_queue',1,'']]],
  ['pattern_202_3a_20health_20monitoring_15',['Pattern 2: Health Monitoring',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md219',1,'']]],
  ['pattern_203_3a_20hot_20standby_20with_20mirroring_16',['Pattern 3: Hot Standby with Mirroring',['../vital_channel_topologies.html#vital_channel_topologies_pattern_mirror_hot_standby',1,'']]],
  ['pattern_203_3a_20layered_20architecture_17',['Pattern 3: Layered Architecture',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md220',1,'']]],
  ['pattern_203_3a_20thread_20local_20state_20multi_20threaded_18',['Pattern 3: Thread-Local State (Multi-Threaded)',['../memory_user_guide.html#memory_user_guide_pattern_thread',1,'']]],
  ['pattern_204_3a_20triple_20redundancy_202oo3_19',['Pattern 4: Triple Redundancy (2oo3)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_2oo3',1,'']]],
  ['pattern_20no_20dynamic_20allocation_20',['3.4 Handle pattern (no dynamic allocation)',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md16',1,'']]],
  ['patterns_21',['patterns',['../memory_user_guide.html#memory_user_guide_allocation_patterns',1,'Allocation Patterns'],['../vital_channel_topologies.html',1,'Channel Topologies and Redundancy Patterns'],['../vital_channel_topologies.html#vital_channel_topologies_topology_overview',1,'Channel Topology Patterns'],['../safestate_user_guide.html#safestate_user_guide_patterns',1,'Common Patterns'],['../vital_channel_user_guide.html#vital_channel_user_guide_patterns',1,'Common Patterns'],['../watchdog_user_guide.html#watchdog_user_guide_patterns',1,'Common Patterns'],['../memory_user_guide.html#memory_user_guide_patterns',1,'Common Patterns'],['../status_user_guide.html#status_user_guide_error_handling',1,'Error Handling Patterns'],['../ipc_transport_selection.html#ipc_transport_selection_online_standby_patterns',1,'Online/Standby Redundancy Patterns'],['../task_user_guide.html#task_user_guide_patterns',1,'Patterns']]],
  ['patterns_20for_20safety_20critical_20systems_22',['Common Diagram Patterns for Safety-Critical Systems',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md217',1,'']]],
  ['patterns_20in_20framework_23',['Usage Patterns in Framework',['../status_architecture.html#status_architecture_usage_patterns',1,'']]],
  ['payload_24',['payload',['../structsapi__vital__message__t.html#ac997ccc9bb231fbc7b87cf3afa7f5858',1,'sapi_vital_message_t']]],
  ['payload_5foversize_25',['payload_oversize',['../structsapi__checksum__stats__t.html#a1c08bab5dba529cdadde31e9780a15b6',1,'sapi_checksum_stats_t']]],
  ['payload_5fsize_26',['payload_size',['../structsapi__vital__message__t.html#a4da9652a45314ec60aa1d66c975cd662',1,'sapi_vital_message_t']]],
  ['per_20buffer_27',['O(n) Per Buffer',['../checksum_architecture.html#checksum_architecture_performance',1,'']]],
  ['per_20call_20no_20default_28',['2.5 Buffer endianness helpers: explicit per call, no default',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md71',1,'']]],
  ['per_20feature_29',['2.2 One CMake target per feature',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md78',1,'']]],
  ['per_20feature_20directory_20layout_30',['ADR-007: Per-Feature Directory Layout',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html',1,'']]],
  ['per_20level_20application_20registered_31',['2.2 One handler per level, application-registered',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md46',1,'']]],
  ['per_20service_32',['2.1 One backend vtable type and one registration function per service',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md57',1,'']]],
  ['per_20service_20one_20aggregator_33',['2.1 One module, one file per service, one aggregator',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md158',1,'']]],
  ['per_20timer_34',['O(1) Per Timer',['../timer_architecture.html#timer_architecture_performance',1,'']]],
  ['per_20watchdog_35',['State Per Watchdog',['../watchdog_architecture.html#watchdog_architecture_state',1,'']]],
  ['perfect_20agreement_20required_36',['2-out-of-2 Voting (Perfect Agreement Required)',['../vital_channel_architecture.html#vital_channel_architecture_example_2oo2',1,'']]],
  ['performance_37',['Performance',['../watchdog_architecture.html#watchdog_architecture_performance',1,'']]],
  ['period_5fms_38',['period_ms',['../structsapi__task__config__t.html#abd8843dc4d435e089a1a469f3d85f5b9',1,'sapi_task_config_t::period_ms'],['../structsapi__timer__config__t.html#a82ef7aa3ad90086b5120a7d320c21a28',1,'sapi_timer_config_t::period_ms']]],
  ['periodic_20heartbeat_39',['Example 1: Periodic Heartbeat',['../timer_user_guide.html#timer_user_guide_example_periodic',1,'']]],
  ['phase_201_3a_20core_20api_20v0_203_200_40',['Phase 1: Core API (v0.3.0)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md120',1,'']]],
  ['phase_202_3a_20integration_20v0_204_200_41',['Phase 2: Integration (v0.4.0)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md121',1,'']]],
  ['phase_203_3a_20advanced_20future_42',['Phase 3: Advanced (Future)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md122',1,'']]],
  ['pipes_20transport_43',['FIFO (Named Pipes) Transport',['../ipc_transport_selection.html#ipc_transport_selection_fifo',1,'']]],
  ['plan_44',['Rollout Plan',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md142',1,'']]],
  ['plantuml_45',['1. Install PlantUML',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md181',1,'']]],
  ['plantuml_20doxygen_46',['Architecture Diagrams with PlantUML &amp; Doxygen',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html',1,'']]],
  ['plantuml_20resources_47',['PlantUML Resources',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md175',1,'']]],
  ['png_3a_48',['Generate all diagrams as PNG:',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md169',1,'']]],
  ['point_20to_20point_20network_20link_49',['Point-to-Point Network Link',['../group__NETLINK.html',1,'']]],
  ['points_50',['Integration Points',['../safestate_architecture.html#safestate_architecture_integration',1,'']]],
  ['polynomial_51',['polynomial',['../structsapi__checksum__manager__t.html#a171f07b7de7dcb59111a9d3bf10e6db0',1,'sapi_checksum_manager_t']]],
  ['polynomial_20options_52',['2. Three Polynomial Options',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md103',1,'']]],
  ['pool_20based_20allocation_53',['Pattern 1: Pool-Based Allocation',['../memory_user_guide.html#memory_user_guide_common_pool',1,'']]],
  ['port_54',['port',['../structsapi__netlink__config__t.html#a57aeb391e22d0c1f768e0f387e85ac33',1,'sapi_netlink_config_t']]],
  ['posix_20linux_20oal_20backend_55',['ADR-018: A Real POSIX/Linux OAL Backend',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html',1,'']]],
  ['posix_20oal_56',['Linux (POSIX OAL)',['../md_docs_2CROSS__COMPILATION.html#autotoc_md231',1,'']]],
  ['practical_20examples_57',['practical examples',['../watchdog_user_guide.html#watchdog_user_guide_examples',1,'Practical Examples'],['../memory_user_guide.html#memory_user_guide_examples',1,'Practical Examples'],['../reboot_user_guide.html#reboot_user_guide_examples',1,'Practical Examples'],['../types_user_guide.html#types_user_guide_examples',1,'Practical Examples'],['../safestate_user_guide.html#safestate_user_guide_examples',1,'Practical Examples'],['../timer_user_guide.html#timer_user_guide_examples',1,'Practical Examples'],['../checksum_user_guide.html#checksum_user_guide_examples',1,'Practical Examples'],['../cast_user_guide.html#cast_user_guide_examples',1,'Practical Examples'],['../status_user_guide.html#status_user_guide_examples',1,'Practical Examples'],['../string_user_guide.html#string_user_guide_examples',1,'Practical Examples'],['../buffer_user_guide.html#buffer_user_guide_examples',1,'Practical Examples']]],
  ['practices_58',['practices',['../status_user_guide.html#status_user_guide_guidelines',1,'Best Practices'],['../watchdog_user_guide.html#watchdog_user_guide_guidelines',1,'Best Practices'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md211',1,'Best Practices'],['../vital_channel_user_guide.html#vital_channel_user_guide_guidelines',1,'Best Practices'],['../buffer_user_guide.html#buffer_user_guide_guidelines',1,'Best Practices'],['../cast_user_guide.html#cast_user_guide_guidelines',1,'Best Practices'],['../checksum_user_guide.html#checksum_user_guide_guidelines',1,'Best Practices'],['../log_user_guide.html#log_user_guide_guidelines',1,'Best Practices'],['../memory_user_guide.html#memory_user_guide_guidelines',1,'Best Practices'],['../nvm_user_guide.html#nvm_user_guide_guidelines',1,'Best Practices'],['../reboot_user_guide.html#reboot_user_guide_guidelines',1,'Best Practices'],['../safestate_user_guide.html#safestate_user_guide_guidelines',1,'Best Practices'],['../string_user_guide.html#string_user_guide_guidelines',1,'Best Practices'],['../timer_user_guide.html#timer_user_guide_guidelines',1,'Best Practices'],['../types_user_guide.html#types_user_guide_guidelines',1,'Best Practices']]],
  ['pre_20computed_59',['1. Lookup Tables (Pre-computed)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md102',1,'']]],
  ['prerequisites_60',['1. Prerequisites',['../md_docs_2CROSS__COMPILATION.html#autotoc_md238',1,'']]],
  ['presets_61',['presets',['../md_docs_2CROSS__COMPILATION.html#autotoc_md245',1,'Linux Presets'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md246',1,'QNX Presets']]],
  ['presets_20recommended_62',['Using CMake Presets (recommended)',['../index.html#autotoc_md3',1,'']]],
  ['presets_20reference_63',['CMake Presets Reference',['../md_docs_2CROSS__COMPILATION.html#autotoc_md244',1,'']]],
  ['primary_20mitigation_3a_20diverse_20compilation_20not_20diverse_20hardware_64',['2.1 Primary mitigation: diverse compilation, not diverse hardware',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md85',1,'']]],
  ['principles_65',['principles',['../ipc_guide.html#ipc_guide_design_principles',1,'Design Principles'],['../index.html#autotoc_md8',1,'Design principles']]],
  ['priority_66',['priority',['../structsapi__task__config__t.html#afe7a346b07a78599030af132bc289f45',1,'sapi_task_config_t']]],
  ['priority_20levels_67',['Priority Levels',['../task_user_guide.html#task_user_guide_priority',1,'']]],
  ['priority_20ordering_68',['Priority Ordering',['../task_architecture.html#task_architecture_priority',1,'']]],
  ['problem_20statement_69',['Problem Statement',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md93',1,'']]],
  ['process_20communication_70',['Inter-Process Communication',['../group__IPC.html',1,'']]],
  ['process_20communication_20guide_71',['IPC (Inter-Process Communication) Guide',['../ipc_guide.html',1,'']]],
  ['process_20communication_20ipc_20transport_20layer_72',['Inter-Process Communication (IPC) Transport Layer',['../ipc_transport_selection.html#ipc_transport_selection_overview',1,'']]],
  ['properties_73',['Safety Properties',['../vital_channel_architecture.html#vital_channel_architecture_safety_properties',1,'']]],
  ['property_20tests_74',['Property Tests',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md135',1,'']]],
  ['public_20api_75',['Public API',['../reboot_architecture.html#reboot_architecture_api',1,'']]],
  ['pure_20c_20abi_76',['3.1 Interface style: pure C ABI',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md13',1,'']]]
];
