var searchData=
[
  ['v0_203_200_0',['Phase 1: Core API (v0.3.0)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md120',1,'']]],
  ['v0_204_200_1',['v0 4 0',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md121',1,'Phase 2: Integration (v0.4.0)'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md108',1,'With Redundancy Framework (Future v0.4.0+)']]],
  ['validates_20adr_20020_2',['2.2 Negotiation link: no functional change required (validates ADR-020)',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md251',1,'']]],
  ['validates_20the_20backend_20only_20executes_3',['2.2 The framework still validates; the backend only executes',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md58',1,'']]],
  ['variables_4',['2. Set Environment Variables',['../md_docs_2CROSS__COMPILATION.html#autotoc_md387',1,'']]],
  ['vector_20_3a_5',['Generate all diagrams as SVG (vector):',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md318',1,'']]],
  ['verification_6',['verification',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md267',1,'3. Verification'],['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md279',1,'3. Verification'],['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md256',1,'3. Verification'],['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html#autotoc_md245',1,'4. Verification'],['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md235',1,'4. Verification'],['../md_docs_2architecture_2ADR-023-consolidate-cmake-libraries.html#autotoc_md211',1,'4. Verification'],['../md_docs_2architecture_2ADR-024-configurable-feature-build.html#autotoc_md221',1,'4. Verification'],['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html#autotoc_md288',1,'4. Verification'],['../md_docs_2architecture_2ADR-031-sapi-mem-util.html#autotoc_md296',1,'4. Verification'],['../md_docs_2architecture_2ADR-032-setup-phase-lock-coverage-extended.html#autotoc_md303',1,'4. Verification'],['../md_docs_2architecture_2ADR-033-sapi-mutex.html#autotoc_md310',1,'Verification']]],
  ['verification_20bar_7',['2.5 Verification bar',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html#autotoc_md202',1,'']]],
  ['verification_5ffailures_8',['verification_failures',['../structsapi__checksum__stats__t.html#a336736b8b2b6b372b5fe66ea0826e1a1',1,'sapi_checksum_stats_t']]],
  ['verification_5fpasses_9',['verification_passes',['../structsapi__checksum__stats__t.html#ac406b727a12b41dbe2e8d8d678f803c8',1,'sapi_checksum_stats_t']]],
  ['verify_20at_20compile_20time_10',['Verify at Compile-Time',['../memory_user_guide.html#memory_user_guide_sizing_verify',1,'']]],
  ['verify_20syntax_20without_20generating_3a_11',['Verify syntax without generating:',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md320',1,'']]],
  ['version_20control_12',['4. Version Control',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md363',1,'']]],
  ['via_20build_20diversity_13',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['via_20callbacks_14',['ADR-005: OAL Backend Registration via Callbacks',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html',1,'']]],
  ['view_15',['view',['../buffer_user_guide.html#buffer_user_guide_qs_init',1,'2. Bind Buffer View'],['../buffer_user_guide.html#buffer_user_guide_example_ringbuf',1,'Example 2: Read-Only View']]],
  ['view_20based_20buffer_20design_16',['View-Based Buffer Design',['../buffer_architecture.html#buffer_architecture_overview',1,'']]],
  ['view_20over_20static_20storage_17',['2.1 Ownership model: caller-owned view over static storage',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md26',1,'']]],
  ['virtual_20dispatch_20c_20redesign_18',['2.4 Why this isn&apos;t a virtual-dispatch / C++ redesign',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md60',1,'']]],
  ['vital_20architecture_20—_20ccf_20mitigation_20via_20build_20diversity_19',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['vital_20channel_20',['vital channel',['../ipc_transport_selection.html#ipc_transport_selection_vital_channel_integration',1,'Integration with Vital Channel'],['../vital_channel_user_guide.html#vital_channel_user_guide_overview',1,'What is Vital Channel?']]],
  ['vital_20channel_20communication_20architecture_21',['Vital Channel Communication Architecture',['../vital_channel_architecture.html',1,'']]],
  ['vital_20channel_20module_20user_20guide_22',['Vital Channel Module - User Guide',['../vital_channel_user_guide.html',1,'']]],
  ['vital_20channels_23',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['vital_20communication_24',['Creating Channels for Vital Communication',['../channel_configuration.html#channel_configuration_channel_creation',1,'']]],
  ['vital_20message_20wrapper_25',['3. Vital Message Wrapper',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md104',1,'']]],
  ['volatile_20memory_26',['Non-Volatile Memory',['../group__NVM.html',1,'']]],
  ['volatile_20memory_20—_20tt_20sapi_5fnvm_20h_20tt_20adr_20001_20§4_27',['2.2 Non-volatile memory — &lt;tt&gt;sapi_nvm.h&lt;/tt&gt; (ADR-001 §4)',['../safeapi_srs.html#autotoc_md419',1,'']]],
  ['volatile_20memory_20architecture_28',['Non-Volatile Memory Architecture',['../nvm_architecture.html',1,'']]],
  ['volatile_20memory_20user_20guide_29',['Non-Volatile Memory User Guide',['../nvm_user_guide.html',1,'']]],
  ['vote_20bug_20fixed_30',['2.2 &lt;tt&gt;sapi_voter&lt;/tt&gt; (new) - N-way voting, with the majority-vote bug fixed',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md227',1,'']]],
  ['voted_20path_31',['2.6 Rewiring &lt;tt&gt;sapi_safechannel&lt;/tt&gt;&apos;s voted path',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md231',1,'']]],
  ['voter_32',['voter',['../structsapi__appmanager__checkpoint__config__t.html#ab70a3fceb4f2a593ca44d7eea58dd4c5',1,'sapi_appmanager_checkpoint_config_t']]],
  ['voter_20—_20tt_20sapi_5fvoter_20h_20tt_20adr_20025_20§2_202_33',['3d.2 N-way voter — &lt;tt&gt;sapi_voter.h&lt;/tt&gt; (ADR-025 §2.2)',['../safeapi_srs.html#autotoc_md435',1,'']]],
  ['voter_20n_20way_20channel_20voting_34',['Voter (N-way channel voting)',['../group__voter.html',1,'']]],
  ['voting_35',['voting',['../vital_channel_architecture.html#vital_channel_architecture_example_nmr',1,'N-out-of-M Voting'],['../vital_channel_architecture.html#vital_channel_architecture_receive_semantics',1,'Receive Semantics (Voting)'],['../group__voter.html',1,'Voter (N-way channel voting)']]],
  ['voting_20and_202_20way_20cross_20comparison_20—_20adr_20025_36',['3d. Single-link channel, N-way voting, and 2-way cross-comparison — ADR-025',['../safeapi_srs.html#autotoc_md433',1,'']]],
  ['voting_20failure_37',['Example 1: Redundant Channel Voting Failure',['../safestate_user_guide.html#safestate_user_guide_example_voting',1,'']]],
  ['voting_20perfect_20agreement_20required_38',['2-out-of-2 Voting (Perfect Agreement Required)',['../vital_channel_architecture.html#vital_channel_architecture_example_2oo2',1,'']]],
  ['voting_20strategies_39',['Voting Strategies',['../vital_channel_user_guide.html#vital_channel_user_guide_strategies',1,'']]],
  ['voting_20tolerate_201_20fault_40',['2-out-of-3 Voting (Tolerate 1 Fault)',['../vital_channel_architecture.html#vital_channel_architecture_example_2oo3',1,'']]],
  ['voting_20with_20the_20majority_20vote_20bug_20fixed_41',['2.2 &lt;tt&gt;sapi_voter&lt;/tt&gt; (new) - N-way voting, with the majority-vote bug fixed',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md227',1,'']]],
  ['voting_5fstrategy_42',['voting_strategy',['../structsapi__voter__config__t.html#a829b7525659540eca8d5bc861cb0e751',1,'sapi_voter_config_t::voting_strategy'],['../structsapi__safechannel__vital__config__t.html#abfef190e48a85bd019306025b487d10a',1,'sapi_safechannel_vital_config_t::voting_strategy']]],
  ['vs_20systematic_20error_20detection_43',['Random vs Systematic Error Detection',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md113',1,'']]],
  ['vtable_20type_20and_20one_20registration_20function_20per_20service_44',['2.1 One backend vtable type and one registration function per service',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md57',1,'']]]
];
