var searchData=
[
  ['g_5fapp_5fstate_0',['g_app_state',['../sapi__appmanager_8c.html#ac8819bf2db204bbef9723ad534f2bb0c',1,'sapi_appmanager.c']]],
  ['g_5fchecksum_5fmanager_1',['g_checksum_manager',['../sapi__checksum_8c.html#af1ad6b41ef2439243997290a100b205d',1,'sapi_checksum.c']]],
  ['g_5fcrc64_5fertms_5ftable_2',['g_crc64_ertms_table',['../sapi__checksum_8c.html#a2a7dd821f6e3957eaf96f4d468a759c1',1,'sapi_checksum.c']]],
  ['g_5fcrc64_5fiso_5ftable_3',['g_crc64_iso_table',['../sapi__checksum_8c.html#ab519a08eee15f2a5f3784515575fcd1a',1,'sapi_checksum.c']]],
  ['g_5fcrc64_5fxz_5ftable_4',['g_crc64_xz_table',['../sapi__checksum_8c.html#ac0d63e484d87326c2efb853a759eeda6',1,'sapi_checksum.c']]],
  ['g_5fmanager_5finitialized_5',['g_manager_initialized',['../sapi__watchdog_8c.html#aad3972cd46f458f137a36ece8d1a6279',1,'sapi_watchdog.c']]],
  ['g_5fsetup_5flocked_6',['g_setup_locked',['../sapi__lifecycle_8c.html#abb0d5c85a510cc931aee048bae6a46df',1,'sapi_lifecycle.c']]],
  ['g_5fshutdown_5frequested_7',['g_shutdown_requested',['../sapi__appmanager_8c.html#ad631998c17d3b2ef7de50e011fbeda48',1,'sapi_appmanager.c']]],
  ['g_5fwatchdog_5fpool_8',['g_watchdog_pool',['../sapi__watchdog_8c.html#a00aeb3a1796aaf2cacfebdfbdd7dd1c4',1,'sapi_watchdog.c']]],
  ['gated_20req_20lifecycle_20001_9',['2.2 Which constructors are gated (REQ-LIFECYCLE-001)',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html#autotoc_md241',1,'']]],
  ['generate_20all_20diagrams_20as_20png_3a_10',['Generate all diagrams as PNG:',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md317',1,'']]],
  ['generate_20all_20diagrams_20as_20svg_20vector_20_3a_11',['Generate all diagrams as SVG (vector):',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md318',1,'']]],
  ['generate_20docs_12',['3. Generate Docs',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md331',1,'']]],
  ['generate_20single_20diagram_3a_13',['Generate single diagram:',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md319',1,'']]],
  ['generated_14',['2.2 Init/register/dispatch are hand-written per call site, not generated',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html#autotoc_md285',1,'']]],
  ['generated_20control_20flow_15',['2.1 Storage-shape macro only, no generated control flow',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html#autotoc_md284',1,'']]],
  ['generating_3a_16',['Verify syntax without generating:',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md320',1,'']]],
  ['generation_20not_20hand_20authorship_17',['2.6 Generation, not hand-authorship',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md39',1,'']]],
  ['generic_20buffer_18',['2.2 No integrity metadata on the generic buffer',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md27',1,'']]],
  ['genuine_20synchronization_20bugs_19',['2.5 The real debugging story: three genuine synchronization bugs',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md276',1,'']]],
  ['get_5fname_20',['get_name',['../structsapi__appmanager__operations__t.html#ab1d4508380375cc0e926c7d03a863533',1,'sapi_appmanager_operations_t']]],
  ['get_5foffset_5fms_21',['get_offset_ms',['../structsapi__clocksync__backend__t.html#ae82617e8b988a4f1f0b67749c935424d',1,'sapi_clocksync_backend_t']]],
  ['get_5fquality_22',['get_quality',['../structsapi__clocksync__backend__t.html#a62c375dc031ba1eaa487a048b469eed5',1,'sapi_clocksync_backend_t']]],
  ['get_5fversion_23',['get_version',['../structsapi__appmanager__operations__t.html#a84270edb615208abc02f99a2546a5058',1,'sapi_appmanager_operations_t']]],
  ['global_20buffers_24',['Pattern 1: Static Global Buffers',['../memory_user_guide.html#memory_user_guide_pattern_global',1,'']]],
  ['go_20next_25',['Where to Go Next',['../system_architecture.html#system_architecture_docs',1,'']]],
  ['goals_20for_20this_20adr_26',['4. Non-goals for this ADR',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md184',1,'']]],
  ['graceful_20degradation_27',['Example 2: Graceful Degradation',['../safestate_user_guide.html#safestate_user_guide_example_degraded',1,'']]],
  ['graph_28',['2.1 The dependency graph',['../md_docs_2architecture_2ADR-024-configurable-feature-build.html#autotoc_md216',1,'']]],
  ['grouping_20folder_20is_20dropped_20not_20renamed_29',['2.1 The &lt;tt&gt;common&lt;/tt&gt;/&lt;tt&gt;os&lt;/tt&gt; grouping folder is dropped, not renamed',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md77',1,'']]],
  ['guaranteed_20sizes_30',['Guaranteed Sizes',['../types_architecture.html#types_architecture_sizes',1,'']]],
  ['guarantees_31',['Safety-Critical Systems Need Guarantees',['../memory_user_guide.html#memory_user_guide_rationale_comparison',1,'']]],
  ['guide_32',['guide',['../buffer_user_guide.html',1,'Buffer Module - User Guide'],['../cast_user_guide.html',1,'Cast Module - User Guide'],['../channel_configuration.html',1,'Channel Configuration Guide'],['../checksum_user_guide.html',1,'Checksum Module - User Guide'],['../md_docs_2CROSS__COMPILATION.html',1,'Cross-Compilation Guide'],['../ipc_guide.html',1,'IPC (Inter-Process Communication) Guide'],['../ipc_transport_selection.html',1,'IPC Transport Selection Guide'],['../log_user_guide.html',1,'Logging Module - User Guide'],['../memory_user_guide.html',1,'Memory Module - User Guide'],['../nvm_user_guide.html',1,'Non-Volatile Memory User Guide'],['../reboot_user_guide.html',1,'Reboot Module - User Guide'],['../safestate_user_guide.html',1,'Safe-State Module - User Guide'],['../status_user_guide.html',1,'Status Module - User Guide'],['../string_user_guide.html',1,'String Module - User Guide'],['../task_user_guide.html',1,'Task Queue Module - User Guide'],['../timer_user_guide.html',1,'Timer Module - User Guide'],['../types_user_guide.html',1,'Types Module - User Guide'],['../vital_channel_user_guide.html',1,'Vital Channel Module - User Guide'],['../watchdog_user_guide.html',1,'Watchdog Module - User Guide']]],
  ['guidelines_33',['Design Guidelines',['../appmanager_integration.html#appmanager_integration_guidelines',1,'']]]
];
