var searchData=
[
  ['h_20foundation_0',['C11 stdint.h Foundation',['../types_architecture.html#types_architecture_overview',1,'']]],
  ['hamming_20codes_1',['4. Hamming Codes',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md130',1,'']]],
  ['hand_20authorship_2',['2.6 Generation, not hand-authorship',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md39',1,'']]],
  ['handle_20pattern_20no_20dynamic_20allocation_3',['3.4 Handle pattern (no dynamic allocation)',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md16',1,'']]],
  ['handler_20at_20startup_4',['1. Register Handler at Startup',['../safestate_user_guide.html#safestate_user_guide_qs_register',1,'']]],
  ['handler_20per_20level_20application_20registered_5',['2.2 One handler per level, application-registered',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md46',1,'']]],
  ['handler_20registration_20and_20invocation_6',['Test 1: Handler Registration and Invocation',['../safestate_architecture.html#safestate_architecture_test_handler',1,'']]],
  ['handler_20signature_7',['Handler Signature',['../safestate_architecture.html#safestate_architecture_handler_signature',1,'']]],
  ['handling_8',['handling',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md18',1,'3.6 Error handling'],['../reboot_architecture.html#reboot_architecture_reason',1,'Reason Code Handling']]],
  ['handling_20callback_9',['Fault Handling Callback',['../vital_channel_user_guide.html#vital_channel_user_guide_pattern_fault',1,'']]],
  ['handling_20patterns_10',['Error Handling Patterns',['../status_user_guide.html#status_user_guide_error_handling',1,'']]],
  ['hardware_11',['2.1 Primary mitigation: diverse compilation, not diverse hardware',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md85',1,'']]],
  ['header_12',['header',['../types_user_guide.html#types_user_guide_qs_include',1,'1. Include Header'],['../watchdog_user_guide.html#watchdog_user_guide_qs_include',1,'1. Include Header'],['../memory_user_guide.html#memory_user_guide_qs_include',1,'1. Include Header']]],
  ['header_20files_13',['In Header Files',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md199',1,'']]],
  ['health_14',['health',['../structsapi__vital__channel__storage__t.html#ac742da0f9076dc7536914c3ff4e35325',1,'sapi_vital_channel_storage_t']]],
  ['health_20monitoring_15',['health monitoring',['../vital_channel_architecture.html#vital_channel_architecture_health_tracking',1,'Health Monitoring'],['../vital_channel_user_guide.html#vital_channel_user_guide_pattern_health',1,'Health Monitoring'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md219',1,'Pattern 2: Health Monitoring']]],
  ['health_20monitoring_20loop_16',['Pattern 1: Health Monitoring Loop',['../safestate_user_guide.html#safestate_user_guide_pattern_health',1,'']]],
  ['heartbeat_17',['heartbeat',['../timer_user_guide.html#timer_user_guide_example_periodic',1,'Example 1: Periodic Heartbeat'],['../watchdog_user_guide.html#watchdog_user_guide_example_system',1,'Example 1: System Watchdog (Main Loop Heartbeat)']]],
  ['helpers_3a_20explicit_20per_20call_20no_20default_18',['2.5 Buffer endianness helpers: explicit per call, no default',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md71',1,'']]],
  ['here_20and_20what_20it_20deliberately_20doesn_20t_19',['2.3 What &quot;real&quot; means here, and what it deliberately doesn&apos;t',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md160',1,'']]],
  ['hmac_20sha256_20',['3. HMAC-SHA256',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md129',1,'']]],
  ['host_21',['host',['../structsapi__netlink__config__t.html#aeb98fba559c242df51c3fb775acb2ef8',1,'sapi_netlink_config_t']]],
  ['hot_20standby_20with_20mirroring_22',['Pattern 3: Hot Standby with Mirroring',['../vital_channel_topologies.html#vital_channel_topologies_pattern_mirror_hot_standby',1,'']]],
  ['how_20to_20choose_20a_20topology_23',['How to Choose a Topology',['../vital_channel_topologies.html#vital_channel_topologies_selecting_topology',1,'']]]
];
