var searchData=
[
  ['wait_20for_20a_20bounded_20ack_20that_20is_20the_20liveness_20signal_0',['2. Always send, wait for a bounded ACK - that IS the liveness signal',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md182',1,'']]],
  ['warnings_20treated_20as_20errors_1',['&quot;Compiler warnings treated as errors&quot;',['../md_docs_2CROSS__COMPILATION.html#autotoc_md397',1,'']]],
  ['was_20shorter_20than_20its_20own_20hysteresis_2',['2.3 Negotiation watchdog timeout was shorter than its own hysteresis',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md263',1,'']]],
  ['watchdog_3',['watchdog',['../watchdog_user_guide.html#watchdog_user_guide_qs_create',1,'2. Create Watchdog'],['../watchdog_user_guide.html#watchdog_user_guide_qs_start',1,'3. Start Watchdog'],['../watchdog_architecture.html#watchdog_architecture_state',1,'State Per Watchdog'],['../structsapi__checkpoint__config__t.html#aadf3ff5dcb28cf555d6712a2c9282089',1,'sapi_checkpoint_config_t::watchdog'],['../structsapi__appmanager__checkpoint__config__t.html#a8e2f62d80ad8c5bec2baa3c2b8499d03',1,'sapi_appmanager_checkpoint_config_t::watchdog'],['../watchdog_user_guide.html#watchdog_user_guide_overview',1,'What is the Watchdog?']]],
  ['watchdog_20—_20tt_20sapi_5fwatchdog_20h_20tt_20partial_4',['3b. Watchdog — &lt;tt&gt;sapi_watchdog.h&lt;/tt&gt; (partial)',['../safeapi_srs.html#autotoc_md423',1,'']]],
  ['watchdog_20main_20loop_20heartbeat_5',['Example 1: System Watchdog (Main Loop Heartbeat)',['../watchdog_user_guide.html#watchdog_user_guide_example_system',1,'']]],
  ['watchdog_20manager_6',['Watchdog Manager',['../watchdog_architecture.html#watchdog_architecture_manager',1,'']]],
  ['watchdog_20mechanism_7',['Watchdog Mechanism',['../group__WATCHDOG.html',1,'']]],
  ['watchdog_20module_8',['With Watchdog Module',['../safestate_architecture.html#safestate_architecture_integ_watchdog',1,'']]],
  ['watchdog_20module_20architecture_9',['Watchdog Module - Architecture',['../watchdog_architecture.html',1,'']]],
  ['watchdog_20module_20user_20guide_10',['Watchdog Module - User Guide',['../watchdog_user_guide.html',1,'']]],
  ['watchdog_20regularly_11',['4. Kick Watchdog Regularly',['../watchdog_user_guide.html#watchdog_user_guide_qs_kick',1,'']]],
  ['watchdog_20status_12',['Pattern 2: Check Watchdog Status',['../watchdog_user_guide.html#watchdog_user_guide_pattern_status',1,'']]],
  ['watchdog_20timeout_20was_20shorter_20than_20its_20own_20hysteresis_13',['2.3 Negotiation watchdog timeout was shorter than its own hysteresis',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md263',1,'']]],
  ['watchdog_20triggered_20reboot_14',['Example 1: Watchdog-Triggered Reboot',['../reboot_user_guide.html#reboot_user_guide_example_watchdog',1,'']]],
  ['watchdog_20types_15',['Watchdog Types',['../watchdog_user_guide.html#watchdog_user_guide_types',1,'']]],
  ['way_20channel_20comparison_16',['Cross-Comparator (2-way channel comparison)',['../group__cross__comparator.html',1,'']]],
  ['way_20channel_20voting_17',['Voter (N-way channel voting)',['../group__voter.html',1,'']]],
  ['way_20cross_20comparator_20—_20tt_20sapi_5fcross_5fcomparator_20h_20tt_20adr_20025_20§2_203_18',['3d.3 2-way cross-comparator — &lt;tt&gt;sapi_cross_comparator.h&lt;/tt&gt; (ADR-025 §2.3)',['../safeapi_srs.html#autotoc_md429',1,'']]],
  ['way_20peer_20comparison_19',['2.3 &lt;tt&gt;sapi_cross_comparator&lt;/tt&gt; (new) - 2-way peer comparison',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md228',1,'']]],
  ['way_20voter_20—_20tt_20sapi_5fvoter_20h_20tt_20adr_20025_20§2_202_20',['3d.2 N-way voter — &lt;tt&gt;sapi_voter.h&lt;/tt&gt; (ADR-025 §2.2)',['../safeapi_srs.html#autotoc_md428',1,'']]],
  ['way_20voting_20and_202_20way_20cross_20comparison_20—_20adr_20025_21',['3d. Single-link channel, N-way voting, and 2-way cross-comparison — ADR-025',['../safeapi_srs.html#autotoc_md426',1,'']]],
  ['way_20voting_20with_20the_20majority_20vote_20bug_20fixed_22',['2.2 &lt;tt&gt;sapi_voter&lt;/tt&gt; (new) - N-way voting, with the majority-vote bug fixed',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md227',1,'']]],
  ['wear_23',['Flash Wear',['../nvm_architecture.html#nvm_architecture_wear',1,'']]],
  ['what_20changes_20mechanically_24',['2.3 What changes mechanically',['../md_docs_2architecture_2ADR-024-configurable-feature-build.html#autotoc_md218',1,'']]],
  ['what_20does_20em_20not_20em_20change_25',['what does em not em change',['../md_docs_2architecture_2ADR-023-consolidate-cmake-libraries.html#autotoc_md208',1,'2.1 What does &lt;em&gt;not&lt;/em&gt; change'],['../md_docs_2architecture_2ADR-024-configurable-feature-build.html#autotoc_md219',1,'2.4 What does &lt;em&gt;not&lt;/em&gt; change']]],
  ['what_20is_20a_20buffer_26',['What is a Buffer?',['../buffer_user_guide.html#buffer_user_guide_overview',1,'']]],
  ['what_20is_20a_20timer_27',['What is a Timer?',['../timer_user_guide.html#timer_user_guide_overview',1,'']]],
  ['what_20is_20checksum_28',['What is Checksum?',['../checksum_user_guide.html#checksum_user_guide_overview',1,'']]],
  ['what_20is_20logging_29',['What is Logging?',['../log_user_guide.html#log_user_guide_overview',1,'']]],
  ['what_20is_20nvm_30',['What is NVM?',['../nvm_user_guide.html#nvm_user_guide_overview',1,'']]],
  ['what_20is_20reboot_31',['What is Reboot?',['../reboot_user_guide.html#reboot_user_guide_overview',1,'']]],
  ['what_20is_20safe_20state_32',['What is Safe-State?',['../safestate_user_guide.html#safestate_user_guide_overview',1,'']]],
  ['what_20is_20task_20queue_33',['What is Task Queue?',['../task_user_guide.html#task_user_guide_overview',1,'']]],
  ['what_20is_20the_20cast_20module_34',['What is the Cast Module?',['../cast_user_guide.html#cast_user_guide_overview',1,'']]],
  ['what_20is_20the_20memory_20module_35',['What is the Memory Module?',['../memory_user_guide.html#memory_user_guide_overview',1,'']]],
  ['what_20is_20the_20status_20module_36',['What is the Status Module?',['../status_user_guide.html#status_user_guide_overview',1,'']]],
  ['what_20is_20the_20string_20module_37',['What is the String Module?',['../string_user_guide.html#string_user_guide_overview',1,'']]],
  ['what_20is_20the_20watchdog_38',['What is the Watchdog?',['../watchdog_user_guide.html#watchdog_user_guide_overview',1,'']]],
  ['what_20is_20types_39',['What is Types?',['../types_user_guide.html#types_user_guide_overview',1,'']]],
  ['what_20is_20vital_20channel_40',['What is Vital Channel?',['../vital_channel_user_guide.html#vital_channel_user_guide_overview',1,'']]],
  ['what_20it_20deliberately_20doesn_20t_41',['2.3 What &quot;real&quot; means here, and what it deliberately doesn&apos;t',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md160',1,'']]],
  ['what_20real_20means_20here_20and_20what_20it_20deliberately_20doesn_20t_42',['2.3 What &quot;real&quot; means here, and what it deliberately doesn&apos;t',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md160',1,'']]],
  ['what_20stays_20true_20from_20earlier_20adrs_20despite_20the_20directory_20change_43',['2.3 What stays true from earlier ADRs despite the directory change',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md79',1,'']]],
  ['what_20still_20lives_20where_44',['2.2 What still lives where',['../md_docs_2architecture_2ADR-021-consumer-backend-header-split.html#autotoc_md191',1,'']]],
  ['what_20you_20need_20to_20implement_45',['What You Need to Implement',['../appmanager_integration.html#appmanager_integration_you_implement',1,'']]],
  ['whenever_20checkpoint_20is_20paused_46',['2.4 The real bug: the cyclic executive starves whenever checkpoint is paused',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md264',1,'']]],
  ['where_47',['2.2 What still lives where',['../md_docs_2architecture_2ADR-021-consumer-backend-header-split.html#autotoc_md191',1,'']]],
  ['where_20to_20go_20next_48',['Where to Go Next',['../system_architecture.html#system_architecture_docs',1,'']]],
  ['which_20constructors_20are_20gated_20req_20lifecycle_20001_49',['2.2 Which constructors are gated (REQ-LIFECYCLE-001)',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html#autotoc_md241',1,'']]],
  ['why_20crc_2064_20is_20right_20for_20sapi_50',['Why CRC-64 is Right for SAPI',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md95',1,'']]],
  ['why_20it_20s_20correct_20without_20triggering_20tt_20wsign_20conversion_20tt_51',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]],
  ['why_20named_20functions_20instead_20of_20macros_20or_20c11_20tt_20_5fgeneric_20tt_52',['2.5 Why named functions instead of macros or C11 &lt;tt&gt;_Generic&lt;/tt&gt;',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md38',1,'']]],
  ['why_20no_20dynamic_20allocation_53',['Why No Dynamic Allocation?',['../memory_user_guide.html#memory_user_guide_rationale',1,'']]],
  ['why_20this_20isn_20t_20a_20virtual_20dispatch_20c_20redesign_54',['2.4 Why this isn&apos;t a virtual-dispatch / C++ redesign',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md60',1,'']]],
  ['why_20tt_20sapi_5fsafestate_20tt_20does_20not_20call_20tt_20sapi_5freboot_20tt_20directly_55',['2.3 Why &lt;tt&gt;sapi_safestate&lt;/tt&gt; does not call &lt;tt&gt;sapi_reboot&lt;/tt&gt; directly',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md47',1,'']]],
  ['wide_20requirements_20claude_20md_20not_20yet_20tagged_20per_20function_56',['3. Project-wide requirements (CLAUDE.md, not yet tagged per-function)',['../safeapi_srs.html#autotoc_md419',1,'']]],
  ['widening_57',['2.1 Scope: every ordered pair, including widening',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md34',1,'']]],
  ['width_20types_58',['2. Use Fixed-Width Types',['../types_user_guide.html#types_user_guide_qs_use',1,'']]],
  ['wire_20protocol_20one_20shared_20fixed_20size_20envelope_59',['2.1 Wire protocol - one shared, fixed-size envelope',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md272',1,'']]],
  ['with_20adr_20027_20§2_205_20s_20open_20reconnect_20livelock_60',['2.6 Known correlation with ADR-027 §2.5&apos;s open reconnect livelock',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md266',1,'']]],
  ['with_20channels_61',['App Manager Integration with Channels',['../appmanager_integration.html',1,'']]],
  ['with_20existing_20modules_62',['With Existing Modules',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md109',1,'']]],
  ['with_20fallback_63',['Example 3: Reboot with Fallback',['../reboot_user_guide.html#reboot_user_guide_example_fallback',1,'']]],
  ['with_20mirroring_64',['Pattern 3: Hot Standby with Mirroring',['../vital_channel_topologies.html#vital_channel_topologies_pattern_mirror_hot_standby',1,'']]],
  ['with_20plantuml_20doxygen_65',['Architecture Diagrams with PlantUML &amp; Doxygen',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html',1,'']]],
  ['with_20reboot_20module_66',['With Reboot Module',['../safestate_architecture.html#safestate_architecture_integ_reboot',1,'']]],
  ['with_20redundancy_20framework_20future_20v0_204_200_67',['With Redundancy Framework (Future v0.4.0+)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md108',1,'']]],
  ['with_20safe_20state_68',['with safe state',['../status_architecture.html#status_architecture_safestate',1,'Integration with Safe-State'],['../reboot_user_guide.html#reboot_user_guide_integration',1,'Integration with Safe-State'],['../watchdog_architecture.html#watchdog_architecture_integration',1,'Integration with Safe-State']]],
  ['with_20the_20majority_20vote_20bug_20fixed_69',['2.2 &lt;tt&gt;sapi_voter&lt;/tt&gt; (new) - N-way voting, with the majority-vote bug fixed',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md227',1,'']]],
  ['with_20vital_20channel_70',['Integration with Vital Channel',['../ipc_transport_selection.html#ipc_transport_selection_vital_channel_integration',1,'']]],
  ['with_20watchdog_20module_71',['With Watchdog Module',['../safestate_architecture.html#safestate_architecture_integ_watchdog',1,'']]],
  ['without_20generating_3a_72',['Verify syntax without generating:',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md313',1,'']]],
  ['without_20malloc_73',['Example 2: Ring Buffer Without malloc',['../memory_user_guide.html#memory_user_guide_example_ringbuf',1,'']]],
  ['without_20triggering_20tt_20wsign_20conversion_20tt_74',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]],
  ['workflow_20for_20online_20standby_20setup_75',['Typical Workflow for Online/Standby Setup',['../ipc_guide.html#ipc_guide_workflow',1,'']]],
  ['world_20impact_76',['Real-World Impact',['../memory_user_guide.html#memory_user_guide_rationale_example',1,'']]],
  ['wrapper_77',['3. Vital Message Wrapper',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md104',1,'']]],
  ['wrappers_20no_20safe_20string_20library_20scope_20creep_78',['2.1 Three trivial wrappers, no &quot;safe string library&quot; scope creep',['../md_docs_2architecture_2ADR-031-sapi-mem-util.html#autotoc_md293',1,'']]],
  ['wraps_20tt_20sapi_5fbuffer_5ft_20tt_79',['2.1 &lt;tt&gt;sapi_string_t&lt;/tt&gt; wraps &lt;tt&gt;sapi_buffer_t&lt;/tt&gt;',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md67',1,'']]],
  ['write_80',['write',['../structsapi__nvm__backend__t.html#afd8403fe9dbd9d44b0360c117fee0ba3',1,'sapi_nvm_backend_t::write'],['../structsapi__log__backend__t.html#a62ee7f650a6816035f55d5514d752481',1,'sapi_log_backend_t::write']]],
  ['write_20data_81',['Write Data',['../buffer_user_guide.html#buffer_user_guide_op_write',1,'']]],
  ['write_20interface_82',['Read/Write Interface',['../nvm_architecture.html#nvm_architecture_api',1,'']]],
  ['written_20per_20call_20site_20not_20generated_83',['2.2 Init/register/dispatch are hand-written per call site, not generated',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html#autotoc_md285',1,'']]],
  ['wsign_20conversion_20tt_84',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]]
];
