var searchData=
[
  ['b↔c_20util_20channel_0',['ADR-038: Status indication - a C-side pub/sub broker + an A/B↔C util channel',['../md_docs_2architecture_2ADR-038-status-indication-and-c-pubsub-broker.html',1,'']]],
  ['b_20§2_204_20cross_20site_20transfer_20the_20full_20snapshot_20no_20longer_20fits_20one_20vital_20frame_1',['B. §2.4 cross-site transfer - the full snapshot no longer fits one vital frame',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md283',1,'']]],
  ['b_20→_20c_2',['Pattern 1: Single-System 2oo2 (A ↔ B → C)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_single_2oo2',1,'']]],
  ['b_20across_20network_3',['Pattern 2: Distributed 2oo2 (A ↔ B Across Network)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_distributed_2oo2',1,'']]],
  ['b_3a_20the_20train_20session_20table_4',['2.3 A/B: the train-session table',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md274',1,'']]],
  ['backend_5',['backend',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md151',1,'2.2 &lt;tt&gt;sapi_checkpoint&lt;/tt&gt;: bounded rendezvous, no new transport backend'],['../md_docs_2architecture_2ADR-018-posix-oal-backend.html',1,'ADR-018: A Real POSIX/Linux OAL Backend']]],
  ['backend_20adaptation_6',['backend adaptation',['../group__CLOCKSYNC__BACKEND.html',1,'Clock Synchronization - Backend Adaptation'],['../group__REBOOT__BACKEND.html',1,'Controlled Reboot - Backend Adaptation'],['../group__IPC__BACKEND.html',1,'Inter-Process Communication - Backend Adaptation'],['../group__LOG__BACKEND.html',1,'Logging and Diagnostics - Backend Adaptation'],['../group__MUTEX__BACKEND.html',1,'Mutex Service - Backend Adaptation'],['../group__NVM__BACKEND.html',1,'NVM Service - Backend Adaptation'],['../group__NETLINK__BACKEND.html',1,'Point-to-Point Network Link - Backend Adaptation'],['../group__PLATFORM__BACKEND.html',1,'Real-Time Platform Configuration - Backend Adaptation'],['../group__MEMORY__BACKEND.html',1,'Static Memory Reservation - Backend Adaptation'],['../group__TASK__BACKEND.html',1,'Task/Thread Scheduling - Backend Adaptation'],['../group__TIMER__BACKEND.html',1,'Timer Service - Backend Adaptation']]],
  ['backend_20at_20startup_7',['1. Register Backend at Startup',['../reboot_user_guide.html#reboot_user_guide_qs_backend',1,'']]],
  ['backend_20header_20separation_8',['ADR-021: Consumer / OS-Backend Header Separation',['../md_docs_2architecture_2ADR-021-consumer-backend-header-split.html',1,'']]],
  ['backend_20implementation_9',['Backend Implementation',['../nvm_architecture.html#nvm_architecture_backend',1,'']]],
  ['backend_20implementation_20pattern_10',['Backend Implementation Pattern',['../ipc_transport_selection.html#ipc_transport_selection_backend_vtable',1,'']]],
  ['backend_20indirection_11',['3.5 Backend indirection',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md17',1,'']]],
  ['backend_20interface_12',['Backend Interface',['../reboot_architecture.html#reboot_architecture_backend',1,'']]],
  ['backend_20only_20executes_13',['2.2 The framework still validates; the backend only executes',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md58',1,'']]],
  ['backend_20registration_20and_20remaining_20setup_20only_20constructors_14',['ADR-032: Setup-phase lock coverage extended to backend registration and remaining setup-only constructors',['../md_docs_2architecture_2ADR-032-setup-phase-lock-coverage-extended.html',1,'']]],
  ['backend_20registration_20via_20callbacks_15',['ADR-005: OAL Backend Registration via Callbacks',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html',1,'']]],
  ['backend_20same_20file_20same_20accessor_20req_20oal_20netlink_20014_16',['2.1 New UDP backend, same file, same accessor (REQ-OAL-NETLINK-014)',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md250',1,'']]],
  ['backend_20vtable_20type_20and_20one_20registration_20function_20per_20service_17',['2.1 One backend vtable type and one registration function per service',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md57',1,'']]],
  ['backends_18',['Transport Backends',['../vital_channel_architecture.html#vital_channel_architecture_transport_backends',1,'']]],
  ['backing_20storage_19',['1. Allocate Backing Storage',['../buffer_user_guide.html#buffer_user_guide_qs_storage',1,'']]],
  ['bar_20',['2.5 Verification bar',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html#autotoc_md202',1,'']]],
  ['base_20channel_20—_20tt_20sapi_5fdual_5fmsgchannel_20h_20tt_20adr_20020_20§1_20layer_201_21',['3e.2 Base Channel — &lt;tt&gt;sapi_dual_msgchannel.h&lt;/tt&gt; (ADR-020 §1, Layer 1)',['../safeapi_srs.html#autotoc_md501',1,'']]],
  ['based_20allocation_22',['Pattern 1: Pool-Based Allocation',['../memory_user_guide.html#memory_user_guide_common_pool',1,'']]],
  ['based_20buffer_20design_23',['View-Based Buffer Design',['../buffer_architecture.html#buffer_architecture_overview',1,'']]],
  ['based_20fault_20detection_24',['Example 3: Assertion-Based Fault Detection',['../safestate_user_guide.html#safestate_user_guide_example_assertion',1,'']]],
  ['basis_20of_20correctness_25',['2.3 &lt;tt&gt;sapi_clocksync&lt;/tt&gt;: diagnostic only, never the basis of correctness',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md152',1,'']]],
  ['before_20convert_26',['Check-Before-Convert',['../cast_architecture.html#cast_architecture_strategy',1,'']]],
  ['behavior_27',['Test 2: SAPI_ASSERT Behavior',['../safestate_architecture.html#safestate_architecture_test_assert',1,'']]],
  ['behavioral_28',['4. State Machine Diagram (Behavioral)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md397',1,'']]],
  ['behavioral_20checkpoint_20flow_29',['6. Activity Diagram (Behavioral - Checkpoint Flow)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md401',1,'']]],
  ['behavioral_20diagrams_20configuration_20sequences_30',['Behavioral Diagrams - Configuration Sequences',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md372',1,'']]],
  ['behavioral_20ipc_31',['2. Sequence Diagram (Behavioral - IPC)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md393',1,'']]],
  ['behavioral_20redundancy_32',['3. Sequence Diagram (Behavioral - Redundancy)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md395',1,'']]],
  ['behind_20the_20vtable_20tt_20safeapibackendposix_20tt_33',['2. POSIX implementation moves behind the vtable (&lt;tt&gt;safeAPIBackendPosix&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-035-platform-realtime-init.html#autotoc_md327',1,'']]],
  ['best_20practices_34',['best practices',['../buffer_user_guide.html#buffer_user_guide_guidelines',1,'Best Practices'],['../safestate_user_guide.html#safestate_user_guide_guidelines',1,'Best Practices'],['../status_user_guide.html#status_user_guide_guidelines',1,'Best Practices'],['../string_user_guide.html#string_user_guide_guidelines',1,'Best Practices'],['../types_user_guide.html#types_user_guide_guidelines',1,'Best Practices'],['../cast_user_guide.html#cast_user_guide_guidelines',1,'Best Practices'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md416',1,'Best Practices'],['../log_user_guide.html#log_user_guide_guidelines',1,'Best Practices'],['../watchdog_user_guide.html#watchdog_user_guide_guidelines',1,'Best Practices'],['../checksum_user_guide.html#checksum_user_guide_guidelines',1,'Best Practices'],['../vital_channel_user_guide.html#vital_channel_user_guide_guidelines',1,'Best Practices'],['../timer_user_guide.html#timer_user_guide_guidelines',1,'Best Practices'],['../reboot_user_guide.html#reboot_user_guide_guidelines',1,'Best Practices'],['../nvm_user_guide.html#nvm_user_guide_guidelines',1,'Best Practices'],['../memory_user_guide.html#memory_user_guide_guidelines',1,'Best Practices']]],
  ['between_20two_20independently_20retrying_20endpoints_35',['2.5 Known open issue: reconnect livelock between two independently-retrying endpoints',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md254',1,'']]],
  ['binaries_36',['ADR-037: Role C gateway - decomposition into per-client-type service binaries',['../md_docs_2architecture_2ADR-037-role-c-gateway-decomposition.html',1,'']]],
  ['binaries_20one_20shared_20library_37',['1. Three service binaries, one shared library',['../md_docs_2architecture_2ADR-037-role-c-gateway-decomposition.html#autotoc_md347',1,'']]],
  ['bind_20buffer_20view_38',['2. Bind Buffer View',['../buffer_user_guide.html#buffer_user_guide_qs_init',1,'']]],
  ['bis_20application_20setup_20phase_20lock_20—_20tt_20sapi_5flifecycle_20h_20tt_20adr_20026_39',['3c-bis. Application setup-phase lock — &lt;tt&gt;sapi_lifecycle.h&lt;/tt&gt; (ADR-026)',['../safeapi_srs.html#autotoc_md494',1,'']]],
  ['block_5fcount_40',['block_count',['../structsapi__mem__pool__config__t.html#abbf4fbb3bfdfdd6e7646009758917ff6',1,'sapi_mem_pool_config_t']]],
  ['block_5fsize_41',['block_size',['../structsapi__mem__pool__config__t.html#a2109332171b85527842fd7d167e92561',1,'sapi_mem_pool_config_t']]],
  ['both_20its_20own_20and_20the_20peer_20s_20state_42',['3. The negotiator keeps both its own and the peer&apos;s state',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md183',1,'']]],
  ['bounded_20ack_20that_20is_20the_20liveness_20signal_43',['2. Always send, wait for a bounded ACK - that IS the liveness signal',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html#autotoc_md182',1,'']]],
  ['bounded_20rendezvous_20no_20new_20transport_20backend_44',['2.2 &lt;tt&gt;sapi_checkpoint&lt;/tt&gt;: bounded rendezvous, no new transport backend',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md151',1,'']]],
  ['bounded_20string_20manipulation_45',['Bounded String Manipulation',['../group__STRING.html',1,'']]],
  ['bounded_20string_20manipulation_20—_20tt_20sapi_5fstring_20h_20tt_20adr_20006_46',['1.6 Bounded string manipulation — &lt;tt&gt;sapi_string.h&lt;/tt&gt; (ADR-006)',['../safeapi_srs.html#autotoc_md476',1,'']]],
  ['bring_20up_47',['ADR-035: &lt;tt&gt;sapi_platform&lt;/tt&gt; OAL service for real-time bring-up',['../md_docs_2architecture_2ADR-035-platform-realtime-init.html',1,'']]],
  ['broadcast_48',['Send Semantics (Atomic Broadcast)',['../vital_channel_architecture.html#vital_channel_architecture_send_semantics',1,'']]],
  ['broker_20an_20a_20b↔c_20util_20channel_49',['ADR-038: Status indication - a C-side pub/sub broker + an A/B↔C util channel',['../md_docs_2architecture_2ADR-038-status-indication-and-c-pubsub-broker.html',1,'']]],
  ['broker_20c_20hosted_20by_20the_20status_20service_50',['2. The broker - C++, hosted by the status service',['../md_docs_2architecture_2ADR-038-status-indication-and-c-pubsub-broker.html#autotoc_md360',1,'']]],
  ['buf_51',['buf',['../structsapi__string__t.html#a6729d6bc50603d43ef507ef8b253eaa5',1,'sapi_string_t']]],
  ['buffer_52',['buffer',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md27',1,'2.2 No integrity metadata on the generic buffer'],['../buffer_user_guide.html#buffer_user_guide_qs_use',1,'3. Use Buffer'],['../group__BUFFER.html',1,'Cross-Layer Data Buffer'],['../buffer_user_guide.html#buffer_user_guide_example_message',1,'Example 1: Fixed-Size Message Buffer'],['../checksum_architecture.html#checksum_architecture_performance',1,'O(n) Per Buffer'],['../log_architecture.html#log_architecture_storage',1,'Ring Buffer'],['../buffer_user_guide.html#buffer_user_guide_overview',1,'What is a Buffer?']]],
  ['buffer_20—_20tt_20sapi_5fbuffer_20h_20tt_20adr_20002_53',['1.3 Cross-layer data buffer — &lt;tt&gt;sapi_buffer.h&lt;/tt&gt; (ADR-002)',['../safeapi_srs.html#autotoc_md472',1,'']]],
  ['buffer_20abstraction_54',['ADR-002: Cross-Layer Data Buffer Abstraction',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html',1,'']]],
  ['buffer_20access_55',['ADR-006: Safe String Manipulation and Endianness-Safe Buffer Access',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html',1,'']]],
  ['buffer_20design_56',['View-Based Buffer Design',['../buffer_architecture.html#buffer_architecture_overview',1,'']]],
  ['buffer_20endianness_20helpers_3a_20explicit_20per_20call_20no_20default_57',['2.5 Buffer endianness helpers: explicit per call, no default',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md71',1,'']]],
  ['buffer_20module_20architecture_58',['Buffer Module - Architecture',['../buffer_architecture.html',1,'']]],
  ['buffer_20module_20user_20guide_59',['Buffer Module - User Guide',['../buffer_user_guide.html',1,'']]],
  ['buffer_20operations_60',['Buffer Operations',['../buffer_user_guide.html#buffer_user_guide_operations',1,'']]],
  ['buffer_20view_61',['2. Bind Buffer View',['../buffer_user_guide.html#buffer_user_guide_qs_init',1,'']]],
  ['buffer_20without_20malloc_62',['Example 2: Ring Buffer Without malloc',['../memory_user_guide.html#memory_user_guide_example_ringbuf',1,'']]],
  ['buffers_63',['Pattern 1: Static Global Buffers',['../memory_user_guide.html#memory_user_guide_pattern_global',1,'']]],
  ['bug_20fixed_64',['2.2 &lt;tt&gt;sapi_voter&lt;/tt&gt; (new) - N-way voting, with the majority-vote bug fixed',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md227',1,'']]],
  ['bug_3a_20the_20cyclic_20executive_20starves_20whenever_20checkpoint_20is_20paused_65',['2.4 The real bug: the cyclic executive starves whenever checkpoint is paused',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md264',1,'']]],
  ['bugs_66',['2.5 The real debugging story: three genuine synchronization bugs',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html#autotoc_md276',1,'']]],
  ['build_67',['build',['../md_docs_2CROSS__COMPILATION.html#autotoc_md437',1,'1. Native Linux Build'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md438',1,'2. Linux Release Build'],['../md_docs_2architecture_2ADR-038-status-indication-and-c-pubsub-broker.html#autotoc_md364',1,'6. Language / build']]],
  ['build_20configuration_20adr_20024_68',['2.8 Build configuration (ADR-024)',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html#autotoc_md233',1,'']]],
  ['build_20diagrams_20locally_69',['Build Diagrams Locally',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md410',1,'']]],
  ['build_20diversity_70',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['build_20for_20qnx_71',['3. Build for QNX',['../md_docs_2CROSS__COMPILATION.html#autotoc_md447',1,'']]],
  ['build_20instructions_72',['Detailed Build Instructions',['../md_docs_2CROSS__COMPILATION.html#autotoc_md435',1,'']]],
  ['build_20integration_73',['2.4 Build integration',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md161',1,'']]],
  ['build_20structure_74',['5. Directory / build structure',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md20',1,'']]],
  ['build_5farrival_5fmessage_75',['build_arrival_message',['../sapi__checkpoint_8c.html#a6eafe59042730a3fc0070b367f6148da',1,'sapi_checkpoint.c']]],
  ['building_76',['Building',['../index.html#autotoc_md2',1,'']]],
  ['building_20diagrams_20locally_77',['Building Diagrams Locally',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md373',1,'']]],
  ['builds_20sapi_20example_20app_20layer_78',['Multi-Architecture Docker Builds (SAPI example app layer)',['../md_docs_2CROSS__COMPILATION.html#autotoc_md442',1,'']]],
  ['built_20in_20checkpoint_20rendezvous_79',['ADR-019: AppManager Cycle Hooks and Built-In Checkpoint Rendezvous',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html',1,'']]],
  ['built_20just_20surfaced_80',['2.2 Negotiation link: HOT/COLD standby readiness (already built, just surfaced)',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html#autotoc_md262',1,'']]],
  ['but_20one_20container_20per_20site_20hosting_20the_20service_20processes_81',['2. Per-site, but one container per site hosting the service processes',['../md_docs_2architecture_2ADR-037-role-c-gateway-decomposition.html#autotoc_md348',1,'']]],
  ['by_20default_82',['Pattern 2: Fail-Safe-by-Default',['../safestate_user_guide.html#safestate_user_guide_pattern_failsafe',1,'']]],
  ['by_20the_20status_20service_83',['2. The broker - C++, hosted by the status service',['../md_docs_2architecture_2ADR-038-status-indication-and-c-pubsub-broker.html#autotoc_md360',1,'']]],
  ['by_20this_20adr_84',['2.6 Deliberately not addressed by this ADR',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html#autotoc_md255',1,'']]]
];
