var searchData=
[
  ['data_0',['data',['../structsapi__const__buffer__t.html#a66ae8d44be021d86bda751afcbbf8855',1,'sapi_const_buffer_t::data'],['../structsapi__buffer__t.html#aca6b9e3238bd0b9b327a754a8375c383',1,'sapi_buffer_t::data'],['../buffer_user_guide.html#buffer_user_guide_op_read',1,'Read Data'],['../buffer_user_guide.html#buffer_user_guide_op_write',1,'Write Data']]],
  ['data_20buffer_1',['Cross-Layer Data Buffer',['../group__BUFFER.html',1,'']]],
  ['data_20buffer_20abstraction_2',['ADR-002: Cross-Layer Data Buffer Abstraction',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html',1,'']]],
  ['data_20integrity_20for_20redundant_20channels_3',['ADR-016: CRC-64 Data Integrity for Redundant Channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'']]],
  ['deadline_5fms_4',['deadline_ms',['../structsapi__watchdog__s.html#aee1cf316eb87f01595fcc3060d391eb7',1,'sapi_watchdog_s']]],
  ['decision_5',['decision',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md66',1,'2. Decision'],['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md25',1,'2. Decision'],['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md33',1,'2. Decision'],['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md44',1,'2. Decision'],['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md56',1,'2. Decision'],['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md76',1,'2. Decision'],['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md84',1,'2. Decision'],['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md149',1,'2. Decision'],['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md157',1,'2. Decision'],['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md12',1,'3. Decision'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md97',1,'Decision']]],
  ['decision_20tree_6',['Transport Selection Decision Tree',['../ipc_transport_selection.html#ipc_transport_selection_decision_tree',1,'']]],
  ['decisions_7',['Key Design Decisions',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md101',1,'']]],
  ['default_8',['default',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md71',1,'2.5 Buffer endianness helpers: explicit per call, no default'],['../watchdog_user_guide.html#watchdog_user_guide_pattern_conditional',1,'Pattern 1: Conditional Kick (Fail-Safe Default)'],['../safestate_user_guide.html#safestate_user_guide_pattern_failsafe',1,'Pattern 2: Fail-Safe-by-Default']]],
  ['defensively_9',['2.4 &quot;Does not return&quot;, enforced defensively',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md48',1,'']]],
  ['definitions_10',['Status Code Definitions',['../status_architecture.html#status_architecture_status_codes',1,'']]],
  ['degradation_11',['Example 2: Graceful Degradation',['../safestate_user_guide.html#safestate_user_guide_example_degraded',1,'']]],
  ['degraded_20level_200_12',['DEGRADED (Level 0)',['../safestate_user_guide.html#safestate_user_guide_level_degraded',1,'']]],
  ['deliberately_20doesn_20t_13',['2.3 What &quot;real&quot; means here, and what it deliberately doesn&apos;t',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md160',1,'']]],
  ['deploy_20to_20qnx_20target_14',['4. Deploy to QNX Target',['../md_docs_2CROSS__COMPILATION.html#autotoc_md241',1,'']]],
  ['deployment_20diagram_20structural_15',['5. Deployment Diagram (Structural)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md194',1,'']]],
  ['design_16',['View-Based Buffer Design',['../buffer_architecture.html#buffer_architecture_overview',1,'']]],
  ['design_20decisions_17',['Key Design Decisions',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md101',1,'']]],
  ['design_20guidelines_18',['Design Guidelines',['../appmanager_integration.html#appmanager_integration_guidelines',1,'']]],
  ['design_20overview_19',['design overview',['../safestate_architecture.html#safestate_architecture_overview',1,'Design Overview'],['../status_architecture.html#status_architecture_overview',1,'Design Overview'],['../reboot_architecture.html#reboot_architecture_overview',1,'Design Overview'],['../timer_architecture.html#timer_architecture_overview',1,'Design Overview'],['../watchdog_architecture.html#watchdog_architecture_overview',1,'Design Overview']]],
  ['design_20principles_20',['design principles',['../ipc_guide.html#ipc_guide_design_principles',1,'Design Principles'],['../index.html#autotoc_md8',1,'Design principles']]],
  ['design_20rationale_21',['Design Rationale',['../status_architecture.html#status_architecture_rationale',1,'']]],
  ['despite_20the_20directory_20change_22',['2.3 What stays true from earlier ADRs despite the directory change',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md79',1,'']]],
  ['destroy_23',['destroy',['../structsapi__timer__backend__t.html#a514ff77645947eb4877ab8b295516ad5',1,'sapi_timer_backend_t::destroy'],['../structsapi__ipc__backend__t.html#adc9f5300072df3ee32fcac083d96921f',1,'sapi_ipc_backend_t::destroy'],['../structsapi__task__backend__t.html#aef93025473130272adec58f2b5eabb7c',1,'sapi_task_backend_t::destroy']]],
  ['detailed_20build_20instructions_24',['Detailed Build Instructions',['../md_docs_2CROSS__COMPILATION.html#autotoc_md230',1,'']]],
  ['details_25',['Implementation Details',['../status_architecture.html#status_architecture_implementation',1,'']]],
  ['detection_26',['detection',['../reboot_user_guide.html#reboot_user_guide_example_memory',1,'Example 2: Memory Corruption Detection'],['../safestate_user_guide.html#safestate_user_guide_example_assertion',1,'Example 3: Assertion-Based Fault Detection'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md113',1,'Random vs Systematic Error Detection']]],
  ['diagnostic_20only_20never_20the_20basis_20of_20correctness_27',['2.3 &lt;tt&gt;sapi_clocksync&lt;/tt&gt;: diagnostic only, never the basis of correctness',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md152',1,'']]],
  ['diagnostic_20timeout_20sizing_20only_28',['Clock Synchronization (diagnostic/timeout-sizing only)',['../group__CLOCKSYNC.html',1,'']]],
  ['diagnostics_29',['Logging and Diagnostics',['../group__LOG.html',1,'']]],
  ['diagram_20behavioral_30',['4. State Machine Diagram (Behavioral)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md192',1,'']]],
  ['diagram_20behavioral_20checkpoint_20flow_31',['6. Activity Diagram (Behavioral - Checkpoint Flow)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md196',1,'']]],
  ['diagram_20behavioral_20ipc_32',['2. Sequence Diagram (Behavioral - IPC)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md188',1,'']]],
  ['diagram_20behavioral_20redundancy_33',['3. Sequence Diagram (Behavioral - Redundancy)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md190',1,'']]],
  ['diagram_20index_34',['Diagram Index',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md165',1,'']]],
  ['diagram_20locations_35',['Diagram Locations',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md203',1,'']]],
  ['diagram_20patterns_20for_20safety_20critical_20systems_36',['Common Diagram Patterns for Safety-Critical Systems',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md217',1,'']]],
  ['diagram_20scope_37',['1. Diagram Scope',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md212',1,'']]],
  ['diagram_20structural_38',['diagram structural',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md186',1,'1. Component Diagram (Structural)'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md194',1,'5. Deployment Diagram (Structural)']]],
  ['diagram_20types_20examples_39',['Diagram Types &amp; Examples',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md185',1,'']]],
  ['diagram_3a_40',['Generate single diagram:',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md171',1,'']]],
  ['diagrams_41',['diagrams',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md166',1,'Structural Diagrams'],['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md174',1,'Updating Diagrams']]],
  ['diagrams_20as_20png_3a_42',['Generate all diagrams as PNG:',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md169',1,'']]],
  ['diagrams_20as_20svg_20vector_20_3a_43',['Generate all diagrams as SVG (vector):',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md170',1,'']]],
  ['diagrams_20configuration_20sequences_44',['Behavioral Diagrams - Configuration Sequences',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md167',1,'']]],
  ['diagrams_20in_20doxygen_20comments_45',['Embedding Diagrams in Doxygen Comments',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md198',1,'']]],
  ['diagrams_20locally_46',['diagrams locally',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md205',1,'Build Diagrams Locally'],['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md168',1,'Building Diagrams Locally']]],
  ['diagrams_20with_20plantuml_20doxygen_47',['Architecture Diagrams with PlantUML &amp; Doxygen',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html',1,'']]],
  ['directly_48',['2.3 Why &lt;tt&gt;sapi_safestate&lt;/tt&gt; does not call &lt;tt&gt;sapi_reboot&lt;/tt&gt; directly',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md47',1,'']]],
  ['directory_20build_20structure_49',['5. Directory / build structure',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md20',1,'']]],
  ['directory_20change_50',['2.3 What stays true from earlier ADRs despite the directory change',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md79',1,'']]],
  ['directory_20layout_51',['ADR-007: Per-Feature Directory Layout',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html',1,'']]],
  ['disagreement_5fcount_52',['disagreement_count',['../structsapi__vital__channel__health__t.html#abcdced25d8ee33a902b77c5c2e9edba8',1,'sapi_vital_channel_health_t']]],
  ['dispatch_20c_20redesign_53',['2.4 Why this isn&apos;t a virtual-dispatch / C++ redesign',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md60',1,'']]],
  ['dispatcher_20callback_20pattern_54',['Dispatcher Callback Pattern',['../channel_configuration.html#channel_configuration_dispatcher_callback',1,'']]],
  ['distributed_202oo2_20a_20↔_20b_20across_20network_55',['Pattern 2: Distributed 2oo2 (A ↔ B Across Network)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_distributed_2oo2',1,'']]],
  ['distributed_20vital_20channels_56',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['diverse_20compilation_20not_20diverse_20hardware_57',['2.1 Primary mitigation: diverse compilation, not diverse hardware',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md85',1,'']]],
  ['diversity_58',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['docs_59',['3. Generate Docs',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md183',1,'']]],
  ['documentation_60',['documentation',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md138',1,'API Documentation'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md139',1,'Architectural Documentation'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md140',1,'Certification Documentation'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md137',1,'Documentation']]],
  ['documented_20not_20implied_61',['2.3 CCF analysis is documented, not implied',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md87',1,'']]],
  ['documents_62',['In ADR Documents',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md201',1,'']]],
  ['does_20not_20call_20tt_20sapi_5freboot_20tt_20directly_63',['2.3 Why &lt;tt&gt;sapi_safestate&lt;/tt&gt; does not call &lt;tt&gt;sapi_reboot&lt;/tt&gt; directly',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md47',1,'']]],
  ['does_20not_20return_20enforced_20defensively_64',['2.4 &quot;Does not return&quot;, enforced defensively',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md48',1,'']]],
  ['doesn_20t_65',['2.3 What &quot;real&quot; means here, and what it deliberately doesn&apos;t',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md160',1,'']]],
  ['don_20t_20rebuild_20it_66',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['doxygen_67',['doxygen',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md182',1,'2. Configure Doxygen'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html',1,'Architecture Diagrams with PlantUML &amp; Doxygen'],['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md173',1,'Using in Doxygen']]],
  ['doxygen_20comments_68',['Embedding Diagrams in Doxygen Comments',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md198',1,'']]],
  ['doxygen_20configuration_69',['Doxygen Configuration',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md207',1,'']]],
  ['dropped_20not_20renamed_70',['2.1 The &lt;tt&gt;common&lt;/tt&gt;/&lt;tt&gt;os&lt;/tt&gt; grouping folder is dropped, not renamed',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md77',1,'']]],
  ['dual_20channel_71',['2oo2 (Dual-Channel)',['../vital_channel_user_guide.html#vital_channel_user_guide_ss_2oo2',1,'']]],
  ['dual_20channel_20identity_20and_20comparison_72',['Dual-Channel Identity and Comparison',['../group__CHANNEL.html',1,'']]],
  ['dual_20channel_20vital_20architecture_20—_20ccf_20mitigation_20via_20build_20diversity_73',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['dual_20redundant_20cpu_74',['Quick Start: 2oo2 Dual-Redundant CPU',['../vital_channel_user_guide.html#vital_channel_user_guide_quick_start',1,'']]],
  ['dynamic_20allocation_75',['dynamic allocation',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md16',1,'3.4 Handle pattern (no dynamic allocation)'],['../memory_user_guide.html#memory_user_guide_rationale',1,'Why No Dynamic Allocation?']]]
];
