var searchData=
[
  ['identity_0',['2.2 New feature: &lt;tt&gt;sapi_channel&lt;/tt&gt; (comparator + identity)',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md86',1,'']]],
  ['identity_20and_20comparison_1',['Dual-Channel Identity and Comparison',['../group__CHANNEL.html',1,'']]],
  ['impact_2',['Real-World Impact',['../memory_user_guide.html#memory_user_guide_rationale_example',1,'']]],
  ['implement_3',['What You Need to Implement',['../appmanager_integration.html#appmanager_integration_you_implement',1,'']]],
  ['implement_20callback_4',['3. Implement Callback',['../timer_user_guide.html#timer_user_guide_qs_callback',1,'']]],
  ['implementation_5',['implementation',['../nvm_architecture.html#nvm_architecture_backend',1,'Backend Implementation'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md99',1,'Implementation'],['../safestate_architecture.html#safestate_architecture_assert',1,'SAPI_ASSERT Implementation']]],
  ['implementation_20checklist_6',['Implementation Checklist',['../ipc_transport_selection.html#ipc_transport_selection_implementation_checklist',1,'']]],
  ['implementation_20details_7',['Implementation Details',['../status_architecture.html#status_architecture_implementation',1,'']]],
  ['implementation_20pattern_8',['Backend Implementation Pattern',['../ipc_transport_selection.html#ipc_transport_selection_backend_vtable',1,'']]],
  ['implementation_20responsibility_9',['Implementation Responsibility',['../channel_configuration.html#channel_configuration_implementation_by_integrator',1,'']]],
  ['implementation_20timeline_10',['Implementation Timeline',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md119',1,'']]],
  ['implications_11',['SIL Implications',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md115',1,'']]],
  ['implied_12',['2.3 CCF analysis is documented, not implied',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md87',1,'']]],
  ['in_20adr_20documents_13',['In ADR Documents',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md201',1,'']]],
  ['in_20doxygen_14',['Using in Doxygen',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md173',1,'']]],
  ['in_20doxygen_20comments_15',['Embedding Diagrams in Doxygen Comments',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md198',1,'']]],
  ['in_20framework_16',['Usage Patterns in Framework',['../status_architecture.html#status_architecture_usage_patterns',1,'']]],
  ['in_20header_20files_17',['In Header Files',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md199',1,'']]],
  ['in_20markdown_20files_18',['In Markdown Files',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md200',1,'']]],
  ['in_20your_20application_19',['4. Use in Your Application',['../md_docs_2CROSS__COMPILATION.html#autotoc_md235',1,'']]],
  ['in_20your_20qnx_20application_20',['5. Use in Your QNX Application',['../md_docs_2CROSS__COMPILATION.html#autotoc_md242',1,'']]],
  ['in_5fuse_21',['in_use',['../structsapi__watchdog__s.html#a00a99f33928204f56a499f1a1dfe420b',1,'sapi_watchdog_s']]],
  ['include_20header_22',['include header',['../types_user_guide.html#types_user_guide_qs_include',1,'1. Include Header'],['../watchdog_user_guide.html#watchdog_user_guide_qs_include',1,'1. Include Header'],['../memory_user_guide.html#memory_user_guide_qs_include',1,'1. Include Header']]],
  ['including_20widening_23',['2.1 Scope: every ordered pair, including widening',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md34',1,'']]],
  ['index_24',['Diagram Index',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md165',1,'']]],
  ['indirection_25',['3.5 Backend indirection',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md17',1,'']]],
  ['init_26',['init',['../structsapi__appmanager__operations__t.html#a1f03aa6489eaf45e7ef8c29044af48b1',1,'sapi_appmanager_operations_t::init'],['../structsapi__log__backend__t.html#a66b725b77e2efc07a0f09b3e9ed052f2',1,'sapi_log_backend_t::init']]],
  ['initialization_27',['initialization',['../memory_user_guide.html#memory_user_guide_qs_allocate',1,'2. Allocate at Compile-Time or Initialization'],['../checksum_architecture.html#checksum_architecture_init',1,'Initialization']]],
  ['initialize_28',['Initialize',['../buffer_user_guide.html#buffer_user_guide_op_init',1,'']]],
  ['initialized_29',['initialized',['../structsapi__checksum__manager__t.html#afa22104aa013495742494d340f35f4c1',1,'sapi_checksum_manager_t']]],
  ['input_30',['2.2 Never call &lt;tt&gt;strlen()&lt;/tt&gt; on unbounded/untrusted input',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md68',1,'']]],
  ['inside_20each_20service_20s_20fixed_20opaque_20storage_31',['2.2 Fitting inside each service&apos;s fixed opaque storage',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md159',1,'']]],
  ['install_20plantuml_32',['1. Install PlantUML',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md181',1,'']]],
  ['install_20to_20system_33',['3. Install to System',['../md_docs_2CROSS__COMPILATION.html#autotoc_md234',1,'']]],
  ['instead_20of_20macros_20or_20c11_20tt_20_5fgeneric_20tt_34',['2.5 Why named functions instead of macros or C11 &lt;tt&gt;_Generic&lt;/tt&gt;',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md38',1,'']]],
  ['instructions_35',['Detailed Build Instructions',['../md_docs_2CROSS__COMPILATION.html#autotoc_md230',1,'']]],
  ['integer_20casting_36',['integer casting',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html',1,'ADR-003: Checked Integer Casting'],['../group__CAST.html',1,'Checked Integer Casting']]],
  ['integration_37',['integration',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md161',1,'2.4 Build integration'],['../vital_channel_architecture.html#vital_channel_architecture_integration',1,'Application Integration'],['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md209',1,'CI/CD Integration']]],
  ['integration_20architecture_38',['Integration Architecture',['../appmanager_integration.html#appmanager_integration_architecture',1,'']]],
  ['integration_20points_39',['Integration Points',['../safestate_architecture.html#safestate_architecture_integration',1,'']]],
  ['integration_20tests_40',['Integration Tests',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md134',1,'']]],
  ['integration_20v0_204_200_41',['Phase 2: Integration (v0.4.0)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md121',1,'']]],
  ['integration_20with_20channels_42',['App Manager Integration with Channels',['../appmanager_integration.html',1,'']]],
  ['integration_20with_20safe_20state_43',['integration with safe state',['../reboot_user_guide.html#reboot_user_guide_integration',1,'Integration with Safe-State'],['../status_architecture.html#status_architecture_safestate',1,'Integration with Safe-State'],['../watchdog_architecture.html#watchdog_architecture_integration',1,'Integration with Safe-State']]],
  ['integration_20with_20vital_20channel_44',['Integration with Vital Channel',['../ipc_transport_selection.html#ipc_transport_selection_vital_channel_integration',1,'']]],
  ['integration_5fguide_45',['INTEGRATION_GUIDE',['../md_include_2safeapi_2appmanager_2INTEGRATION__GUIDE.html',1,'']]],
  ['integrity_20for_20redundant_20channels_46',['ADR-016: CRC-64 Data Integrity for Redundant Channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'']]],
  ['integrity_20level_3a_20sil_203_204_47',['3.2 Target integrity level: SIL 3/4',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md14',1,'']]],
  ['integrity_20metadata_20on_20the_20generic_20buffer_48',['2.2 No integrity metadata on the generic buffer',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html#autotoc_md27',1,'']]],
  ['inter_20process_20communication_49',['Inter-Process Communication',['../group__IPC.html',1,'']]],
  ['inter_20process_20communication_20guide_50',['IPC (Inter-Process Communication) Guide',['../ipc_guide.html',1,'']]],
  ['inter_20process_20communication_20ipc_20transport_20layer_51',['Inter-Process Communication (IPC) Transport Layer',['../ipc_transport_selection.html#ipc_transport_selection_overview',1,'']]],
  ['interface_52',['interface',['../reboot_architecture.html#reboot_architecture_backend',1,'Backend Interface'],['../nvm_architecture.html#nvm_architecture_api',1,'Read/Write Interface']]],
  ['interface_20style_3a_20pure_20c_20abi_53',['3.1 Interface style: pure C ABI',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md13',1,'']]],
  ['invariants_54',['Invariants',['../buffer_architecture.html#buffer_architecture_invariants',1,'']]],
  ['invocation_55',['invocation',['../index.html#autotoc_md5',1,'Manual CMake invocation'],['../safestate_architecture.html#safestate_architecture_test_handler',1,'Test 1: Handler Registration and Invocation']]],
  ['ip_20transport_56',['TCP/IP Transport',['../ipc_transport_selection.html#ipc_transport_selection_tcp_ip',1,'']]],
  ['ipc_57',['2. Sequence Diagram (Behavioral - IPC)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md188',1,'']]],
  ['ipc_20architecture_20layers_58',['IPC Architecture Layers',['../ipc_guide.html#ipc_guide_layers',1,'']]],
  ['ipc_20inter_20process_20communication_20guide_59',['IPC (Inter-Process Communication) Guide',['../ipc_guide.html',1,'']]],
  ['ipc_20transport_20layer_60',['Inter-Process Communication (IPC) Transport Layer',['../ipc_transport_selection.html#ipc_transport_selection_overview',1,'']]],
  ['ipc_20transport_20selection_20guide_61',['IPC Transport Selection Guide',['../ipc_transport_selection.html',1,'']]],
  ['ipc_5fguide_62',['IPC_GUIDE',['../md_include_2safeapi_2ipc_2IPC__GUIDE.html',1,'']]],
  ['ipc_5ftransport_5fselection_63',['IPC_TRANSPORT_SELECTION',['../md_include_2safeapi_2ipc_2IPC__TRANSPORT__SELECTION.html',1,'']]],
  ['is_20a_20buffer_64',['What is a Buffer?',['../buffer_user_guide.html#buffer_user_guide_overview',1,'']]],
  ['is_20a_20timer_65',['What is a Timer?',['../timer_user_guide.html#timer_user_guide_overview',1,'']]],
  ['is_20always_20active_66',['2.5 &lt;tt&gt;SAPI_ASSERT&lt;/tt&gt; is always active',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md49',1,'']]],
  ['is_20checksum_67',['What is Checksum?',['../checksum_user_guide.html#checksum_user_guide_overview',1,'']]],
  ['is_20documented_20not_20implied_68',['2.3 CCF analysis is documented, not implied',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html#autotoc_md87',1,'']]],
  ['is_20dropped_20not_20renamed_69',['2.1 The &lt;tt&gt;common&lt;/tt&gt;/&lt;tt&gt;os&lt;/tt&gt; grouping folder is dropped, not renamed',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md77',1,'']]],
  ['is_20logging_70',['What is Logging?',['../log_user_guide.html#log_user_guide_overview',1,'']]],
  ['is_20nvm_71',['What is NVM?',['../nvm_user_guide.html#nvm_user_guide_overview',1,'']]],
  ['is_20reboot_72',['What is Reboot?',['../reboot_user_guide.html#reboot_user_guide_overview',1,'']]],
  ['is_20reentrant_20unlike_20tt_20strtok_20tt_73',['2.4 Splitting is reentrant, unlike &lt;tt&gt;strtok&lt;/tt&gt;',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md70',1,'']]],
  ['is_20right_20for_20sapi_74',['Why CRC-64 is Right for SAPI',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md95',1,'']]],
  ['is_20safe_20state_75',['What is Safe-State?',['../safestate_user_guide.html#safestate_user_guide_overview',1,'']]],
  ['is_20task_20queue_76',['What is Task Queue?',['../task_user_guide.html#task_user_guide_overview',1,'']]],
  ['is_20the_20cast_20module_77',['What is the Cast Module?',['../cast_user_guide.html#cast_user_guide_overview',1,'']]],
  ['is_20the_20memory_20module_78',['What is the Memory Module?',['../memory_user_guide.html#memory_user_guide_overview',1,'']]],
  ['is_20the_20status_20module_79',['What is the Status Module?',['../status_user_guide.html#status_user_guide_overview',1,'']]],
  ['is_20the_20string_20module_80',['What is the String Module?',['../string_user_guide.html#string_user_guide_overview',1,'']]],
  ['is_20the_20watchdog_81',['What is the Watchdog?',['../watchdog_user_guide.html#watchdog_user_guide_overview',1,'']]],
  ['is_20types_82',['What is Types?',['../types_user_guide.html#types_user_guide_overview',1,'']]],
  ['is_20vital_20channel_83',['What is Vital Channel?',['../vital_channel_user_guide.html#vital_channel_user_guide_overview',1,'']]],
  ['is_5fhealthy_84',['is_healthy',['../structsapi__vital__channel__health__t.html#a50f5df303e3aebe086ddddb3a74242ae',1,'sapi_vital_channel_health_t']]],
  ['is_5fvalid_5faction_85',['is_valid_action',['../sapi__watchdog_8c.html#ae80e4fca3c6bbb43bf990420aa97df19',1,'sapi_watchdog.c']]],
  ['is_5fvalid_5fhandle_86',['is_valid_handle',['../sapi__watchdog_8c.html#a276607429a1cd38238764fc6cd8cef70',1,'sapi_watchdog.c']]],
  ['isn_20t_20a_20virtual_20dispatch_20c_20redesign_87',['2.4 Why this isn&apos;t a virtual-dispatch / C++ redesign',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md60',1,'']]],
  ['it_88',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['it_20deliberately_20doesn_20t_89',['2.3 What &quot;real&quot; means here, and what it deliberately doesn&apos;t',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md160',1,'']]],
  ['it_20s_20correct_20without_20triggering_20tt_20wsign_20conversion_20tt_90',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]],
  ['items_91',['7. Open items',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md22',1,'']]],
  ['iteration_5fcount_92',['iteration_count',['../structsapi__appmanager__state__t.html#a86a7eec86ed0c4ec3931073735e496d3',1,'sapi_appmanager_state_t']]]
];
