var searchData=
[
  ['each_20service_20s_20fixed_20opaque_20storage_0',['2.2 Fitting inside each service&apos;s fixed opaque storage',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md159',1,'']]],
  ['earlier_20adrs_20despite_20the_20directory_20change_1',['2.3 What stays true from earlier ADRs despite the directory change',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md79',1,'']]],
  ['embedding_20diagrams_20in_20doxygen_20comments_2',['Embedding Diagrams in Doxygen Comments',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md198',1,'']]],
  ['en_2050128_20compliance_3',['EN 50128 Compliance',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md111',1,'']]],
  ['en_2050159_20envelope_20that_20already_20exists_20—_20don_20t_20rebuild_20it_4',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['endianness_20helpers_3a_20explicit_20per_20call_20no_20default_5',['2.5 Buffer endianness helpers: explicit per call, no default',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md71',1,'']]],
  ['endianness_20safe_20buffer_20access_6',['ADR-006: Safe String Manipulation and Endianness-Safe Buffer Access',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html',1,'']]],
  ['enforced_20defensively_7',['2.4 &quot;Does not return&quot;, enforced defensively',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md48',1,'']]],
  ['entering_20a_20level_8',['Entering a Level',['../safestate_architecture.html#safestate_architecture_api_enter',1,'']]],
  ['entry_9',['entry',['../structsapi__task__config__t.html#a0f2b31d8a9a183487ba731c7cd83e446',1,'sapi_task_config_t']]],
  ['entry_20format_10',['Entry Format',['../log_architecture.html#log_architecture_format',1,'']]],
  ['envelope_20that_20already_20exists_20—_20don_20t_20rebuild_20it_11',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['environment_20variables_12',['2. Set Environment Variables',['../md_docs_2CROSS__COMPILATION.html#autotoc_md239',1,'']]],
  ['error_13',['2. Request Reboot on Critical Error',['../reboot_user_guide.html#reboot_user_guide_qs_request',1,'']]],
  ['error_20codes_14',['Common Status and Error Codes',['../group__STATUS.html',1,'']]],
  ['error_20detection_15',['Random vs Systematic Error Detection',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md113',1,'']]],
  ['error_20handling_16',['3.6 Error handling',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html#autotoc_md18',1,'']]],
  ['error_20handling_20patterns_17',['Error Handling Patterns',['../status_user_guide.html#status_user_guide_error_handling',1,'']]],
  ['error_5fcount_18',['error_count',['../structsapi__appmanager__state__t.html#ae5a611fc818cbc7d59fce546d049a9f1',1,'sapi_appmanager_state_t']]],
  ['error_5fthreshold_19',['error_threshold',['../structsapi__appmanager__config__t.html#a5ea836b854f51d6062bf60cc97222d0b',1,'sapi_appmanager_config_t']]],
  ['errors_20',['&quot;Compiler warnings treated as errors&quot;',['../md_docs_2CROSS__COMPILATION.html#autotoc_md256',1,'']]],
  ['etc_21',['Cross-Compilation (Linux, QNX, etc.)',['../index.html#autotoc_md4',1,'']]],
  ['every_20ordered_20pair_20including_20widening_22',['2.1 Scope: every ordered pair, including widening',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md34',1,'']]],
  ['example_23',['example',['../vital_channel_architecture.html#vital_channel_architecture_communication_flow',1,'Communication Flow (2oo2 Example)'],['../appmanager_integration.html#appmanager_integration_complete_example',1,'Complete Example']]],
  ['example_201_3a_20fixed_20size_20message_20buffer_24',['Example 1: Fixed-Size Message Buffer',['../buffer_user_guide.html#buffer_user_guide_example_message',1,'']]],
  ['example_201_3a_20periodic_20heartbeat_25',['Example 1: Periodic Heartbeat',['../timer_user_guide.html#timer_user_guide_example_periodic',1,'']]],
  ['example_201_3a_20redundant_20channel_20voting_20failure_26',['Example 1: Redundant Channel Voting Failure',['../safestate_user_guide.html#safestate_user_guide_example_voting',1,'']]],
  ['example_201_3a_20system_20watchdog_20main_20loop_20heartbeat_27',['Example 1: System Watchdog (Main Loop Heartbeat)',['../watchdog_user_guide.html#watchdog_user_guide_example_system',1,'']]],
  ['example_201_3a_20train_20control_20system_28',['Example 1: Train Control System',['../memory_user_guide.html#memory_user_guide_example_train',1,'']]],
  ['example_201_3a_20type_20safe_20structure_29',['Example 1: Type-Safe Structure',['../types_user_guide.html#types_user_guide_example_struct',1,'']]],
  ['example_201_3a_20watchdog_20triggered_20reboot_30',['Example 1: Watchdog-Triggered Reboot',['../reboot_user_guide.html#reboot_user_guide_example_watchdog',1,'']]],
  ['example_202_3a_20custom_20callback_20on_20timeout_31',['Example 2: Custom Callback on Timeout',['../watchdog_user_guide.html#watchdog_user_guide_example_custom',1,'']]],
  ['example_202_3a_20graceful_20degradation_32',['Example 2: Graceful Degradation',['../safestate_user_guide.html#safestate_user_guide_example_degraded',1,'']]],
  ['example_202_3a_20memory_20corruption_20detection_33',['Example 2: Memory Corruption Detection',['../reboot_user_guide.html#reboot_user_guide_example_memory',1,'']]],
  ['example_202_3a_20one_20shot_20timeout_34',['Example 2: One-Shot Timeout',['../timer_user_guide.html#timer_user_guide_example_oneshot',1,'']]],
  ['example_202_3a_20read_20only_20view_35',['Example 2: Read-Only View',['../buffer_user_guide.html#buffer_user_guide_example_ringbuf',1,'']]],
  ['example_202_3a_20ring_20buffer_20without_20malloc_36',['Example 2: Ring Buffer Without malloc',['../memory_user_guide.html#memory_user_guide_example_ringbuf',1,'']]],
  ['example_202_3a_20sized_20counters_37',['Example 2: Sized Counters',['../types_user_guide.html#types_user_guide_example_counter',1,'']]],
  ['example_203_3a_20assertion_20based_20fault_20detection_38',['Example 3: Assertion-Based Fault Detection',['../safestate_user_guide.html#safestate_user_guide_example_assertion',1,'']]],
  ['example_203_3a_20reboot_20with_20fallback_39',['Example 3: Reboot with Fallback',['../reboot_user_guide.html#reboot_user_guide_example_fallback',1,'']]],
  ['examples_40',['examples',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md185',1,'Diagram Types &amp; Examples'],['../memory_user_guide.html#memory_user_guide_examples',1,'Practical Examples'],['../reboot_user_guide.html#reboot_user_guide_examples',1,'Practical Examples'],['../buffer_user_guide.html#buffer_user_guide_examples',1,'Practical Examples'],['../cast_user_guide.html#cast_user_guide_examples',1,'Practical Examples'],['../checksum_user_guide.html#checksum_user_guide_examples',1,'Practical Examples'],['../status_user_guide.html#status_user_guide_examples',1,'Practical Examples'],['../string_user_guide.html#string_user_guide_examples',1,'Practical Examples'],['../timer_user_guide.html#timer_user_guide_examples',1,'Practical Examples'],['../types_user_guide.html#types_user_guide_examples',1,'Practical Examples'],['../safestate_user_guide.html#safestate_user_guide_examples',1,'Practical Examples'],['../watchdog_user_guide.html#watchdog_user_guide_examples',1,'Practical Examples'],['../ipc_guide.html#ipc_guide_examples',1,'Quick Examples'],['../vital_channel_architecture.html#vital_channel_architecture_examples',1,'Usage Examples']]],
  ['execute_41',['execute',['../structsapi__appmanager__operations__t.html#a5f5e8440cd3b527558aa00b3c3adaad4',1,'sapi_appmanager_operations_t']]],
  ['executes_42',['2.2 The framework still validates; the backend only executes',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md58',1,'']]],
  ['existing_20approaches_43',['Existing Approaches',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md94',1,'']]],
  ['existing_20modules_44',['With Existing Modules',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md109',1,'']]],
  ['exists_20—_20don_20t_20rebuild_20it_45',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['expected_46',['expected',['../structsapi__checksum__result__t.html#a35b67972c86205128fb8fd0bd8edd965',1,'sapi_checksum_result_t']]],
  ['expected_5fnode_5fcount_47',['expected_node_count',['../structsapi__checkpoint__config__t.html#a499e6cc24cad2ce3424df0010f79a3b1',1,'sapi_checkpoint_config_t']]],
  ['explicit_20per_20call_20no_20default_48',['2.5 Buffer endianness helpers: explicit per call, no default',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md71',1,'']]],
  ['explicitly_49',['3. Trigger Safe-State Explicitly',['../safestate_user_guide.html#safestate_user_guide_qs_trigger',1,'']]],
  ['extensions_50',['Future Extensions',['../status_architecture.html#status_architecture_future',1,'']]]
];
