var searchData=
[
  ['random_20vs_20systematic_20error_20detection_0',['Random vs Systematic Error Detection',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md113',1,'']]],
  ['range_20check_20algorithm_20why_20it_20s_20correct_20without_20triggering_20tt_20wsign_20conversion_20tt_1',['2.3 Range-check algorithm (why it&apos;s correct without triggering &lt;tt&gt;-Wsign-conversion&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html#autotoc_md36',1,'']]],
  ['ranges_2',['Type Ranges',['../types_user_guide.html#types_user_guide_ranges',1,'']]],
  ['rationale_3',['Design Rationale',['../status_architecture.html#status_architecture_rationale',1,'']]],
  ['read_4',['read',['../structsapi__nvm__backend__t.html#a946711f74b92fe96d7c0b575c95ffab6',1,'sapi_nvm_backend_t']]],
  ['read_20data_5',['Read Data',['../buffer_user_guide.html#buffer_user_guide_op_read',1,'']]],
  ['read_20only_20view_6',['Example 2: Read-Only View',['../buffer_user_guide.html#buffer_user_guide_example_ringbuf',1,'']]],
  ['read_20write_20interface_7',['Read/Write Interface',['../nvm_architecture.html#nvm_architecture_api',1,'']]],
  ['real_20means_20here_20and_20what_20it_20deliberately_20doesn_20t_8',['2.3 What &quot;real&quot; means here, and what it deliberately doesn&apos;t',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html#autotoc_md160',1,'']]],
  ['real_20posix_20linux_20oal_20backend_9',['ADR-018: A Real POSIX/Linux OAL Backend',['../md_docs_2architecture_2ADR-018-posix-oal-backend.html',1,'']]],
  ['real_20world_20impact_10',['Real-World Impact',['../memory_user_guide.html#memory_user_guide_rationale_example',1,'']]],
  ['reason_20code_20handling_11',['Reason Code Handling',['../reboot_architecture.html#reboot_architecture_reason',1,'']]],
  ['reason_20code_20strategy_12',['Reason Code Strategy',['../safestate_architecture.html#safestate_architecture_reason_codes',1,'']]],
  ['reason_20codes_13',['reason codes',['../safestate_user_guide.html#safestate_user_guide_app_reason_codes',1,'Application-Specific Reason Codes'],['../reboot_user_guide.html#reboot_user_guide_reason_codes',1,'Reason Codes']]],
  ['reasons_200_204095_14',['Framework Reasons (0-4095)',['../safestate_architecture.html#safestate_architecture_reason_framework',1,'']]],
  ['reasons_204096_15',['Application Reasons (4096+)',['../safestate_architecture.html#safestate_architecture_reason_application',1,'']]],
  ['reboot_16',['reboot',['../group__REBOOT.html',1,'Controlled Reboot'],['../reboot_user_guide.html#reboot_user_guide_example_watchdog',1,'Example 1: Watchdog-Triggered Reboot'],['../reboot_user_guide.html#reboot_user_guide_overview',1,'What is Reboot?']]],
  ['reboot_20flow_17',['Reboot Flow',['../reboot_architecture.html#reboot_architecture_flow',1,'']]],
  ['reboot_20level_202_18',['REBOOT (Level 2)',['../safestate_user_guide.html#safestate_user_guide_level_reboot',1,'']]],
  ['reboot_20module_19',['With Reboot Module',['../safestate_architecture.html#safestate_architecture_integ_reboot',1,'']]],
  ['reboot_20module_20architecture_20',['Reboot Module - Architecture',['../reboot_architecture.html',1,'']]],
  ['reboot_20module_20user_20guide_21',['Reboot Module - User Guide',['../reboot_user_guide.html',1,'']]],
  ['reboot_20on_20critical_20error_22',['2. Request Reboot on Critical Error',['../reboot_user_guide.html#reboot_user_guide_qs_request',1,'']]],
  ['reboot_20with_20fallback_23',['Example 3: Reboot with Fallback',['../reboot_user_guide.html#reboot_user_guide_example_fallback',1,'']]],
  ['rebuild_20it_24',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['receive_25',['receive',['../structsapi__ipc__backend__t.html#afaede7ddbe9ca2a0c80e6e3bd5ecc9b0',1,'sapi_ipc_backend_t::receive'],['../structsapi__netlink__backend__t.html#ad1dc5bca6bb4cb15229cebdd4340e494',1,'sapi_netlink_backend_t::receive']]],
  ['receive_20semantics_20voting_26',['Receive Semantics (Voting)',['../vital_channel_architecture.html#vital_channel_architecture_receive_semantics',1,'']]],
  ['receive_5fcount_27',['receive_count',['../structsapi__vital__channel__health__t.html#a75e793cdfb5901de5a2cec8791214678',1,'sapi_vital_channel_health_t']]],
  ['receive_5ferror_5fcount_28',['receive_error_count',['../structsapi__vital__channel__health__t.html#a835989b9369437da898ffaa4deff17e0',1,'sapi_vital_channel_health_t']]],
  ['recommended_29',['Using CMake Presets (recommended)',['../index.html#autotoc_md3',1,'']]],
  ['recommended_20configurations_30',['Recommended Configurations',['../ipc_transport_selection.html#ipc_transport_selection_recommended_configurations',1,'']]],
  ['recoveries_31',['recoveries',['../structsapi__watchdog__status__t.html#a1695a29f4470c911073b0943c4451a89',1,'sapi_watchdog_status_t::recoveries'],['../structsapi__watchdog__s.html#a3dd18e803fd5c248cb2cd68f61aa24dc',1,'sapi_watchdog_s::recoveries']]],
  ['recovery_20actions_32',['recovery actions',['../watchdog_architecture.html#watchdog_architecture_recovery',1,'Recovery Actions'],['../watchdog_user_guide.html#watchdog_user_guide_actions',1,'Recovery Actions']]],
  ['redesign_33',['2.4 Why this isn&apos;t a virtual-dispatch / C++ redesign',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md60',1,'']]],
  ['redundancy_34',['3. Sequence Diagram (Behavioral - Redundancy)',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md190',1,'']]],
  ['redundancy_202oo3_35',['Pattern 4: Triple Redundancy (2oo3)',['../vital_channel_topologies.html#vital_channel_topologies_pattern_2oo3',1,'']]],
  ['redundancy_20framework_20future_20v0_204_200_36',['With Redundancy Framework (Future v0.4.0+)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md108',1,'']]],
  ['redundancy_20patterns_37',['redundancy patterns',['../vital_channel_topologies.html',1,'Channel Topologies and Redundancy Patterns'],['../ipc_transport_selection.html#ipc_transport_selection_online_standby_patterns',1,'Online/Standby Redundancy Patterns']]],
  ['redundant_20channel_20voting_20failure_38',['Example 1: Redundant Channel Voting Failure',['../safestate_user_guide.html#safestate_user_guide_example_voting',1,'']]],
  ['redundant_20channels_39',['ADR-016: CRC-64 Data Integrity for Redundant Channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'']]],
  ['redundant_20cpu_40',['Quick Start: 2oo2 Dual-Redundant CPU',['../vital_channel_user_guide.html#vital_channel_user_guide_quick_start',1,'']]],
  ['redundant_20systems_41',['SIL 3-4 (Redundant Systems)',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md117',1,'']]],
  ['reentrant_20unlike_20tt_20strtok_20tt_42',['2.4 Splitting is reentrant, unlike &lt;tt&gt;strtok&lt;/tt&gt;',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html#autotoc_md70',1,'']]],
  ['reference_43',['reference',['../md_docs_2CROSS__COMPILATION.html#autotoc_md244',1,'CMake Presets Reference'],['../status_user_guide.html#status_user_guide_status_codes',1,'Complete Status Code Reference']]],
  ['references_44',['references',['../md_docs_2architecture_2DIAGRAMS__GUIDE.html#autotoc_md222',1,'References'],['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md144',1,'References'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md260',1,'References']]],
  ['region_5fname_45',['region_name',['../structsapi__nvm__config__t.html#a9693d58c9386ca2177eebaf3e3221e78',1,'sapi_nvm_config_t']]],
  ['region_5fsize_46',['region_size',['../structsapi__nvm__config__t.html#ab21d1d72e4be6fa34a629ec9993506fb',1,'sapi_nvm_config_t']]],
  ['register_20backend_20at_20startup_47',['1. Register Backend at Startup',['../reboot_user_guide.html#reboot_user_guide_qs_backend',1,'']]],
  ['register_20handler_20at_20startup_48',['1. Register Handler at Startup',['../safestate_user_guide.html#safestate_user_guide_qs_register',1,'']]],
  ['registered_49',['2.2 One handler per level, application-registered',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md46',1,'']]],
  ['registration_50',['Registration',['../safestate_architecture.html#safestate_architecture_api_register',1,'']]],
  ['registration_20and_20invocation_51',['Test 1: Handler Registration and Invocation',['../safestate_architecture.html#safestate_architecture_test_handler',1,'']]],
  ['registration_20function_20per_20service_52',['2.1 One backend vtable type and one registration function per service',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html#autotoc_md57',1,'']]],
  ['registration_20via_20callbacks_53',['ADR-005: OAL Backend Registration via Callbacks',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html',1,'']]],
  ['regularly_54',['4. Kick Watchdog Regularly',['../watchdog_user_guide.html#watchdog_user_guide_qs_kick',1,'']]],
  ['release_55',['release',['../structsapi__mem__pool__backend__t.html#a429ddb0bd137a23a34423187afd40b64',1,'sapi_mem_pool_backend_t']]],
  ['release_20build_56',['2. Linux Release Build',['../md_docs_2CROSS__COMPILATION.html#autotoc_md233',1,'']]],
  ['remaining_5fbudget_5fms_57',['remaining_budget_ms',['../sapi__checkpoint_8c.html#af417ffad5639f066111c166f6dcf92b9',1,'sapi_checkpoint.c']]],
  ['renamed_58',['2.1 The &lt;tt&gt;common&lt;/tt&gt;/&lt;tt&gt;os&lt;/tt&gt; grouping folder is dropped, not renamed',['../md_docs_2architecture_2ADR-007-per-feature-directory-layout.html#autotoc_md77',1,'']]],
  ['rendezvous_59',['Checkpoint Rendezvous',['../group__CHECKPOINT.html',1,'']]],
  ['rendezvous_20and_20clock_20synchronization_20for_20distributed_20vital_20channels_60',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['rendezvous_20no_20new_20transport_20backend_61',['2.2 &lt;tt&gt;sapi_checkpoint&lt;/tt&gt;: bounded rendezvous, no new transport backend',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md151',1,'']]],
  ['reply_5fconfirms_5fcheckpoint_62',['reply_confirms_checkpoint',['../sapi__checkpoint_8c.html#a543471f9296dbaf8a5eee2f432b99c75',1,'sapi_checkpoint.c']]],
  ['reply_5fsize_63',['reply_size',['../structsapi__ipc__rr__server__config__t.html#a2f360d0f68323f42a9d4cecd95a506b9',1,'sapi_ipc_rr_server_config_t::reply_size'],['../structsapi__ipc__rr__client__config__t.html#a632c1c63f0079a095de911fb4a9afa16',1,'sapi_ipc_rr_client_config_t::reply_size']]],
  ['request_64',['request',['../structsapi__reboot__backend__t.html#a9aca0dde01fe603e487ea93fcd0ca73c',1,'sapi_reboot_backend_t']]],
  ['request_20reboot_20on_20critical_20error_65',['2. Request Reboot on Critical Error',['../reboot_user_guide.html#reboot_user_guide_qs_request',1,'']]],
  ['request_5fdata_66',['request_data',['../structsapi__ipc__rr__request__t.html#ad518e14d7ee868c573418e58a3dd6619',1,'sapi_ipc_rr_request_t']]],
  ['request_5fid_67',['request_id',['../structsapi__ipc__rr__request__t.html#a2a04d70cfaceb4aae1c8433c777335d5',1,'sapi_ipc_rr_request_t']]],
  ['request_5fsize_68',['request_size',['../structsapi__ipc__rr__client__config__t.html#a8a609e301e6c525cde811610be38ec82',1,'sapi_ipc_rr_client_config_t::request_size'],['../structsapi__ipc__rr__server__config__t.html#a5103c61d3e1eeb0628583a600691b5a6',1,'sapi_ipc_rr_server_config_t::request_size'],['../structsapi__ipc__rr__request__t.html#a20ea682b09837c909a47a4cc49282378',1,'sapi_ipc_rr_request_t::request_size']]],
  ['required_69',['2-out-of-2 Voting (Perfect Agreement Required)',['../vital_channel_architecture.html#vital_channel_architecture_example_2oo2',1,'']]],
  ['required_20sizes_20upfront_70',['3. Calculate Required Sizes Upfront',['../memory_user_guide.html#memory_user_guide_qs_calculate',1,'']]],
  ['requirements_71',['requirements',['../memory_user_guide.html#memory_user_guide_sizing_calc',1,'Calculate Max Requirements'],['../vital_channel_architecture.html#vital_channel_architecture_quorum',1,'Quorum Requirements']]],
  ['reservation_72',['Static Memory Reservation',['../group__MEMORY.html',1,'']]],
  ['reserved_73',['reserved',['../structsapi__vital__message__t.html#a1d0a2edc1501f1b547ed52bbc15b7a10',1,'sapi_vital_message_t']]],
  ['resource_20model_74',['Resource Model',['../reboot_architecture.html#reboot_architecture_resource',1,'']]],
  ['resource_20sizing_75',['Resource Sizing',['../memory_user_guide.html#memory_user_guide_sizing',1,'']]],
  ['resources_76',['PlantUML Resources',['..//home/runner/work/safeAPIFreamwork/safeAPIFreamwork/docs/architecture/diagrams/README.md#autotoc_md175',1,'']]],
  ['responsibility_77',['Implementation Responsibility',['../channel_configuration.html#channel_configuration_implementation_by_integrator',1,'']]],
  ['responsibility_20summary_78',['Responsibility Summary',['../appmanager_integration.html#appmanager_integration_responsibility',1,'']]],
  ['retrieval_79',['Retrieval',['../log_architecture.html#log_architecture_retrieve',1,'']]],
  ['return_20enforced_20defensively_80',['2.4 &quot;Does not return&quot;, enforced defensively',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html#autotoc_md48',1,'']]],
  ['reuse_20the_20en_2050159_20envelope_20that_20already_20exists_20—_20don_20t_20rebuild_20it_81',['2.1 Reuse the EN 50159 envelope that already exists — don&apos;t rebuild it',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html#autotoc_md150',1,'']]],
  ['right_20for_20sapi_82',['Why CRC-64 is Right for SAPI',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md95',1,'']]],
  ['ring_20buffer_83',['Ring Buffer',['../log_architecture.html#log_architecture_storage',1,'']]],
  ['ring_20buffer_20without_20malloc_84',['Example 2: Ring Buffer Without malloc',['../memory_user_guide.html#memory_user_guide_example_ringbuf',1,'']]],
  ['risk_20mitigation_85',['Risk Mitigation',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md124',1,'']]],
  ['role_86',['role',['../structsapi__netlink__config__t.html#a7344858f69326b31c5543b84e8c19358',1,'sapi_netlink_config_t']]],
  ['rollout_20plan_87',['Rollout Plan',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html#autotoc_md142',1,'']]],
  ['rtos_88',['rtos',['../md_docs_2CROSS__COMPILATION.html#autotoc_md228',1,'QNX RTOS'],['../md_docs_2CROSS__COMPILATION.html#autotoc_md237',1,'QNX RTOS']]],
  ['rule_2010_201_89',['MISRA Rule 10.1',['../cast_architecture.html#cast_architecture_misra',1,'']]],
  ['rule_2020_206_90',['MISRA Rule 20.6',['../memory_architecture.html#memory_architecture_misra',1,'']]],
  ['rule_2021_206_91',['MISRA Rule 21.6',['../string_architecture.html#string_architecture_misra',1,'']]]
];
