var searchData=
[
  ['safe_20api_20framework_0',['safe api framework',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html',1,'ADR-001: OS Abstraction Layer (OAL) for the Safe API Framework'],['../index.html',1,'Safe API Framework']]],
  ['safe_20state_20module_20architecture_1',['Safe-State Module - Architecture',['../safestate_architecture.html',1,'']]],
  ['safe_20state_20module_20user_20guide_2',['Safe-State Module - User Guide',['../safestate_user_guide.html',1,'']]],
  ['safe_20state_20transitions_20and_20checked_20assertions_3',['ADR-004: Safe-State Transitions and Checked Assertions',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html',1,'']]],
  ['safe_20string_20manipulation_20and_20endianness_20safe_20buffer_20access_4',['ADR-006: Safe String Manipulation and Endianness-Safe Buffer Access',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html',1,'']]],
  ['sanctioned_20call_20site_20per_20libc_20memory_20primitive_5',['ADR-031: &lt;tt&gt;sapi_mem_util&lt;/tt&gt; - one sanctioned call site per libc memory primitive',['../md_docs_2architecture_2ADR-031-sapi-mem-util.html',1,'']]],
  ['sapi_5fchannel_20tt_20tt_20sapi_5fvoter_20tt_20tt_20sapi_5fcross_5fcomparator_20tt_6',['ADR-025: Split &lt;tt&gt;sapi_vital_channel&lt;/tt&gt; into &lt;tt&gt;sapi_channel&lt;/tt&gt; + &lt;tt&gt;sapi_voter&lt;/tt&gt; + &lt;tt&gt;sapi_cross_comparator&lt;/tt&gt;',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html',1,'']]],
  ['sapi_5fcross_5fcomparator_20tt_7',['ADR-025: Split &lt;tt&gt;sapi_vital_channel&lt;/tt&gt; into &lt;tt&gt;sapi_channel&lt;/tt&gt; + &lt;tt&gt;sapi_voter&lt;/tt&gt; + &lt;tt&gt;sapi_cross_comparator&lt;/tt&gt;',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html',1,'']]],
  ['sapi_5fdual_20tt_8',['ADR-020: Dual-Transfer State Negotiation (&lt;tt&gt;sapi_dual&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html',1,'']]],
  ['sapi_5fmem_5futil_20tt_20one_20sanctioned_20call_20site_20per_20libc_20memory_20primitive_9',['ADR-031: &lt;tt&gt;sapi_mem_util&lt;/tt&gt; - one sanctioned call site per libc memory primitive',['../md_docs_2architecture_2ADR-031-sapi-mem-util.html',1,'']]],
  ['sapi_5fmutex_20a_20portable_20mutual_20exclusion_20primitive_10',['ADR-033: sapi_mutex - a portable mutual-exclusion primitive',['../md_docs_2architecture_2ADR-033-sapi-mutex.html',1,'']]],
  ['sapi_5fnetlink_20tt_11',['ADR-027: UDP Transport for &lt;tt&gt;sapi_netlink&lt;/tt&gt;',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html',1,'']]],
  ['sapi_5fnotify_20tt_20fixed_20capacity_20registered_20callback_20list_20shape_12',['ADR-030: &lt;tt&gt;sapi_notify&lt;/tt&gt; - fixed-capacity registered-callback list shape',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html',1,'']]],
  ['sapi_5fplatform_20tt_20oal_20service_20for_20real_20time_20bring_20up_13',['ADR-035: &lt;tt&gt;sapi_platform&lt;/tt&gt; OAL service for real-time bring-up',['../md_docs_2architecture_2ADR-035-platform-realtime-init.html',1,'']]],
  ['sapi_5fsafechannel_20tt_20factory_20hiding_20ipc_20netlink_20from_20app_20code_14',['ADR-022: Unified &lt;tt&gt;sapi_safechannel&lt;/tt&gt; Factory (Hiding IPC/Netlink from App Code)',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html',1,'']]],
  ['sapi_5fvital_5fchannel_20tt_20into_20tt_20sapi_5fchannel_20tt_20tt_20sapi_5fvoter_20tt_20tt_20sapi_5fcross_5fcomparator_20tt_15',['ADR-025: Split &lt;tt&gt;sapi_vital_channel&lt;/tt&gt; into &lt;tt&gt;sapi_channel&lt;/tt&gt; + &lt;tt&gt;sapi_voter&lt;/tt&gt; + &lt;tt&gt;sapi_cross_comparator&lt;/tt&gt;',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html',1,'']]],
  ['sapi_5fvoter_20tt_20tt_20sapi_5fcross_5fcomparator_20tt_16',['ADR-025: Split &lt;tt&gt;sapi_vital_channel&lt;/tt&gt; into &lt;tt&gt;sapi_channel&lt;/tt&gt; + &lt;tt&gt;sapi_voter&lt;/tt&gt; + &lt;tt&gt;sapi_cross_comparator&lt;/tt&gt;',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html',1,'']]],
  ['scenario_20real_20multi_20train_20protocol_20and_20failover_20ready_20session_20state_17',['ADR-029: RBC Train/IL/CTC Scenario - Real Multi-Train Protocol and Failover-Ready Session State',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html',1,'']]],
  ['selection_20at_20configure_20time_18',['ADR-024: Per-Module Feature Selection at Configure Time',['../md_docs_2architecture_2ADR-024-configurable-feature-build.html',1,'']]],
  ['selection_20guide_19',['IPC Transport Selection Guide',['../ipc_transport_selection.html',1,'']]],
  ['separation_20',['ADR-021: Consumer / OS-Backend Header Separation',['../md_docs_2architecture_2ADR-021-consumer-backend-header-split.html',1,'']]],
  ['service_20for_20real_20time_20bring_20up_21',['ADR-035: &lt;tt&gt;sapi_platform&lt;/tt&gt; OAL service for real-time bring-up',['../md_docs_2architecture_2ADR-035-platform-realtime-init.html',1,'']]],
  ['session_20state_22',['ADR-029: RBC Train/IL/CTC Scenario - Real Multi-Train Protocol and Failover-Ready Session State',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html',1,'']]],
  ['setup_20phase_20lock_20and_20single_20entry_20point_20enforcement_23',['ADR-026: Application Setup-Phase Lock and Single-Entry-Point Enforcement',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html',1,'']]],
  ['setup_20phase_20lock_20coverage_20extended_20to_20backend_20registration_20and_20remaining_20setup_20only_20constructors_24',['ADR-032: Setup-phase lock coverage extended to backend registration and remaining setup-only constructors',['../md_docs_2architecture_2ADR-032-setup-phase-lock-coverage-extended.html',1,'']]],
  ['shape_25',['ADR-030: &lt;tt&gt;sapi_notify&lt;/tt&gt; - fixed-capacity registered-callback list shape',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html',1,'']]],
  ['signature_20marks_20and_20stage_20then_20commit_20output_26',['ADR-034: Checkpoint-signature marks and stage-then-commit output',['../md_docs_2architecture_2ADR-034-checkpoint-signature-marks.html',1,'']]],
  ['single_20entry_20point_20enforcement_27',['ADR-026: Application Setup-Phase Lock and Single-Entry-Point Enforcement',['../md_docs_2architecture_2ADR-026-application-setup-phase-lock.html',1,'']]],
  ['site_20per_20libc_20memory_20primitive_28',['ADR-031: &lt;tt&gt;sapi_mem_util&lt;/tt&gt; - one sanctioned call site per libc memory primitive',['../md_docs_2architecture_2ADR-031-sapi-mem-util.html',1,'']]],
  ['software_20requirements_20specification_20srs_29',['Software Requirements Specification (SRS)',['../safeapi_srs.html',1,'']]],
  ['specification_20srs_30',['Software Requirements Specification (SRS)',['../safeapi_srs.html',1,'']]],
  ['split_20tt_20sapi_5fvital_5fchannel_20tt_20into_20tt_20sapi_5fchannel_20tt_20tt_20sapi_5fvoter_20tt_20tt_20sapi_5fcross_5fcomparator_20tt_31',['ADR-025: Split &lt;tt&gt;sapi_vital_channel&lt;/tt&gt; into &lt;tt&gt;sapi_channel&lt;/tt&gt; + &lt;tt&gt;sapi_voter&lt;/tt&gt; + &lt;tt&gt;sapi_cross_comparator&lt;/tt&gt;',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html',1,'']]],
  ['srs_32',['Software Requirements Specification (SRS)',['../safeapi_srs.html',1,'']]],
  ['stage_20then_20commit_20output_33',['ADR-034: Checkpoint-signature marks and stage-then-commit output',['../md_docs_2architecture_2ADR-034-checkpoint-signature-marks.html',1,'']]],
  ['starvation_20fix_34',['ADR-028: Channel-Down Escalation to REBOOT, and a Cyclic-Executive Starvation Fix',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html',1,'']]],
  ['state_35',['ADR-029: RBC Train/IL/CTC Scenario - Real Multi-Train Protocol and Failover-Ready Session State',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html',1,'']]],
  ['state_20module_20architecture_36',['Safe-State Module - Architecture',['../safestate_architecture.html',1,'']]],
  ['state_20module_20user_20guide_37',['Safe-State Module - User Guide',['../safestate_user_guide.html',1,'']]],
  ['state_20negotiation_20tt_20sapi_5fdual_20tt_38',['ADR-020: Dual-Transfer State Negotiation (&lt;tt&gt;sapi_dual&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html',1,'']]],
  ['state_20transitions_20and_20checked_20assertions_39',['ADR-004: Safe-State Transitions and Checked Assertions',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html',1,'']]],
  ['status_20module_20architecture_40',['Status Module - Architecture',['../status_architecture.html',1,'']]],
  ['status_20module_20user_20guide_41',['Status Module - User Guide',['../status_user_guide.html',1,'']]],
  ['string_20manipulation_20and_20endianness_20safe_20buffer_20access_42',['ADR-006: Safe String Manipulation and Endianness-Safe Buffer Access',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html',1,'']]],
  ['string_20module_20architecture_43',['String Module - Architecture',['../string_architecture.html',1,'']]],
  ['string_20module_20user_20guide_44',['String Module - User Guide',['../string_user_guide.html',1,'']]],
  ['synchronization_20for_20distributed_20vital_20channels_45',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['system_20architecture_20overview_46',['System Architecture Overview',['../system_architecture.html',1,'']]],
  ['system_5foverview_47',['SYSTEM_OVERVIEW',['../md_docs_2architecture_2SYSTEM__OVERVIEW.html',1,'']]]
];
