var searchData=
[
  ['c_20gateway_20decomposition_20into_20per_20client_20type_20service_20binaries_0',['ADR-037: Role C gateway - decomposition into per-client-type service binaries',['../md_docs_2architecture_2ADR-037-role-c-gateway-decomposition.html',1,'']]],
  ['c_20side_20pub_20sub_20broker_20an_20a_20b↔c_20util_20channel_1',['ADR-038: Status indication - a C-side pub/sub broker + an A/B↔C util channel',['../md_docs_2architecture_2ADR-038-status-indication-and-c-pubsub-broker.html',1,'']]],
  ['call_20site_20per_20libc_20memory_20primitive_2',['ADR-031: &lt;tt&gt;sapi_mem_util&lt;/tt&gt; - one sanctioned call site per libc memory primitive',['../md_docs_2architecture_2ADR-031-sapi-mem-util.html',1,'']]],
  ['callback_20list_20shape_3',['ADR-030: &lt;tt&gt;sapi_notify&lt;/tt&gt; - fixed-capacity registered-callback list shape',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html',1,'']]],
  ['callbacks_4',['ADR-005: OAL Backend Registration via Callbacks',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html',1,'']]],
  ['capacity_20registered_20callback_20list_20shape_5',['ADR-030: &lt;tt&gt;sapi_notify&lt;/tt&gt; - fixed-capacity registered-callback list shape',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html',1,'']]],
  ['cast_20module_20architecture_6',['Cast Module - Architecture',['../cast_architecture.html',1,'']]],
  ['cast_20module_20user_20guide_7',['Cast Module - User Guide',['../cast_user_guide.html',1,'']]],
  ['casting_8',['ADR-003: Checked Integer Casting',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html',1,'']]],
  ['ccf_20mitigation_20via_20build_20diversity_9',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['channel_10',['ADR-038: Status indication - a C-side pub/sub broker + an A/B↔C util channel',['../md_docs_2architecture_2ADR-038-status-indication-and-c-pubsub-broker.html',1,'']]],
  ['channel_20communication_20architecture_11',['Vital Channel Communication Architecture',['../vital_channel_architecture.html',1,'']]],
  ['channel_20configuration_20guide_12',['Channel Configuration Guide',['../channel_configuration.html',1,'']]],
  ['channel_20down_20escalation_20to_20reboot_20and_20a_20cyclic_20executive_20starvation_20fix_13',['ADR-028: Channel-Down Escalation to REBOOT, and a Cyclic-Executive Starvation Fix',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html',1,'']]],
  ['channel_20module_20user_20guide_14',['Vital Channel Module - User Guide',['../vital_channel_user_guide.html',1,'']]],
  ['channel_20topologies_20and_20redundancy_20patterns_15',['Channel Topologies and Redundancy Patterns',['../vital_channel_topologies.html',1,'']]],
  ['channel_20vital_20architecture_20—_20ccf_20mitigation_20via_20build_20diversity_16',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['channel_5fconfiguration_17',['CHANNEL_CONFIGURATION',['../md_include_2safeapi_2oal_2ipc_2CHANNEL__CONFIGURATION.html',1,'']]],
  ['channel_5ftopologies_18',['CHANNEL_TOPOLOGIES',['../md_include_2safeapi_2redundancy_2channel__link_2CHANNEL__TOPOLOGIES.html',1,'']]],
  ['channels_19',['channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'ADR-016: CRC-64 Data Integrity for Redundant Channels'],['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels'],['../appmanager_integration.html',1,'App Manager Integration with Channels']]],
  ['checked_20assertions_20',['ADR-004: Safe-State Transitions and Checked Assertions',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html',1,'']]],
  ['checked_20integer_20casting_21',['ADR-003: Checked Integer Casting',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html',1,'']]],
  ['checkpoint_20rendezvous_22',['ADR-019: AppManager Cycle Hooks and Built-In Checkpoint Rendezvous',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html',1,'']]],
  ['checkpoint_20rendezvous_20and_20clock_20synchronization_20for_20distributed_20vital_20channels_23',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['checkpoint_20signature_20marks_20and_20stage_20then_20commit_20output_24',['ADR-034: Checkpoint-signature marks and stage-then-commit output',['../md_docs_2architecture_2ADR-034-checkpoint-signature-marks.html',1,'']]],
  ['checksum_20module_20architecture_25',['Checksum Module - Architecture',['../checksum_architecture.html',1,'']]],
  ['checksum_20module_20user_20guide_26',['Checksum Module - User Guide',['../checksum_user_guide.html',1,'']]],
  ['client_20type_20service_20binaries_27',['ADR-037: Role C gateway - decomposition into per-client-type service binaries',['../md_docs_2architecture_2ADR-037-role-c-gateway-decomposition.html',1,'']]],
  ['clock_20synchronization_20for_20distributed_20vital_20channels_28',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['cmake_20library_20targets_20into_204_29',['ADR-023: Consolidate 22 CMake Library Targets into 4',['../md_docs_2architecture_2ADR-023-consolidate-cmake-libraries.html',1,'']]],
  ['code_30',['ADR-022: Unified &lt;tt&gt;sapi_safechannel&lt;/tt&gt; Factory (Hiding IPC/Netlink from App Code)',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html',1,'']]],
  ['commit_20output_31',['ADR-034: Checkpoint-signature marks and stage-then-commit output',['../md_docs_2architecture_2ADR-034-checkpoint-signature-marks.html',1,'']]],
  ['communication_20architecture_32',['Vital Channel Communication Architecture',['../vital_channel_architecture.html',1,'']]],
  ['communication_20guide_33',['IPC (Inter-Process Communication) Guide',['../ipc_guide.html',1,'']]],
  ['compilation_20guide_34',['Cross-Compilation Guide',['../md_docs_2CROSS__COMPILATION.html',1,'']]],
  ['configuration_20guide_35',['Channel Configuration Guide',['../channel_configuration.html',1,'']]],
  ['configure_20time_36',['ADR-024: Per-Module Feature Selection at Configure Time',['../md_docs_2architecture_2ADR-024-configurable-feature-build.html',1,'']]],
  ['consolidate_2022_20cmake_20library_20targets_20into_204_37',['ADR-023: Consolidate 22 CMake Library Targets into 4',['../md_docs_2architecture_2ADR-023-consolidate-cmake-libraries.html',1,'']]],
  ['constructors_38',['ADR-032: Setup-phase lock coverage extended to backend registration and remaining setup-only constructors',['../md_docs_2architecture_2ADR-032-setup-phase-lock-coverage-extended.html',1,'']]],
  ['consumer_20os_20backend_20header_20separation_39',['ADR-021: Consumer / OS-Backend Header Separation',['../md_docs_2architecture_2ADR-021-consumer-backend-header-split.html',1,'']]],
  ['coverage_20extended_20to_20backend_20registration_20and_20remaining_20setup_20only_20constructors_40',['ADR-032: Setup-phase lock coverage extended to backend registration and remaining setup-only constructors',['../md_docs_2architecture_2ADR-032-setup-phase-lock-coverage-extended.html',1,'']]],
  ['crc_2064_20data_20integrity_20for_20redundant_20channels_41',['ADR-016: CRC-64 Data Integrity for Redundant Channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'']]],
  ['cross_20compilation_20guide_42',['Cross-Compilation Guide',['../md_docs_2CROSS__COMPILATION.html',1,'']]],
  ['cross_20layer_20data_20buffer_20abstraction_43',['ADR-002: Cross-Layer Data Buffer Abstraction',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html',1,'']]],
  ['ctc_20scenario_20real_20multi_20train_20protocol_20and_20failover_20ready_20session_20state_44',['ADR-029: RBC Train/IL/CTC Scenario - Real Multi-Train Protocol and Failover-Ready Session State',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html',1,'']]],
  ['cycle_20hooks_20and_20built_20in_20checkpoint_20rendezvous_45',['ADR-019: AppManager Cycle Hooks and Built-In Checkpoint Rendezvous',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html',1,'']]],
  ['cyclic_20executive_20starvation_20fix_46',['ADR-028: Channel-Down Escalation to REBOOT, and a Cyclic-Executive Starvation Fix',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html',1,'']]]
];
