var searchData=
[
  ['manager_20integration_20with_20channels_0',['App Manager Integration with Channels',['../appmanager_integration.html',1,'']]],
  ['manipulation_20and_20endianness_20safe_20buffer_20access_1',['ADR-006: Safe String Manipulation and Endianness-Safe Buffer Access',['../md_docs_2architecture_2ADR-006-string-and-endian-buffer-access.html',1,'']]],
  ['marks_20and_20stage_20then_20commit_20output_2',['ADR-034: Checkpoint-signature marks and stage-then-commit output',['../md_docs_2architecture_2ADR-034-checkpoint-signature-marks.html',1,'']]],
  ['memory_20architecture_3',['Non-Volatile Memory Architecture',['../nvm_architecture.html',1,'']]],
  ['memory_20module_20architecture_4',['Memory Module - Architecture',['../memory_architecture.html',1,'']]],
  ['memory_20module_20user_20guide_5',['Memory Module - User Guide',['../memory_user_guide.html',1,'']]],
  ['memory_20primitive_6',['ADR-031: &lt;tt&gt;sapi_mem_util&lt;/tt&gt; - one sanctioned call site per libc memory primitive',['../md_docs_2architecture_2ADR-031-sapi-mem-util.html',1,'']]],
  ['memory_20user_20guide_7',['Non-Volatile Memory User Guide',['../nvm_user_guide.html',1,'']]],
  ['mitigation_20via_20build_20diversity_8',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['module_20architecture_9',['module architecture',['../buffer_architecture.html',1,'Buffer Module - Architecture'],['../cast_architecture.html',1,'Cast Module - Architecture'],['../checksum_architecture.html',1,'Checksum Module - Architecture'],['../log_architecture.html',1,'Log Module - Architecture'],['../memory_architecture.html',1,'Memory Module - Architecture'],['../reboot_architecture.html',1,'Reboot Module - Architecture'],['../safestate_architecture.html',1,'Safe-State Module - Architecture'],['../status_architecture.html',1,'Status Module - Architecture'],['../string_architecture.html',1,'String Module - Architecture'],['../task_architecture.html',1,'Task Queue Module - Architecture'],['../timer_architecture.html',1,'Timer Module - Architecture'],['../types_architecture.html',1,'Types Module - Architecture'],['../watchdog_architecture.html',1,'Watchdog Module - Architecture']]],
  ['module_20feature_20selection_20at_20configure_20time_10',['ADR-024: Per-Module Feature Selection at Configure Time',['../md_docs_2architecture_2ADR-024-configurable-feature-build.html',1,'']]],
  ['module_20user_20guide_11',['module user guide',['../buffer_user_guide.html',1,'Buffer Module - User Guide'],['../cast_user_guide.html',1,'Cast Module - User Guide'],['../checksum_user_guide.html',1,'Checksum Module - User Guide'],['../log_user_guide.html',1,'Logging Module - User Guide'],['../memory_user_guide.html',1,'Memory Module - User Guide'],['../reboot_user_guide.html',1,'Reboot Module - User Guide'],['../safestate_user_guide.html',1,'Safe-State Module - User Guide'],['../status_user_guide.html',1,'Status Module - User Guide'],['../string_user_guide.html',1,'String Module - User Guide'],['../task_user_guide.html',1,'Task Queue Module - User Guide'],['../timer_user_guide.html',1,'Timer Module - User Guide'],['../types_user_guide.html',1,'Types Module - User Guide'],['../vital_channel_user_guide.html',1,'Vital Channel Module - User Guide'],['../watchdog_user_guide.html',1,'Watchdog Module - User Guide']]],
  ['multi_20train_20protocol_20and_20failover_20ready_20session_20state_12',['ADR-029: RBC Train/IL/CTC Scenario - Real Multi-Train Protocol and Failover-Ready Session State',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html',1,'']]],
  ['mutual_20exclusion_20primitive_13',['ADR-033: sapi_mutex - a portable mutual-exclusion primitive',['../md_docs_2architecture_2ADR-033-sapi-mutex.html',1,'']]]
];
