var searchData=
[
  ['targets_20into_204_0',['ADR-023: Consolidate 22 CMake Library Targets into 4',['../md_docs_2architecture_2ADR-023-consolidate-cmake-libraries.html',1,'']]],
  ['task_20queue_20module_20architecture_1',['Task Queue Module - Architecture',['../task_architecture.html',1,'']]],
  ['task_20queue_20module_20user_20guide_2',['Task Queue Module - User Guide',['../task_user_guide.html',1,'']]],
  ['the_20safe_20api_20framework_3',['ADR-001: OS Abstraction Layer (OAL) for the Safe API Framework',['../md_docs_2architecture_2ADR-001-os-abstraction-layer.html',1,'']]],
  ['then_20commit_20output_4',['ADR-034: Checkpoint-signature marks and stage-then-commit output',['../md_docs_2architecture_2ADR-034-checkpoint-signature-marks.html',1,'']]],
  ['time_5',['ADR-024: Per-Module Feature Selection at Configure Time',['../md_docs_2architecture_2ADR-024-configurable-feature-build.html',1,'']]],
  ['time_20bring_20up_6',['ADR-035: &lt;tt&gt;sapi_platform&lt;/tt&gt; OAL service for real-time bring-up',['../md_docs_2architecture_2ADR-035-platform-realtime-init.html',1,'']]],
  ['timer_20module_20architecture_7',['Timer Module - Architecture',['../timer_architecture.html',1,'']]],
  ['timer_20module_20user_20guide_8',['Timer Module - User Guide',['../timer_user_guide.html',1,'']]],
  ['to_20100_9',['ADR-036: Train-session multiplexing - one link, many trains (up to 100)',['../md_docs_2architecture_2ADR-036-train-session-multiplexing.html',1,'']]],
  ['to_20backend_20registration_20and_20remaining_20setup_20only_20constructors_10',['ADR-032: Setup-phase lock coverage extended to backend registration and remaining setup-only constructors',['../md_docs_2architecture_2ADR-032-setup-phase-lock-coverage-extended.html',1,'']]],
  ['to_20reboot_20and_20a_20cyclic_20executive_20starvation_20fix_11',['ADR-028: Channel-Down Escalation to REBOOT, and a Cyclic-Executive Starvation Fix',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html',1,'']]],
  ['topologies_20and_20redundancy_20patterns_12',['Channel Topologies and Redundancy Patterns',['../vital_channel_topologies.html',1,'']]],
  ['train_20il_20ctc_20scenario_20real_20multi_20train_20protocol_20and_20failover_20ready_20session_20state_13',['ADR-029: RBC Train/IL/CTC Scenario - Real Multi-Train Protocol and Failover-Ready Session State',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html',1,'']]],
  ['train_20session_20multiplexing_20one_20link_20many_20trains_20up_20to_20100_14',['ADR-036: Train-session multiplexing - one link, many trains (up to 100)',['../md_docs_2architecture_2ADR-036-train-session-multiplexing.html',1,'']]],
  ['trains_20up_20to_20100_15',['ADR-036: Train-session multiplexing - one link, many trains (up to 100)',['../md_docs_2architecture_2ADR-036-train-session-multiplexing.html',1,'']]],
  ['transfer_20state_20negotiation_20tt_20sapi_5fdual_20tt_16',['ADR-020: Dual-Transfer State Negotiation (&lt;tt&gt;sapi_dual&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html',1,'']]],
  ['transitions_20and_20checked_20assertions_17',['ADR-004: Safe-State Transitions and Checked Assertions',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html',1,'']]],
  ['transport_20for_20tt_20sapi_5fnetlink_20tt_18',['ADR-027: UDP Transport for &lt;tt&gt;sapi_netlink&lt;/tt&gt;',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html',1,'']]],
  ['transport_20selection_20guide_19',['IPC Transport Selection Guide',['../ipc_transport_selection.html',1,'']]],
  ['tt_20sapi_5fdual_20tt_20',['ADR-020: Dual-Transfer State Negotiation (&lt;tt&gt;sapi_dual&lt;/tt&gt;)',['../md_docs_2architecture_2ADR-020-dual-transfer-state-negotiation.html',1,'']]],
  ['tt_20sapi_5fmem_5futil_20tt_20one_20sanctioned_20call_20site_20per_20libc_20memory_20primitive_21',['ADR-031: &lt;tt&gt;sapi_mem_util&lt;/tt&gt; - one sanctioned call site per libc memory primitive',['../md_docs_2architecture_2ADR-031-sapi-mem-util.html',1,'']]],
  ['tt_20sapi_5fnetlink_20tt_22',['ADR-027: UDP Transport for &lt;tt&gt;sapi_netlink&lt;/tt&gt;',['../md_docs_2architecture_2ADR-027-udp-netlink-transport.html',1,'']]],
  ['tt_20sapi_5fnotify_20tt_20fixed_20capacity_20registered_20callback_20list_20shape_23',['ADR-030: &lt;tt&gt;sapi_notify&lt;/tt&gt; - fixed-capacity registered-callback list shape',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html',1,'']]],
  ['tt_20sapi_5fplatform_20tt_20oal_20service_20for_20real_20time_20bring_20up_24',['ADR-035: &lt;tt&gt;sapi_platform&lt;/tt&gt; OAL service for real-time bring-up',['../md_docs_2architecture_2ADR-035-platform-realtime-init.html',1,'']]],
  ['tt_20sapi_5fsafechannel_20tt_20factory_20hiding_20ipc_20netlink_20from_20app_20code_25',['ADR-022: Unified &lt;tt&gt;sapi_safechannel&lt;/tt&gt; Factory (Hiding IPC/Netlink from App Code)',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html',1,'']]],
  ['tt_20sapi_5fvital_5fchannel_20tt_20into_20tt_20sapi_5fchannel_20tt_20tt_20sapi_5fvoter_20tt_20tt_20sapi_5fcross_5fcomparator_20tt_26',['ADR-025: Split &lt;tt&gt;sapi_vital_channel&lt;/tt&gt; into &lt;tt&gt;sapi_channel&lt;/tt&gt; + &lt;tt&gt;sapi_voter&lt;/tt&gt; + &lt;tt&gt;sapi_cross_comparator&lt;/tt&gt;',['../md_docs_2architecture_2ADR-025-vital-channel-voter-cross-comparator-split.html',1,'']]],
  ['type_20service_20binaries_27',['ADR-037: Role C gateway - decomposition into per-client-type service binaries',['../md_docs_2architecture_2ADR-037-role-c-gateway-decomposition.html',1,'']]],
  ['types_20module_20architecture_28',['Types Module - Architecture',['../types_architecture.html',1,'']]],
  ['types_20module_20user_20guide_29',['Types Module - User Guide',['../types_user_guide.html',1,'']]]
];
