var searchData=
[
  ['callbacks_0',['ADR-005: OAL Backend Registration via Callbacks',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html',1,'']]],
  ['cast_20module_20architecture_1',['Cast Module - Architecture',['../cast_architecture.html',1,'']]],
  ['cast_20module_20user_20guide_2',['Cast Module - User Guide',['../cast_user_guide.html',1,'']]],
  ['casting_3',['ADR-003: Checked Integer Casting',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html',1,'']]],
  ['ccf_20mitigation_20via_20build_20diversity_4',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['channel_20communication_20architecture_5',['Vital Channel Communication Architecture',['../vital_channel_architecture.html',1,'']]],
  ['channel_20configuration_20guide_6',['Channel Configuration Guide',['../channel_configuration.html',1,'']]],
  ['channel_20module_20user_20guide_7',['Vital Channel Module - User Guide',['../vital_channel_user_guide.html',1,'']]],
  ['channel_20topologies_20and_20redundancy_20patterns_8',['Channel Topologies and Redundancy Patterns',['../vital_channel_topologies.html',1,'']]],
  ['channel_20vital_20architecture_20—_20ccf_20mitigation_20via_20build_20diversity_9',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['channel_5fconfiguration_10',['CHANNEL_CONFIGURATION',['../md_include_2safeapi_2ipc_2CHANNEL__CONFIGURATION.html',1,'']]],
  ['channel_5ftopologies_11',['CHANNEL_TOPOLOGIES',['../md_include_2safeapi_2vital__channel_2CHANNEL__TOPOLOGIES.html',1,'']]],
  ['channels_12',['channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'ADR-016: CRC-64 Data Integrity for Redundant Channels'],['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels'],['../appmanager_integration.html',1,'App Manager Integration with Channels']]],
  ['checked_20assertions_13',['ADR-004: Safe-State Transitions and Checked Assertions',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html',1,'']]],
  ['checked_20integer_20casting_14',['ADR-003: Checked Integer Casting',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html',1,'']]],
  ['checkpoint_20rendezvous_20and_20clock_20synchronization_20for_20distributed_20vital_20channels_15',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['checksum_20module_20architecture_16',['Checksum Module - Architecture',['../checksum_architecture.html',1,'']]],
  ['checksum_20module_20user_20guide_17',['Checksum Module - User Guide',['../checksum_user_guide.html',1,'']]],
  ['clock_20synchronization_20for_20distributed_20vital_20channels_18',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['communication_20architecture_19',['Vital Channel Communication Architecture',['../vital_channel_architecture.html',1,'']]],
  ['communication_20guide_20',['IPC (Inter-Process Communication) Guide',['../ipc_guide.html',1,'']]],
  ['compilation_20guide_21',['Cross-Compilation Guide',['../md_docs_2CROSS__COMPILATION.html',1,'']]],
  ['configuration_20guide_22',['Channel Configuration Guide',['../channel_configuration.html',1,'']]],
  ['crc_2064_20data_20integrity_20for_20redundant_20channels_23',['ADR-016: CRC-64 Data Integrity for Redundant Channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'']]],
  ['cross_20compilation_20guide_24',['Cross-Compilation Guide',['../md_docs_2CROSS__COMPILATION.html',1,'']]],
  ['cross_20layer_20data_20buffer_20abstraction_25',['ADR-002: Cross-Layer Data Buffer Abstraction',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html',1,'']]]
];
