var searchData=
[
  ['call_20site_20per_20libc_20memory_20primitive_0',['ADR-031: &lt;tt&gt;sapi_mem_util&lt;/tt&gt; - one sanctioned call site per libc memory primitive',['../md_docs_2architecture_2ADR-031-sapi-mem-util.html',1,'']]],
  ['callback_20list_20shape_1',['ADR-030: &lt;tt&gt;sapi_notify&lt;/tt&gt; - fixed-capacity registered-callback list shape',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html',1,'']]],
  ['callbacks_2',['ADR-005: OAL Backend Registration via Callbacks',['../md_docs_2architecture_2ADR-005-oal-backend-registration.html',1,'']]],
  ['capacity_20registered_20callback_20list_20shape_3',['ADR-030: &lt;tt&gt;sapi_notify&lt;/tt&gt; - fixed-capacity registered-callback list shape',['../md_docs_2architecture_2ADR-030-registered-callback-list-shape.html',1,'']]],
  ['cast_20module_20architecture_4',['Cast Module - Architecture',['../cast_architecture.html',1,'']]],
  ['cast_20module_20user_20guide_5',['Cast Module - User Guide',['../cast_user_guide.html',1,'']]],
  ['casting_6',['ADR-003: Checked Integer Casting',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html',1,'']]],
  ['ccf_20mitigation_20via_20build_20diversity_7',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['channel_20communication_20architecture_8',['Vital Channel Communication Architecture',['../vital_channel_architecture.html',1,'']]],
  ['channel_20configuration_20guide_9',['Channel Configuration Guide',['../channel_configuration.html',1,'']]],
  ['channel_20down_20escalation_20to_20reboot_20and_20a_20cyclic_20executive_20starvation_20fix_10',['ADR-028: Channel-Down Escalation to REBOOT, and a Cyclic-Executive Starvation Fix',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html',1,'']]],
  ['channel_20module_20user_20guide_11',['Vital Channel Module - User Guide',['../vital_channel_user_guide.html',1,'']]],
  ['channel_20topologies_20and_20redundancy_20patterns_12',['Channel Topologies and Redundancy Patterns',['../vital_channel_topologies.html',1,'']]],
  ['channel_20vital_20architecture_20—_20ccf_20mitigation_20via_20build_20diversity_13',['ADR-008: Dual-Channel Vital Architecture — CCF Mitigation via Build Diversity',['../md_docs_2architecture_2ADR-008-dual-channel-ccf-mitigation.html',1,'']]],
  ['channel_5fconfiguration_14',['CHANNEL_CONFIGURATION',['../md_include_2safeapi_2oal_2ipc_2CHANNEL__CONFIGURATION.html',1,'']]],
  ['channel_5ftopologies_15',['CHANNEL_TOPOLOGIES',['../md_include_2safeapi_2redundancy_2channel__link_2CHANNEL__TOPOLOGIES.html',1,'']]],
  ['channels_16',['channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'ADR-016: CRC-64 Data Integrity for Redundant Channels'],['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels'],['../appmanager_integration.html',1,'App Manager Integration with Channels']]],
  ['checked_20assertions_17',['ADR-004: Safe-State Transitions and Checked Assertions',['../md_docs_2architecture_2ADR-004-safe-state-transitions.html',1,'']]],
  ['checked_20integer_20casting_18',['ADR-003: Checked Integer Casting',['../md_docs_2architecture_2ADR-003-checked-integer-casting.html',1,'']]],
  ['checkpoint_20rendezvous_19',['ADR-019: AppManager Cycle Hooks and Built-In Checkpoint Rendezvous',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html',1,'']]],
  ['checkpoint_20rendezvous_20and_20clock_20synchronization_20for_20distributed_20vital_20channels_20',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['checkpoint_20signature_20marks_20and_20stage_20then_20commit_20output_21',['ADR-034: Checkpoint-signature marks and stage-then-commit output',['../md_docs_2architecture_2ADR-034-checkpoint-signature-marks.html',1,'']]],
  ['checksum_20module_20architecture_22',['Checksum Module - Architecture',['../checksum_architecture.html',1,'']]],
  ['checksum_20module_20user_20guide_23',['Checksum Module - User Guide',['../checksum_user_guide.html',1,'']]],
  ['clock_20synchronization_20for_20distributed_20vital_20channels_24',['ADR-017: Checkpoint Rendezvous and Clock Synchronization for Distributed Vital Channels',['../md_docs_2architecture_2ADR-017-checkpoint-and-clock-sync.html',1,'']]],
  ['cmake_20library_20targets_20into_204_25',['ADR-023: Consolidate 22 CMake Library Targets into 4',['../md_docs_2architecture_2ADR-023-consolidate-cmake-libraries.html',1,'']]],
  ['code_26',['ADR-022: Unified &lt;tt&gt;sapi_safechannel&lt;/tt&gt; Factory (Hiding IPC/Netlink from App Code)',['../md_docs_2architecture_2ADR-022-unified-safechannel-factory.html',1,'']]],
  ['commit_20output_27',['ADR-034: Checkpoint-signature marks and stage-then-commit output',['../md_docs_2architecture_2ADR-034-checkpoint-signature-marks.html',1,'']]],
  ['communication_20architecture_28',['Vital Channel Communication Architecture',['../vital_channel_architecture.html',1,'']]],
  ['communication_20guide_29',['IPC (Inter-Process Communication) Guide',['../ipc_guide.html',1,'']]],
  ['compilation_20guide_30',['Cross-Compilation Guide',['../md_docs_2CROSS__COMPILATION.html',1,'']]],
  ['configuration_20guide_31',['Channel Configuration Guide',['../channel_configuration.html',1,'']]],
  ['configure_20time_32',['ADR-024: Per-Module Feature Selection at Configure Time',['../md_docs_2architecture_2ADR-024-configurable-feature-build.html',1,'']]],
  ['consolidate_2022_20cmake_20library_20targets_20into_204_33',['ADR-023: Consolidate 22 CMake Library Targets into 4',['../md_docs_2architecture_2ADR-023-consolidate-cmake-libraries.html',1,'']]],
  ['constructors_34',['ADR-032: Setup-phase lock coverage extended to backend registration and remaining setup-only constructors',['../md_docs_2architecture_2ADR-032-setup-phase-lock-coverage-extended.html',1,'']]],
  ['consumer_20os_20backend_20header_20separation_35',['ADR-021: Consumer / OS-Backend Header Separation',['../md_docs_2architecture_2ADR-021-consumer-backend-header-split.html',1,'']]],
  ['coverage_20extended_20to_20backend_20registration_20and_20remaining_20setup_20only_20constructors_36',['ADR-032: Setup-phase lock coverage extended to backend registration and remaining setup-only constructors',['../md_docs_2architecture_2ADR-032-setup-phase-lock-coverage-extended.html',1,'']]],
  ['crc_2064_20data_20integrity_20for_20redundant_20channels_37',['ADR-016: CRC-64 Data Integrity for Redundant Channels',['../md_docs_2architecture_2ADR-016-crc64-data-integrity.html',1,'']]],
  ['cross_20compilation_20guide_38',['Cross-Compilation Guide',['../md_docs_2CROSS__COMPILATION.html',1,'']]],
  ['cross_20layer_20data_20buffer_20abstraction_39',['ADR-002: Cross-Layer Data Buffer Abstraction',['../md_docs_2architecture_2ADR-002-cross-layer-data-buffers.html',1,'']]],
  ['ctc_20scenario_20real_20multi_20train_20protocol_20and_20failover_20ready_20session_20state_40',['ADR-029: RBC Train/IL/CTC Scenario - Real Multi-Train Protocol and Failover-Ready Session State',['../md_docs_2architecture_2ADR-029-rbc-train-il-ctc-scenario.html',1,'']]],
  ['cycle_20hooks_20and_20built_20in_20checkpoint_20rendezvous_41',['ADR-019: AppManager Cycle Hooks and Built-In Checkpoint Rendezvous',['../md_docs_2architecture_2ADR-019-appmanager-cycle-hooks-and-checkpoint.html',1,'']]],
  ['cyclic_20executive_20starvation_20fix_42',['ADR-028: Channel-Down Escalation to REBOOT, and a Cyclic-Executive Starvation Fix',['../md_docs_2architecture_2ADR-028-channel-down-reboot-and-executive-starvation-fix.html',1,'']]]
];
